/* Tide aquarium studio, breeding, decor, and special catches */
'use strict';
const studioDecorDefs={
 coral:{name:'Coral Grove',art:'🪸',layer:'back',starter:true,size:1.2,cat:'nature'},
 kelp:{name:'Kelp Fronds',art:'🌿',layer:'back',starter:true,size:1.15,cat:'nature'},
 shells:{name:'Shell Bed',art:'🐚',layer:'back',starter:true,size:1,cat:'nature'},
 castle:{name:'Sunken Castle',art:'🏰',layer:'back',size:1.45,cat:'treasure'},
 chest:{name:'Treasure Chest',art:'🧰',layer:'front',size:1.05,cat:'treasure'},
 anchor:{name:'Old Anchor',art:'⚓',layer:'front',size:1.05,cat:'treasure'},
 lantern:{name:'Pearl Lantern',art:'🏮',layer:'front',size:1.05,cat:'treasure'},
 ruins:{name:'Ancient Ruins',art:'🏛️',layer:'back',size:1.35,cat:'ruins'},
 statue:{name:'Sea Statue',art:'🗿',layer:'front',size:1.05,cat:'ruins'},
 crown:{name:'Sunken Crown',art:'👑',layer:'front',size:.9,cat:'treasure'},
 ship:{name:'Mini Shipwreck',art:'⛵',layer:'back',size:1.3,cat:'treasure'},
 wheel:{name:'Captain Wheel',art:'☸️',layer:'front',size:1,cat:'treasure'},
 gem:{name:'Ocean Gem',art:'💎',layer:'front',size:.8,cat:'treasure'},
 compass:{name:'Lost Compass',art:'🧭',layer:'front',size:.9,cat:'treasure'},
 pearl:{name:'Giant Pearl',art:'🦪',layer:'front',size:1,cat:'treasure'}
};
let aquaFishActors=[],selectedDecorUid=null,aquaDragState=null,aquaEditMode=false,aquaSheetKind=null,aquaSheetTab='decor',aquaSheetPage=0;
function makeAquaItem(defId,x=.5,y=.78,s=null){let d=studioDecorDefs[defId]||studioDecorDefs.coral;return{uid:'ad_'+now()+'_'+Math.random().toString(36).slice(2,7),def:defId,x,y,s:s||d.size||1,rot:0,layer:d.layer||'back'}}
function defaultAquaItems(){return[makeAquaItem('coral',.34,.82,1.15),makeAquaItem('kelp',.55,.79,1.08),makeAquaItem('shells',.72,.85,.9)]}
function ensureAquaStudioState(){
 if(!state.aqua)state.aqua=defaultState().aqua;
 if(!Array.isArray(state.aqua.items))state.aqua.items=defaultAquaItems();
 if(!Array.isArray(state.aqua.unlockedDecor))state.aqua.unlockedDecor=['coral','kelp','shells'];
 if(!state.aqua.decorInventory||typeof state.aqua.decorInventory!=='object')state.aqua.decorInventory={coral:3,kelp:3,shells:3};
 ['coral','kelp','shells'].forEach(id=>{state.aqua.decorInventory[id]=Math.max(state.aqua.decorInventory[id]||0,3);if(!state.aqua.unlockedDecor.includes(id))state.aqua.unlockedDecor.push(id)});
 state.aqua.unlockedDecor.forEach(id=>{if(studioDecorDefs[id]&&!studioDecorDefs[id].starter&&state.aqua.decorInventory[id]==null)state.aqua.decorInventory[id]=1});
 state.aqua.items.forEach(it=>{if(!it.uid)it.uid='ad_'+Math.random().toString(36).slice(2,8);if(!studioDecorDefs[it.def])it.def='coral';if(it.s==null)it.s=studioDecorDefs[it.def].size||1;if(!it.layer)it.layer=studioDecorDefs[it.def].layer||'back';it.x=clamp(+it.x||.5,.05,.95);it.y=clamp(+it.y||.8,.1,.91)});
 Object.keys(studioDecorDefs).forEach(id=>{let placed=state.aqua.items.filter(x=>x.def===id).length;if(placed>(state.aqua.decorInventory[id]||0))state.aqua.decorInventory[id]=placed});
 if(selectedDecorUid&&!state.aqua.items.some(x=>x.uid===selectedDecorUid))selectedDecorUid=null;
}
function decorOwned(id){ensureAquaStudioState();return state.aqua.decorInventory[id]||0}
function decorPlaced(id){return state.aqua.items.filter(x=>x.def===id).length}
function decorAvailable(id){return Math.max(0,decorOwned(id)-decorPlaced(id))}
function selectedDecor(){ensureAquaStudioState();return state.aqua.items.find(x=>x.uid===selectedDecorUid)||null}
function setAquaEditMode(on){aquaEditMode=!!on;if(!aquaEditMode)selectedDecorUid=null;let stage=$('#aquaStage'),btn=$('#aquaEditBtn');if(stage)stage.classList.toggle('editing',aquaEditMode);if(btn){btn.classList.toggle('active',aquaEditMode);btn.querySelector('b').textContent=aquaEditMode?'DONE':'EDIT'}let label=$('#aquaModeText');if(label)label.textContent=aquaEditMode?'Edit mode · drag, resize, rotate':'Living display';renderAquaEditor();refreshAquaSelection()}
function addDecorToTank(id){ensureAquaStudioState();if(decorAvailable(id)<=0)return toast('No unused '+studioDecorDefs[id].name+' pieces.');let d=studioDecorDefs[id],it=makeAquaItem(id,.5,.7,d.size);state.aqua.items.push(it);selectedDecorUid=it.uid;closeAquaSheet();setAquaEditMode(true);save();renderAquarium();toast(d.name+' added. Drag it into place.')}
function renderAquaEditor(){let item=selectedDecor(),name=$('#aquaEditName'),hint=$('#aquaEditHint'),label=$('#aquaEditLabel');if(item){let d=studioDecorDefs[item.def];if(name)name.textContent=d.name;if(hint)hint.textContent='Drag item to move · drag ⤢ to resize · drag ↻ to rotate';if(label)label.textContent='EDIT MODE · drag handles to transform'}else{if(name)name.textContent='Select an item';if(hint)hint.textContent='Tap a decoration, then drag it or a transform handle.';if(label)label.textContent='EDIT MODE · tap item to edit'}}
function updateAquaItemEl(item){let view=$('#aquaView'),el=view&&view.querySelector('[data-uid="'+item.uid+'"]');if(!el)return;el.style.left=(item.x*100)+'%';el.style.top=(item.y*100)+'%';el.style.fontSize=(33*(item.s||1))+'px';el.style.transform='translate(-50%,-50%) rotate('+(item.rot||0)+'deg)'}
function deleteSelectedDecor(){let item=selectedDecor();if(!item)return;state.aqua.items=state.aqua.items.filter(x=>x.uid!==item.uid);selectedDecorUid=null;aquaDragState=null;save();renderAquarium();toast('Decoration returned to inventory.')}
function refreshAquaSelection(){let view=$('#aquaView');if(view)view.querySelectorAll('.aqua-item').forEach(el=>el.classList.toggle('selected',aquaEditMode&&el.dataset.uid===selectedDecorUid));renderAquaEditor()}
function syncAquaFishActors(force=false){ensureAquaStudioState();let ids=new Set(state.aquarium.map(x=>x.uid));aquaFishActors=aquaFishActors.filter(a=>ids.has(a.uid));state.aquarium.forEach((x,i)=>{let actor=aquaFishActors.find(a=>a.uid===x.uid);if(!actor||force){let size=clamp((x.gene?.size||1),.85,1.45);let lane=((i%5)+1)/6;let next={uid:x.uid,id:x.id,gene:x.gene||{},x:rand(.12,.88),y:clamp(lane+rand(-.13,.13),.16,.84),vx:(Math.random()<.5?-1:1)*(14+Math.random()*17),vy:rand(-4,4),wander:rand(.7,2.8),size};if(actor)Object.assign(actor,next);else aquaFishActors.push(next)}})}
function updateAquariumStudio(dt){let view=$('#aquaView');if(!view||!$('#screen-aquarium').classList.contains('active'))return;syncAquaFishActors();let W=view.clientWidth||320,H=view.clientHeight||380,fishLayer=view.querySelector('#aquaFishLayer');aquaFishActors.forEach((a,i)=>{a.wander-=dt;if(a.wander<=0){a.wander=rand(1.1,3.4);a.vx=clamp(a.vx+rand(-12,12),-30,30);a.vy=clamp(a.vy+rand(-6,6),-9,9)}a.x+=a.vx*dt/W;a.y+=a.vy*dt/H+Math.sin(animT*1.3+i*.7)*.0007;if(a.x<.08){a.x=.08;a.vx=Math.abs(a.vx)}if(a.x>.92){a.x=.92;a.vx=-Math.abs(a.vx)}if(a.y<.13){a.y=.13;a.vy=Math.abs(a.vy)}if(a.y>.87){a.y=.87;a.vy=-Math.abs(a.vy)}let el=fishLayer&&fishLayer.querySelector('[data-fish="'+a.uid+'"]');if(el){let dir=a.vx<0?-1:1;el.style.left=(a.x*100)+'%';el.style.top=(a.y*100)+'%';el.style.transform='translate(-50%,-50%) scaleX('+dir+') scale('+(0.82+a.size*.28)+')'}})}
function tankThemeClass(){ensureAquaStudioState();return themes[state.aqua.theme]?.cls||'theme-reef'}
function itemScreenCenter(item,view){let r=view.getBoundingClientRect();return{x:r.left+item.x*r.width,y:r.top+item.y*r.height}}
function beginAquaGesture(ev,uid,el,mode='move'){if(!aquaEditMode)return;let item=state.aqua.items.find(x=>x.uid===uid),view=$('#aquaView');if(!item||!view)return;selectedDecorUid=uid;let c=itemScreenCenter(item,view);aquaDragState={uid,pointerId:ev.pointerId,mode,startX:ev.clientX,startY:ev.clientY,startItemX:item.x,startItemY:item.y,startScale:item.s||1,startRot:item.rot||0,centerX:c.x,centerY:c.y};if(mode==='resize')aquaDragState.startDist=Math.max(12,Math.hypot(ev.clientX-c.x,ev.clientY-c.y));if(mode==='rotate')aquaDragState.startAngle=Math.atan2(ev.clientY-c.y,ev.clientX-c.x);try{el.setPointerCapture?.(ev.pointerId)}catch(e){}refreshAquaSelection()}
function renderAquarium(){ensureAquaStudioState();let stored=aquariumStored();$('#aquaCount').textContent=state.aquarium.length+'/'+state.aqua.slots;$('#aquaRate').textContent=fmt(aquariumRate());$('#aquaStored').textContent=fmt(stored);$('#aquaHappy').textContent=aquariumHappiness()+'%';$('#claimAqua').disabled=stored<=0;let view=$('#aquaView');view.className='aqua-view '+tankThemeClass();view.innerHTML='<div class="aqua-layer aqua-decor-layer" id="aquaDecorLayer"></div><div class="aqua-layer aqua-fish-layer" id="aquaFishLayer"></div><div class="bubbles"></div>';
 let dl=$('#aquaDecorLayer');state.aqua.items.forEach(it=>{let d=studioDecorDefs[it.def],el=document.createElement('div');el.className='aqua-item '+(it.layer||d.layer||'back')+(aquaEditMode&&selectedDecorUid===it.uid?' selected':'');el.dataset.uid=it.uid;el.innerHTML='<span class="aqua-art">'+d.art+'</span><button class="aqua-action-handle aqua-size-handle" type="button" aria-label="Drag to resize decoration">⤢</button><button class="aqua-action-handle aqua-delete-handle" type="button" aria-label="Remove decoration">×</button><button class="aqua-action-handle aqua-rotate-handle" type="button" aria-label="Drag to rotate decoration">↻</button>';dl.appendChild(el);updateAquaItemEl(it);el.addEventListener('pointerdown',ev=>{if(!aquaEditMode)return;let sizeBtn=ev.target.closest('.aqua-size-handle'),delBtn=ev.target.closest('.aqua-delete-handle'),rotBtn=ev.target.closest('.aqua-rotate-handle');if(delBtn){ev.preventDefault();ev.stopPropagation();selectedDecorUid=it.uid;deleteSelectedDecor();return}if(sizeBtn){ev.preventDefault();ev.stopPropagation();beginAquaGesture(ev,it.uid,el,'resize');return}if(rotBtn){ev.preventDefault();ev.stopPropagation();beginAquaGesture(ev,it.uid,el,'rotate');return}ev.preventDefault();ev.stopPropagation();beginAquaGesture(ev,it.uid,el,'move')})});
 let fl=$('#aquaFishLayer');state.aquarium.forEach(x=>{let el=document.createElement('div');el.className='aqua-fish';el.dataset.fish=x.uid;el.innerHTML=fishSvg(x.id,x.gene);fl.appendChild(el)});syncAquaFishActors(false);updateAquariumStudio(0);
 view.onpointerdown=ev=>{if(aquaEditMode&&(ev.target===view||ev.target.classList.contains('bubbles')||ev.target.id==='aquaFishLayer'||ev.target.id==='aquaDecorLayer')){selectedDecorUid=null;refreshAquaSelection()}};
 setAquaEditMode(aquaEditMode);if(aquaSheetKind)renderAquaSheet()}
function aquariumPointerMove(ev){if(!aquaEditMode||!aquaDragState||aquaDragState.pointerId!==ev.pointerId)return;let item=state.aqua.items.find(x=>x.uid===aquaDragState.uid),view=$('#aquaView');if(!item||!view)return;ev.preventDefault();let r=view.getBoundingClientRect(),g=aquaDragState;if(g.mode==='resize'){let dist=Math.max(8,Math.hypot(ev.clientX-g.centerX,ev.clientY-g.centerY));item.s=clamp(g.startScale*(dist/g.startDist),.5,3)}else if(g.mode==='rotate'){let angle=Math.atan2(ev.clientY-g.centerY,ev.clientX-g.centerX),delta=angle-g.startAngle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;item.rot=((g.startRot+delta*180/Math.PI)%360+360)%360}else{item.x=clamp(g.startItemX+(ev.clientX-g.startX)/r.width,.06,.94);item.y=clamp(g.startItemY+(ev.clientY-g.startY)/r.height,.1,.9)}updateAquaItemEl(item);selectedDecorUid=item.uid;refreshAquaSelection()}
function aquariumPointerUp(ev){if(!aquaDragState||aquaDragState.pointerId!==ev.pointerId)return;aquaDragState=null;save()}
window.addEventListener('pointermove',aquariumPointerMove,{passive:false});window.addEventListener('pointerup',aquariumPointerUp);window.addEventListener('pointercancel',aquariumPointerUp);
function openAquaSheet(kind,tab){aquaSheetKind=kind;aquaSheetTab=tab||((kind==='inventory')?'decor':'');aquaSheetPage=0;let s=$('#aquaSheet');s.classList.add('open');s.setAttribute('aria-hidden','false');renderAquaSheet()}
function closeAquaSheet(){aquaSheetKind=null;let s=$('#aquaSheet');if(s){s.classList.remove('open');s.setAttribute('aria-hidden','true')}}
function pageSlice(arr,size){let pages=Math.max(1,Math.ceil(arr.length/size));aquaSheetPage=clamp(aquaSheetPage,0,pages-1);return{items:arr.slice(aquaSheetPage*size,aquaSheetPage*size+size),pages}}
function renderPager(pages){let p=$('#aquaSheetPager');p.innerHTML='';if(pages<=1)return;let prev=document.createElement('button'),next=document.createElement('button'),txt=document.createElement('span');prev.textContent='‹';next.textContent='›';txt.textContent=(aquaSheetPage+1)+' / '+pages;prev.disabled=aquaSheetPage<=0;next.disabled=aquaSheetPage>=pages-1;prev.onclick=()=>{aquaSheetPage--;renderAquaSheet()};next.onclick=()=>{aquaSheetPage++;renderAquaSheet()};p.append(prev,txt,next)}
function renderAquaSheet(){let title=$('#aquaSheetTitle'),sub=$('#aquaSheetSub'),tabs=$('#aquaSheetTabs'),body=$('#aquaSheetBody'),pager=$('#aquaSheetPager');if(!aquaSheetKind)return;tabs.innerHTML='';body.innerHTML='';pager.innerHTML='';
 if(aquaSheetKind==='inventory'){title.textContent='ADD TO AQUARIUM';sub.textContent='Your collection stays here — not on the main screen.';['decor','theme'].forEach(t=>{let b=document.createElement('button');b.textContent=t==='decor'?'DECOR':'THEMES';b.className=aquaSheetTab===t?'active':'';b.onclick=()=>{aquaSheetTab=t;aquaSheetPage=0;renderAquaSheet()};tabs.appendChild(b)});if(aquaSheetTab==='theme'){let g=document.createElement('div');g.className='aqua-theme-grid';Object.entries(themes).forEach(([id,t])=>{let b=document.createElement('button');b.className='aqua-theme-card'+(state.aqua.theme===id?' active':'');b.style.background=id==='reef'?'linear-gradient(#4f9cab,#155d78)':id==='moon'?'linear-gradient(#60728d,#173b5e)':id==='kelp'?'linear-gradient(#5e9b7e,#1a5f55)':'linear-gradient(#718384,#28515b)';b.innerHTML='<b>'+t.name+'</b>';b.onclick=()=>{state.aqua.theme=id;save();renderAquarium();renderAquaSheet()};g.appendChild(b)});body.appendChild(g);return}let ids=Object.keys(studioDecorDefs).filter(id=>decorOwned(id)>0);let page=pageSlice(ids,6),g=document.createElement('div');g.className='aqua-inventory-grid';page.items.forEach(id=>{let d=studioDecorDefs[id],avail=decorAvailable(id),b=document.createElement('button');b.className='aqua-inventory-item';b.disabled=avail<=0;b.innerHTML='<span class="count">'+avail+'/'+decorOwned(id)+'</span><div class="art">'+d.art+'</div><b>'+d.name+'</b><small>'+(avail?'Tap to place':'All placed')+'</small>';b.onclick=()=>addDecorToTank(id);g.appendChild(b)});body.appendChild(g);renderPager(page.pages);return}
 if(aquaSheetKind==='care'){title.textContent='AQUARIUM CARE';sub.textContent='Maintenance and upgrades, kept out of the main view.';let g=document.createElement('div');g.className='aqua-care-grid';let actions=[['🍽️','Feed fish','Boost happiness 30 min',()=>{feedAquarium();renderAquaSheet()}],['✨','Clean tank','Restore cleanliness',()=>{cleanAquarium();renderAquaSheet()}],['↔','Expand tank',state.aqua.slots+' slots',()=>{expandAquarium();renderAquaSheet()}],['⬆','Upgrade tank','Level '+state.aqua.level,()=>{upgradeTank();renderAquaSheet()}]];actions.forEach(a=>{let b=document.createElement('button');b.className='aqua-care-card';b.innerHTML='<span>'+a[0]+'</span><b>'+a[1]+'</b><small>'+a[2]+'</small>';b.onclick=a[3];g.appendChild(b)});body.appendChild(g);return}
 if(aquaSheetKind==='fish'){title.textContent='YOUR FISH';sub.textContent='Manage aquarium residents.';let page=pageSlice(state.aquarium,4),g=document.createElement('div');g.className='aqua-fish-grid';page.items.forEach(x=>{let f=allDefs()[x.id],c=document.createElement('div');c.className='aqua-fish-card';c.innerHTML='<div class="fishpic">'+fishSvg(x.id,x.gene)+'</div><div><b>'+instanceName(x)+'</b><small>'+f.name+' · x'+(x.gene?.value||1).toFixed(2)+'</small><div class="mini-actions"><button class="sell">SELL</button></div></div>';c.querySelector('.sell').onclick=()=>{let i=state.aquarium.findIndex(q=>q.uid===x.uid);if(i<0)return;state.gold+=Math.round(f.value*(x.gene?.value||1));state.aquarium.splice(i,1);state.hatchery.parents=state.hatchery.parents.filter(u=>u!==x.uid);aquaFishActors=aquaFishActors.filter(a=>a.uid!==x.uid);save();renderAquarium();renderAquaSheet()};g.appendChild(c)});if(!page.items.length){body.innerHTML='<div class="hatch-status-compact"><div class="copy"><b>No fish yet</b><small>Catch a fish and choose AQUARIUM.</small></div></div>'}else body.appendChild(g);renderPager(page.pages);return}
 if(aquaSheetKind==='hatch'){title.textContent='HATCHERY';sub.textContent='Breeding is now part of the aquarium workspace.';let wrap=document.createElement('div');wrap.className='aqua-hatch-layout';let status=document.createElement('div');status.className='hatch-status-compact';let egg=state.hatchery.egg;if(egg){let left=Math.max(0,egg.ready-now());status.innerHTML='<div class="egg-mini">◉</div><div class="copy"><b>'+(left<=0?'Egg ready!':'Incubating')+'</b><small>'+(left<=0?'Ready to hatch':Math.ceil(left/1000)+' sec remaining')+'</small></div><button>'+(left<=0?'HATCH':'HATCH EARLY')+'</button>';status.querySelector('button').onclick=()=>{hatchEgg(false);renderAquaSheet()}}else{let names=state.hatchery.parents.map(u=>{let q=state.aquarium.find(x=>x.uid===u);return q?instanceName(q):'?'});status.innerHTML='<div class="egg-mini">♡</div><div class="copy"><b>'+(names.length?names.join(' + '):'Choose two parents')+'</b><small>Tap fish below to select breeders.</small></div><button '+(state.hatchery.parents.length!==2?'disabled':'')+'>BREED</button>';status.querySelector('button').onclick=()=>{breedSelected();renderAquaSheet()}}wrap.appendChild(status);let page=pageSlice(state.aquarium,4),g=document.createElement('div');g.className='aqua-fish-grid';page.items.forEach(x=>{let f=allDefs()[x.id],sel=state.hatchery.parents.includes(x.uid),c=document.createElement('button');c.className='aqua-fish-card'+(sel?' selected':'');c.innerHTML='<div class="fishpic">'+fishSvg(x.id,x.gene)+'</div><div><b>'+instanceName(x)+'</b><small>'+f.name+(sel?' · PARENT':' · tap to select')+'</small></div>';c.onclick=()=>{toggleBreeder(x.uid);renderAquaSheet()};g.appendChild(c)});wrap.appendChild(g);body.appendChild(wrap);renderPager(page.pages);return}}

function maybeFindTreasureDecor(){ensureAquaStudioState();if(Math.random()>.62)return null;let pool=Object.keys(studioDecorDefs).filter(id=>!studioDecorDefs[id].starter),id=pool[Math.floor(Math.random()*pool.length)];state.aqua.decorInventory[id]=(state.aqua.decorInventory[id]||0)+1;if(!state.aqua.unlockedDecor.includes(id))state.aqua.unlockedDecor.push(id);return id}
function landSpecial(s){haptic('treasure');specialPending=s;let w=ensureWorldState();if(s.type==='chest'){let g=Math.floor(rand(100,500)*(1+state.region*.25)),pearl=Math.random()<.18?1:0,wood=Math.max(1,Math.floor(rand(1,4)*salvageYieldMultiplier())),shell=Math.floor(rand(0,3)),decor=maybeFindTreasureDecor();state.gold+=g;state.pearls+=pearl;state.wood+=wood;state.shells+=shell;state.materialsFound+=wood+shell;$('#specialTitle').textContent='Treasure Chest';$('#specialArt').textContent=decor?studioDecorDefs[decor].art:'▣';$('#specialName').textContent=decor?'Aquarium Treasure: '+studioDecorDefs[decor].name:'Saltworn Cache';$('#specialMeta').textContent=`${g} gold · ${wood} wood · ${shell} shells${pearl?' · 1 pearl':''}${decor?' · '+studioDecorDefs[decor].name+' added to aquarium inventory':''}`;tone(820,.08)}else if(s.type==='bottle'){let g=Math.floor(rand(90,220)*(1+state.region*.12));w.messagesFound++;w.chartLuckUntil=Math.max(w.chartLuckUntil||0,now()+5*60000);state.gold+=g;state.shells+=1;$('#specialTitle').textContent='Message in a Bottle';$('#specialArt').textContent='✉';$('#specialName').textContent='Saltworn Chart Fragment';$('#specialMeta').textContent=`${g} gold · 1 shell · rare-fish sightings improved for 5 minutes.`;tone(760,.09);setTimeout(()=>tone(960,.07),80)}else if(s.type==='debris'){let wood=Math.max(1,Math.floor(rand(2,6)*salvageYieldMultiplier())),shell=Math.random()<.45?1:0;w.debrisFound++;state.wood+=wood;state.shells+=shell;state.materialsFound+=wood+shell;$('#specialTitle').textContent='Drifting Wreckage';$('#specialArt').textContent='▰';$('#specialName').textContent='Salvaged Timber';$('#specialMeta').textContent=`${wood} wood${shell?' · 1 shell':''}. The current carried it here.`;tone(520,.07)}else{let r=relicDefs.find(x=>x.id===s.id);if(r&&!state.relics.includes(r.id)){state.relics.push(r.id);state.pearls++;state.secrets[state.region]=(state.secrets[state.region]||0)+1}$('#specialTitle').textContent='Ancient Relic';$('#specialArt').textContent=r?r.icon:'◈';$('#specialName').textContent=r?r.name:'Unknown Relic';$('#specialMeta').textContent=r?r.desc:'Recovered from a submerged ruin.';tone(900,.12)}$('#specialModal').classList.add('show');save();renderAll()}


// Pirate Map + component-based Dock Builder
const regionLayout=[{x:180,y:520},{x:330,y:405},{x:500,y:325},{x:650,y:430},{x:805,y:285},{x:965,y:180},{x:1110,y:330}];
