/* Tide living ocean, conditions, events, and spawning */
'use strict';
const OCEAN_DAY_MS=12*60*1000;
let oceanRuntime={phase:.32,tide:0,current:0,event:null,eventUntil:0,nextEvent:performance.now()+rand(9000,16000),eventX:W*.65,eventDepth:120,cinema:0,lastHud:0,gestureX:0,gestureY:0,gestureAt:0,ambientUntil:0,ambientKind:null,schoolSerial:1};
function ensureWorldState(){if(!state.world)state.world={cycleStart:now()-OCEAN_DAY_MS*.3,eventsSeen:0,messagesFound:0,debrisFound:0,chartLuckUntil:0};if(!Number.isFinite(state.world.cycleStart))state.world.cycleStart=now()-OCEAN_DAY_MS*.3;return state.world}
function oceanCycle(){let w=ensureWorldState(),phase=(((now()-w.cycleStart)%OCEAN_DAY_MS)+OCEAN_DAY_MS)%OCEAN_DAY_MS/OCEAN_DAY_MS;let label='DAY',short='DAY',light=1;if(phase<.16){label='Night';short='NIGHT';light=.18}else if(phase<.25){label='Dawn';short='DAWN';light=.55+(phase-.16)/.09*.45}else if(phase<.62){label='Day';short='DAY';light=1}else if(phase<.73){label='Golden Hour';short='GOLDEN';light=.94}else if(phase<.82){label='Dusk';short='DUSK';light=.5}else{label='Night';short='NIGHT';light=.18}return{phase,label,short,light,night:phase<.16||phase>=.82,twilight:(phase>=.16&&phase<.25)||(phase>=.73&&phase<.82)}}
function oceanCondition(){let c=oceanCycle(),tide=Math.sin(c.phase*TAU*2+state.region*.73),weather=state.weather.type,weatherPush=weather==='storm'?1.8:weather==='wind'?1.45:weather==='rain'?1.15:1,base=2.1+state.region*.85,current=Math.sin(c.phase*TAU*2.6+state.region*1.12)*base*weatherPush;oceanRuntime.phase=c.phase;oceanRuntime.tide=tide;oceanRuntime.current=current;return{...c,tide,current}}
function currentLabel(v){let a=Math.abs(v);if(a<1.4)return'CALM';return(a<4?'GENTLE ':a<7?'STEADY ':'STRONG ')+(v>0?'→':'←')}
function eventDefinition(type){return{
 frenzy:{name:'FEEDING FRENZY',bite:1.55,rare:1.15,desc:'Birds mark a bait ball. Work your lure through it.'},
 migration:{name:'MIGRATION',bite:1.28,rare:1.28,desc:'A large school is crossing this water.'},
 bloom:{name:'NIGHT BLOOM',bite:1.22,rare:1.38,desc:'Bioluminescent plankton draws deep-water fish.'},
 glass:{name:'GLASS WATER',bite:1.16,rare:1.08,desc:'A quiet window makes subtle bites easier to read.'}
}[type]||{name:'OPEN WATER',bite:1,rare:1,desc:'The ocean is settled.'}}
function activeOceanEvent(){if(!oceanRuntime.event||performance.now()>oceanRuntime.eventUntil)return null;return eventDefinition(oceanRuntime.event)}
function startOceanEvent(type){oceanRuntime.event=type;oceanRuntime.eventUntil=performance.now()+rand(26000,42000);oceanRuntime.eventX=rand(W*.34,W*.82);oceanRuntime.eventDepth=type==='bloom'?rand(currentRegion().depth*.48,currentRegion().depth*.8):rand(55,Math.min(currentRegion().depth*.55,260));oceanRuntime.nextEvent=oceanRuntime.eventUntil+rand(35000,65000);ensureWorldState().eventsSeen++;if(type==='frenzy'){for(let i=0;i<5;i++)spawnFish(false,{x:oceanRuntime.eventX+rand(-55,55),depth:oceanRuntime.eventDepth+rand(-24,24),school:'frenzy'})}else if(type==='migration'){for(let i=0;i<4;i++)spawnFish(i===3,{x:rand(-30,40),depth:oceanRuntime.eventDepth+rand(-45,45),school:'migration'})}else if(type==='bloom'){for(let i=0;i<3;i++)spawnFish(true,{depth:oceanRuntime.eventDepth+rand(-60,60),school:'bloom'})}let e=eventDefinition(type);toast(e.name+': '+e.desc);tone(type==='bloom'?520:640,.06,'sine',.018);renderOceanHud(true)}
function updateOceanEvents(dt){let c=oceanCondition(),t=performance.now();if(oceanRuntime.event&&t>oceanRuntime.eventUntil)oceanRuntime.event=null;if(!oceanRuntime.event&&t>oceanRuntime.nextEvent){let type=c.night&&state.region>=3?'bloom':state.weather.type==='clear'&&Math.random()<.22?'glass':Math.random()<.55?'frenzy':'migration';startOceanEvent(type)}if(!oceanRuntime.ambientKind&&Math.random()<dt*.014){oceanRuntime.ambientKind=c.night?'glow':'dolphin';oceanRuntime.ambientUntil=t+rand(3500,6500)}if(oceanRuntime.ambientKind&&t>oceanRuntime.ambientUntil)oceanRuntime.ambientKind=null;if(oceanRuntime.cinema>0)oceanRuntime.cinema=Math.max(0,oceanRuntime.cinema-dt*.11);if(hook.actionEnergy)hook.actionEnergy=Math.max(0,hook.actionEnergy-dt*.34);renderOceanHud()}
function renderOceanHud(force=false){let t=performance.now();if(!force&&t-oceanRuntime.lastHud<220)return;oceanRuntime.lastHud=t;let c=oceanCondition(),ev=activeOceanEvent(),time=$('#oceanTime'),cur=$('#oceanCurrent'),event=$('#oceanEvent'),act=$('#lureActionChip');if(time)time.textContent=c.short;if(cur)cur.textContent=currentLabel(c.current);if(event){event.textContent=ev?ev.name:(state.weather.type==='storm'?'STORM FEEDING':c.twilight?'TWILIGHT BITE':'OPEN WATER');event.classList.toggle('live',!!ev||state.weather.type==='storm')}if(act){let sinking=hook.mode==='sinking';let energy=hook.actionEnergy||0;act.classList.toggle('show',sinking);act.classList.toggle('hot',sinking&&energy>.45);act.textContent=sinking?((hook.action||'STILL')+(energy>.45?' · ACTIVE':' · GENTLE')):'LURE STILL'}}
function fishActivityMultiplier(id,f){let c=oceanCycle(),deep=fishDepthProfile(f)==='deep',nightNamed=/moon|night|ghost|star|abyss|lantern/i.test(id+f.name);let m=1;if(c.twilight)m*=1.24;if(c.night){m*=deep?1.38:.78;if(nightNamed)m*=1.48}else if(nightNamed)m*=.82;return m}
function eventFishMultiplier(f){let ev=activeOceanEvent();if(!ev)return 1;if(oceanRuntime.event==='frenzy')return f.temper==='school'||f.temper==='hunter'?1.48:1.06;if(oceanRuntime.event==='migration')return f.temper==='school'?1.55:f.tier>=3?1.16:1;if(oceanRuntime.event==='bloom')return fishDepthProfile(f)==='deep'?1.62:1;if(oceanRuntime.event==='glass')return f.temper==='shy'||f.temper==='calm'?1.32:1.08;return 1}
function lureActionMultiplier(l){let e=hook.actionEnergy||0,a=hook.action||'STILL';if(!e)return(l.tag==='scent'||l.tag==='treasure')?1.1:.92;if(l.tag==='deep')return a==='JIG'?1+e*.55:1+e*.12;if(l.tag==='predator')return a==='SWEEP'?1+e*.48:1+e*.2;if(l.tag==='flash')return(a==='SWEEP'||a==='TWITCH')?1+e*.5:1+e*.12;if(l.tag==='surface')return a==='TWITCH'?1+e*.55:1+e*.18;if(l.tag==='scent')return 1+Math.min(.18,e*.12);return 1+e*.08}
function chartLuckMultiplier(){return now()<(ensureWorldState().chartLuckUntil||0)?1.28:1}
function castBaitDef(){return baitDefs[hook.bait||0]||baitDefs[0]}
function castHookId(){return hook.hookType&&hookDefs[hook.hookType]?hook.hookType:state.selectedHook}
function castHookDef(){return hookDefs[castHookId()]||hookDefs.standard}
function castLineDepth(){let l=lureDefs[hook.lure]||lureDefs[state.selectedLure]||lureDefs.none;return Math.round(230+(gearStat('line')-1)*62+(l.depth||0))}

function resetHook(){hook={mode:'idle',x:125,y:waterY-16,vx:0,vy:0,targetX:240,power:0,fish:null,tension:0,stamina:0,maxStamina:0,reeling:false,lure:'none',bait:0,hookType:state.selectedHook,carry:null,fightTimer:0,burstTimer:0,burstText:'',pullX:0,pullY:0,action:'STILL',actionEnergy:0,jigImpulse:0};powering=false;$('#oceanHud')?.classList.remove('fighting');$('#tension').classList.remove('show');$('#castBtn').textContent='CAST';$('#castBtn').classList.remove('warn');$('#seaHint').textContent='Tap water to aim. Hold CAST, release to throw.';renderOceanHud(true)}
function chooseFishId(forceRare=false){let pool=Object.entries(fishDefs).filter(([id,f])=>f.regs.includes(state.region)&&f.min<currentRegion().depth);let w=state.weather.type,active=state.hunts.active,leg=null,ev=activeOceanEvent(),rareBoost=(activeBaitDef().rare||1)*(activeHookDef().rare||1)*chartLuckMultiplier()*(ev?ev.rare:1)*captainRareBonus()*rodBuildBonuses().rare*boatFishingBonuses().rare;if(active&&legendaryDefs[active]&&legendaryDefs[active].region===state.region){let chance=(w==='storm'?.075:.032)*(state.selectedHook==='heavy'?1.55:state.selectedHook==='large'?1.25:.5)*rareBoost;if(Math.random()<chance)leg=active}if(leg)return leg;let total=0,arr=pool.map(([id,f])=>{let weight=Math.max(.08,7-f.tier*1.2)*fishActivityMultiplier(id,f)*eventFishMultiplier(f);if(forceRare)weight*=f.tier>=3?3.2:.32;if(f.tier>=4)weight*=rareBoost;if(w==='storm'&&f.tier>=4)weight*=1.75;if(w==='rain'&&f.temper==='curious')weight*=1.4;total+=weight;return{id,f,weight}});let r=Math.random()*Math.max(.01,total);for(const q of arr){r-=q.weight;if(r<=0)return q.id}return arr[0]?arr[0].id:'silverfin'}
function spawnFish(forceRare=false,opts={}){if(fish.length>30)return;let id=opts.id||chooseFishId(forceRare),f=allDefs()[id];if(!f)return;let maxD=Math.max(Math.max(35,f.min+8),Math.min(currentRegion().depth-20,f.max)),d=opts.depth!=null?clamp(opts.depth,28,currentRegion().depth-20):rand(Math.max(25,f.min),maxD),fromLeft=opts.x==null?Math.random()<.5:opts.x<W*.5,school=opts.school||((f.temper==='school')?'s'+(oceanRuntime.schoolSerial++%5):'solo'+Math.random());let q={id,x:opts.x!=null?opts.x:(fromLeft?-55:W+55),y:depthToY(d),vx:(fromLeft?1:-1)*f.speed*rand(.72,1.12),vy:rand(-4,4),dir:fromLeft?1:-1,state:'cruise',think:rand(.8,2.6),appetite:rand(.45,1),sonarUntil:0,school,hooked:false,burst:0,turn:0};fish.push(q);if(!opts.noGroup&&f.temper==='school'&&fish.length<27&&Math.random()<.16){let n=1+Math.floor(Math.random()*2);for(let i=0;i<n;i++)spawnFish(false,{id,x:q.x+rand(-45,45),depth:d+rand(-18,18),school,noGroup:true})}}
function maybeSpawnSpecial(){if(specials.length>4)return;let lure=lureDefs[state.selectedLure]||lureDefs.none,ch=.009+(lure.chest||0),luck=chartLuckMultiplier()*captainExplorerBonus()*boatFishingBonuses().special;if(Math.random()<ch*luck)specials.push({type:'chest',x:rand(70,W-50),y:depthToY(rand(90,Math.min(currentRegion().depth-30,lineDepth()))),bob:rand(0,TAU)});if(Math.random()<.0045&&!specials.some(s=>s.type==='bottle'))specials.push({type:'bottle',x:rand(70,W-50),y:depthToY(rand(30,Math.min(170,currentRegion().depth*.55))),bob:rand(0,TAU)});if(Math.random()<.006&&!specials.some(s=>s.type==='debris'))specials.push({type:'debris',x:rand(65,W-45),y:depthToY(rand(35,Math.min(210,currentRegion().depth*.65))),bob:rand(0,TAU)});if(currentRegion().ruin&&sonar&&Math.random()<.12){let relic=relicDefs.find(r=>r.region===state.region&&!state.relics.includes(r.id));if(relic&&!specials.some(s=>s.type==='relic'))specials.push({type:'relic',id:relic.id,x:rand(100,W-70),y:depthToY(rand(currentRegion().depth*.58,currentRegion().depth*.88)),bob:rand(0,TAU)})}}
function updateWeather(force=false){let w=state.weather;if(force||now()>=w.until){let type=pick(currentRegion().weather);w.type=type;w.until=now()+rand(70000,150000);w.lightningAt=now()+rand(8000,20000);renderTop();updateSoundscape()}if(w.type==='storm'&&now()>w.lightningAt){screenShake=5;w.lightningAt=now()+rand(7000,16000);tone(75,.16,'sawtooth')}}
function weatherLabel(){return{clear:'CLEAR',mist:'MIST',rain:'RAIN',wind:'WIND',storm:'STORM'}[state.weather.type]||'CLEAR'}
