/* Tide navigation, pointer controls, save tools, and core input */
'use strict';
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
$$('.nav').forEach(b=>b.addEventListener('click',()=>{haptic('select');ensureAudio();
 $$('.nav').forEach(x=>{let active=x===b;x.classList.toggle('active',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});
 $$('.screen').forEach(x=>x.classList.toggle('active',x.id==='screen-'+b.dataset.screen));
 document.body.classList.toggle('aquarium-active',b.dataset.screen==='aquarium');
 if(b.dataset.screen==='map'){renderWorldMap();requestAnimationFrame(fitWorldMap)}
 if(b.dataset.screen==='dock')renderDockBuilder();
 if(b.dataset.screen==='aquarium')renderAquarium();
 if(b.dataset.screen==='journal'){renderBook();renderHunts();renderRelics();renderCaptainLog()}
}));
$('#huntBtn').addEventListener('click',openHuntModal);$('#sonarBtn').addEventListener('click',sonarPing);$('#tackleOpen').addEventListener('click',openTackle);document.querySelectorAll('#tackleTabs button').forEach(b=>b.addEventListener('click',()=>{tackleTab=b.dataset.tackleTab;tacklePage=0;renderTackleSheet()}));
$('#lureSelect').addEventListener('change',e=>{state.selectedLure=e.target.value;save();renderAll()});$('#baitSelect').addEventListener('change',e=>{state.selectedBait=+e.target.value||0;save();renderStatus()});
let castAimX=W*.72,castDragStartX=0,castDragBaseAim=castAimX;function setCastAimX(x,feedback=false){castAimX=clamp(x,24,W-24);if(feedback&&hook.mode==='idle')haptic('select')}const castBtn=$('#castBtn');castBtn.addEventListener('pointerdown',e=>{e.preventDefault();castDragStartX=e.clientX;castDragBaseAim=castAimX;try{castBtn.setPointerCapture?.(e.pointerId)}catch(_){}if(hook.mode==='idle')castStart();else reelPress(true)});castBtn.addEventListener('pointermove',e=>{if(!powering)return;let r=canvas.getBoundingClientRect(),scale=W/Math.max(1,r.width),dx=(e.clientX-castDragStartX)*scale;setCastAimX(castDragBaseAim+dx*1.25)});castBtn.addEventListener('pointerup',e=>{e.preventDefault();try{castBtn.releasePointerCapture?.(e.pointerId)}catch(_){}if(powering)castRelease();reelPress(false)});castBtn.addEventListener('pointercancel',e=>{try{castBtn.releasePointerCapture?.(e.pointerId)}catch(_){}if(powering)castRelease();reelPress(false)});castBtn.addEventListener('pointerleave',()=>{if(hook.mode==='hooked')reelPress(false)});
let castAimPointer=null;function castAimFromEvent(e,feedback=false){let r=canvas.getBoundingClientRect();setCastAimX((e.clientX-r.left)/Math.max(1,r.width)*W,feedback);$('#seaHint').textContent=(castAimX<rodTip().x?'Aiming left':'Aiming right')+' · Hold CAST, then release.'}canvas.addEventListener('pointerdown',e=>{if(hook.mode!=='idle'||powering)return;e.preventDefault();castAimPointer=e.pointerId;try{canvas.setPointerCapture?.(e.pointerId)}catch(_){}castAimFromEvent(e,true)},{passive:false});canvas.addEventListener('pointermove',e=>{if(castAimPointer!==e.pointerId||hook.mode!=='idle'||powering)return;e.preventDefault();castAimFromEvent(e,false)},{passive:false});function endCastAim(e){if(castAimPointer!==e.pointerId)return;try{canvas.releasePointerCapture?.(e.pointerId)}catch(_){}castAimPointer=null}canvas.addEventListener('pointerup',endCastAim,{passive:false});canvas.addEventListener('pointercancel',endCastAim,{passive:false});
let canvasPointerId=null,canvasLastY=0;
canvas.addEventListener('pointerdown',e=>{if(!['sinking','hooked'].includes(hook.mode))return;e.preventDefault();canvasPointerId=e.pointerId;canvas.setPointerCapture?.(e.pointerId);let r=canvas.getBoundingClientRect();hook.targetX=clamp((e.clientX-r.left)/r.width*W,24,W-24);canvasLastY=(e.clientY-r.top)/r.height*H},{passive:false});
canvas.addEventListener('pointermove',e=>{if(canvasPointerId!==e.pointerId||!['sinking','hooked'].includes(hook.mode))return;e.preventDefault();let r=canvas.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width*W,24,W-24),y=clamp((e.clientY-r.top)/r.height*H,waterY,H-20),dx=x-hook.x,dy=y-canvasLastY;if(hook.mode==='sinking'){let action=Math.abs(dy)>Math.abs(dx)*1.15?'JIG':Math.abs(dx)>10?'SWEEP':'TWITCH';hook.action=action;hook.actionEnergy=clamp((hook.actionEnergy||0)+.22+Math.min(.38,Math.hypot(dx,dy)/90),0,1);if(action==='JIG')hook.jigImpulse=clamp((hook.jigImpulse||0)-dy/20,-1.4,1.4);renderOceanHud(true)}hook.targetX=x;if(hook.mode==='hooked'){hook.pullX-=clamp(dx/130,-.35,.35);hook.pullY-=clamp(dy/85,-.28,.28)}canvasLastY=y},{passive:false});
function endCanvasPointer(e){if(canvasPointerId!==e.pointerId)return;e.preventDefault();try{canvas.releasePointerCapture?.(e.pointerId)}catch(_){}canvasPointerId=null}
canvas.addEventListener('pointerup',endCanvasPointer,{passive:false});canvas.addEventListener('pointercancel',endCanvasPointer,{passive:false});
canvas.addEventListener('touchmove',e=>{if(['sinking','hooked','casting'].includes(hook.mode))e.preventDefault()},{passive:false});
$('#steerBtn').addEventListener('click',()=>toast(hook.mode==='hooked'?'Drag opposite the fish pull to reduce surges.':hook.mode==='sinking'?'Drag directly on the water to steer the lure.':'Cast first, then drag across the water.'));
$('#claimAqua').addEventListener('click',claimAquarium);$('#feedAqua').addEventListener('click',feedAquarium);$('#cleanAqua').addEventListener('click',cleanAquarium);$('#slotUpgrade').addEventListener('click',expandAquarium);$('#tankUpgrade').addEventListener('click',upgradeTank);$('#breedBtn').addEventListener('click',breedSelected);$('#hatchNowBtn').addEventListener('click',()=>hatchEgg(false));
$('#sellCatch').addEventListener('click',()=>catchAction('sell'));$('#aquaCatch').addEventListener('click',()=>catchAction('aqua'));$('#baitCatch').addEventListener('click',()=>catchAction('bait'));
$('#exportBtn').addEventListener('click',()=>{saveMode='export';$('#saveTitle').textContent='Export Save';$('#saveText').value=encodeSaveData(state);$('#saveAction').textContent='SELECT TEXT';$('#saveModal').classList.add('show')});
$('#importBtn').addEventListener('click',()=>{saveMode='import';$('#saveTitle').textContent='Import Save';$('#saveText').value='';$('#saveAction').textContent='IMPORT SAVE';$('#saveModal').classList.add('show')});
$('#saveAction').addEventListener('click',()=>{if(saveMode==='export'){let e=$('#saveText');e.focus();e.select();toast('Save text selected. Use Android Copy.')}else{try{state=sanitizeState(decodeSaveData($('#saveText').value));ensureAquaStudioState();ensureDockBuilderState();save();applyPreferences();closeModal('saveModal');fish=[];specials=[];resetHook();for(let i=0;i<12;i++)spawnFish();renderAll();haptic('success');toast('Save imported.')}catch(error){console.warn('[Tide & Tranquility] Import failed.',error);haptic('error');toast('Invalid save text.')}}});
$('#resetBtn').addEventListener('click',()=>{if(!confirm('Factory reset Tide & Tranquility? This erases all progress.'))return;if(!confirm('Final confirmation: erase everything and start over?'))return;try{localStorage.removeItem('tideTranquilitySaveV2');localStorage.removeItem('tideTranquilitySaveV2Backup');localStorage.removeItem('tideTranquilitySave')}catch(e){}state=defaultState();ensureAquaStudioState();aquaFishActors=[];selectedDecorUid=null;fish=[];specials=[];resetHook();for(let i=0;i<12;i++)spawnFish();updateWeather(true);save();applyPreferences();renderAll();haptic('success');toast('Factory reset complete.')});
// Prevent Android long-press text selection/callouts on game UI. Save textarea remains exempt.
$('#app').addEventListener('contextmenu',e=>{if(e.target.closest('textarea,input,.selectable'))return;e.preventDefault()});document.addEventListener('pointerdown',e=>{ensureAudio();if(e.target.closest('button:not(:disabled),select'))haptic('tap')},{capture:true,passive:true,once:false});
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();clearTimeout(musicTimer)}else{updateOffline();ensureAudio();applyPreferences();renderAll()}});
