/* Tide HUD, missions, catches, sonar, and tackle UI */
'use strict';
function renderTop(){let r=currentRegion();$('#goldTxt').textContent=fmt(state.gold);$('#pearlTxt').textContent=fmt(state.pearls);$('#journalGold')&&($('#journalGold').textContent=fmt(state.gold));$('#regionKicker').textContent='REGION '+(state.region+1);$('#regionName').textContent=r.name;$('#regionDepth').textContent=`Reach ${Math.min(r.depth,lineDepth())}m · Rod Tier ${rodTier()} · ${rarity[state.equipment.rod.rarity].n}`;$('#weatherBadge').textContent=weatherLabel();$('#sonarBtn').classList.toggle('ready',now()>=state.sonarAt);$('#huntBtn').classList.toggle('ready',!!state.hunts.active)}
function renderBait(){let s=$('#baitSelect'),cur=String(state.selectedBait||0);s.innerHTML=Object.entries(baitDefs).map(([id,b])=>`<option value="${id}">${b.name}${+id?' · '+(state.bait[id]||0):''}</option>`).join('');s.value=cur;let b=activeBaitDef();$('#baitLoadoutName')&&($('#baitLoadoutName').textContent=b.name+(state.selectedBait?' ×'+(state.bait[state.selectedBait]||0):''))}
function renderLures(){let s=$('#lureSelect');s.innerHTML=Object.entries(lureDefs).map(([id,l])=>`<option value="${id}">${l.name}${id==='none'?'':' · '+(state.lures[id]||0)}</option>`).join('');if(!lureDefs[state.selectedLure])state.selectedLure='none';s.value=state.selectedLure;$('#lureLoadoutName')&&($('#lureLoadoutName').textContent=lureDefs[state.selectedLure].name);$('#hookLoadoutName')&&($('#hookLoadoutName').textContent=activeHookDef().name.replace(' Hook',''))}
function renderStatus(){let m=tackleMetrics(),hunt=state.hunts.active?` · Hunt: ${legendaryDefs[state.hunts.active].name}`:'',c=oceanCondition(),ev=activeOceanEvent(),r=$('#tackleReadout');if(r)r.innerHTML=`<span><small>TARGET</small><b>${m.target}</b></span><span><small>BITE</small><b>${m.biteLabel}</b></span><span><small>MAX</small><b>Tier ${m.maxTier}</b></span><span><small>RARE</small><b>${m.rare?'+'+m.rare+'%':'Normal'}</b></span>`;$('#status').innerHTML=`${m.h.name} · ${m.l.name} · ${m.b.name} · ${c.label.toLowerCase()} · ${currentLabel(c.current).toLowerCase()}${ev?' · '+ev.name.toLowerCase():''}${hunt}`;renderTackleModalSummary();renderOceanHud(true)}
function storyCondition(){let d=storyDefs[state.story];return d?d.ok(state):false}
function claimStory(){let d=storyDefs[state.story];if(!d||!d.ok(state))return toast('Story objective is not complete yet.');state.gold+=d.gold||0;state.pearls+=d.pearls||0;state.coral+=d.coral||0;if(Number.isInteger(d.unlock))state.unlockedRegion=Math.max(state.unlockedRegion,d.unlock);if(d.final)state.finalBonus=true;state.story=Math.min(storyDefs.length,state.story+1);save();renderAll();tone(820,.09);haptic('success');toast('Story chapter completed.')}
function instanceName(x){let f=allDefs()[x.id]||fishDefs.silverfin;if(x.nickname)return x.nickname;let g=x.gene||{};let p=g.mutant?'Mutant ':g.value>1.15?'Gilded ':g.size>1.12?'Grand ':'';return p+f.name}
function claimAquarium(){let n=aquariumStored();if(n<=0)return toast('No aquarium income ready yet.');state.gold+=n;state.totalGold+=n;state.aqua.lastClaim=now();save();renderAll();tone(720,.07);haptic('success');toast('Collected '+fmt(n)+' gold.')}
function feedAquarium(){if(!state.aquarium.length)return toast('Add fish first.');state.aqua.feedUntil=now()+30*60000;state.aqua.clean=clamp(state.aqua.clean+6,0,100);save();renderAll();toast('Fed. Happiness and income boosted for 30 minutes.')}
function cleanAquarium(){let cost=Math.max(20,Math.floor(state.aquarium.length*8));if(state.gold<cost)return toast('Need '+cost+' gold.');state.gold-=cost;state.aqua.clean=100;save();renderAll();toast('Tank cleaned.')}
function expandAquarium(){let cost=900+(state.aqua.slots-8)*280;if(state.aqua.slots>=30)return toast('Maximum aquarium size reached.');if(state.gold<cost)return toast('Need '+fmt(cost)+' gold.');state.gold-=cost;state.aqua.slots+=2;save();renderAll()}
function upgradeTank(){let cost=800*state.aqua.level;if(state.aqua.level>=10)return;if(state.gold<cost)return toast('Need '+fmt(cost)+' gold.');state.gold-=cost;state.aqua.level++;save();renderAll()}
function toggleBreeder(uid){let p=state.hatchery.parents;if(p.includes(uid))p.splice(p.indexOf(uid),1);else{if(p.length>=2)p.shift();p.push(uid)}save();renderAquarium()}
function renderHatchery(){let e=$('#hatchDisplay'),egg=state.hatchery.egg;if(egg){let left=Math.max(0,egg.ready-now());e.innerHTML=`<div><div class="egg">◉</div><b>${left<=0?'Egg ready to hatch!':'Incubating'}</b><div class="card-sub">${left<=0?'Tap HATCH / CHECK':Math.ceil(left/1000)+' seconds remaining'}</div></div>`;$('#hatchNowBtn').textContent=left<=0?'HATCH EGG':'HATCH EARLY · 1 PEARL';$('#breedBtn').disabled=true}else{let names=state.hatchery.parents.map(u=>{let x=state.aquarium.find(a=>a.uid===u);return x?instanceName(x):'?'});e.innerHTML=`<div><div style="font-size:30px">${state.hatchery.parents.length===2?'♡':'○'}</div><b>${names.length?names.join(' + '):'Select two breeders'}</b><div class="card-sub">Choose BREED on aquarium fish below.</div></div>`;$('#breedBtn').disabled=state.hatchery.parents.length!==2;$('#hatchNowBtn').textContent='NO EGG'} }
function breedSelected(){if(state.hatchery.egg)return;if(state.hatchery.parents.length!==2)return toast('Select two aquarium fish.');let a=state.aquarium.find(x=>x.uid===state.hatchery.parents[0]),b=state.aquarium.find(x=>x.uid===state.hatchery.parents[1]);if(!a||!b)return;let cost=500;if(state.gold<cost)return toast('Need 500 gold.');state.gold-=cost;let mutant=Math.random()<.12;let gene={value:clamp(((a.gene?.value||1)+(b.gene?.value||1))/2+rand(-.05,.1)+(mutant?.18:0),.85,1.55),size:clamp(((a.gene?.size||1)+(b.gene?.size||1))/2+rand(-.07,.12),.85,1.45),hue:Math.round(((a.gene?.hue||0)+(b.gene?.hue||0))/2+rand(-22,22)),mutant};let child=Math.random()<.5?a.id:b.id;state.hatchery.egg={id:child,gene,ready:now()+60000};save();renderAll();tone(560,.09);toast(mutant?'A strange mutation formed in the egg!':'Egg placed in the incubator.')}
function hatchEgg(force=false){let egg=state.hatchery.egg;if(!egg)return toast('No egg is incubating.');if(now()<egg.ready){if(!force){if(state.pearls<1)return toast('Wait or use 1 pearl to hatch early.');state.pearls--;force=true}}if(state.aquarium.length>=state.aqua.slots)return toast('Aquarium is full.');state.aquarium.push({uid:'h_'+now()+'_'+Math.random().toString(36).slice(2,6),id:egg.id,gene:egg.gene,nickname:'',added:now()});state.hatchery={parents:[],egg:null};save();renderAll();tone(920,.13);haptic('success');toast('A new hatchling joined the aquarium!')}

function huntEntries(){return Object.entries(legendaryDefs)}
function renderHunts(){
 let e=$('#huntList');if(!e)return;e.innerHTML='';
 let entries=huntEntries(),page=pagedLogItems('hunts',entries,logPageSize('hunts'));
 page.items.forEach(([id,h])=>{
   let done=state.hunts.completed[id]||0,unlocked=state.unlockedRegion>=h.region,active=state.hunts.active===id,r=document.createElement('div');
   r.className='row '+(active?'hunt-live':'');
   r.innerHTML=`<div class="row-icon" style="color:#b77700">★</div><div class="row-copy"><b>${h.name}</b><small>${regions[h.region].name} · ${h.desc} · Caught ${done}</small></div><button type="button" ${!unlocked?'disabled':''}>${active?'ACTIVE':done?'AGAIN':'START'}</button>`;
   r.querySelector('button').addEventListener('click',()=>{if(!unlocked)return;state.hunts.active=id;state.region=h.region;fish=[];specials=[];for(let i=0;i<14;i++)spawnFish(i>10);save();renderAll();toast('Hunt started: '+h.name)});
   e.appendChild(r);
 });
 renderLogPager();
}
function openHuntModal(){let h=state.hunts.active?legendaryDefs[state.hunts.active]:null;let e=$('#huntModalBody');if(h)e.innerHTML=`<div class="card legendary-card"><h3>ACTIVE: ${h.name}</h3><p>${h.desc}<br>Region: ${regions[h.region].name}<br>Storms increase appearance chance.</p><button class="widebtn danger" id="cancelHunt" type="button">CANCEL HUNT</button></div>`;else e.innerHTML='<div class="card"><h3>No hunt active</h3><p>Open Journal → Legendary Hunts and choose a target.</p></div>';$('#huntModal').classList.add('show');$('#cancelHunt')?.addEventListener('click',()=>{state.hunts.active=null;save();$('#huntModal').classList.remove('show');renderAll()})}
function renderRelics(){
 let e=$('#relicList');if(!e)return;e.innerHTML='';
 $('#relicSummary')&&($('#relicSummary').textContent=state.relics.length+' of '+relicDefs.length+' relics recovered.');
 let page=pagedLogItems('relics',relicDefs,logPageSize('relics'));
 page.items.forEach(r=>{let found=state.relics.includes(r.id),row=document.createElement('div');row.className='row';row.innerHTML=`<div class="row-icon">${found?r.icon:'?'}</div><div class="row-copy"><b>${found?r.name:'Unknown Relic'}</b><small>${found?r.desc:'Hidden near submerged ruins.'}</small></div>`;e.appendChild(row)});
 renderLogPager();
}
function renderBook(){
 let e=$('#bookGrid');if(!e)return;let defs=allDefs(),entries=Object.entries(defs),known=Object.keys(state.book).length;e.innerHTML='';
 $('#bookSummary')&&($('#bookSummary').textContent=known+' of '+entries.length+' species discovered.');
 let page=pagedLogItems('atlas',entries,logPageSize('atlas'));
 page.items.forEach(([id,f])=>{let seen=!!state.book[id],c=document.createElement('div');c.className='fish-card'+(id in legendaryDefs?' legendary-card':'');c.innerHTML=`<div class="fish-icon" style="filter:${seen?'none':'brightness(0) opacity(.28)'}">${fishSvg(id)}</div><h3>${seen?f.name:'Unknown Species'}</h3><p>Tier ${f.tier} · ${seen?'Caught '+state.book[id]+' · '+f.fight:'Change region, lure, weather, or depth.'}</p>`;e.appendChild(c)});
 renderMissions();renderLogPager();
}
function missionDefs(){return[
 {id:'catch10',name:'A Full Creel',desc:'Catch 10 fish',now:state.catches,max:10,reward:450},
 {id:'aqua5',name:'Living Gallery',desc:'Keep 5 aquarium fish',now:state.aquarium.length,max:5,reward:650},
 {id:'raregear',name:'Fine Equipment',desc:'Reforge any item to Rare',now:Object.values(state.equipment).some(g=>g.rarity>=2)?1:0,max:1,reward:800},
 {id:'relic2',name:'Ruins Scholar',desc:'Recover 2 relics',now:state.relics.length,max:2,reward:1100}
]}
function renderMissions(){
 let e=$('#missionList');if(!e)return;e.innerHTML='';
 let page=pagedLogItems('missions',missionDefs(),logPageSize('missions'));
 page.items.forEach(m=>{let done=m.now>=m.max,claimed=state.missions[m.id],r=document.createElement('div');r.className='row';r.innerHTML=`<div class="row-copy"><b>${m.name}</b><small>${m.desc} · ${Math.min(m.now,m.max)}/${m.max}</small><div class="progress"><span style="width:${clamp(m.now/m.max*100,0,100)}%"></span></div></div><button type="button" ${!done||claimed?'disabled':''}>${claimed?'CLAIMED':'+'+m.reward+'G'}</button>`;r.querySelector('button').addEventListener('click',()=>{if(!done||claimed)return;state.missions[m.id]=true;state.gold+=m.reward;save();renderAll();tone(740,.07);toast('Reward: '+m.reward+' gold')});e.appendChild(r)});
 renderLogPager();
}

function showCatch(c){let f=allDefs()[c.id];$('#catchArt').innerHTML=fishSvg(c.id,c.gene);$('#catchName').textContent=f.name+(c.id in legendaryDefs?' ★':'');$('#catchMeta').textContent=`Tier ${f.tier} · ${c.weight.toFixed(2)} kg · ${c.moment||oceanCycle().label} · Fight: ${f.fight} · Value ${c.val} gold${c.id in legendaryDefs?' · LEGENDARY':''}`;$('#aquaCatch').disabled=state.aquarium.length>=state.aqua.slots;$('#baitCatch').disabled=f.tier>=5;$('#catchModal').classList.add('show')}
function catchAction(type){if(!catchPending)return;haptic('success');let f=allDefs()[catchPending.id];if(type==='sell'){state.gold+=catchPending.val;state.totalGold+=catchPending.val;toast('Sold '+f.name+' for '+catchPending.val+' gold.')}else if(type==='aqua'){if(state.aquarium.length>=state.aqua.slots)return toast('Aquarium is full.');state.aquarium.push({uid:'c_'+now()+'_'+Math.random().toString(36).slice(2,7),id:catchPending.id,gene:catchPending.gene||{value:1,size:1,hue:0},nickname:'',added:now()});toast(f.name+' added to the aquarium.')}else if(type==='bait'){let tier=clamp(f.tier,1,5);state.bait[tier]=(state.bait[tier]||0)+1;toast(f.name+' prepared as '+baitDefs[tier].name+'.')}catchPending=null;$('#catchModal').classList.remove('show');save();renderAll()}
function sonarPing(){let n=now();if(n<state.sonarAt)return toast('Sonar recharging for '+Math.ceil((state.sonarAt-n)/1000)+'s.');state.sonarAt=n+sonarCooldown();sonar=true;fish.forEach(q=>{if(allDefs()[q.id].tier>=3)q.sonarUntil=performance.now()+7500});for(let i=0;i<3;i++)spawnFish(true);maybeSpawnSpecial();setTimeout(()=>{sonar=false},7500);haptic('sonar');tone(900,.08);setTimeout(()=>tone(650,.1),90);toast('Sonar reveals large fish, treasure, and ruin secrets.');save();renderAll()}

let tackleTab='hook',tacklePage=0;
function renderTackleModalSummary(){let e=$('#tackleModalSummary');if(!e)return;let m=tackleMetrics();e.innerHTML=`<div><small>TARGET</small><b>${m.target}</b></div><div><small>BITE RATE</small><b>${m.biteLabel}</b></div><div><small>MAX FISH</small><b>Tier ${m.maxTier}</b></div><div><small>TREASURE</small><b>${m.treasure?'+'+m.treasure+'%':'Normal'}</b></div>`}
function tackleList(){if(tackleTab==='hook')return Object.entries(hookDefs).map(([id,x])=>({id,...x,count:null,active:state.selectedHook===id,locked:!hookUnlocked(id),note:(!hookUnlocked(id)?'Rod Tier '+x.unlock+' required. ': '')+x.desc}));if(tackleTab==='lure')return Object.entries(lureDefs).map(([id,x])=>({id,...x,count:id==='none'?null:(state.lures[id]||0),active:state.selectedLure===id,locked:id!=='none'&&(state.lures[id]||0)<=0,note:x.desc||('Targets '+x.target+'.')}));return Object.entries(baitDefs).map(([id,x])=>({id:+id,...x,count:+id?(state.bait[id]||0):null,active:(state.selectedBait||0)===+id,locked:+id>0&&(state.bait[id]||0)<=0,note:x.desc}))}
function renderTackleSheet(){let grid=$('#tackleGrid'),pager=$('#tacklePager');if(!grid||!pager)return;document.querySelectorAll('#tackleTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tackleTab===tackleTab));let list=tackleList(),pages=Math.max(1,Math.ceil(list.length/4));tacklePage=clamp(tacklePage,0,pages-1);let items=list.slice(tacklePage*4,tacklePage*4+4);grid.innerHTML='';items.forEach(x=>{let b=document.createElement('button');b.type='button';b.className='tackle-option'+(x.active?' active':'')+(x.locked?' locked':'');b.disabled=!!x.locked;b.innerHTML=`<span class="tackle-art">${x.icon||'○'}</span><span class="tackle-option-copy"><b>${x.name}</b><small>${x.note}</small></span>${x.count!==null?`<span class="tackle-count">×${x.count}</span>`:''}${x.active?'<span class="tackle-equipped">EQUIPPED</span>':''}`;b.onclick=()=>{haptic('select');if(tackleTab==='hook')state.selectedHook=x.id;else if(tackleTab==='lure')state.selectedLure=x.id;else state.selectedBait=+x.id;save();renderAll();renderTackleSheet()};grid.appendChild(b)});pager.innerHTML='';if(pages>1){let p=document.createElement('button'),n=document.createElement('button'),s=document.createElement('span');p.textContent='‹';n.textContent='›';s.textContent=(tacklePage+1)+' / '+pages;p.disabled=tacklePage<=0;n.disabled=tacklePage>=pages-1;p.onclick=()=>{tacklePage--;renderTackleSheet()};n.onclick=()=>{tacklePage++;renderTackleSheet()};pager.append(p,s,n)}else{let s=document.createElement('span');s.textContent=tackleTab==='hook'?'Hooks unlock with Rod Tier.':tackleTab==='bait'?'Bait is prepared from catches.':'Lures are reusable unless lost on a snapped line.';pager.appendChild(s)}renderTackleModalSummary()}
function openTackle(){if(hook.mode!=='idle')return toast('Finish the current cast before changing tackle.');tacklePage=0;renderTackleSheet();$('#tackleModal').classList.add('show');haptic('select')}
function closeModal(id){$('#'+id).classList.remove('show')}
