(()=>{'use strict';
const $=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg';
const COLORS=['#ef574f','#f5c63d','#36a1e9','#58b96d','#a44bc1'];
const POWERS={8:'back',15:'block',22:'swap',29:'back',36:'block',43:'swap'};
const VIEW={w:1000,h:1350};
const YS=1, Y=y=>Math.round(y*YS);
const BASE_WAYPOINTS=[[115,1215],[315,1135],[650,1170],[850,1060],[855,905],[650,840],[355,905],[180,800],[220,655],[500,590],[785,645],[830,505],[650,425],[345,470],[180,360],[420,292],[705,330],[850,215]];
const WAYPOINTS=BASE_WAYPOINTS.map(([x,y])=>[x,Y(y)]);
let tokens=['🦊','🐼'],players=[],turn=0,busy=false,action='normal',prediction=null;
let cameraMode='map',zoom=1,tx=0,ty=0,drag=null,pinch=null,moved=false;

function S(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n}
function text(g,s,x,y,size,attrs={}){const n=S('text',{x,y,'text-anchor':'middle','font-size':size,...attrs});n.textContent=s;g.append(n);return n}
function pathD(points){return points.map((p,i)=>(i?'L':'M')+p[0]+' '+p[1]).join(' ')}
function samplePath(points,count){const seg=[];let total=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],d=Math.hypot(b[0]-a[0],b[1]-a[1]);seg.push({a,b,d,start:total});total+=d}const out=[];for(let i=0;i<count;i++){const target=total*i/(count-1);let s=seg.find(x=>target<=x.start+x.d)||seg[seg.length-1];const t=Math.max(0,Math.min(1,(target-s.start)/s.d));const x=s.a[0]+(s.b[0]-s.a[0])*t,y=s.a[1]+(s.b[1]-s.a[1])*t,ang=Math.atan2(s.b[1]-s.a[1],s.b[0]-s.a[0])*180/Math.PI;out.push({x,y,ang})}return out}
const SPACES=samplePath(WAYPOINTS,48);

function tree(g,x,y,s=1,autumn=false){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'});q.append(S('rect',{x:-7,y:5,width:14,height:36,rx:4,fill:'#6f4025'}));const c=autumn?['#d96e2e','#ee9b35','#b94928']:['#23683f','#2e8a4e','#3da45a'];[[0,-28,34],[0,-3,29],[0,19,24]].forEach((a,i)=>q.append(S('path',{d:`M${-a[2]} ${a[1]+22} L0 ${a[1]-24} L${a[2]} ${a[1]+22}Z`,fill:c[i]})));g.append(q)}
function mountain(g,x,y,s=1){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'});q.append(S('path',{d:'M-90 70 L0 -95 L90 70 Z',fill:'#66788e'}),S('path',{d:'M-38 -24 L0 -95 L36 -26 L14 -37 L0 -26 L-13 -40Z',fill:'#eef7ff'}),S('path',{d:'M-75 70 L-22 -25 L-6 5 L12 -17 L55 70Z',fill:'#4c5d70','fill-opacity':'.65'}));g.append(q)}
function rock(g,x,y,s=1){const q=S('path',{d:`M${x-30*s} ${y+18*s}Q${x-26*s} ${y-19*s} ${x} ${y-25*s}Q${x+31*s} ${y-17*s} ${x+34*s} ${y+18*s}Z`,fill:'#6f7b84',stroke:'#46515a','stroke-width':3*s});g.append(q)}
function castle(g,x,y,s=1,golden=false){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'}),wall=golden?'#ffc536':'#d8e5ef',roof=golden?'#e86c12':'#3566a5',dark=golden?'#8d4100':'#24446c';q.append(S('rect',{x:-75,y:-15,width:150,height:95,rx:8,fill:wall,stroke:dark,'stroke-width':5}));[-62,0,62].forEach(dx=>{q.append(S('rect',{x:dx-27,y:-76,width:54,height:155,rx:5,fill:wall,stroke:dark,'stroke-width':5}),S('path',{d:`M${dx-38} -76 L${dx} -126 L${dx+38} -76Z`,fill:roof,stroke:dark,'stroke-width':5}));[-13,13].forEach(w=>q.append(S('rect',{x:dx+w-5,y:-36,width:10,height:20,rx:4,fill:'#66d9ff'})))});q.append(S('path',{d:'M-18 80 V40 Q0 13 18 40 V80Z',fill:dark}));if(golden){text(q,'💎',0,-135,42);text(q,'GRAND PRIZE',0,116,22,{fill:'#7b3100','font-weight':'900'})}g.append(q)}
function haunted(g,x,y,s=1){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'});q.append(S('ellipse',{cx:0,cy:50,rx:105,ry:30,fill:'#21172d','fill-opacity':'.55'}));[-60,0,60].forEach(dx=>{q.append(S('rect',{x:dx-24,y:-45,width:48,height:110,fill:'#241a38',stroke:'#090b1a','stroke-width':4}),S('path',{d:`M${dx-34} -45 L${dx} -100 L${dx+34} -45Z`,fill:'#160d27',stroke:'#6d2a92','stroke-width':4}));q.append(S('rect',{x:dx-6,y:-8,width:12,height:25,rx:5,fill:'#ff4be3',filter:'url(#glow)'}))});g.append(q)}
function mine(g,x,y,s=1){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'});q.append(S('path',{d:'M-100 65 L-78 -42 L-35 -84 L38 -75 L92 -25 L105 65Z',fill:'#b76b3f',stroke:'#713922','stroke-width':6}),S('path',{d:'M-48 65 V-12 Q0 -64 48 -12 V65Z',fill:'#261d22',stroke:'#5b321f','stroke-width':7}));text(q,'⛏️',0,34,45);g.append(q)}
function ship(g,x,y,s=1){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'});q.append(S('path',{d:'M-90 38 Q0 80 90 38 L65 70 H-60Z',fill:'#6f3c1d',stroke:'#3d2416','stroke-width':5}),S('line',{x1:0,y1:35,x2:0,y2:-95,stroke:'#4b2a18','stroke-width':7}),S('path',{d:'M5 -84 Q68 -62 70 5 Q30 -10 5 5Z',fill:'#f5efe6',stroke:'#bb432e','stroke-width':5}),S('path',{d:'M5 -78 Q38 -66 43 -50 L5 -50Z',fill:'#c94432'}));g.append(q)}
function dragon(g,x,y,s=1){const pos=S('g',{transform:`translate(${x} ${y}) scale(${s})`}),q=S('g',{class:'interactive dragon',filter:'url(#softShadow)'});q.append(S('ellipse',{cx:0,cy:45,rx:90,ry:26,fill:'#000','fill-opacity':'.22'}),S('ellipse',{cx:-5,cy:8,rx:70,ry:45,fill:'#d84e32',stroke:'#7b241d','stroke-width':5}),S('path',{d:'M-40 -8 Q-110 -80 -115 15 Q-74 -8 -38 25Z',fill:'#ba382d',stroke:'#76201d','stroke-width':5}),S('path',{d:'M40 -8 Q115 -80 118 15 Q72 -7 38 25Z',fill:'#ba382d',stroke:'#76201d','stroke-width':5}),S('ellipse',{cx:62,cy:-20,rx:38,ry:30,fill:'#e05c36',stroke:'#7b241d','stroke-width':5}),S('circle',{cx:75,cy:-28,r:6,fill:'#fff'}),S('circle',{cx:77,cy:-27,r:3,fill:'#111'}),S('path',{d:'M84 -14 Q104 -6 89 5',fill:'none',stroke:'#7b241d','stroke-width':4}),S('path',{d:'M50 -46 L58 -68 L66 -43Z',fill:'#f4c15d'}),S('path',{d:'M73 -47 L85 -67 L87 -39Z',fill:'#f4c15d'}));q.append(S('circle',{cx:0,cy:0,r:120,class:'hit'}));q.addEventListener('pointerdown',e=>react(e,q,'The dragon wakes!','🔥'));pos.append(q);g.append(pos)}
function ghost(g,x,y,s=1){const pos=S('g',{transform:`translate(${x} ${y}) scale(${s})`}),q=S('g',{class:'interactive',filter:'url(#softShadow)'});q.append(S('path',{d:'M0 -55 Q48 -55 50 -5 V62 L26 44 L6 62 L-15 44 L-40 62 L-50 42 V-5 Q-48 -55 0 -55Z',fill:'#f4f6ff',stroke:'#c6d1ef','stroke-width':5}),S('ellipse',{cx:-17,cy:-12,rx:7,ry:11,fill:'#2c2740'}),S('ellipse',{cx:17,cy:-12,rx:7,ry:11,fill:'#2c2740'}));q.append(S('circle',{r:80,class:'hit'}));q.addEventListener('pointerdown',e=>react(e,q,'Boo!','✨'));pos.append(q);g.append(pos)}
function frog(g,x,y,s=1){const pos=S('g',{transform:`translate(${x} ${y}) scale(${s})`}),q=S('g',{class:'interactive',filter:'url(#softShadow)'});q.append(S('ellipse',{cx:0,cy:22,rx:48,ry:32,fill:'#77b92f',stroke:'#376d1c','stroke-width':5}),S('circle',{cx:-27,cy:-10,r:18,fill:'#85cb38'}),S('circle',{cx:27,cy:-10,r:18,fill:'#85cb38'}),S('circle',{cx:-27,cy:-12,r:7,fill:'#fff'}),S('circle',{cx:27,cy:-12,r:7,fill:'#fff'}),S('circle',{cx:-27,cy:-11,r:3,fill:'#111'}),S('circle',{cx:27,cy:-11,r:3,fill:'#111'}),S('path',{d:'M-16 28 Q0 38 16 28',fill:'none',stroke:'#2f5b18','stroke-width':4}));q.append(S('circle',{r:72,class:'hit'}));q.addEventListener('pointerdown',e=>react(e,q,'Ribbit!','💦'));pos.append(q);g.append(pos)}
function crystal(g,x,y,s=1){const pos=S('g',{transform:`translate(${x} ${y}) scale(${s})`}),q=S('g',{class:'interactive',filter:'url(#glow)'});[['#55e7ff',-34,12,40,80],['#7b6cff',5,-12,50,108],['#b9fbff',39,16,34,76]].forEach(([c,dx,dy,w,h])=>q.append(S('path',{d:`M${dx-w/2} ${dy+h/2} L${dx-w/4} ${dy-h/3} L${dx} ${dy-h/2} L${dx+w/2} ${dy+h/2}Z`,fill:c,stroke:'#dffcff','stroke-width':4})));q.append(S('circle',{r:90,class:'hit'}));q.addEventListener('pointerdown',e=>react(e,q,'The crystal hums!','✨'));pos.append(q);g.append(pos)}
function sign(g,x,y,s=1,label='START'){const q=S('g',{transform:`translate(${x} ${y}) scale(${s})`,filter:'url(#softShadow)'});q.append(S('rect',{x:-78,y:-34,width:156,height:68,rx:8,fill:'#8b4e22',stroke:'#4d2a16','stroke-width':6}),S('line',{x1:-44,y1:34,x2:-44,y2:90,stroke:'#4d2a16','stroke-width':12}),S('line',{x1:44,y1:34,x2:44,y2:90,stroke:'#4d2a16','stroke-width':12}));text(q,label,0,12,28,{fill:'#ffd56a','font-weight':'900',stroke:'#4d2a16','stroke-width':2});g.append(q)}

function buildWorld(){const g=$('#worldArt');g.append(S('rect',{width:1000,height:1350,fill:'url(#grass)'}),S('rect',{width:1000,height:Y(285),fill:'url(#sky)'}),S('circle',{cx:865,cy:Y(125),r:75,fill:'#ffe978','fill-opacity':'.75',filter:'url(#glow)'}));
  g.append(S('path',{d:`M650 ${Y(480)} C790 ${Y(430)} 965 ${Y(500)} 980 ${Y(640)} C970 ${Y(770)} 850 ${Y(790)} 700 ${Y(710)} C620 ${Y(660)} 610 ${Y(540)} 650 ${Y(480)}Z`,fill:'url(#haunt)','fill-opacity':'.82'}),S('path',{d:`M700 ${Y(735)} C850 ${Y(700)} 1010 ${Y(790)} 1015 ${Y(925)} C970 ${Y(1040)} 840 ${Y(1050)} 720 ${Y(970)} C650 ${Y(900)} 645 ${Y(800)} 700 ${Y(735)}Z`,fill:'#b8663d','fill-opacity':'.82'}),S('path',{d:`M-25 ${Y(620)} C110 ${Y(565)} 225 ${Y(630)} 245 ${Y(760)} C230 ${Y(900)} 130 ${Y(955)} -20 ${Y(895)}Z`,fill:'#286847','fill-opacity':'.72'}));
  text(g,'☁️',520,Y(115),72,{opacity:'.9'});text(g,'☁️',690,Y(165),54,{opacity:'.8'});text(g,'🦅',365,Y(170),48);
  mountain(g,115,Y(255),1.2);mountain(g,260,Y(275),.95);mountain(g,410,Y(255),.8);castle(g,185,Y(250),.6,false);
  g.append(S('path',{d:pathD([[-40,Y(1140)],[160,Y(1020)],[270,Y(1100)],[420,Y(1045)],[690,Y(1120)],[1060,Y(980)]]),fill:'none',stroke:'#056c9e','stroke-width':155,'stroke-linecap':'round'}),S('path',{d:pathD([[-40,Y(1140)],[160,Y(1020)],[270,Y(1100)],[420,Y(1045)],[690,Y(1120)],[1060,Y(980)]]),fill:'none',stroke:'url(#river)','stroke-width':120,'stroke-linecap':'round'}));
  for(let i=0;i<7;i++) rock(g,440+i*30,Y(1020-i*3),.5);
  for(const [x,y,s,a] of [[90,1120,.9,0],[180,1080,.75,0],[300,1010,.8,0],[120,900,.85,0],[325,760,.72,0],[500,770,.65,1],[585,760,.7,1],[680,735,.8,1],[735,340,.8,1],[620,310,.75,1],[510,350,.7,0],[110,520,.8,0],[900,400,.65,0]])tree(g,x,Y(y),s,!!a);
  mine(g,875,Y(830),.72);ship(g,825,Y(1190),.76);haunted(g,795,Y(600),.78);castle(g,835,Y(205),.82,true);sign(g,110,Y(1265),.72,'START');
  const ig=$('#interactiveLayer');crystal(ig,105,Y(610),.7);dragon(ig,90,Y(735),.82);ghost(ig,930,Y(525),.7);frog(ig,470,Y(1035),.72);
  g.append(S('path',{d:pathD([[335,Y(997)],[395,Y(950)],[455,Y(997)]]),fill:'none',stroke:'#6c4328','stroke-width':24,'stroke-linecap':'round'}),S('path',{d:pathD([[335,Y(997)],[395,Y(958)],[455,Y(997)]]),fill:'none',stroke:'#d9a15e','stroke-width':14,'stroke-linecap':'round'}));
  const road=$('#pathLayer');road.append(S('path',{d:pathD(WAYPOINTS),fill:'none',stroke:'#5b3519','stroke-width':94,'stroke-linejoin':'round','stroke-linecap':'round','opacity':'.55'}),S('path',{d:pathD(WAYPOINTS),fill:'none',stroke:'#f0c96a','stroke-width':78,'stroke-linejoin':'round','stroke-linecap':'round'}));
  SPACES.forEach((p,i)=>{const q=S('g',{transform:`translate(${p.x} ${p.y}) rotate(${p.ang})`}),c=COLORS[i%COLORS.length],r=S('rect',{x:-36,y:-25,width:72,height:50,rx:15,fill:c,stroke:'#fff3d6','stroke-width':4,class:'tile'}),shine=S('path',{d:'M-25 -18 Q0 -27 25 -18',fill:'none',stroke:'#fff','stroke-opacity':'.35','stroke-width':5,'stroke-linecap':'round'});q.append(r,shine);if(POWERS[i]){r.setAttribute('fill',POWERS[i]==='back'?'#d83b47':POWERS[i]==='block'?'#227ed5':'#8c33bd');r.setAttribute('class','tile pulse');text(q,POWERS[i]==='back'?'⏪':POWERS[i]==='block'?'🛡️':'🔄',0,11,27,{transform:`rotate(${-p.ang} 0 0)`})}road.append(q)});
}
function react(e,node,msg,icon){e.stopPropagation();node.classList.remove('react');void node.getBBox();node.classList.add('react');say(msg);vibrate([25,15,45]);burstAtEvent(e,icon)}
function burstAtEvent(e,icon){const rect=$('#viewport').getBoundingClientRect();for(let i=0;i<8;i++){const s=document.createElement('span');s.className='spark';s.textContent=i<2?icon:'';s.style.left=(e.clientX-rect.left)+'px';s.style.top=(e.clientY-rect.top)+'px';s.style.setProperty('--dx',((Math.random()-.5)*110)+'px');s.style.setProperty('--dy',((-40-Math.random()*90))+'px');$('#fxLayer').append(s);setTimeout(()=>s.remove(),850)}}

function drawPieces(hop=false){const g=$('#pieceLayer');g.textContent='';players.forEach((p,i)=>{const q=SPACES[p.pos],x=q.x+(i?17:-17),y=q.y-44,w=S('g',{class:hop&&i===turn?'hop':''});w.append(S('ellipse',{cx:x,cy:y+28,rx:28,ry:10,fill:'#000','fill-opacity':'.28'}),S('ellipse',{cx:x,cy:y+18,rx:27,ry:14,fill:i?'#4c85da':'#dd5146',stroke:'#e7f1ff','stroke-width':3}));text(w,p.token,x,y+5,45,{class:'piece'});g.append(w)})}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hud(){players.forEach((p,i)=>{$('#p'+i+'hud').innerHTML=`<b>${p.token}</b>${esc(p.name)} · ${p.pos}/${SPACES.length-1}`;$('#p'+i+'hud').classList.toggle('active',i===turn)});$('#turnText').textContent=players[turn].name+"'s turn"}
function say(s){$('#message').textContent=s}
function vibrate(v){try{navigator.vibrate&&navigator.vibrate(v)}catch{}}
function showFx(s,isTurn=false){const n=document.createElement('div');n.className='fx'+(isTurn?' turn':'');n.textContent=s;$('#fxLayer').append(n);setTimeout(()=>n.remove(),950)}
function start(){players=[{name:$('#p1').value.trim()||'Player 1',token:tokens[0],pos:0,blocked:false},{name:$('#p2').value.trim()||'Player 2',token:tokens[1],pos:0,blocked:false}];turn=0;$('#setup').hidden=true;$('#game').hidden=false;drawPieces();hud();setTimeout(()=>setCamera('map'),40);showFx(players[0].name.toUpperCase()+"'S TURN",true)}
function randomRoll(){return 1+Math.floor(Math.random()*6)}
function setDie(n){$('#dieFace').dataset.roll=String(n)}
function rollAnimation(done){busy=true;$('#roll').disabled=true;$('#roll').classList.add('rolling');vibrate(18);let n=0;const id=setInterval(()=>{setDie(randomRoll());if(++n>=11){clearInterval(id);const r=randomRoll();setDie(r);$('#roll').classList.remove('rolling');$('#roll').classList.add('result');setTimeout(()=>$('#roll').classList.remove('result'),600);showFx('YOU ROLLED '+r+'!');vibrate([30,20,60]);setTimeout(()=>done(r),650)}},65)}
function roll(){if(busy)return;if(action==='choose'){say('Choose ODD or EVEN first.');return}rollAnimation(r=>{if(action==='back'){const o=1-turn;players[o].pos=Math.max(0,players[o].pos-r);say(players[o].name+' goes back '+r+'!');drawPieces(true);if(cameraMode==='follow')centerOn(o);setTimeout(endTurn,900);return}if(action==='swaproll'){const good=(r%2===0)===(prediction==='even'),me=players[turn],o=players[1-turn],dir=good?'ahead':'behind',eligible=dir==='ahead'?o.pos>me.pos:o.pos<me.pos;if(eligible)[me.pos,o.pos]=[o.pos,me.pos];say(eligible?(good?'Correct — positions switched!':'Wrong — positions switched!'):'Nobody '+dir+' to switch with.');drawPieces(true);setTimeout(endTurn,1000);return}move(r)})}
function move(r){const p=players[turn],goal=Math.min(SPACES.length-1,p.pos+r);let s=p.pos;const id=setInterval(()=>{p.pos=++s;drawPieces(true);hud();vibrate(10);if(cameraMode==='follow')centerOn(turn);if(s>=goal){clearInterval(id);if(p.pos===SPACES.length-1)return win();setTimeout(resolveLanding,350)}},280)}
function resolveLanding(){const k=POWERS[players[turn].pos];if(!k)return endTurn();vibrate([45,30,70]);if(k==='back'){action='back';say('SEND BACK! Roll again.');showFx('⏪ SEND BACK!',true);ready()}else if(k==='block'){players[1-turn].blocked=true;say(players[1-turn].name+' is blocked next turn!');showFx('🛡️ BLOCK!',true);setTimeout(endTurn,950)}else{action='choose';say('Pick ODD or EVEN.');showFx('🔄 LUCKY SWITCH!',true);$('#odd').hidden=$('#even').hidden=false;ready()}}
function choose(v){if(action!=='choose')return;prediction=v;action='swaproll';$('#odd').hidden=$('#even').hidden=true;say(v.toUpperCase()+' selected — roll!')}
function ready(){busy=false;$('#roll').disabled=false}
function endTurn(){action='normal';prediction=null;turn=1-turn;hud();if(players[turn].blocked){players[turn].blocked=false;say(players[turn].name+' was blocked!');showFx('🛡️ TURN BLOCKED',true);setTimeout(()=>{turn=1-turn;hud();say('Roll the die!');ready();if(cameraMode==='follow')centerOn(turn);showFx(players[turn].name.toUpperCase()+"'S TURN",true)},1250)}else{say('Roll the die!');ready();if(cameraMode==='follow')centerOn(turn);showFx(players[turn].name.toUpperCase()+"'S TURN",true)}}
function win(){busy=true;vibrate([80,40,80,40,150]);$('#winner').textContent=players[turn].name+' WINS!';$('#celebrate').hidden=false}

function fit(){const v=$('#viewport'),scale=Math.min(v.clientWidth/VIEW.w,v.clientHeight/VIEW.h);return{scale,ox:(v.clientWidth-VIEW.w*scale)/2,oy:(v.clientHeight-VIEW.h*scale)/2}}
function clampTransform(){const v=$('#viewport');if(zoom<=1){tx=0;ty=0;return}const minX=v.clientWidth-v.clientWidth*zoom,minY=v.clientHeight-v.clientHeight*zoom;tx=Math.min(0,Math.max(minX,tx));ty=Math.min(0,Math.max(minY,ty))}
function apply(){clampTransform();$('#world').style.transform=`translate(${tx}px,${ty}px) scale(${zoom})`}
function centerOn(i){const v=$('#viewport'),m=fit(),p=SPACES[players[i].pos];zoom=2;tx=v.clientWidth/2-zoom*(m.ox+p.x*m.scale);ty=v.clientHeight/2-zoom*(m.oy+p.y*m.scale);apply()}
function setCamera(mode){cameraMode=mode;document.querySelectorAll('.cam').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='map'){zoom=1;tx=ty=0;apply()}else if(mode==='follow'){centerOn(turn)}else{if(zoom<1.25)zoom=1.45;apply()}}
function manualZoom(delta){zoom=Math.max(1,Math.min(3.2,zoom+delta));cameraMode='explore';document.querySelectorAll('.cam').forEach(b=>b.classList.toggle('active',b.dataset.mode==='explore'));apply()}

buildWorld();
document.querySelectorAll('.token').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll(`.token[data-p="${b.dataset.p}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active');tokens[+b.dataset.p]=b.dataset.token}));
$('#startBtn').addEventListener('click',start);$('#roll').addEventListener('click',roll);$('#odd').addEventListener('click',()=>choose('odd'));$('#even').addEventListener('click',()=>choose('even'));$('#zoomIn').addEventListener('click',()=>manualZoom(.2));$('#zoomOut').addEventListener('click',()=>manualZoom(-.2));document.querySelectorAll('.cam').forEach(b=>b.addEventListener('click',()=>setCamera(b.dataset.mode)));$('#rulesBtn').addEventListener('click',()=>$('#rules').showModal());$('#closeRules').addEventListener('click',()=>$('#rules').close());$('#again').addEventListener('click',()=>location.reload());

const vp=$('#viewport'),touches=new Map();
vp.addEventListener('pointerdown',e=>{if(e.target.closest?.('.camera-panel')||e.target.closest?.('.interactive'))return;drag={x:e.clientX,y:e.clientY,tx,ty};moved=false;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});vp.setPointerCapture(e.pointerId);$('#world').classList.add('dragging');if(touches.size===2){const a=[...touches.values()];pinch={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z:zoom}}});
vp.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2&&pinch){const a=[...touches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);zoom=Math.max(1,Math.min(3.2,pinch.z*d/pinch.d));moved=true;apply()}else if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)moved=true;tx=drag.tx+dx;ty=drag.ty+dy;apply()}});
function pointerEnd(e){touches.delete(e.pointerId);if(moved){cameraMode='explore';document.querySelectorAll('.cam').forEach(b=>b.classList.toggle('active',b.dataset.mode==='explore'))}if(touches.size<2)pinch=null;if(touches.size===0)drag=null;$('#world').classList.remove('dragging')}
vp.addEventListener('pointerup',pointerEnd);vp.addEventListener('pointercancel',pointerEnd);
window.addEventListener('resize',()=>{if(cameraMode==='map')setCamera('map');else if(cameraMode==='follow')centerOn(turn)});
if(new URLSearchParams(location.search).get('autostart')==='1')start();
})();