/* Tide world map, dock builder, captain log, and settings */
'use strict';
let worldMapPan={x:null,y:null},worldMapDrag=null,worldMapZoom=.82;
let dockMode='boat',dockPart='hull',dockTrayPage=0;
const sailColors=['#efe0bd','#b84e45','#486e8d','#5f805c','#755c8d'];
const trimColors=['#d6bd81','#e5e0d2','#242a31','#7f4939','#5e7181'];
const rodAccent=['#c8d4df','#ffd36d','#79d5cb','#e28787','#9da7ee'];
function ensureDockBuilderState(){let d={boatDesign:{sail:0,cabin:0,flag:0,sailColor:0,trim:0},rodDesign:{blank:0,grip:0,reel:0,guides:0,accent:0}};if(!state.dockBuilder)state.dockBuilder=JSON.parse(JSON.stringify(d));state.dockBuilder.boatDesign=Object.assign({},d.boatDesign,state.dockBuilder.boatDesign||{});state.dockBuilder.rodDesign=Object.assign({},d.rodDesign,state.dockBuilder.rodDesign||{})}
function syncViewportVars(){
 const vv=window.visualViewport,h=Math.max(320,Math.round(vv?.height||window.innerHeight||document.documentElement.clientHeight||800));
 document.documentElement.style.setProperty('--app-height',h+'px');
 const nav=$('.bottom')?.getBoundingClientRect().height||64;document.documentElement.style.setProperty('--nav-height',Math.ceil(nav)+'px');setupCanvasResolution();
}
let layoutFrame=0;
function scheduleLayout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{syncViewportVars();fitWorldMap()})}
function buildStoryCard(){if(state.story>=storyDefs.length)return '<b>Story Complete</b><p>The whole chart is open. Legendary hunts and treasure remain.</p>';let d=storyDefs[state.story],ok=d.ok(state);return `<b>Chapter ${state.story+1}: ${d.title}</b><p>${d.goal} · Reward: ${d.reward}</p><button type="button" ${ok?'':'disabled'}>${ok?'CLAIM':'INCOMPLETE'}</button>`}
function pirateMapSvg(){let islands=regionLayout.map((p,i)=>{let s=1+(i%3)*.12;return `<g transform="translate(${p.x},${p.y}) scale(${s})"><path d="M-66 18 Q-78 -10 -50 -38 Q-16 -62 20 -45 Q58 -51 78 -20 Q68 12 41 28 Q6 49 -34 39Z" fill="#b58b4d" stroke="#6a4a27" stroke-width="4"/><path d="M-49 4 Q-20 -25 4 -13 Q24 -35 48 -9 Q24 -2 13 14 Q-17 6 -38 22Z" fill="#6f7b43" opacity=".88"/><path d="M-7 17 l12 -26 l12 26Z" fill="#745438" opacity=".6"/></g>`}).join('');let route=regionLayout.map((p,i)=>(i?'L ':'M ')+p.x+' '+p.y).join(' ');return `<svg class="pirate-map-art" viewBox="0 0 1280 760" preserveAspectRatio="none"><defs><filter id="paper"><feTurbulence baseFrequency=".012" numOctaves="3" seed="7" type="fractalNoise" result="n"/><feBlend in="SourceGraphic" in2="n" mode="multiply"/></filter><pattern id="waves" width="54" height="34" patternUnits="userSpaceOnUse"><path d="M2 20 q12 -11 24 0 q12 11 24 0" fill="none" stroke="#775b38" stroke-width="1.2" opacity=".22"/></pattern></defs><rect width="1280" height="760" fill="#d2b477"/><rect width="1280" height="760" fill="url(#waves)"/><path d="M30 28 Q340 8 620 30 T1245 25 L1252 720 Q920 742 645 724 T27 732Z" fill="none" stroke="#75502a" stroke-width="5" opacity=".45"/><path d="${route}" fill="none" stroke="#6f4024" stroke-width="5" stroke-dasharray="4 15" stroke-linecap="round" opacity=".7"/>${islands}<g transform="translate(105,120)" stroke="#5c4125" fill="none"><circle r="58" stroke-width="3"/><circle r="43"/><path d="M0 -72 L9 -13 L0 0 L-9 -13Z M72 0 L13 9 L0 0 L13 -9Z M0 72 L-9 13 L0 0 L9 13Z M-72 0 L-13 -9 L0 0 L-13 9Z" fill="#65451f"/><text x="0" y="-82" text-anchor="middle" fill="#5c4125" font-family="Georgia" font-size="19">N</text></g><g fill="#5d4225" opacity=".72" font-family="Georgia"><text x="1100" y="610" font-size="42">☠</text><text x="1020" y="620" font-size="15">BEWARE</text><text x="720" y="590" font-size="34">✕</text><text x="747" y="596" font-size="13">Lost Gold</text><text x="430" y="640" font-size="34">🐉</text><text x="463" y="644" font-size="13">Sea Beast</text><text x="220" y="175" font-size="24">⚓</text><text x="850" y="500" font-size="27">⛵</text></g><g stroke="#5e4428" stroke-width="2" opacity=".48"><path d="M170 620 q22 -22 44 0 q22 22 44 0" fill="none"/><path d="M870 90 q22 -22 44 0 q22 22 44 0" fill="none"/><path d="M560 90 q22 -22 44 0 q22 22 44 0" fill="none"/></g></svg>`}
function fitWorldMap(){
 const wrap=$('#worldMapWrap'),canvas=$('#worldMapCanvas');
 if(!wrap||!canvas)return;
 canvas.style.left='0';canvas.style.top='0';canvas.style.width='100%';canvas.style.height='100%';canvas.style.transform='none';
}

function clampWorldMapPan(){let wrap=$('#worldMapWrap');if(!wrap)return;let sw=1280*worldMapZoom,sh=760*worldMapZoom,minX=wrap.clientWidth-sw-18,minY=wrap.clientHeight-sh-18;worldMapPan.x=clamp(worldMapPan.x??10,Math.min(10,minX),10);worldMapPan.y=clamp(worldMapPan.y??10,Math.min(10,minY),10)}
function applyWorldMapPan(){fitWorldMap()}
function centerWorldMap(){fitWorldMap()}
function travelToRegionIndex(i){let r=regions[i],unlocked=i<=state.unlockedRegion&&state.boat.level>=r.boat&&state.story>=r.story;if(!unlocked)return toast('That island is still locked.');if(i===state.region)return toast('You are already anchored at '+r.name+'.');state.region=i;fish=[];specials=[];resetHook();for(let j=0;j<12;j++)spawnFish();updateWeather(true);save();renderAll();centerWorldMap(i);haptic('success');toast('Sailed to '+r.name)}
function initWorldMap(){fitWorldMap()}
function renderWorldMap(){let s=$('#storyCard');if(s){s.innerHTML=buildStoryCard();s.querySelector('button')?.addEventListener('click',claimStory)}let canvas=$('#worldMapCanvas');if(!canvas)return;canvas.innerHTML=pirateMapSvg();const nextIndex=Math.min(state.unlockedRegion+1,regions.length-1);regions.forEach((r,i)=>{const unlocked=i<=state.unlockedRegion&&state.boat.level>=r.boat&&state.story>=r.story,active=i===state.region,next=i===nextIndex&&i!==state.region;let n=document.createElement('button');n.type='button';n.className='worldmap-node'+(active?' active':'')+(next?' next':'')+(unlocked?'':' locked');n.style.left=(regionLayout[i].x/1280*100)+'%';n.style.top=(regionLayout[i].y/760*100)+'%';n.disabled=!unlocked;n.setAttribute('aria-label',active?'Current location: '+r.name:unlocked?'Sail to '+r.name:'Locked: '+r.name);n.setAttribute('aria-pressed',active?'true':'false');n.innerHTML=`<span class="marker-glyph">${active?'⛵':i+1}</span><span class="marker-name">${r.name}</span>`;n.addEventListener('click',()=>{if(active)toast('Anchored at '+r.name);else travelToRegionIndex(i)});canvas.appendChild(n)});let fc=$('#forecastText'),lg=$('#mapLegend'),next=regions[nextIndex],c=oceanCondition(),ev=activeOceanEvent();if(fc)fc.innerHTML=`<b>${currentRegion().name}</b>${c.label} · ${weatherLabel()} · ${currentLabel(c.current)}${ev?' · '+ev.name:''}`;if(lg)lg.innerHTML=state.unlockedRegion<regions.length-1?`<b>Next: ${next.name}</b>Boat ${next.boat}+ and story progress.`:`<b>Chart complete</b>All waters discovered.`;fitWorldMap()}
function boatBuilderSvg(){ensureDockBuilderState();let d=state.dockBuilder.boatDesign,h=state.boat.hull,hullColor=paints[state.boat.paint]||paints[0],sail=sailColors[d.sailColor%sailColors.length],trim=trimColors[d.trim%trimColors.length];let hullPath={skiff:'M70 150 L405 150 L360 205 L120 205 Z',cutter:'M55 145 L430 145 L385 207 L110 207 Z',sloop:'M48 143 L445 143 L395 210 L105 210 Z',research:'M45 145 L455 145 L410 212 L95 212 Z',trawler:'M35 138 L465 138 L420 216 L90 216 Z',crown:'M30 134 L470 134 L425 218 L85 218 Z'}[h]||'M70 150 L405 150 L360 205 L120 205 Z';let sailShapes=[`<path d="M225 48 L225 139 L347 139 Z" fill="${sail}"/>`,`<path d="M224 42 L224 140 L340 126 L315 66 Z" fill="${sail}"/>`,`<path d="M221 45 L221 140 L320 140 L352 92 Z" fill="${sail}"/><path d="M215 55 L145 126 L215 126 Z" fill="${sail}" opacity=".9"/>`,`<path d="M225 42 L225 140 L345 135 L305 76 Z" fill="${sail}"/><path d="M216 50 L154 120 L216 125 Z" fill="${trim}"/>`][d.sail%4];let cabins=[``, `<g><rect x="270" y="115" width="75" height="34" rx="6" fill="#e5e0d2"/><rect x="280" y="122" width="22" height="12" fill="#56758a"/><rect x="308" y="122" width="22" height="12" fill="#56758a"/></g>`,`<g><rect x="260" y="108" width="93" height="41" rx="5" fill="#d4dadd"/><path d="M253 108 L363 108 L345 96 L270 96 Z" fill="${trim}"/><rect x="276" y="117" width="20" height="12" fill="#55768b"/><rect x="304" y="117" width="20" height="12" fill="#55768b"/></g>`,`<g><rect x="255" y="112" width="104" height="37" rx="4" fill="#c8b58d"/><circle cx="282" cy="128" r="8" fill="#4f7185"/><circle cx="316" cy="128" r="8" fill="#4f7185"/><circle cx="346" cy="128" r="8" fill="#4f7185"/></g>`][d.cabin%4];let flags=['',`<path d="M226 48 L226 24 L270 33 L226 42 Z" fill="#b54d45"/>`,`<path d="M226 48 L226 20 L275 32 L226 44 Z" fill="#1d2429"/><text x="240" y="36" font-size="14" fill="#eee">☠</text>`,`<path d="M226 48 L226 22 L270 33 L226 43 Z" fill="#466e91"/>`][d.flag%4];return `<svg class="boat-builder-svg" viewBox="0 0 500 260"><g class="build-part ${dockPart==='hull'?'selected':''}" data-build-part="hull"><path d="${hullPath}" fill="${hullColor}" stroke="${trim}" stroke-width="6"/><path class="build-hit" d="${hullPath}"/></g><g class="build-part ${dockPart==='sail'?'selected':''}" data-build-part="sail"><line x1="222" y1="142" x2="222" y2="38" stroke="#8b6840" stroke-width="10"/><line x1="222" y1="142" x2="222" y2="38" class="build-hit"/>${sailShapes}</g><g class="build-part ${dockPart==='cabin'?'selected':''}" data-build-part="cabin">${cabins}<rect class="build-hit" x="245" y="92" width="125" height="62"/></g><g class="build-part ${dockPart==='flag'?'selected':''}" data-build-part="flag">${flags}<rect class="build-hit" x="215" y="10" width="70" height="48"/></g><g class="build-part ${dockPart==='paint'?'selected':''}" data-build-part="paint"><path d="M110 184 L390 184" stroke="${trim}" stroke-width="7"/><path class="build-hit" d="M100 184 L400 184"/></g></svg>`}
function rodBuilderSvg(){ensureDockBuilderState();let d=state.dockBuilder.rodDesign,a=rodAccent[d.accent%rodAccent.length],blank=['#a77745','#596c84','#353e48','#69908b'][d.blank%4],grip=['#5f4029','#171b20','#7d5438','#37575b'][d.grip%4],reel=['#9db0bd','#d6ae50','#292f36','#497b9d'][d.reel%4];let guideCount=[4,5,6,7][d.guides%4];let guides=Array.from({length:guideCount},(_,i)=>{let x=190+i*(225/(guideCount-1));let y=145-i*12;return `<circle cx="${x}" cy="${y}" r="7" fill="none" stroke="${a}" stroke-width="4"/>`}).join('');return `<svg class="rod-builder-svg" viewBox="0 0 500 260"><g class="build-part ${dockPart==='grip'?'selected':''}" data-build-part="grip"><path d="M60 180 L165 151" stroke="${grip}" stroke-width="22" stroke-linecap="round"/><path class="build-hit" d="M60 180 L165 151"/></g><g class="build-part ${dockPart==='blank'?'selected':''}" data-build-part="blank"><path d="M150 154 Q300 112 445 60" fill="none" stroke="${blank}" stroke-width="9" stroke-linecap="round"/><path d="M160 151 Q310 110 450 58" fill="none" stroke="${a}" stroke-width="2"/><path class="build-hit" d="M150 154 Q300 112 445 60" fill="none"/></g><g class="build-part ${dockPart==='reel'?'selected':''}" data-build-part="reel"><circle cx="155" cy="177" r="27" fill="#1b2731" stroke="${reel}" stroke-width="8"/><circle cx="155" cy="177" r="9" fill="${a}"/><path class="build-hit" d="M126 148 H184 V206 H126Z"/></g><g class="build-part ${dockPart==='guides'?'selected':''}" data-build-part="guides">${guides}<path class="build-hit" d="M182 140 Q300 105 435 58" fill="none"/></g><g class="build-part ${dockPart==='accent'?'selected':''}" data-build-part="accent"><circle cx="84" cy="174" r="10" fill="${a}"/><circle class="build-hit" cx="84" cy="174" r="20"/></g></svg>`}
function selectDockPart(part){dockPart=part;dockTrayPage=0;renderDockBuilder()}
function builderParts(){if(dockMode==='boat')return [['hull','⛵','HULL'],['sail','◢','SAIL'],['cabin','▣','CABIN'],['flag','⚑','FLAG'],['paint','●','COLOR'],['systems','⚙','SYSTEM']];if(dockMode==='rod')return [['blank','╱','BLANK'],['grip','▰','GRIP'],['reel','⊙','REEL'],['guides','○','GUIDES'],['accent','●','ACCENT'],['upgrades','⚙','UPGRADE']];return [['materials','📦','MAT'],['decor','🏰','DECOR'],['lures','~','LURES'],['fish','🐟','FISH'],['all','💰','ALL'],['help','?','VALUE']]}
function boatPartOptions(){let d=state.dockBuilder.boatDesign;if(dockPart==='hull')return hulls.map(h=>({name:h.name,art:boatMiniSvg(h.id,paints[state.boat.paint]),active:state.boat.hull===h.id,disabled:state.boat.level<h.need,note:state.boat.level>=h.need?'Hull':'Boat '+h.need,act:()=>{state.boat.hull=h.id;save();renderDockBuilder()}}));if(dockPart==='sail')return [0,1,2,3].map(i=>({name:['Classic','Square','Lateen','Twin'][i],art:'◢',active:d.sail===i,act:()=>{d.sail=i;save();renderDockBuilder()}}));if(dockPart==='cabin')return [0,1,2,3].map(i=>({name:['Open deck','Cabin','Wheelhouse','Portholes'][i],art:['≈','▣','▤','◉'][i],active:d.cabin===i,act:()=>{d.cabin=i;save();renderDockBuilder()}}));if(dockPart==='flag')return [0,1,2,3].map(i=>({name:['None','Red','Pirate','Blue'][i],art:['—','⚑','☠','⚑'][i],active:d.flag===i,act:()=>{d.flag=i;save();renderDockBuilder()}}));if(dockPart==='paint')return paints.map((c,i)=>({name:'Hull '+(i+1),art:`<span style="width:34px;height:34px;border-radius:50%;background:${c};display:block"></span>`,active:state.boat.paint===i,act:()=>{state.boat.paint=i;save();renderDockBuilder()}})).concat(sailColors.map((c,i)=>({name:'Sail '+(i+1),art:`<span style="width:34px;height:34px;border-radius:8px;background:${c};display:block"></span>`,active:d.sailColor===i,act:()=>{d.sailColor=i;save();renderDockBuilder()}}))).concat(trimColors.map((c,i)=>({name:'Trim '+(i+1),art:`<span style="width:34px;height:12px;border-radius:8px;background:${c};display:block"></span>`,active:d.trim===i,act:()=>{d.trim=i;save();renderDockBuilder()}})));let lvl=Math.floor(1200*Math.pow(1.75,state.boat.level-1)),eng=500*state.boat.engine,sto=450*state.boat.storage;return [{name:'Boat Lv '+state.boat.level,art:'⬆',note:fmt(lvl)+'G',act:()=>{if(state.gold<lvl)return toast('Need '+fmt(lvl)+' gold');state.gold-=lvl;state.boat.level++;save();renderAll()}},{name:'Engine '+state.boat.engine,art:'⚙',note:fmt(eng)+'G',act:()=>{if(state.gold<eng)return toast('Need '+fmt(eng)+' gold');state.gold-=eng;state.boat.engine++;save();renderAll()}},{name:'Storage '+state.boat.storage,art:'▣',note:fmt(sto)+'G',act:()=>{if(state.gold<sto)return toast('Need '+fmt(sto)+' gold');state.gold-=sto;state.boat.storage++;save();renderAll()}}]}
function rodPartOptions(){let d=state.dockBuilder.rodDesign;if(dockPart==='blank')return [0,1,2,3].map(i=>({name:['Cedar','Sport','Graphite','Tidal'][i],art:'╱',active:d.blank===i,act:()=>{d.blank=i;save();renderDockBuilder()}}));if(dockPart==='grip')return [0,1,2,3].map(i=>({name:['Cork','Rubber','Leather','Seafoam'][i],art:'▰',active:d.grip===i,act:()=>{d.grip=i;save();renderDockBuilder()}}));if(dockPart==='reel')return [0,1,2,3].map(i=>({name:['Silver','Gold','Black','Blue'][i],art:'⊙',active:d.reel===i,act:()=>{d.reel=i;save();renderDockBuilder()}}));if(dockPart==='guides')return [0,1,2,3].map(i=>({name:(i+4)+' Guides',art:'○○',active:d.guides===i,act:()=>{d.guides=i;save();renderDockBuilder()}}));if(dockPart==='accent')return rodAccent.map((c,i)=>({name:'Accent '+(i+1),art:`<span style="width:34px;height:34px;border-radius:50%;background:${c};display:block"></span>`,active:d.accent===i,act:()=>{d.accent=i;save();renderDockBuilder()}}));let ids=[['rod','Rod'],['line','Line'],['reel','Reel'],['sonar','Sonar']];return ids.map(([id,name])=>{let g=state.equipment[id],cost=Math.floor((160+g.level*140)*Math.pow(1.38,g.level-1));return{name:name+' '+g.level,art:gearIcon(id),note:fmt(cost)+'G',act:()=>{if(state.gold<cost)return toast('Need '+fmt(cost)+' gold');state.gold-=cost;g.level++;save();renderAll()}}})}
function sellValueForDecor(id){let d=studioDecorDefs[id]||{cat:'treasure'};return d.cat==='ruins'?220:d.cat==='treasure'?160:90}
function marketOptions(){let arr=[];if(dockPart==='materials'||dockPart==='all'){[['wood','Wood',35,'🪵'],['shells','Shells',22,'🐚'],['coral','Coral',60,'🪸']].forEach(([key,name,val,art])=>{let n=state[key]||0;if(n)arr.push({name,art,note:n+' owned · '+val+'G',sell:true,act:()=>{if(!state[key])return;state[key]--;state.gold+=val;save();renderAll()},all:()=>{let qty=state[key]||0;state[key]=0;state.gold+=qty*val;save();renderAll()}})})}if(dockPart==='decor'||dockPart==='all')Object.keys(studioDecorDefs).forEach(id=>{let n=decorAvailable(id);if(n){let val=sellValueForDecor(id);arr.push({name:studioDecorDefs[id].name,art:studioDecorDefs[id].art,note:n+' unused · '+val+'G',sell:true,act:()=>{if(decorAvailable(id)<=0)return;state.aqua.decorInventory[id]--;state.gold+=val;save();renderAll()},all:()=>{let qty=decorAvailable(id);state.aqua.decorInventory[id]-=qty;state.gold+=qty*val;save();renderAll()}})}});if(dockPart==='lures'||dockPart==='all')Object.entries(state.lures).forEach(([id,n])=>{if(n>0&&lureDefs[id]){let val=Math.max(8,Math.round(lureDefs[id].cost*.35));arr.push({name:lureDefs[id].name,art:lureDefs[id].icon,note:n+' owned · '+val+'G',sell:true,act:()=>{if(!state.lures[id])return;state.lures[id]--;state.gold+=val;save();renderAll()},all:()=>{let q=state.lures[id]||0;state.lures[id]=0;state.gold+=q*val;save();renderAll()}})}});if(dockPart==='fish'){arr=state.aquarium.map(x=>{let f=allDefs()[x.id],val=Math.round(f.value*(x.gene?.value||1));return{name:instanceName(x),art:fishSvg(x.id,x.gene),note:val+'G',sell:true,act:()=>{let i=state.aquarium.findIndex(q=>q.uid===x.uid);if(i<0)return;state.aquarium.splice(i,1);state.gold+=val;save();renderAll()}}})}if(!arr.length)arr.push({name:dockPart==='help'?'Market values':'Nothing here',art:dockPart==='help'?'💰':'📦',note:dockPart==='help'?'Treasure and rare decor sell for more.':'Collect more items first.',disabled:true});return arr}
function renderOptionGrid(items){
 let tray=$('#dockTray'),pager=$('#dockPager');
 if(!tray||!pager)return;
 tray.innerHTML='';pager.innerHTML='';
 const perPage=2,pages=Math.max(1,Math.ceil(items.length/perPage));
 dockTrayPage=clamp(dockTrayPage,0,pages-1);
 items.slice(dockTrayPage*perPage,dockTrayPage*perPage+perPage).forEach(o=>{
   let c=document.createElement('div');
   c.className='builder-option'+(o.active?' active':'');
   c.innerHTML=`<div class="art">${o.art}</div><b>${o.name}</b><small>${o.note||''}</small><div style="width:100%;display:grid;grid-template-columns:${o.sell&&o.all?'1fr 1fr':'1fr'};gap:4px"><button type="button" ${o.disabled?'disabled':''}>${o.sell?'SELL 1':o.active?'ACTIVE':'SELECT'}</button>${o.sell&&o.all?'<button class="sellbtn" type="button">ALL</button>':''}</div>`;
   let bs=c.querySelectorAll('button');
   bs[0].onclick=()=>o.act?.();
   if(bs[1])bs[1].onclick=()=>o.all?.();
   tray.appendChild(c);
 });
 if(pages>1){
   let a=document.createElement('button'),b=document.createElement('button'),s=document.createElement('span');
   a.textContent='‹';b.textContent='›';s.textContent=(dockTrayPage+1)+' / '+pages;
   a.disabled=dockTrayPage===0;b.disabled=dockTrayPage===pages-1;
   a.onclick=()=>{dockTrayPage--;renderDockBuilder()};b.onclick=()=>{dockTrayPage++;renderDockBuilder()};
   pager.append(a,s,b);
 }
}
function renderDockBuilder(){ensureDockBuilderState();$('#dockGold').textContent=fmt(state.gold);$('#woodTxt').textContent=fmt(state.wood);$('#shellTxt').textContent=fmt(state.shells);$('#coralTxt').textContent=fmt(state.coral);document.querySelectorAll('#dockModeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===dockMode));let visual=$('#dockBuildVisual');if(dockMode==='boat'){visual.innerHTML=boatBuilderSvg();$('#dockHint').textContent='Tap the boat itself to edit the selected part.'}else if(dockMode==='rod'){visual.innerHTML=rodBuilderSvg();$('#dockHint').textContent='Tap the rod itself to edit the selected part.'}else{visual.innerHTML='<div class="market-stage"><div class="market-crate">📦</div><div class="market-copy">Sell extra finds without leaving the dock.</div></div>';$('#dockHint').textContent='Choose a category below, then sell what you do not need.'}visual.onpointerdown=ev=>{let part=ev.target.closest&&ev.target.closest('[data-build-part]');if(!part)return;ev.preventDefault();ev.stopPropagation();selectDockPart(part.dataset.buildPart)};visual.onclick=ev=>{let part=ev.target.closest&&ev.target.closest('[data-build-part]');if(!part)return;selectDockPart(part.dataset.buildPart)};let parts=$('#dockPartBar');parts.innerHTML='';builderParts().forEach(([id,icon,label])=>{let b=document.createElement('button');b.classList.toggle('active',dockPart===id);b.innerHTML=`<span>${icon}</span>${label}`;b.onclick=()=>selectDockPart(id);parts.appendChild(b)});let opts=dockMode==='boat'?boatPartOptions():dockMode==='rod'?rodPartOptions():marketOptions();$('#dockTrayTitle').textContent=(builderParts().find(x=>x[0]===dockPart)||['','',dockMode==='sell'?'MARKET':'PART'])[2];renderOptionGrid(opts)}
function initDockBuilder(){ensureDockBuilderState();document.querySelectorAll('#dockModeTabs button').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=()=>{dockMode=b.dataset.mode;dockPart=dockMode==='boat'?'hull':dockMode==='rod'?'blank':'materials';dockTrayPage=0;renderDockBuilder()}})}
function showSystemNotice(message){let el=$('#systemNotice');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(showSystemNotice.timer);showSystemNotice.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function safeRender(name,fn){try{fn()}catch(error){console.error('[Tide & Tranquility] '+name,error);showSystemNotice('A display section recovered automatically.')}}
function renderAll(){
 syncViewportVars();
 [
  ['top',renderTop],['bait',renderBait],['lures',renderLures],['status',renderStatus],
  ['chart',renderWorldMap],['dock',renderDockBuilder],['aquarium',renderAquarium],
  ['hunts',renderHunts],['relics',renderRelics],['atlas',renderBook],['log',renderCaptainLog]
 ].forEach(([name,fn])=>safeRender(name,fn));
 requestAnimationFrame(()=>{fitWorldMap();});
}

let captainLogTab='missions';
const logPageState={missions:0,hunts:0,relics:0,atlas:0,data:0};
function logSource(tab){if(tab==='missions')return missionDefs();if(tab==='hunts')return huntEntries();if(tab==='relics')return relicDefs;if(tab==='atlas')return Object.entries(allDefs());return[]}
function logPageSize(tab){let compact=window.innerHeight<650||(window.innerWidth>window.innerHeight&&window.innerHeight<560);if(tab==='atlas')return compact?4:6;return compact?2:3}
function pagedLogItems(tab,items,size=logPageSize(tab)){let pages=Math.max(1,Math.ceil(items.length/size));logPageState[tab]=clamp(logPageState[tab]||0,0,pages-1);return{items:items.slice(logPageState[tab]*size,logPageState[tab]*size+size),pages}}
function renderLogPager(){let p=$('#logPager');if(!p)return;p.innerHTML='';let items=logSource(captainLogTab),size=logPageSize(captainLogTab),pages=Math.max(1,Math.ceil(items.length/size)),page=clamp(logPageState[captainLogTab]||0,0,pages-1);logPageState[captainLogTab]=page;if(pages<=1||captainLogTab==='data')return;let prev=document.createElement('button'),next=document.createElement('button'),label=document.createElement('span');prev.textContent='‹';next.textContent='›';label.textContent=(page+1)+' / '+pages;prev.disabled=page===0;next.disabled=page===pages-1;const redraw=()=>{if(captainLogTab==='missions')renderMissions();else if(captainLogTab==='hunts')renderHunts();else if(captainLogTab==='relics')renderRelics();else if(captainLogTab==='atlas')renderBook()};prev.onclick=()=>{logPageState[captainLogTab]--;redraw()};next.onclick=()=>{logPageState[captainLogTab]++;redraw()};p.append(prev,label,next)}
function setCaptainLogTab(tab){captainLogTab=tab||captainLogTab;document.querySelectorAll('#logTabs button').forEach(b=>{let active=b.dataset.logtab===captainLogTab;b.classList.toggle('active',active);b.setAttribute('aria-selected',active?'true':'false')});document.querySelectorAll('[data-logpanel]').forEach(p=>p.classList.toggle('active',p.dataset.logpanel===captainLogTab));renderLogPager()}
function initCaptainLog(){document.querySelectorAll('#logTabs button').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.setAttribute('role','tab');b.addEventListener('click',()=>setCaptainLogTab(b.dataset.logtab))});setCaptainLogTab(captainLogTab)}
function renderCaptainLog(){initCaptainLog();$('#missionHeroCopy')&&($('#missionHeroCopy').textContent='Story '+Math.min(state.story+1,storyDefs.length)+' of '+storyDefs.length+' · '+state.catches+' catches · '+state.relics.length+' relics.');renderExperienceSettings();renderLogPager()}

function renderExperienceSettings(){let p=currentPrefs();[['soundToggle','soundState','sound'],['musicToggle','musicState','music'],['hapticToggle','hapticState','haptics'],['motionToggle','motionState','motion']].forEach(([bid,sid,key])=>{let b=$('#'+bid),s=$('#'+sid);if(b){b.setAttribute('aria-pressed',p[key]?'true':'false');b.classList.toggle('active',!!p[key])}if(s)s.textContent=p[key]?'ON':'OFF'});let v=$('#audioVolume');if(v&&document.activeElement!==v)v.value=String(p.volume)}
function togglePreference(key){state.preferences[key]=!state.preferences[key];if(key==='sound'&&state.preferences.sound)ensureAudio();if(key==='haptics'&&state.preferences.haptics)haptic('success');save();applyPreferences();renderExperienceSettings()}
function bindExperienceSettings(){[['soundToggle','sound'],['musicToggle','music'],['hapticToggle','haptics'],['motionToggle','motion']].forEach(([id,key])=>$('#'+id)?.addEventListener('click',()=>togglePreference(key)));let v=$('#audioVolume');if(v){v.addEventListener('input',e=>{state.preferences.volume=clamp(Number(e.target.value)||0,0,1);ensureAudio();applyPreferences()});v.addEventListener('change',()=>save())}}
