function chartProgress(){ensureV10State();let total=V10_SPOTS.reduce((a,x)=>a+x.length,0),known=Object.values(state.expedition.discoveredSpots).reduce((a,x)=>a+x.length,0);return Math.round(known/total*100)}
function voyageWeatherIcon(){return state.weather.type==='storm'?'ϟ':state.weather.type==='rain'?'☂':state.weather.type==='mist'?'≈':oceanCycle().night?'☾':'☀'}
function expeditionLog(text,icon='✧'){ensureV10State();state.expedition.log.push({t:now(),icon,text});state.expedition.log=state.expedition.log.slice(-18)}
function renderSpotCards(region){ensureV10State();return V10_SPOTS[region].map((s,i)=>{let known=spotDiscovered(region,i),current=region===state.region&&currentSpotIndex(region)===i,eligible=spotRequirementsMet(region,i);return `<button type="button" class="spot-card${current?' current':''}${known?'':' locked'}" data-spot="${i}" ${known?'':'disabled'}><span class="spot-icon">${known?s.icon:'?'}</span><span><b>${known?s.name:'Uncharted Water'}</b><small>${known?s.desc:(eligible?'A new route can now be charted.':s.hint)}</small></span><span class="spot-state">${current?'ANCHORED':known?'FISH':'LOCKED'}</span></button>`}).join('')}
let v10VoyageBusy=false,v10PlannerRegion=0;
function openExpeditionPlanner(region=state.region){ensureV10State();v10PlannerRegion=clamp(region,0,regions.length-1);let r=regions[v10PlannerRegion],same=v10PlannerRegion===state.region,unlocked=v10PlannerRegion<=state.unlockedRegion&&state.boat.level>=r.boat&&state.story>=r.story;$('#expeditionKicker').textContent=same?'LOCAL WATERS':'EXPEDITION';$('#expeditionTitle').textContent=same?r.name:'Course to '+r.name;$('#voyageFrom').textContent=currentRegion().name;$('#voyageTo').textContent=r.name;$('#voyageWeather').textContent=voyageWeatherIcon();$('#voyageVisual').classList.remove('sailing');$('#voyageVisual').style.display=same?'none':'block';$('#expeditionBody').innerHTML=`<div class="expedition-summary"><b>${same?'Choose a fishing ground':unlocked?'Ready to sail':'Route not yet available'}</b><small>${same?'Each ground has different depth, bite pressure, and rare-fish odds.':unlocked?'Voyages can reveal salvage, migrations, chart fragments, and hidden water.':'Requires Boat '+r.boat+' and story progress.'}</small></div><div class="spot-grid">${renderSpotCards(v10PlannerRegion)}</div>`;$('#expeditionBody').querySelectorAll('.spot-card:not([disabled])').forEach(b=>b.onclick=()=>selectFishingSpot(v10PlannerRegion,+b.dataset.spot));$('#expeditionSecondary').textContent='CLOSE';$('#expeditionSecondary').disabled=false;$('#expeditionSecondary').onclick=closeExpeditionModal;$('#expeditionActions').style.gridTemplateColumns=same?'1fr':'1fr 1fr';$('#expeditionPrimary').style.display=same?'none':'block';$('#expeditionPrimary').textContent='SAIL';$('#expeditionPrimary').disabled=!unlocked;$('#expeditionPrimary').onclick=()=>startVoyage(v10PlannerRegion);$('#expeditionClose').disabled=false;$('#expeditionClose').onclick=closeExpeditionModal;$('#expeditionModal').classList.add('show');haptic('select')}
function closeExpeditionModal(){if(v10VoyageBusy)return;$('#expeditionModal').classList.remove('show')}
function selectFishingSpot(region,idx){ensureV10State();if(!spotDiscovered(region,idx))return toast('That water is still uncharted.');if(region!==state.region)return openExpeditionPlanner(region);state.expedition.currentSpot[region]=idx;fish=[];specials=[];resetHook();for(let i=0;i<14;i++)spawnFish(i>11);save();renderAll();closeExpeditionModal();haptic('success');toast('Anchored at '+V10_SPOTS[region][idx].name);updateLegendClueForSpot()}
function chooseVoyageEvent(to){let pool=V10_VOYAGE_EVENTS.slice();if(state.weather.type==='storm')pool.push(V10_VOYAGE_EVENTS.find(x=>x.id==='squall'));if(to>=4)pool.push(V10_VOYAGE_EVENTS.find(x=>x.id==='glow'));return pick(pool.filter(Boolean))}
function startVoyage(to){ensureV10State();if(v10VoyageBusy)return;let r=regions[to],unlocked=to<=state.unlockedRegion&&state.boat.level>=r.boat&&state.story>=r.story;if(!unlocked)return toast('That route is still locked.');if(to===state.region)return openExpeditionPlanner(to);v10VoyageBusy=true;let from=state.region,event=chooseVoyageEvent(to),visual=$('#voyageVisual');visual.style.display='block';visual.classList.remove('sailing');void visual.offsetWidth;visual.classList.add('sailing');$('#expeditionKicker').textContent='UNDERWAY';$('#expeditionTitle').textContent=regions[from].name+' → '+r.name;$('#expeditionBody').innerHTML='<div class="expedition-summary"><b>Crossing open water</b><small>The route, weather, and boat systems can produce encounters between regions.</small></div>';$('#expeditionActions').style.gridTemplateColumns='1fr 1fr';$('#expeditionPrimary').style.display='block';$('#expeditionPrimary').disabled=true;$('#expeditionPrimary').textContent='SAILING…';$('#expeditionSecondary').disabled=true;$('#expeditionClose').disabled=true;haptic('cast');noiseBurst(.09,.025,220);setTimeout(()=>{let extra=event.apply?.()||'';$('#expeditionBody').innerHTML=`<div class="voyage-event"><span class="event-icon">${event.icon}</span><span><b>${event.name}</b><small>${event.desc}${extra?' · '+extra:''}</small></span></div>`;tone(620,.06);},850);setTimeout(()=>{state.region=to;state.expedition.voyages++;state.expedition.currentSpot[to]=state.expedition.currentSpot[to]||0;if(!spotDiscovered(to,0))state.expedition.discoveredSpots[to].push(0);if(event.id==='message'||event.id==='glow')tryDiscoverSpot(to,true);expeditionLog('Voyage to '+r.name,'⛵');fish=[];specials=[];resetHook();updateWeather(true);for(let i=0;i<14;i++)spawnFish(i>11);save();renderAll();v10VoyageBusy=false;$('#expeditionKicker').textContent='LANDFALL';$('#expeditionTitle').textContent=r.name;$('#expeditionPrimary').disabled=false;$('#expeditionPrimary').textContent='DROP ANCHOR';$('#expeditionPrimary').onclick=()=>{closeExpeditionModal();openExpeditionPlanner(to)};$('#expeditionSecondary').disabled=false;$('#expeditionSecondary').textContent='CLOSE';$('#expeditionSecondary').onclick=closeExpeditionModal;$('#expeditionClose').disabled=false;haptic('success');tone(760,.08);},1750)}
function openHarborDispatch(){ensureV10State();let crew=V10_CREW[(state.story+state.expedition.discoveries)%V10_CREW.length],logs=state.expedition.log.slice(-3).reverse();state.expedition.crewSeen[crew.id]=(state.expedition.crewSeen[crew.id]||0)+1;$('#expeditionKicker').textContent='HARBOR DISPATCH';$('#expeditionTitle').textContent=crew.name;$('#voyageVisual').style.display='none';$('#expeditionBody').innerHTML=`<div class="dispatch-card"><span class="dispatch-avatar">${crew.icon}</span><span><b>${crew.name}</b><small>${crew.role}</small><p>${crew.line(state)}</p></span></div><div class="expedition-summary"><b>Expedition Record</b><small>${state.expedition.voyages} voyages · ${state.expedition.discoveries} hidden grounds · ${state.expedition.chartFragments} chart fragments · ${chartProgress()}% charted</small></div><div class="expedition-log">${logs.length?logs.map(x=>`<div class="expedition-log-row"><span>${x.icon}</span><span>${x.text}</span><time>${Math.max(1,Math.round((now()-x.t)/60000))}m</time></div>`).join(''):'<div class="expedition-log-row"><span>✧</span><span>Your expedition log is waiting for its first entry.</span></div>'}</div>`;$('#expeditionActions').style.gridTemplateColumns='1fr 1fr';$('#expeditionPrimary').style.display='block';$('#expeditionPrimary').textContent='OPEN CHART';$('#expeditionPrimary').disabled=false;$('#expeditionPrimary').onclick=()=>{closeExpeditionModal();document.querySelector('.nav[data-screen="map"]')?.click()};$('#expeditionSecondary').textContent='CLOSE';$('#expeditionSecondary').disabled=false;$('#expeditionSecondary').onclick=closeExpeditionModal;$('#expeditionClose').disabled=false;$('#expeditionClose').onclick=closeExpeditionModal;$('#expeditionModal').classList.add('show');save();haptic('select')}
function legendClue(id){ensureV10State();return state.expedition.legendaryClues[id]||0}
function requiredLegendSpot(id){return V10_LEGEND_SPOT[id]||[legendaryDefs[id]?.region||0,0]}
function updateLegendClueForCatch(id){if(state.hunts.active!==id)return;let h=legendaryDefs[id];if(!h||state.region!==h.region)return;state.expedition.huntCatches[id]=(state.expedition.huntCatches[id]||0)+1;if(legendClue(id)<1&&state.expedition.huntCatches[id]>=2){state.expedition.legendaryClues[id]=1;showSystemNotice('Legendary clue found · feeding pattern');haptic('success');save()}}
function updateLegendClueForSonar(){let id=state.hunts.active;if(!id||state.region!==legendaryDefs[id]?.region)return;if(legendClue(id)>=1&&legendClue(id)<2){state.expedition.legendaryClues[id]=2;showSystemNotice('Legendary clue found · sonar trail');haptic('success');save();renderAll()}}
function updateLegendClueForSpot(){let id=state.hunts.active;if(!id)return;let [r,s]=requiredLegendSpot(id);if(state.region===r&&currentSpotIndex()===s&&legendClue(id)>=2&&legendClue(id)<3){state.expedition.legendaryClues[id]=3;showSystemNotice(legendaryDefs[id].name+' can now appear here.');haptic('treasure');tone(940,.10);save();renderAll()}}
function startLegendTracking(id){ensureV10State();let h=legendaryDefs[id];if(!h||state.unlockedRegion<h.region)return;state.hunts.active=id;if(state.hunts.completed[id])state.expedition.legendaryClues[id]=Math.max(2,legendClue(id));state.expedition.huntCatches[id]=0;save();renderAll();toast('Tracking '+h.name);if(state.region!==h.region)openExpeditionPlanner(h.region);else openHuntModal()}
const v10BaseChooseFishId=chooseFishId;chooseFishId=function(forceRare=false){ensureV10State();let id=state.hunts.active,allow=true;if(id){let [r,s]=requiredLegendSpot(id);allow=legendClue(id)>=3&&state.region===r&&currentSpotIndex()===s}let active=state.hunts.active;if(active&&!allow)state.hunts.active=null;let extra=state.expedition.bonusUntil>now()&&state.expedition.bonusType==='migration';let result=v10BaseChooseFishId(forceRare||extra&&Math.random()<.11);state.hunts.active=active;return result};
const v10BaseCaptainBite=captainBiteBonus;captainBiteBonus=function(){ensureV10State();let s=currentSpotDef(),voy=state.expedition.bonusUntil>now()&&state.expedition.bonusType==='migration'?1.16:1;return v10BaseCaptainBite()*s.bite*voy};
const v10BaseCaptainRare=captainRareBonus;captainRareBonus=function(){ensureV10State();return v10BaseCaptainRare()*currentSpotDef().rare};
const v10BaseLineDepth=lineDepth;lineDepth=function(){ensureV10State();return Math.round(v10BaseLineDepth()+currentSpotDef().depth)};
const v10BaseSpawnFish=spawnFish;function activeFishCap(){let ev=activeOceanEvent(),base=7+(state.region>=3?1:0)+(state.region>=5?1:0);if(ev&&(oceanRuntime.event==='migration'||oceanRuntime.event==='frenzy'))base+=2;return clamp(base,7,11)}spawnFish=function(forceRare=false,opts={}){let cap=activeFishCap();if(fish.length>=cap)return;let before=fish.length;v10BaseSpawnFish(forceRare,opts);if(fish.length>cap)fish.splice(cap);if(fish.length>before){let q=fish[fish.length-1],s=currentSpotDef(),f=allDefs()[q.id];if(q&&f&&s&&opts.depth==null){let minD=Math.max(25,f.min),maxD=Math.min(currentRegion().depth-20,f.max),center=clamp((f.min+Math.min(f.max,currentRegion().depth))/2+s.depth*.35,25,currentRegion().depth-25);q.y=depthToY(clamp(center+rand(-65,65),minD,maxD));let minY=depthToY(minD),maxY=depthToY(maxD);for(let tries=0;tries<5;tries++){let crowded=fish.some(p=>p!==q&&Math.abs(p.y-q.y)<34&&Math.abs(p.x-q.x)<110);if(!crowded)break;let shift=(tries%2?1:-1)*(36+tries*11);q.y=clamp(q.y+shift,Math.min(minY,maxY),Math.max(minY,maxY))}}}};let fishDensityTimer=0;function rebalanceFishDensity(dt){fishDensityTimer-=dt;if(fishDensityTimer>0)return;fishDensityTimer=.8;let cap=activeFishCap();while(fish.length>cap){let idx=fish.findIndex(q=>!q.hooked&&q!==hook.fish);if(idx<0)break;fish.splice(idx,1)}};
const v10BaseDrawHabitat=drawHabitat;drawHabitat=function(){v10BaseDrawHabitat();drawV10SpotHabitat()};
function drawV10SpotHabitat(){let s=currentSpotDef(),base=H-20,t=currentPrefs().motion?animT:0;ctx.save();ctx.globalAlpha=.26;if(s.art==='wreck'){ctx.strokeStyle='#8e7457';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(280,base-42);ctx.lineTo(350,base-18);ctx.lineTo(305,base-8);ctx.closePath();ctx.stroke();ctx.strokeStyle='#705c48';ctx.beginPath();ctx.moveTo(312,base-38);ctx.lineTo(312,base-88);ctx.stroke()}else if(['ruins','city','crown','vault','gate','statues'].includes(s.art)){ctx.fillStyle='#a79877';for(let i=0;i<4;i++){let x=220+i*48,h=35+(i%3)*24;ctx.fillRect(x,base-h,12,h);ctx.fillRect(x-7,base-h-7,26,7)}if(s.art==='gate'){ctx.strokeStyle='#c2a768';ctx.lineWidth=5;ctx.beginPath();ctx.arc(330,base-48,44,Math.PI,0);ctx.stroke()}}else if(s.art==='vents'){for(let i=0;i<4;i++){let x=260+i*45;ctx.fillStyle='#5a4b43';ctx.beginPath();ctx.moveTo(x-12,base);ctx.lineTo(x,base-35-i*5);ctx.lineTo(x+13,base);ctx.fill();ctx.fillStyle='rgba(210,235,235,.12)';ctx.beginPath();ctx.arc(x+Math.sin(t+i)*7,base-55-(t*9+i*14)%70,4+i%2,0,TAU);ctx.fill()}}else if(s.art==='rocks'||s.art==='storm'){ctx.fillStyle='#5d6670';for(let i=0;i<5;i++){let x=230+i*48;ctx.beginPath();ctx.moveTo(x-24,base);ctx.lineTo(x,base-35-(i%2)*22);ctx.lineTo(x+25,base);ctx.fill()}}else if(s.art==='mirror'){ctx.strokeStyle='rgba(160,225,236,.18)';ctx.lineWidth=1;for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(290,waterY+130+i*52,130-i*12,12,0,0,TAU);ctx.stroke()}}ctx.restore()}
const v10BaseLandFish=landFish;landFish=function(q){let id=state.hunts.active;ensureV10State();state.expedition.regionCatches[state.region]=(state.expedition.regionCatches[state.region]||0)+1;if(id)updateLegendClueForCatch(id);let discovered=tryDiscoverSpot(state.region,false);v10BaseLandFish(q);if(discovered)save()};
const v10BaseLandSpecial=landSpecial;landSpecial=function(s){ensureV10State();if(s.type==='bottle')state.expedition.chartFragments++;v10BaseLandSpecial(s);if(s.type==='relic'||s.type==='bottle'){tryDiscoverSpot(state.region,true);expeditionLog(s.type==='relic'?'Recovered a relic near '+currentSpotDef().name:'Chart fragment recovered','✧');save()}};
const v10BaseRenderTop=renderTop;renderTop=function(){ensureV10State();v10BaseRenderTop();let s=currentSpotDef(),k=$('#regionKicker'),d=$('#regionDepth');if(k)k.textContent='REGION '+(state.region+1)+' · '+s.name.toUpperCase();if(d)d.textContent='Reach '+Math.min(currentRegion().depth,lineDepth())+'m · '+s.target+' · '+Math.round((s.rare-1)*100)+'% rare'};
const v10BaseRenderStatus=renderStatus;renderStatus=function(){v10BaseRenderStatus();let e=$('#status'),s=currentSpotDef();if(e)e.textContent=s.name+' · '+s.target+' · '+(s.bite>=1.12?'strong bite':s.rare>=1.25?'rare-water':'balanced water')+' · '+e.textContent};
const v10BaseRenderWorldMap=renderWorldMap;renderWorldMap=function(){ensureV10State();v10BaseRenderWorldMap();$('#chartProgressText')&&($('#chartProgressText').textContent=chartProgress()+'%');let canvas=$('#worldMapCanvas');if(canvas){regions.forEach((r,i)=>{if(i>state.unlockedRegion){let f=document.createElement('div');f.className='map-fog';f.style.left=(regionLayout[i].x/1280*100)+'%';f.style.top=(regionLayout[i].y/760*100)+'%';f.style.animationDelay=(-i*.9)+'s';canvas.appendChild(f)}})}let lg=$('#mapLegend'),s=currentSpotDef();if(lg)lg.innerHTML=`<div class="spot-map-note"><span><b>${s.icon} ${s.name}</b>${state.expedition.discoveredSpots[state.region].length}/${V10_SPOTS[state.region].length} grounds charted</span></div>`};
travelToRegionIndex=function(i){openExpeditionPlanner(i)};
renderHunts=function(){ensureV10State();let e=$('#huntList');if(!e)return;e.innerHTML='';let entries=huntEntries(),page=pagedLogItems('hunts',entries,logPageSize('hunts'));page.items.forEach(([id,h])=>{let done=state.hunts.completed[id]||0,unlocked=state.unlockedRegion>=h.region,active=state.hunts.active===id,clue=legendClue(id),req=requiredLegendSpot(id),spot=V10_SPOTS[req[0]][req[1]],r=document.createElement('div');r.className='row '+(active?'hunt-live':'');r.innerHTML=`<div class="row-icon" style="color:#b77700">★</div><div class="row-copy"><b>${h.name}</b><small>${regions[h.region].name} · ${active?clue+'/3 clues · ':''}${clue>=3?'Target located at '+spot.name:h.desc} · Caught ${done}</small></div><button type="button" ${!unlocked?'disabled':''}>${active?'TRACKING':done?'TRACK AGAIN':'TRACK'}</button>`;r.querySelector('button').onclick=()=>{if(unlocked)startLegendTracking(id)};e.appendChild(r)});renderLogPager()};
openHuntModal=function(){ensureV10State();let id=state.hunts.active,h=id?legendaryDefs[id]:null,e=$('#huntModalBody');if(!h)e.innerHTML='<div class="card"><h3>No hunt active</h3><p>Open Captain’s Log → Hunts and begin tracking a legendary fish.</p></div>';else{let clue=legendClue(id),[rr,ss]=requiredLegendSpot(id),spot=V10_SPOTS[rr][ss];e.innerHTML=`<div class="card legendary-card"><h3>${h.name}</h3><p>${h.desc}<br><b>Target water:</b> ${regions[rr].name} · ${spot.name}</p><div class="hunt-path"><div class="hunt-step ${clue>=1?'done':''}"><b>1 · EVIDENCE</b><small>Catch 2 fish</small></div><div class="hunt-step ${clue>=2?'done':''}"><b>2 · TRAIL</b><small>Use sonar</small></div><div class="hunt-step ${clue>=3?'done':''}"><b>3 · LAIR</b><small>Reach ${spot.name}</small></div></div><button class="widebtn" id="huntRoute" type="button">${state.region===rr?'OPEN LOCAL WATERS':'CHART COURSE'}</button><button class="widebtn danger" id="cancelHunt" type="button">CANCEL TRACKING</button></div>`;$('#huntRoute')?.addEventListener('click',()=>{$('#huntModal').classList.remove('show');openExpeditionPlanner(rr)});$('#cancelHunt')?.addEventListener('click',()=>{state.hunts.active=null;save();$('#huntModal').classList.remove('show');renderAll()})}$('#huntModal').classList.add('show')};
const v10BaseRenderCaptainLog=renderCaptainLog;renderCaptainLog=function(){v10BaseRenderCaptainLog();let h=$('#missionHeroCopy');if(h)h.textContent='Expedition '+chartProgress()+'% charted · '+state.expedition.voyages+' voyages · '+state.catches+' catches · '+state.relics.length+' relics'};
const v10BaseRenderHarborPulse=renderHarborPulse;renderHarborPulse=function(){v10BaseRenderHarborPulse();let b=$('#harborTrend');if(b)b.textContent=state.expedition?.chartFragments?'CHART '+state.expedition.chartFragments:'DISPATCH'};
const v10BaseSave=save;save=function(){ensureV10State();return v10BaseSave()};
ensureV10State();
// Replace the V9 Harbor listener with V10 Dispatch behavior.
(()=>{let old=$('#harborPulse');if(old){let neo=old.cloneNode(true);old.replaceWith(neo);neo.addEventListener('click',openHarborDispatch)}})();
(()=>{let old=$('#huntBtn');if(old){let neo=old.cloneNode(true);old.replaceWith(neo);neo.addEventListener('click',openHuntModal)}})();
$('#chartProgressBtn')?.addEventListener('click',()=>openExpeditionPlanner(state.region));
$('.region-info')?.addEventListener('click',()=>openExpeditionPlanner(state.region));
$('#expeditionSecondary')?.addEventListener('click',closeExpeditionModal);$('#expeditionClose')?.addEventListener('click',closeExpeditionModal);
$('#sonarBtn')?.addEventListener('click',()=>setTimeout(updateLegendClueForSonar,40));

ensureV10State();

ensureAquaStudioState();
ensureDockBuilderState();
bindExperienceSettings();applyPreferences();syncViewportVars();
window.addEventListener('error',event=>{console.error(event.error||event.message);showSystemNotice('Recovered from an unexpected display issue.')});
window.addEventListener('unhandledrejection',event=>{console.error(event.reason);showSystemNotice('Recovered from an unexpected display issue.')});
if(window.visualViewport){visualViewport.addEventListener('resize',scheduleLayout);visualViewport.addEventListener('scroll',scheduleLayout)}
if(window.ResizeObserver){new ResizeObserver(scheduleLayout).observe($('#app'))}

initWorldMap();
initDockBuilder();
initCaptainLog();
setupCanvasResolution();
window.addEventListener('resize',()=>{scheduleLayout();setupCanvasResolution()});window.addEventListener('orientationchange',()=>{scheduleLayout();setupCanvasResolution()});
updateWeather(true);oceanCondition();for(let i=0;i<14;i++)spawnFish();resetHook();renderAll();renderCaptainLog();renderOceanHud(true);requestAnimationFrame(frame);
setInterval(()=>{renderTop();renderStatus();renderHatchery()},1200);
