function endCanvasPointer(e){if(canvasPointerId!==e.pointerId)return;e.preventDefault();try{canvas.releasePointerCapture?.(e.pointerId)}catch(_){}canvasPointerId=null}
canvas.addEventListener('pointerup',endCanvasPointer,{passive:false});canvas.addEventListener('pointercancel',endCanvasPointer,{passive:false});
canvas.addEventListener('touchmove',e=>{if(['sinking','hooked','casting'].includes(hook.mode))e.preventDefault()},{passive:false});
$('#steerBtn').addEventListener('click',()=>toast(hook.mode==='hooked'?'Drag opposite the fish pull to reduce surges.':hook.mode==='sinking'?'Drag directly on the water to steer the lure.':'Cast first, then drag across the water.'));
$('#claimAqua').addEventListener('click',claimAquarium);$('#feedAqua').addEventListener('click',feedAquarium);$('#cleanAqua').addEventListener('click',cleanAquarium);$('#slotUpgrade').addEventListener('click',expandAquarium);$('#tankUpgrade').addEventListener('click',upgradeTank);$('#breedBtn').addEventListener('click',breedSelected);$('#hatchNowBtn').addEventListener('click',()=>hatchEgg(false));
$('#sellCatch').addEventListener('click',()=>catchAction('sell'));$('#aquaCatch').addEventListener('click',()=>catchAction('aqua'));$('#baitCatch').addEventListener('click',()=>catchAction('bait'));
$('#exportBtn').addEventListener('click',()=>{saveMode='export';$('#saveTitle').textContent='Export Save';$('#saveText').value=encodeSaveData(state);$('#saveAction').textContent='SELECT TEXT';$('#saveModal').classList.add('show')});
$('#importBtn').addEventListener('click',()=>{saveMode='import';$('#saveTitle').textContent='Import Save';$('#saveText').value='';$('#saveAction').textContent='IMPORT SAVE';$('#saveModal').classList.add('show')});
$('#saveAction').addEventListener('click',()=>{if(saveMode==='export'){let e=$('#saveText');e.focus();e.select();toast('Save text selected. Use Android Copy.')}else{try{state=sanitizeState(decodeSaveData($('#saveText').value));ensureAquaStudioState();ensureDockBuilderState();save();applyPreferences();closeModal('saveModal');fish=[];specials=[];resetHook();for(let i=0;i<12;i++)spawnFish();renderAll();haptic('success');toast('Save imported.')}catch(error){console.warn('[Tide & Tranquility] Import failed.',error);haptic('error');toast('Invalid save text.')}}});
$('#resetBtn').addEventListener('click',()=>{if(!confirm('Factory reset Tide & Tranquility? This erases all progress.'))return;if(!confirm('Final confirmation: erase everything and start over?'))return;try{localStorage.removeItem('tideTranquilitySaveV2');localStorage.removeItem('tideTranquilitySaveV2Backup');localStorage.removeItem('tideTranquilitySave')}catch(e){}state=defaultState();ensureAquaStudioState();aquaFishActors=[];selectedDecorUid=null;fish=[];specials=[];resetHook();for(let i=0;i<12;i++)spawnFish();updateWeather(true);save();applyPreferences();renderAll();haptic('success');toast('Factory reset complete.')});
// Prevent Android long-press text selection/callouts on game UI. Save textarea remains exempt.
$('#app').addEventListener('contextmenu',e=>{if(e.target.closest('textarea,input,.selectable'))return;e.preventDefault()});document.addEventListener('pointerdown',e=>{ensureAudio();if(e.target.closest('button:not(:disabled),select'))haptic('tap')},{capture:true,passive:true,once:false});
window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden){save();clearTimeout(musicTimer)}else{updateOffline();ensureAudio();applyPreferences();renderAll()}});

const studioDecorDefs={
 coral:{name:'Coral Grove',art:'🪸',layer:'back',starter:true,size:1.2,cat:'nature'},
 kelp:{name:'Kelp Fronds',art:'🌿',layer:'back',starter:true,size:1.15,cat:'nature'},
 shells:{name:'Shell Bed',art:'🐚',layer:'back',starter:true,size:1,cat:'nature'},
 castle:{name:'Sunken Castle',art:'🏰',layer:'back',size:1.45,cat:'treasure'},
 chest:{name:'Treasure Chest',art:'🧰',layer:'front',size:1.05,cat:'treasure'},
 anchor:{name:'Old Anchor',art:'⚓',layer:'front',size:1.05,cat:'treasure'},
 lantern:{name:'Pearl Lantern',art:'🏮',layer:'front',size:1.05,cat:'treasure'},
 ruins:{name:'Ancient Ruins',art:'🏛️',layer:'back',size:1.35,cat:'ruins'},
 statue:{name:'Sea Statue',art:'🗿',layer:'front',size:1.05,cat:'ruins'},
 crown:{name:'Sunken Crown',art:'👑',layer:'front',size:.9,cat:'treasure'},
 ship:{name:'Mini Shipwreck',art:'⛵',layer:'back',size:1.3,cat:'treasure'},
 wheel:{name:'Captain Wheel',art:'☸️',layer:'front',size:1,cat:'treasure'},
 gem:{name:'Ocean Gem',art:'💎',layer:'front',size:.8,cat:'treasure'},
 compass:{name:'Lost Compass',art:'🧭',layer:'front',size:.9,cat:'treasure'},
 pearl:{name:'Giant Pearl',art:'🦪',layer:'front',size:1,cat:'treasure'}
};
let aquaFishActors=[],selectedDecorUid=null,aquaDragState=null,aquaEditMode=false,aquaSheetKind=null,aquaSheetTab='decor',aquaSheetPage=0;
function makeAquaItem(defId,x=.5,y=.78,s=null){let d=studioDecorDefs[defId]||studioDecorDefs.coral;return{uid:'ad_'+now()+'_'+Math.random().toString(36).slice(2,7),def:defId,x,y,s:s||d.size||1,rot:0,layer:d.layer||'back'}}
function defaultAquaItems(){return[makeAquaItem('coral',.34,.82,1.15),makeAquaItem('kelp',.55,.79,1.08),makeAquaItem('shells',.72,.85,.9)]}
function ensureAquaStudioState(){
 if(!state.aqua)state.aqua=defaultState().aqua;
 if(!Array.isArray(state.aqua.items))state.aqua.items=defaultAquaItems();
 if(!Array.isArray(state.aqua.unlockedDecor))state.aqua.unlockedDecor=['coral','kelp','shells'];
 if(!state.aqua.decorInventory||typeof state.aqua.decorInventory!=='object')state.aqua.decorInventory={coral:3,kelp:3,shells:3};
 ['coral','kelp','shells'].forEach(id=>{state.aqua.decorInventory[id]=Math.max(state.aqua.decorInventory[id]||0,3);if(!state.aqua.unlockedDecor.includes(id))state.aqua.unlockedDecor.push(id)});
 state.aqua.unlockedDecor.forEach(id=>{if(studioDecorDefs[id]&&!studioDecorDefs[id].starter&&state.aqua.decorInventory[id]==null)state.aqua.decorInventory[id]=1});
 state.aqua.items.forEach(it=>{if(!it.uid)it.uid='ad_'+Math.random().toString(36).slice(2,8);if(!studioDecorDefs[it.def])it.def='coral';if(it.s==null)it.s=studioDecorDefs[it.def].size||1;if(!it.layer)it.layer=studioDecorDefs[it.def].layer||'back';it.x=clamp(+it.x||.5,.05,.95);it.y=clamp(+it.y||.8,.1,.91)});
 Object.keys(studioDecorDefs).forEach(id=>{let placed=state.aqua.items.filter(x=>x.def===id).length;if(placed>(state.aqua.decorInventory[id]||0))state.aqua.decorInventory[id]=placed});
 if(selectedDecorUid&&!state.aqua.items.some(x=>x.uid===selectedDecorUid))selectedDecorUid=null;
}
function decorOwned(id){ensureAquaStudioState();return state.aqua.decorInventory[id]||0}
function decorPlaced(id){return state.aqua.items.filter(x=>x.def===id).length}
function decorAvailable(id){return Math.max(0,decorOwned(id)-decorPlaced(id))}
function selectedDecor(){ensureAquaStudioState();return state.aqua.items.find(x=>x.uid===selectedDecorUid)||null}
function setAquaEditMode(on){aquaEditMode=!!on;if(!aquaEditMode)selectedDecorUid=null;let stage=$('#aquaStage'),btn=$('#aquaEditBtn');if(stage)stage.classList.toggle('editing',aquaEditMode);if(btn){btn.classList.toggle('active',aquaEditMode);btn.querySelector('b').textContent=aquaEditMode?'DONE':'EDIT'}let label=$('#aquaModeText');if(label)label.textContent=aquaEditMode?'Edit mode · drag, resize, rotate':'Living display';renderAquaEditor();refreshAquaSelection()}
function addDecorToTank(id){ensureAquaStudioState();if(decorAvailable(id)<=0)return toast('No unused '+studioDecorDefs[id].name+' pieces.');let d=studioDecorDefs[id],it=makeAquaItem(id,.5,.7,d.size);state.aqua.items.push(it);selectedDecorUid=it.uid;closeAquaSheet();setAquaEditMode(true);save();renderAquarium();toast(d.name+' added. Drag it into place.')}
function renderAquaEditor(){let item=selectedDecor(),name=$('#aquaEditName'),hint=$('#aquaEditHint'),label=$('#aquaEditLabel');if(item){let d=studioDecorDefs[item.def];if(name)name.textContent=d.name;if(hint)hint.textContent='Drag item to move · drag ⤢ to resize · drag ↻ to rotate';if(label)label.textContent='EDIT MODE · drag handles to transform'}else{if(name)name.textContent='Select an item';if(hint)hint.textContent='Tap a decoration, then drag it or a transform handle.';if(label)label.textContent='EDIT MODE · tap item to edit'}}
function updateAquaItemEl(item){let view=$('#aquaView'),el=view&&view.querySelector('[data-uid="'+item.uid+'"]');if(!el)return;el.style.left=(item.x*100)+'%';el.style.top=(item.y*100)+'%';el.style.fontSize=(33*(item.s||1))+'px';el.style.transform='translate(-50%,-50%) rotate('+(item.rot||0)+'deg)'}
function deleteSelectedDecor(){let item=selectedDecor();if(!item)return;state.aqua.items=state.aqua.items.filter(x=>x.uid!==item.uid);selectedDecorUid=null;aquaDragState=null;save();renderAquarium();toast('Decoration returned to inventory.')}
function refreshAquaSelection(){let view=$('#aquaView');if(view)view.querySelectorAll('.aqua-item').forEach(el=>el.classList.toggle('selected',aquaEditMode&&el.dataset.uid===selectedDecorUid));renderAquaEditor()}
function syncAquaFishActors(force=false){ensureAquaStudioState();let ids=new Set(state.aquarium.map(x=>x.uid));aquaFishActors=aquaFishActors.filter(a=>ids.has(a.uid));state.aquarium.forEach((x,i)=>{let actor=aquaFishActors.find(a=>a.uid===x.uid);if(!actor||force){let size=clamp((x.gene?.size||1),.85,1.45);let lane=((i%5)+1)/6;let next={uid:x.uid,id:x.id,gene:x.gene||{},x:rand(.12,.88),y:clamp(lane+rand(-.13,.13),.16,.84),vx:(Math.random()<.5?-1:1)*(14+Math.random()*17),vy:rand(-4,4),wander:rand(.7,2.8),size};if(actor)Object.assign(actor,next);else aquaFishActors.push(next)}})}
function updateAquariumStudio(dt){let view=$('#aquaView');if(!view||!$('#screen-aquarium').classList.contains('active'))return;syncAquaFishActors();let W=view.clientWidth||320,H=view.clientHeight||380,fishLayer=view.querySelector('#aquaFishLayer');aquaFishActors.forEach((a,i)=>{a.wander-=dt;if(a.wander<=0){a.wander=rand(1.1,3.4);a.vx=clamp(a.vx+rand(-12,12),-30,30);a.vy=clamp(a.vy+rand(-6,6),-9,9)}a.x+=a.vx*dt/W;a.y+=a.vy*dt/H+Math.sin(animT*1.3+i*.7)*.0007;if(a.x<.08){a.x=.08;a.vx=Math.abs(a.vx)}if(a.x>.92){a.x=.92;a.vx=-Math.abs(a.vx)}if(a.y<.13){a.y=.13;a.vy=Math.abs(a.vy)}if(a.y>.87){a.y=.87;a.vy=-Math.abs(a.vy)}let el=fishLayer&&fishLayer.querySelector('[data-fish="'+a.uid+'"]');if(el){let dir=a.vx<0?-1:1;el.style.left=(a.x*100)+'%';el.style.top=(a.y*100)+'%';el.style.transform='translate(-50%,-50%) scaleX('+dir+') scale('+(0.82+a.size*.28)+')'}})}
function tankThemeClass(){ensureAquaStudioState();return themes[state.aqua.theme]?.cls||'theme-reef'}
function itemScreenCenter(item,view){let r=view.getBoundingClientRect();return{x:r.left+item.x*r.width,y:r.top+item.y*r.height}}
function beginAquaGesture(ev,uid,el,mode='move'){if(!aquaEditMode)return;let item=state.aqua.items.find(x=>x.uid===uid),view=$('#aquaView');if(!item||!view)return;selectedDecorUid=uid;let c=itemScreenCenter(item,view);aquaDragState={uid,pointerId:ev.pointerId,mode,startX:ev.clientX,startY:ev.clientY,startItemX:item.x,startItemY:item.y,startScale:item.s||1,startRot:item.rot||0,centerX:c.x,centerY:c.y};if(mode==='resize')aquaDragState.startDist=Math.max(12,Math.hypot(ev.clientX-c.x,ev.clientY-c.y));if(mode==='rotate')aquaDragState.startAngle=Math.atan2(ev.clientY-c.y,ev.clientX-c.x);try{el.setPointerCapture?.(ev.pointerId)}catch(e){}refreshAquaSelection()}
function renderAquarium(){ensureAquaStudioState();let stored=aquariumStored();$('#aquaCount').textContent=state.aquarium.length+'/'+state.aqua.slots;$('#aquaRate').textContent=fmt(aquariumRate());$('#aquaStored').textContent=fmt(stored);$('#aquaHappy').textContent=aquariumHappiness()+'%';$('#claimAqua').disabled=stored<=0;let view=$('#aquaView');view.className='aqua-view '+tankThemeClass();view.innerHTML='<div class="aqua-layer aqua-decor-layer" id="aquaDecorLayer"></div><div class="aqua-layer aqua-fish-layer" id="aquaFishLayer"></div><div class="bubbles"></div>';
 let dl=$('#aquaDecorLayer');state.aqua.items.forEach(it=>{let d=studioDecorDefs[it.def],el=document.createElement('div');el.className='aqua-item '+(it.layer||d.layer||'back')+(aquaEditMode&&selectedDecorUid===it.uid?' selected':'');el.dataset.uid=it.uid;el.innerHTML='<span class="aqua-art">'+d.art+'</span><button class="aqua-action-handle aqua-size-handle" type="button" aria-label="Drag to resize decoration">⤢</button><button class="aqua-action-handle aqua-delete-handle" type="button" aria-label="Remove decoration">×</button><button class="aqua-action-handle aqua-rotate-handle" type="button" aria-label="Drag to rotate decoration">↻</button>';dl.appendChild(el);updateAquaItemEl(it);el.addEventListener('pointerdown',ev=>{if(!aquaEditMode)return;let sizeBtn=ev.target.closest('.aqua-size-handle'),delBtn=ev.target.closest('.aqua-delete-handle'),rotBtn=ev.target.closest('.aqua-rotate-handle');if(delBtn){ev.preventDefault();ev.stopPropagation();selectedDecorUid=it.uid;deleteSelectedDecor();return}if(sizeBtn){ev.preventDefault();ev.stopPropagation();beginAquaGesture(ev,it.uid,el,'resize');return}if(rotBtn){ev.preventDefault();ev.stopPropagation();beginAquaGesture(ev,it.uid,el,'rotate');return}ev.preventDefault();ev.stopPropagation();beginAquaGesture(ev,it.uid,el,'move')})});
 let fl=$('#aquaFishLayer');state.aquarium.forEach(x=>{let el=document.createElement('div');el.className='aqua-fish';el.dataset.fish=x.uid;el.innerHTML=fishSvg(x.id,x.gene);fl.appendChild(el)});syncAquaFishActors(false);updateAquariumStudio(0);
 view.onpointerdown=ev=>{if(aquaEditMode&&(ev.target===view||ev.target.classList.contains('bubbles')||ev.target.id==='aquaFishLayer'||ev.target.id==='aquaDecorLayer')){selectedDecorUid=null;refreshAquaSelection()}};
 setAquaEditMode(aquaEditMode);if(aquaSheetKind)renderAquaSheet()}
function aquariumPointerMove(ev){if(!aquaEditMode||!aquaDragState||aquaDragState.pointerId!==ev.pointerId)return;let item=state.aqua.items.find(x=>x.uid===aquaDragState.uid),view=$('#aquaView');if(!item||!view)return;ev.preventDefault();let r=view.getBoundingClientRect(),g=aquaDragState;if(g.mode==='resize'){let dist=Math.max(8,Math.hypot(ev.clientX-g.centerX,ev.clientY-g.centerY));item.s=clamp(g.startScale*(dist/g.startDist),.5,3)}else if(g.mode==='rotate'){let angle=Math.atan2(ev.clientY-g.centerY,ev.clientX-g.centerX),delta=angle-g.startAngle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;item.rot=((g.startRot+delta*180/Math.PI)%360+360)%360}else{item.x=clamp(g.startItemX+(ev.clientX-g.startX)/r.width,.06,.94);item.y=clamp(g.startItemY+(ev.clientY-g.startY)/r.height,.1,.9)}updateAquaItemEl(item);selectedDecorUid=item.uid;refreshAquaSelection()}
function aquariumPointerUp(ev){if(!aquaDragState||aquaDragState.pointerId!==ev.pointerId)return;aquaDragState=null;save()}
window.addEventListener('pointermove',aquariumPointerMove,{passive:false});window.addEventListener('pointerup',aquariumPointerUp);window.addEventListener('pointercancel',aquariumPointerUp);
function openAquaSheet(kind,tab){aquaSheetKind=kind;aquaSheetTab=tab||((kind==='inventory')?'decor':'');aquaSheetPage=0;let s=$('#aquaSheet');s.classList.add('open');s.setAttribute('aria-hidden','false');renderAquaSheet()}
function closeAquaSheet(){aquaSheetKind=null;let s=$('#aquaSheet');if(s){s.classList.remove('open');s.setAttribute('aria-hidden','true')}}
function pageSlice(arr,size){let pages=Math.max(1,Math.ceil(arr.length/size));aquaSheetPage=clamp(aquaSheetPage,0,pages-1);return{items:arr.slice(aquaSheetPage*size,aquaSheetPage*size+size),pages}}
function renderPager(pages){let p=$('#aquaSheetPager');p.innerHTML='';if(pages<=1)return;let prev=document.createElement('button'),next=document.createElement('button'),txt=document.createElement('span');prev.textContent='‹';next.textContent='›';txt.textContent=(aquaSheetPage+1)+' / '+pages;prev.disabled=aquaSheetPage<=0;next.disabled=aquaSheetPage>=pages-1;prev.onclick=()=>{aquaSheetPage--;renderAquaSheet()};next.onclick=()=>{aquaSheetPage++;renderAquaSheet()};p.append(prev,txt,next)}
function renderAquaSheet(){let title=$('#aquaSheetTitle'),sub=$('#aquaSheetSub'),tabs=$('#aquaSheetTabs'),body=$('#aquaSheetBody'),pager=$('#aquaSheetPager');if(!aquaSheetKind)return;tabs.innerHTML='';body.innerHTML='';pager.innerHTML='';
 if(aquaSheetKind==='inventory'){title.textContent='ADD TO AQUARIUM';sub.textContent='Your collection stays here — not on the main screen.';['decor','theme'].forEach(t=>{let b=document.createElement('button');b.textContent=t==='decor'?'DECOR':'THEMES';b.className=aquaSheetTab===t?'active':'';b.onclick=()=>{aquaSheetTab=t;aquaSheetPage=0;renderAquaSheet()};tabs.appendChild(b)});if(aquaSheetTab==='theme'){let g=document.createElement('div');g.className='aqua-theme-grid';Object.entries(themes).forEach(([id,t])=>{let b=document.createElement('button');b.className='aqua-theme-card'+(state.aqua.theme===id?' active':'');b.style.background=id==='reef'?'linear-gradient(#4f9cab,#155d78)':id==='moon'?'linear-gradient(#60728d,#173b5e)':id==='kelp'?'linear-gradient(#5e9b7e,#1a5f55)':'linear-gradient(#718384,#28515b)';b.innerHTML='<b>'+t.name+'</b>';b.onclick=()=>{state.aqua.theme=id;save();renderAquarium();renderAquaSheet()};g.appendChild(b)});body.appendChild(g);return}let ids=Object.keys(studioDecorDefs).filter(id=>decorOwned(id)>0);let page=pageSlice(ids,6),g=document.createElement('div');g.className='aqua-inventory-grid';page.items.forEach(id=>{let d=studioDecorDefs[id],avail=decorAvailable(id),b=document.createElement('button');b.className='aqua-inventory-item';b.disabled=avail<=0;b.innerHTML='<span class="count">'+avail+'/'+decorOwned(id)+'</span><div class="art">'+d.art+'</div><b>'+d.name+'</b><small>'+(avail?'Tap to place':'All placed')+'</small>';b.onclick=()=>addDecorToTank(id);g.appendChild(b)});body.appendChild(g);renderPager(page.pages);return}
 if(aquaSheetKind==='care'){title.textContent='AQUARIUM CARE';sub.textContent='Maintenance and upgrades, kept out of the main view.';let g=document.createElement('div');g.className='aqua-care-grid';let actions=[['🍽️','Feed fish','Boost happiness 30 min',()=>{feedAquarium();renderAquaSheet()}],['✨','Clean tank','Restore cleanliness',()=>{cleanAquarium();renderAquaSheet()}],['↔','Expand tank',state.aqua.slots+' slots',()=>{expandAquarium();renderAquaSheet()}],['⬆','Upgrade tank','Level '+state.aqua.level,()=>{upgradeTank();renderAquaSheet()}]];actions.forEach(a=>{let b=document.createElement('button');b.className='aqua-care-card';b.innerHTML='<span>'+a[0]+'</span><b>'+a[1]+'</b><small>'+a[2]+'</small>';b.onclick=a[3];g.appendChild(b)});body.appendChild(g);return}
 if(aquaSheetKind==='fish'){title.textContent='YOUR FISH';sub.textContent='Manage aquarium residents.';let page=pageSlice(state.aquarium,4),g=document.createElement('div');g.className='aqua-fish-grid';page.items.forEach(x=>{let f=allDefs()[x.id],c=document.createElement('div');c.className='aqua-fish-card';c.innerHTML='<div class="fishpic">'+fishSvg(x.id,x.gene)+'</div><div><b>'+instanceName(x)+'</b><small>'+f.name+' · x'+(x.gene?.value||1).toFixed(2)+'</small><div class="mini-actions"><button class="sell">SELL</button></div></div>';c.querySelector('.sell').onclick=()=>{let i=state.aquarium.findIndex(q=>q.uid===x.uid);if(i<0)return;state.gold+=Math.round(f.value*(x.gene?.value||1));state.aquarium.splice(i,1);state.hatchery.parents=state.hatchery.parents.filter(u=>u!==x.uid);aquaFishActors=aquaFishActors.filter(a=>a.uid!==x.uid);save();renderAquarium();renderAquaSheet()};g.appendChild(c)});if(!page.items.length){body.innerHTML='<div class="hatch-status-compact"><div class="copy"><b>No fish yet</b><small>Catch a fish and choose AQUARIUM.</small></div></div>'}else body.appendChild(g);renderPager(page.pages);return}
 if(aquaSheetKind==='hatch'){title.textContent='HATCHERY';sub.textContent='Breeding is now part of the aquarium workspace.';let wrap=document.createElement('div');wrap.className='aqua-hatch-layout';let status=document.createElement('div');status.className='hatch-status-compact';let egg=state.hatchery.egg;if(egg){let left=Math.max(0,egg.ready-now());status.innerHTML='<div class="egg-mini">◉</div><div class="copy"><b>'+(left<=0?'Egg ready!':'Incubating')+'</b><small>'+(left<=0?'Ready to hatch':Math.ceil(left/1000)+' sec remaining')+'</small></div><button>'+(left<=0?'HATCH':'HATCH EARLY')+'</button>';status.querySelector('button').onclick=()=>{hatchEgg(false);renderAquaSheet()}}else{let names=state.hatchery.parents.map(u=>{let q=state.aquarium.find(x=>x.uid===u);return q?instanceName(q):'?'});status.innerHTML='<div class="egg-mini">♡</div><div class="copy"><b>'+(names.length?names.join(' + '):'Choose two parents')+'</b><small>Tap fish below to select breeders.</small></div><button '+(state.hatchery.parents.length!==2?'disabled':'')+'>BREED</button>';status.querySelector('button').onclick=()=>{breedSelected();renderAquaSheet()}}wrap.appendChild(status);let page=pageSlice(state.aquarium,4),g=document.createElement('div');g.className='aqua-fish-grid';page.items.forEach(x=>{let f=allDefs()[x.id],sel=state.hatchery.parents.includes(x.uid),c=document.createElement('button');c.className='aqua-fish-card'+(sel?' selected':'');c.innerHTML='<div class="fishpic">'+fishSvg(x.id,x.gene)+'</div><div><b>'+instanceName(x)+'</b><small>'+f.name+(sel?' · PARENT':' · tap to select')+'</small></div>';c.onclick=()=>{toggleBreeder(x.uid);renderAquaSheet()};g.appendChild(c)});wrap.appendChild(g);body.appendChild(wrap);renderPager(page.pages);return}}

function maybeFindTreasureDecor(){ensureAquaStudioState();if(Math.random()>.62)return null;let pool=Object.keys(studioDecorDefs).filter(id=>!studioDecorDefs[id].starter),id=pool[Math.floor(Math.random()*pool.length)];state.aqua.decorInventory[id]=(state.aqua.decorInventory[id]||0)+1;if(!state.aqua.unlockedDecor.includes(id))state.aqua.unlockedDecor.push(id);return id}
function landSpecial(s){haptic('treasure');specialPending=s;let w=ensureWorldState();if(s.type==='chest'){let g=Math.floor(rand(100,500)*(1+state.region*.25)),pearl=Math.random()<.18?1:0,wood=Math.max(1,Math.floor(rand(1,4)*salvageYieldMultiplier())),shell=Math.floor(rand(0,3)),decor=maybeFindTreasureDecor();state.gold+=g;state.pearls+=pearl;state.wood+=wood;state.shells+=shell;state.materialsFound+=wood+shell;$('#specialTitle').textContent='Treasure Chest';$('#specialArt').textContent=decor?studioDecorDefs[decor].art:'▣';$('#specialName').textContent=decor?'Aquarium Treasure: '+studioDecorDefs[decor].name:'Saltworn Cache';$('#specialMeta').textContent=`${g} gold · ${wood} wood · ${shell} shells${pearl?' · 1 pearl':''}${decor?' · '+studioDecorDefs[decor].name+' added to aquarium inventory':''}`;tone(820,.08)}else if(s.type==='bottle'){let g=Math.floor(rand(90,220)*(1+state.region*.12));w.messagesFound++;w.chartLuckUntil=Math.max(w.chartLuckUntil||0,now()+5*60000);state.gold+=g;state.shells+=1;$('#specialTitle').textContent='Message in a Bottle';$('#specialArt').textContent='✉';$('#specialName').textContent='Saltworn Chart Fragment';$('#specialMeta').textContent=`${g} gold · 1 shell · rare-fish sightings improved for 5 minutes.`;tone(760,.09);setTimeout(()=>tone(960,.07),80)}else if(s.type==='debris'){let wood=Math.max(1,Math.floor(rand(2,6)*salvageYieldMultiplier())),shell=Math.random()<.45?1:0;w.debrisFound++;state.wood+=wood;state.shells+=shell;state.materialsFound+=wood+shell;$('#specialTitle').textContent='Drifting Wreckage';$('#specialArt').textContent='▰';$('#specialName').textContent='Salvaged Timber';$('#specialMeta').textContent=`${wood} wood${shell?' · 1 shell':''}. The current carried it here.`;tone(520,.07)}else{let r=relicDefs.find(x=>x.id===s.id);if(r&&!state.relics.includes(r.id)){state.relics.push(r.id);state.pearls++;state.secrets[state.region]=(state.secrets[state.region]||0)+1}$('#specialTitle').textContent='Ancient Relic';$('#specialArt').textContent=r?r.icon:'◈';$('#specialName').textContent=r?r.name:'Unknown Relic';$('#specialMeta').textContent=r?r.desc:'Recovered from a submerged ruin.';tone(900,.12)}$('#specialModal').classList.add('show');save();renderAll()}


// Pirate Map + component-based Dock Builder
const regionLayout=[{x:180,y:520},{x:330,y:405},{x:500,y:325},{x:650,y:430},{x:805,y:285},{x:965,y:180},{x:1110,y:330}];
let worldMapPan={x:null,y:null},worldMapDrag=null,worldMapZoom=.82;
let dockMode='boat',dockPart='hull',dockTrayPage=0;
const sailColors=['#efe0bd','#b84e45','#486e8d','#5f805c','#755c8d'];
const trimColors=['#d6bd81','#e5e0d2','#242a31','#7f4939','#5e7181'];
const rodAccent=['#c8d4df','#ffd36d','#79d5cb','#e28787','#9da7ee'];
function ensureDockBuilderState(){let d={boatDesign:{sail:0,cabin:0,flag:0,sailColor:0,trim:0},rodDesign:{blank:0,grip:0,reel:0,guides:0,accent:0}};if(!state.dockBuilder)state.dockBuilder=JSON.parse(JSON.stringify(d));state.dockBuilder.boatDesign=Object.assign({},d.boatDesign,state.dockBuilder.boatDesign||{});state.dockBuilder.rodDesign=Object.assign({},d.rodDesign,state.dockBuilder.rodDesign||{})}
function syncViewportVars(){
 const vv=window.visualViewport,h=Math.max(320,Math.round(vv?.height||window.innerHeight||document.documentElement.clientHeight||800));
 document.documentElement.style.setProperty('--app-height',h+'px');
 const nav=$('.bottom')?.getBoundingClientRect().height||64;document.documentElement.style.setProperty('--nav-height',Math.ceil(nav)+'px');setupCanvasResolution();
}
let layoutFrame=0;
function scheduleLayout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{syncViewportVars();fitWorldMap()})}
function buildStoryCard(){if(state.story>=storyDefs.length)return '<b>Story Complete</b><p>The whole chart is open. Legendary hunts and treasure remain.</p>';let d=storyDefs[state.story],ok=d.ok(state);return `<b>Chapter ${state.story+1}: ${d.title}</b><p>${d.goal} · Reward: ${d.reward}</p><button type="button" ${ok?'':'disabled'}>${ok?'CLAIM':'INCOMPLETE'}</button>`}
function pirateMapSvg(){let islands=regionLayout.map((p,i)=>{let s=1+(i%3)*.12;return `<g transform="translate(${p.x},${p.y}) scale(${s})"><path d="M-66 18 Q-78 -10 -50 -38 Q-16 -62 20 -45 Q58 -51 78 -20 Q68 12 41 28 Q6 49 -34 39Z" fill="#b58b4d" stroke="#6a4a27" stroke-width="4"/><path d="M-49 4 Q-20 -25 4 -13 Q24 -35 48 -9 Q24 -2 13 14 Q-17 6 -38 22Z" fill="#6f7b43" opacity=".88"/><path d="M-7 17 l12 -26 l12 26Z" fill="#745438" opacity=".6"/></g>`}).join('');let route=regionLayout.map((p,i)=>(i?'L ':'M ')+p.x+' '+p.y).join(' ');return `<svg class="pirate-map-art" viewBox="0 0 1280 760" preserveAspectRatio="none"><defs><filter id="paper"><feTurbulence baseFrequency=".012" numOctaves="3" seed="7" type="fractalNoise" result="n"/><feBlend in="SourceGraphic" in2="n" mode="multiply"/></filter><pattern id="waves" width="54" height="34" patternUnits="userSpaceOnUse"><path d="M2 20 q12 -11 24 0 q12 11 24 0" fill="none" stroke="#775b38" stroke-width="1.2" opacity=".22"/></pattern></defs><rect width="1280" height="760" fill="#d2b477"/><rect width="1280" height="760" fill="url(#waves)"/><path d="M30 28 Q340 8 620 30 T1245 25 L1252 720 Q920 742 645 724 T27 732Z" fill="none" stroke="#75502a" stroke-width="5" opacity=".45"/><path d="${route}" fill="none" stroke="#6f4024" stroke-width="5" stroke-dasharray="4 15" stroke-linecap="round" opacity=".7"/>${islands}<g transform="translate(105,120)" stroke="#5c4125" fill="none"><circle r="58" stroke-width="3"/><circle r="43"/><path d="M0 -72 L9 -13 L0 0 L-9 -13Z M72 0 L13 9 L0 0 L13 -9Z M0 72 L-9 13 L0 0 L9 13Z M-72 0 L-13 -9 L0 0 L-13 9Z" fill="#65451f"/><text x="0" y="-82" text-anchor="middle" fill="#5c4125" font-family="Georgia" font-size="19">N</text></g><g fill="#5d4225" opacity=".72" font-family="Georgia"><text x="1100" y="610" font-size="42">☠</text><text x="1020" y="620" font-size="15">BEWARE</text><text x="720" y="590" font-size="34">✕</text><text x="747" y="596" font-size="13">Lost Gold</text><text x="430" y="640" font-size="34">🐉</text><text x="463" y="644" font-size="13">Sea Beast</text><text x="220" y="175" font-size="24">⚓</text><text x="850" y="500" font-size="27">⛵</text></g><g stroke="#5e4428" stroke-width="2" opacity=".48"><path d="M170 620 q22 -22 44 0 q22 22 44 0" fill="none"/><path d="M870 90 q22 -22 44 0 q22 22 44 0" fill="none"/><path d="M560 90 q22 -22 44 0 q22 22 44 0" fill="none"/></g></svg>`}
function fitWorldMap(){
 const wrap=$('#worldMapWrap'),canvas=$('#worldMapCanvas');
 if(!wrap||!canvas)return;
 canvas.style.left='0';canvas.style.top='0';canvas.style.width='100%';canvas.style.height='100%';canvas.style.transform='none';
}

function clampWorldMapPan(){let wrap=$('#worldMapWrap');if(!wrap)return;let sw=1280*worldMapZoom,sh=760*worldMapZoom,minX=wrap.clientWidth-sw-18,minY=wrap.clientHeight-sh-18;worldMapPan.x=clamp(worldMapPan.x??10,Math.min(10,minX),10);worldMapPan.y=clamp(worldMapPan.y??10,Math.min(10,minY),10)}
function applyWorldMapPan(){fitWorldMap()}
function centerWorldMap(){fitWorldMap()}
function travelToRegionIndex(i){let r=regions[i],unlocked=i<=state.unlockedRegion&&state.boat.level>=r.boat&&state.story>=r.story;if(!unlocked)return toast('That island is still locked.');if(i===state.region)return toast('You are already anchored at '+r.name+'.');state.region=i;fish=[];specials=[];resetHook();for(let j=0;j<12;j++)spawnFish();updateWeather(true);save();renderAll();centerWorldMap(i);haptic('success');toast('Sailed to '+r.name)}
function initWorldMap(){fitWorldMap()}
function renderWorldMap(){let s=$('#storyCard');if(s){s.innerHTML=buildStoryCard();s.querySelector('button')?.addEventListener('click',claimStory)}let canvas=$('#worldMapCanvas');if(!canvas)return;canvas.innerHTML=pirateMapSvg();const nextIndex=Math.min(state.unlockedRegion+1,regions.length-1);regions.forEach((r,i)=>{const unlocked=i<=state.unlockedRegion&&state.boat.level>=r.boat&&state.story>=r.story,active=i===state.region,next=i===nextIndex&&i!==state.region;let n=document.createElement('button');n.type='button';n.className='worldmap-node'+(active?' active':'')+(next?' next':'')+(unlocked?'':' locked');n.style.left=(regionLayout[i].x/1280*100)+'%';n.style.top=(regionLayout[i].y/760*100)+'%';n.disabled=!unlocked;n.setAttribute('aria-label',active?'Current location: '+r.name:unlocked?'Sail to '+r.name:'Locked: '+r.name);n.setAttribute('aria-pressed',active?'true':'false');n.innerHTML=`<span class="marker-glyph">${active?'⛵':i+1}</span><span class="marker-name">${r.name}</span>`;n.addEventListener('click',()=>{if(active)toast('Anchored at '+r.name);else travelToRegionIndex(i)});canvas.appendChild(n)});let fc=$('#forecastText'),lg=$('#mapLegend'),next=regions[nextIndex],c=oceanCondition(),ev=activeOceanEvent();if(fc)fc.innerHTML=`<b>${currentRegion().name}</b>${c.label} · ${weatherLabel()} · ${currentLabel(c.current)}${ev?' · '+ev.name:''}`;if(lg)lg.innerHTML=state.unlockedRegion<regions.length-1?`<b>Next: ${next.name}</b>Boat ${next.boat}+ and story progress.`:`<b>Chart complete</b>All waters discovered.`;fitWorldMap()}
function boatBuilderSvg(){ensureDockBuilderState();let d=state.dockBuilder.boatDesign,h=state.boat.hull,hullColor=paints[state.boat.paint]||paints[0],sail=sailColors[d.sailColor%sailColors.length],trim=trimColors[d.trim%trimColors.length];let hullPath={skiff:'M70 150 L405 150 L360 205 L120 205 Z',cutter:'M55 145 L430 145 L385 207 L110 207 Z',sloop:'M48 143 L445 143 L395 210 L105 210 Z',research:'M45 145 L455 145 L410 212 L95 212 Z',trawler:'M35 138 L465 138 L420 216 L90 216 Z',crown:'M30 134 L470 134 L425 218 L85 218 Z'}[h]||'M70 150 L405 150 L360 205 L120 205 Z';let sailShapes=[`<path d="M225 48 L225 139 L347 139 Z" fill="${sail}"/>`,`<path d="M224 42 L224 140 L340 126 L315 66 Z" fill="${sail}"/>`,`<path d="M221 45 L221 140 L320 140 L352 92 Z" fill="${sail}"/><path d="M215 55 L145 126 L215 126 Z" fill="${sail}" opacity=".9"/>`,`<path d="M225 42 L225 140 L345 135 L305 76 Z" fill="${sail}"/><path d="M216 50 L154 120 L216 125 Z" fill="${trim}"/>`][d.sail%4];let cabins=[``, `<g><rect x="270" y="115" width="75" height="34" rx="6" fill="#e5e0d2"/><rect x="280" y="122" width="22" height="12" fill="#56758a"/><rect x="308" y="122" width="22" height="12" fill="#56758a"/></g>`,`<g><rect x="260" y="108" width="93" height="41" rx="5" fill="#d4dadd"/><path d="M253 108 L363 108 L345 96 L270 96 Z" fill="${trim}"/><rect x="276" y="117" width="20" height="12" fill="#55768b"/><rect x="304" y="117" width="20" height="12" fill="#55768b"/></g>`,`<g><rect x="255" y="112" width="104" height="37" rx="4" fill="#c8b58d"/><circle cx="282" cy="128" r="8" fill="#4f7185"/><circle cx="316" cy="128" r="8" fill="#4f7185"/><circle cx="346" cy="128" r="8" fill="#4f7185"/></g>`][d.cabin%4];let flags=['',`<path d="M226 48 L226 24 L270 33 L226 42 Z" fill="#b54d45"/>`,`<path d="M226 48 L226 20 L275 32 L226 44 Z" fill="#1d2429"/><text x="240" y="36" font-size="14" fill="#eee">☠</text>`,`<path d="M226 48 L226 22 L270 33 L226 43 Z" fill="#466e91"/>`][d.flag%4];return `<svg class="boat-builder-svg" viewBox="0 0 500 260"><g class="build-part ${dockPart==='hull'?'selected':''}" data-build-part="hull"><path d="${hullPath}" fill="${hullColor}" stroke="${trim}" stroke-width="6"/><path class="build-hit" d="${hullPath}"/></g><g class="build-part ${dockPart==='sail'?'selected':''}" data-build-part="sail"><line x1="222" y1="142" x2="222" y2="38" stroke="#8b6840" stroke-width="10"/><line x1="222" y1="142" x2="222" y2="38" class="build-hit"/>${sailShapes}</g><g class="build-part ${dockPart==='cabin'?'selected':''}" data-build-part="cabin">${cabins}<rect class="build-hit" x="245" y="92" width="125" height="62"/></g><g class="build-part ${dockPart==='flag'?'selected':''}" data-build-part="flag">${flags}<rect class="build-hit" x="215" y="10" width="70" height="48"/></g><g class="build-part ${dockPart==='paint'?'selected':''}" data-build-part="paint"><path d="M110 184 L390 184" stroke="${trim}" stroke-width="7"/><path class="build-hit" d="M100 184 L400 184"/></g></svg>`}
function rodBuilderSvg(){ensureDockBuilderState();let d=state.dockBuilder.rodDesign,a=rodAccent[d.accent%rodAccent.length],blank=['#a77745','#596c84','#353e48','#69908b'][d.blank%4],grip=['#5f4029','#171b20','#7d5438','#37575b'][d.grip%4],reel=['#9db0bd','#d6ae50','#292f36','#497b9d'][d.reel%4];let guideCount=[4,5,6,7][d.guides%4];let guides=Array.from({length:guideCount},(_,i)=>{let x=190+i*(225/(guideCount-1));let y=145-i*12;return `<circle cx="${x}" cy="${y}" r="7" fill="none" stroke="${a}" stroke-width="4"/>`}).join('');return `<svg class="rod-builder-svg" viewBox="0 0 500 260"><g class="build-part ${dockPart==='grip'?'selected':''}" data-build-part="grip"><path d="M60 180 L165 151" stroke="${grip}" stroke-width="22" stroke-linecap="round"/><path class="build-hit" d="M60 180 L165 151"/></g><g class="build-part ${dockPart==='blank'?'selected':''}" data-build-part="blank"><path d="M150 154 Q300 112 445 60" fill="none" stroke="${blank}" stroke-width="9" stroke-linecap="round"/><path d="M160 151 Q310 110 450 58" fill="none" stroke="${a}" stroke-width="2"/><path class="build-hit" d="M150 154 Q300 112 445 60" fill="none"/></g><g class="build-part ${dockPart==='reel'?'selected':''}" data-build-part="reel"><circle cx="155" cy="177" r="27" fill="#1b2731" stroke="${reel}" stroke-width="8"/><circle cx="155" cy="177" r="9" fill="${a}"/><path class="build-hit" d="M126 148 H184 V206 H126Z"/></g><g class="build-part ${dockPart==='guides'?'selected':''}" data-build-part="guides">${guides}<path class="build-hit" d="M182 140 Q300 105 435 58" fill="none"/></g><g class="build-part ${dockPart==='accent'?'selected':''}" data-build-part="accent"><circle cx="84" cy="174" r="10" fill="${a}"/><circle class="build-hit" cx="84" cy="174" r="20"/></g></svg>`}
function selectDockPart(part){dockPart=part;dockTrayPage=0;renderDockBuilder()}
function builderParts(){if(dockMode==='boat')return [['hull','⛵','HULL'],['sail','◢','SAIL'],['cabin','▣','CABIN'],['flag','⚑','FLAG'],['paint','●','COLOR'],['systems','⚙','SYSTEM']];if(dockMode==='rod')return [['blank','╱','BLANK'],['grip','▰','GRIP'],['reel','⊙','REEL'],['guides','○','GUIDES'],['accent','●','ACCENT'],['upgrades','⚙','UPGRADE']];return [['materials','📦','MAT'],['decor','🏰','DECOR'],['lures','~','LURES'],['fish','🐟','FISH'],['all','💰','ALL'],['help','?','VALUE']]}
function boatPartOptions(){let d=state.dockBuilder.boatDesign;if(dockPart==='hull')return hulls.map(h=>({name:h.name,art:boatMiniSvg(h.id,paints[state.boat.paint]),active:state.boat.hull===h.id,disabled:state.boat.level<h.need,note:state.boat.level>=h.need?'Hull':'Boat '+h.need,act:()=>{state.boat.hull=h.id;save();renderDockBuilder()}}));if(dockPart==='sail')return [0,1,2,3].map(i=>({name:['Classic','Square','Lateen','Twin'][i],art:'◢',active:d.sail===i,act:()=>{d.sail=i;save();renderDockBuilder()}}));if(dockPart==='cabin')return [0,1,2,3].map(i=>({name:['Open deck','Cabin','Wheelhouse','Portholes'][i],art:['≈','▣','▤','◉'][i],active:d.cabin===i,act:()=>{d.cabin=i;save();renderDockBuilder()}}));if(dockPart==='flag')return [0,1,2,3].map(i=>({name:['None','Red','Pirate','Blue'][i],art:['—','⚑','☠','⚑'][i],active:d.flag===i,act:()=>{d.flag=i;save();renderDockBuilder()}}));if(dockPart==='paint')return paints.map((c,i)=>({name:'Hull '+(i+1),art:`<span style="width:34px;height:34px;border-radius:50%;background:${c};display:block"></span>`,active:state.boat.paint===i,act:()=>{state.boat.paint=i;save();renderDockBuilder()}})).concat(sailColors.map((c,i)=>({name:'Sail '+(i+1),art:`<span style="width:34px;height:34px;border-radius:8px;background:${c};display:block"></span>`,active:d.sailColor===i,act:()=>{d.sailColor=i;save();renderDockBuilder()}}))).concat(trimColors.map((c,i)=>({name:'Trim '+(i+1),art:`<span style="width:34px;height:12px;border-radius:8px;background:${c};display:block"></span>`,active:d.trim===i,act:()=>{d.trim=i;save();renderDockBuilder()}})));let lvl=Math.floor(1200*Math.pow(1.75,state.boat.level-1)),eng=500*state.boat.engine,sto=450*state.boat.storage;return [{name:'Boat Lv '+state.boat.level,art:'⬆',note:fmt(lvl)+'G',act:()=>{if(state.gold<lvl)return toast('Need '+fmt(lvl)+' gold');state.gold-=lvl;state.boat.level++;save();renderAll()}},{name:'Engine '+state.boat.engine,art:'⚙',note:fmt(eng)+'G',act:()=>{if(state.gold<eng)return toast('Need '+fmt(eng)+' gold');state.gold-=eng;state.boat.engine++;save();renderAll()}},{name:'Storage '+state.boat.storage,art:'▣',note:fmt(sto)+'G',act:()=>{if(state.gold<sto)return toast('Need '+fmt(sto)+' gold');state.gold-=sto;state.boat.storage++;save();renderAll()}}]}
function rodPartOptions(){let d=state.dockBuilder.rodDesign;if(dockPart==='blank')return [0,1,2,3].map(i=>({name:['Cedar','Sport','Graphite','Tidal'][i],art:'╱',active:d.blank===i,act:()=>{d.blank=i;save();renderDockBuilder()}}));if(dockPart==='grip')return [0,1,2,3].map(i=>({name:['Cork','Rubber','Leather','Seafoam'][i],art:'▰',active:d.grip===i,act:()=>{d.grip=i;save();renderDockBuilder()}}));if(dockPart==='reel')return [0,1,2,3].map(i=>({name:['Silver','Gold','Black','Blue'][i],art:'⊙',active:d.reel===i,act:()=>{d.reel=i;save();renderDockBuilder()}}));if(dockPart==='guides')return [0,1,2,3].map(i=>({name:(i+4)+' Guides',art:'○○',active:d.guides===i,act:()=>{d.guides=i;save();renderDockBuilder()}}));if(dockPart==='accent')return rodAccent.map((c,i)=>({name:'Accent '+(i+1),art:`<span style="width:34px;height:34px;border-radius:50%;background:${c};display:block"></span>`,active:d.accent===i,act:()=>{d.accent=i;save();renderDockBuilder()}}));let ids=[['rod','Rod'],['line','Line'],['reel','Reel'],['sonar','Sonar']];return ids.map(([id,name])=>{let g=state.equipment[id],cost=Math.floor((160+g.level*140)*Math.pow(1.38,g.level-1));return{name:name+' '+g.level,art:gearIcon(id),note:fmt(cost)+'G',act:()=>{if(state.gold<cost)return toast('Need '+fmt(cost)+' gold');state.gold-=cost;g.level++;save();renderAll()}}})}
function sellValueForDecor(id){let d=studioDecorDefs[id]||{cat:'treasure'};return d.cat==='ruins'?220:d.cat==='treasure'?160:90}
function marketOptions(){let arr=[];if(dockPart==='materials'||dockPart==='all'){[['wood','Wood',35,'🪵'],['shells','Shells',22,'🐚'],['coral','Coral',60,'🪸']].forEach(([key,name,val,art])=>{let n=state[key]||0;if(n)arr.push({name,art,note:n+' owned · '+val+'G',sell:true,act:()=>{if(!state[key])return;state[key]--;state.gold+=val;save();renderAll()},all:()=>{let qty=state[key]||0;state[key]=0;state.gold+=qty*val;save();renderAll()}})})}if(dockPart==='decor'||dockPart==='all')Object.keys(studioDecorDefs).forEach(id=>{let n=decorAvailable(id);if(n){let val=sellValueForDecor(id);arr.push({name:studioDecorDefs[id].name,art:studioDecorDefs[id].art,note:n+' unused · '+val+'G',sell:true,act:()=>{if(decorAvailable(id)<=0)return;state.aqua.decorInventory[id]--;state.gold+=val;save();renderAll()},all:()=>{let qty=decorAvailable(id);state.aqua.decorInventory[id]-=qty;state.gold+=qty*val;save();renderAll()}})}});if(dockPart==='lures'||dockPart==='all')Object.entries(state.lures).forEach(([id,n])=>{if(n>0&&lureDefs[id]){let val=Math.max(8,Math.round(lureDefs[id].cost*.35));arr.push({name:lureDefs[id].name,art:lureDefs[id].icon,note:n+' owned · '+val+'G',sell:true,act:()=>{if(!state.lures[id])return;state.lures[id]--;state.gold+=val;save();renderAll()},all:()=>{let q=state.lures[id]||0;state.lures[id]=0;state.gold+=q*val;save();renderAll()}})}});if(dockPart==='fish'){arr=state.aquarium.map(x=>{let f=allDefs()[x.id],val=Math.round(f.value*(x.gene?.value||1));return{name:instanceName(x),art:fishSvg(x.id,x.gene),note:val+'G',sell:true,act:()=>{let i=state.aquarium.findIndex(q=>q.uid===x.uid);if(i<0)return;state.aquarium.splice(i,1);state.gold+=val;save();renderAll()}}})}if(!arr.length)arr.push({name:dockPart==='help'?'Market values':'Nothing here',art:dockPart==='help'?'💰':'📦',note:dockPart==='help'?'Treasure and rare decor sell for more.':'Collect more items first.',disabled:true});return arr}
function renderOptionGrid(items){
 let tray=$('#dockTray'),pager=$('#dockPager');
 if(!tray||!pager)return;
 tray.innerHTML='';pager.innerHTML='';
 const perPage=2,pages=Math.max(1,Math.ceil(items.length/perPage));
 dockTrayPage=clamp(dockTrayPage,0,pages-1);
 items.slice(dockTrayPage*perPage,dockTrayPage*perPage+perPage).forEach(o=>{
   let c=document.createElement('div');
   c.className='builder-option'+(o.active?' active':'');
   c.innerHTML=`<div class="art">${o.art}</div><b>${o.name}</b><small>${o.note||''}</small><div style="width:100%;display:grid;grid-template-columns:${o.sell&&o.all?'1fr 1fr':'1fr'};gap:4px"><button type="button" ${o.disabled?'disabled':''}>${o.sell?'SELL 1':o.active?'ACTIVE':'SELECT'}</button>${o.sell&&o.all?'<button class="sellbtn" type="button">ALL</button>':''}</div>`;
   let bs=c.querySelectorAll('button');
   bs[0].onclick=()=>o.act?.();
   if(bs[1])bs[1].onclick=()=>o.all?.();
   tray.appendChild(c);
 });
 if(pages>1){
   let a=document.createElement('button'),b=document.createElement('button'),s=document.createElement('span');
   a.textContent='‹';b.textContent='›';s.textContent=(dockTrayPage+1)+' / '+pages;
   a.disabled=dockTrayPage===0;b.disabled=dockTrayPage===pages-1;
   a.onclick=()=>{dockTrayPage--;renderDockBuilder()};b.onclick=()=>{dockTrayPage++;renderDockBuilder()};
   pager.append(a,s,b);
 }
}
function renderDockBuilder(){ensureDockBuilderState();$('#dockGold').textContent=fmt(state.gold);$('#woodTxt').textContent=fmt(state.wood);$('#shellTxt').textContent=fmt(state.shells);$('#coralTxt').textContent=fmt(state.coral);document.querySelectorAll('#dockModeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===dockMode));let visual=$('#dockBuildVisual');if(dockMode==='boat'){visual.innerHTML=boatBuilderSvg();$('#dockHint').textContent='Tap the boat itself to edit the selected part.'}else if(dockMode==='rod'){visual.innerHTML=rodBuilderSvg();$('#dockHint').textContent='Tap the rod itself to edit the selected part.'}else{visual.innerHTML='<div class="market-stage"><div class="market-crate">📦</div><div class="market-copy">Sell extra finds without leaving the dock.</div></div>';$('#dockHint').textContent='Choose a category below, then sell what you do not need.'}visual.onpointerdown=ev=>{let part=ev.target.closest&&ev.target.closest('[data-build-part]');if(!part)return;ev.preventDefault();ev.stopPropagation();selectDockPart(part.dataset.buildPart)};visual.onclick=ev=>{let part=ev.target.closest&&ev.target.closest('[data-build-part]');if(!part)return;selectDockPart(part.dataset.buildPart)};let parts=$('#dockPartBar');parts.innerHTML='';builderParts().forEach(([id,icon,label])=>{let b=document.createElement('button');b.classList.toggle('active',dockPart===id);b.innerHTML=`<span>${icon}</span>${label}`;b.onclick=()=>selectDockPart(id);parts.appendChild(b)});let opts=dockMode==='boat'?boatPartOptions():dockMode==='rod'?rodPartOptions():marketOptions();$('#dockTrayTitle').textContent=(builderParts().find(x=>x[0]===dockPart)||['','',dockMode==='sell'?'MARKET':'PART'])[2];renderOptionGrid(opts)}
