function updateWeather(force=false){let w=state.weather;if(force||now()>=w.until){let type=pick(currentRegion().weather);w.type=type;w.until=now()+rand(70000,150000);w.lightningAt=now()+rand(8000,20000);renderTop();updateSoundscape()}if(w.type==='storm'&&now()>w.lightningAt){screenShake=5;w.lightningAt=now()+rand(7000,16000);tone(75,.16,'sawtooth')}}
function weatherLabel(){return{clear:'CLEAR',mist:'MIST',rain:'RAIN',wind:'WIND',storm:'STORM'}[state.weather.type]||'CLEAR'}
function fishAI(q,dt){let f=allDefs()[q.id];if(!f||q.hooked)return;q.think-=dt;let c=oceanCondition();if(q.think<=0){q.think=rand(.7,2.2);if(q.state!=='flee'&&q.state!=='chase'&&q.state!=='feed'){q.vy=rand(-8,8);if(Math.random()<.16)q.vx*=-1}}if(f.temper==='school'&&q.state==='cruise'){let mates=fish.filter(p=>p!==q&&!p.hooked&&p.id===q.id&&p.school===q.school&&Math.hypot(p.x-q.x,p.y-q.y)<115);if(mates.length){let ax=0,ay=0,avx=0;for(const p of mates){ax+=p.x;ay+=p.y;avx+=p.vx}ax/=mates.length;ay/=mates.length;avx/=mates.length;q.vx+=clamp((ax-q.x)*.006+(avx-q.vx)*.025,-5,5);q.vy+=clamp((ay-q.y)*.012,-3,3)}}let ev=activeOceanEvent();if(ev&&oceanRuntime.event==='frenzy'){let fy=depthToY(oceanRuntime.eventDepth),fd=Math.hypot(oceanRuntime.eventX-q.x,fy-q.y);if(fd<210&&(f.temper==='school'||f.temper==='hunter')){q.state='feed';q.vx+=clamp((oceanRuntime.eventX-q.x)*.045,-7,7);q.vy+=clamp((fy-q.y)*.04,-5,5)}}else if(q.state==='feed')q.state='cruise';let dx=hook.x-q.x,dy=hook.y-q.y,dist=Math.hypot(dx,dy),l=lureDefs[hook.lure]||lureDefs.none,b=castBaitDef(),h=castHookDef(),aff=lureAffinity(l,f)*baitAffinity(b,f)*hookAffinity(h,f,castHookId())*lureActionMultiplier(l);if(hook.mode==='sinking'&&dist<175){if(f.temper==='shy'&&dist<68&&aff<1.32){q.state='flee';q.vx=-Math.sign(dx||1)*f.speed*1.7;q.vy=-Math.sign(dy||1)*12}else if(aff>1.03||f.temper==='curious'||f.temper==='hunter'){q.state='chase';let att=l.attract*Math.sqrt(Math.max(.55,aff))*(state.weather.type==='rain'?1.1:1);q.vx=clamp(dx*1.05,-f.speed*att,f.speed*att);q.vy=clamp(dy*.78,-20,20)}}if(q.state==='flee'&&dist>160)q.state='cruise';if(q.state==='chase'&&hook.mode!=='sinking')q.state='cruise';if(f.temper==='hunter'&&hook.mode!=='sinking'&&Math.random()<.004){let prey=fish.find(p=>p!==q&&!p.hooked&&allDefs()[p.id].tier<f.tier&&Math.hypot(p.x-q.x,p.y-q.y)<135);if(prey){q.vx=clamp((prey.x-q.x)*1.3,-f.speed*1.55,f.speed*1.55);q.vy=clamp((prey.y-q.y)*.8,-20,20)}}let rest=(c.night&&fishDepthProfile(f)==='shallow'&&!/moon|night|ghost|star|lantern/i.test(q.id+f.name))?.72:1;q.vx=clamp(q.vx,-f.speed*1.85,f.speed*1.85);q.vy=clamp(q.vy,-22,22);q.x+=(q.vx*rest+c.current*.16)*dt;q.y+=q.vy*dt;q.y=clamp(q.y,waterY+22,H-34);if(q.x<-70)q.x=W+60;if(q.x>W+70)q.x=-60;if(hook.mode==='sinking'&&dist<27){let eligible=f.tier<=tackleAccessTier()||q.id===state.hunts.active,legendaryOK=!(q.id in legendaryDefs)||castHookId()==='large'||castHookId()==='heavy',event=activeOceanEvent(),chance=.0185*l.attract*b.bite*h.bite*aff*q.appetite*fishActivityMultiplier(q.id,f)*(event?event.bite:1)*(state.weather.type==='rain'?1.26:1)*(state.weather.type==='storm'?1.08:1)*captainBiteBonus()*rodBuildBonuses().bite*boatFishingBonuses().bite;if(eligible&&legendaryOK&&Math.random()<chance)hookFish(q)}}
function hookFish(q){let f=allDefs()[q.id];haptic('bite');q.hooked=true;hook.mode='hooked';hook.fish=q;hook.stamina=hook.maxStamina=(45+f.tier*34+f.size*.8)*(q.id in legendaryDefs?1.7:1);hook.tension=35;hook.fightTimer=0;hook.burstTimer=rand(.7,1.5);oceanRuntime.cinema=q.id in legendaryDefs?.07:f.tier>=4?.035:.018;$('#oceanHud')?.classList.add('fighting');$('#tension').classList.add('show');$('#castBtn').textContent='REEL';$('#seaHint').textContent=q.id in legendaryDefs?'Legendary strike. Bring it to the surface without snapping the line.':'Bring it to the surface. Release during dangerous surges.';tone(680,.09);setTimeout(()=>tone(q.id in legendaryDefs?1040:880,.08),70)}
function fightProfile(f,dt){hook.burstTimer-=dt;hook.burstText='';let pull=.5+f.tier*.11,px=0,py=0;if(hook.burstTimer<=0){hook.burstTimer=rand(.8,1.8);let dir=Math.random()<.5?-1:1;switch(f.fight){case'sprinter':px=dir*1.5;pull*=1.8;hook.burstText='SPRINT!';break;case'diver':py=1.5;pull*=1.75;hook.burstText='DIVING!';break;case'thrash':px=dir*1.1;py=rand(-.5,.8);pull*=1.55;hook.burstText='THRASHING!';break;case'trickster':px=dir*1.25;py=rand(-1,1);pull*=1.5;hook.burstText='DIRECTION CHANGE!';break;case'tank':py=.7;pull*=1.45;hook.burstText='HEAVY PULL!';break;case'surger':px=dir*.9;py=.6;pull*=2;hook.burstText='SURGE!';break;default:pull*=1.25;hook.burstText='PULLING!'}hook.pullX=px;hook.pullY=py;screenShake=f.tier>=4?4:2}hook.pullX*=Math.pow(.25,dt);hook.pullY*=Math.pow(.25,dt);return pull*(1+Math.abs(hook.pullX)+Math.abs(hook.pullY))*castHookDef().fight}
function updateHook(dt){if(powering){hook.power+=powerDir*dt*.9;if(hook.power>=1){hook.power=1;powerDir=-1}if(hook.power<=.12){hook.power=.12;powerDir=1}$('#powerFill').style.width=(hook.power*100)+'%'}let current=oceanRuntime.current||0;if(hook.mode==='casting'){hook.vy+=180*dt;hook.x=clamp(hook.x+hook.vx*dt,20,W-20);hook.y+=hook.vy*dt;if(hook.x>=W-20||hook.x<=20)hook.vx=0;if(hook.y>=waterY){hook.y=waterY+2;hook.mode='sinking';hook.vy=52;hook.targetX=hook.x;splashSound();haptic('select')}}else if(hook.mode==='sinking'){let action=hook.actionEnergy||0,jig=hook.jigImpulse||0;hook.x+=clamp(hook.targetX-hook.x,-60*dt,60*dt)+current*dt*(.6+state.region*.04);hook.y+=hook.vy*dt*(state.weather.type==='storm'?1.07:1)+jig*24*dt;hook.jigImpulse=(hook.jigImpulse||0)*Math.pow(.06,dt);hook.x=clamp(hook.x,22,W-22);if(yToDepth(hook.y)>=Math.min(currentRegion().depth-12,castLineDepth())){hook.mode='returning';hook.carry=null}for(let i=specials.length-1;i>=0;i--){let s=specials[i];if(Math.hypot(hook.x-s.x,hook.y-s.y)<24){hook.carry=s;specials.splice(i,1);hook.mode='returning';tone(760,.08);break}}}else if(hook.mode==='hooked'&&hook.fish){let q=hook.fish,f=allDefs()[q.id],pull=fightProfile(f,dt),storm=state.weather.type==='storm'?1.18:1;if(hook.reeling){hook.tension+=dt*(25*pull*storm-10*reelPower())/(1+Math.max(0,gearStat('line')-1)*.045);hook.stamina-=dt*(14*reelPower())*(hook.tension<82?1:.45);hook.y-=dt*(20+18*reelPower())}else{hook.tension-=dt*(23/reelPower());hook.y+=dt*7*pull}hook.x+=(hook.pullX*18+current*.18)*dt;hook.y+=hook.pullY*15*dt;let landingPull=clamp(1-(hook.y-waterY)/150,0,1);if(hook.reeling&&landingPull>0){let tip=rodTip();hook.x+=(tip.x-hook.x)*dt*(1.6+landingPull*4.8)}hook.x=clamp(hook.x,28,W-28);hook.y=clamp(hook.y,waterY-4,H-35);q.x=hook.x+18*Math.sign(hook.pullX||q.vx||1);q.y=hook.y+8;hook.tension=clamp(hook.tension,0,120);if(hook.tension>=100){snapLine();return}if(hook.stamina<=0){hook.stamina=0;hook.tension=Math.min(hook.tension,72);hook.y-=dt*(42+23*reelPower())}if(hook.y<=waterY+7){landFish(q);return}$('#needle').style.left=clamp(hook.tension,0,100)+'%';$('#staminaFill').style.width=clamp(hook.stamina/hook.maxStamina*100,0,100)+'%';$('#tensionText').textContent=hook.tension<56?'SAFE':hook.tension<78?'CAUTION':'DANGER';$('#fightTag').textContent=hook.burstText||f.fight.toUpperCase()+' FIGHTER';$('#fightName').textContent=f.name.toUpperCase()}else if(hook.mode==='returning'){let tip=rodTip(),dx=tip.x-hook.x,dy=tip.y-hook.y,d=Math.hypot(dx,dy)||1;hook.x+=dx/d*180*dt;hook.y+=dy/d*180*dt;if(d<16){if(hook.carry)landSpecial(hook.carry);resetHook()}}}
function castStart(){if(hook.mode!=='idle')return;haptic('cast');ensureAudio();if(!hookUnlocked(state.selectedHook)){state.selectedHook='standard';toast('That hook needs a stronger rod. Standard Hook equipped.')}let lure=state.selectedLure;if(lure!=='none'&&(state.lures[lure]||0)<=0){state.selectedLure='none';renderLures();toast('That lure is not in your tackle box. Using no lure.')}hook.power=.15;powerDir=1;powering=true;$('#castBtn').textContent='RELEASE';$('#seaHint').textContent='Drag left or right to aim, then release.';tone(360,.035,'sine',.025)}
function castRelease(){if(!powering)return;powering=false;let bait=state.selectedBait||0;if(bait&&(state.bait[bait]||0)<=0){state.selectedBait=0;bait=0;toast('That bait is gone. Casting without bait.')}else if(bait){state.bait[bait]--;if(state.bait[bait]<=0)state.selectedBait=0}let lure=state.selectedLure;hook.lure=lure;hook.bait=bait;hook.hookType=state.selectedHook;hook.action='STILL';hook.actionEnergy=0;hook.jigImpulse=0;hook.mode='casting';let tip=rodTip(),targetX=clamp(Number.isFinite(castAimX)?castAimX:W*.72,24,W-24),vy=-95-hook.power*90,g=180,dy=waterY-tip.y,disc=Math.max(1,vy*vy+2*g*dy),flight=Math.max(.45,(-vy+Math.sqrt(disc))/g);hook.x=tip.x;hook.y=tip.y;hook.vx=clamp((targetX-tip.x)/flight,-185,185);hook.vy=vy;$('#castBtn').textContent='RETRIEVE';$('#seaHint').textContent='Drag the water to work the lure. Tap RETRIEVE when ready.';$('#powerFill').style.width='0%';save();renderBait();renderLures();renderStatus();tone(420,.05,'sine',.04);haptic('cast')}
function reelPress(v){if(hook.mode==='hooked'){hook.reeling=v;$('#castBtn').classList.toggle('warn',v&&hook.tension>75)}else if(hook.mode==='sinking'&&v){hook.mode='returning'}}
function snapLine(){haptic('error');let q=hook.fish;if(q){q.hooked=false;q.state='flee';q.vx*=2}let lost='';if(hook.lure&&hook.lure!=='none'&&Math.random()<.18&&(state.lures[hook.lure]||0)>0){state.lures[hook.lure]--;lost=' Lost one '+lureDefs[hook.lure].name+'.';if(state.lures[hook.lure]<=0)state.selectedLure='none';save()}tone(120,.16,'square');toast('Line snapped! Release the reel during surges.'+lost);resetHook();renderAll()}
function landFish(q){haptic(q.id in legendaryDefs?'treasure':'catch');let f=allDefs()[q.id],hd=castHookDef(),cycle=oceanCycle(),ev=activeOceanEvent(),weight=(f.size*.08*rand(.78,1.32))*hd.sizeBias*(q.id in legendaryDefs?1.4:1),moment=(cycle.twilight?1.05:1)*(ev?1.03:1),val=Math.round(f.value*(.75+weight/(f.size*.1))*.7*(1+(hd.rare-1)*.16)*moment);catchPending={id:q.id,weight,val,gene:{value:1,size:1,hue:0},moment:cycle.label};fish=fish.filter(x=>x!==q);state.catches++;state.bestValue=Math.max(state.bestValue,val);state.bestWeight=Math.max(state.bestWeight,weight);state.net.push({id:q.id,weight:+weight.toFixed(2),val,time:now(),moment:cycle.label});state.net=state.net.slice(-50);state.book[q.id]=(state.book[q.id]||0)+1;if(q.id in legendaryDefs){state.hunts.completed[q.id]=(state.hunts.completed[q.id]||0)+1;state.hunts.active=null;state.pearls+=2;state.coral+=3;tone(980,.15);setTimeout(()=>tone(1180,.14),120)}showCatch(catchPending);save();resetHook();renderAll()}

function rodTip(){let t=hook.mode==='hooked'?clamp(hook.tension/100,0,1):0,baseX=113,baseY=waterY-24;return{x:baseX+48+t*15,y:baseY-45+t*37}}
function drawSky(){let r=currentRegion(),c=oceanCycle(),grad=ctx.createLinearGradient(0,0,0,waterY),top=r.sky[0],bottom=r.sky[1];if(c.night){top='#071322';bottom='#182d48'}else if(c.phase>=.73&&c.phase<.82){top='#5c4b72';bottom='#d98269'}else if(c.phase>=.16&&c.phase<.25){top='#594d75';bottom='#e9a26c'}else if(c.phase>=.62&&c.phase<.73){top=r.sky[0];bottom='#e49a69'}grad.addColorStop(0,top);grad.addColorStop(1,bottom);ctx.fillStyle=grad;ctx.fillRect(0,0,W,waterY);if(c.night){ctx.fillStyle='rgba(230,242,255,.72)';for(let i=0;i<34;i++){let x=(i*83%W),y=10+(i*37%(waterY-34)),a=.35+((i*17)%55)/100;ctx.globalAlpha=a*(.78+.22*Math.sin(animT*.55+i));ctx.fillRect(x,y,i%5===0?1.6:1,i%5===0?1.6:1)}ctx.globalAlpha=1}let celestial=c.phase<.5?c.phase/.5:(c.phase-.5)/.5,cx=30+celestial*(W-60),arc=Math.sin(celestial*Math.PI),cy=waterY-22-arc*96;if(c.night){ctx.fillStyle='rgba(224,236,244,.82)';ctx.beginPath();ctx.arc(cx,cy,12,0,TAU);ctx.fill();ctx.fillStyle=top;ctx.beginPath();ctx.arc(cx+5,cy-3,10,0,TAU);ctx.fill()}else{ctx.fillStyle=c.twilight?'rgba(255,212,151,.88)':'rgba(255,231,180,.78)';ctx.beginPath();ctx.arc(cx,cy,17,0,TAU);ctx.fill()}let wt=state.weather.type;ctx.globalAlpha=wt==='storm'?.32:wt==='rain'?.22:.13;ctx.fillStyle='#fff';for(let i=0;i<5;i++){let x=(i*110+animT*(wt==='wind'?18:8))%560-60,y=22+i*13;ctx.beginPath();ctx.ellipse(x,y,58,13,0,0,TAU);ctx.fill()}ctx.globalAlpha=1;if(wt==='storm'){ctx.fillStyle='rgba(10,19,32,.38)';ctx.fillRect(0,0,W,waterY)}if(wt==='mist'){ctx.fillStyle='rgba(220,235,239,.18)';ctx.fillRect(0,70,W,90)}}
function drawHorizon(){let c=oceanCycle();ctx.fillStyle=c.night?'rgba(15,28,43,.76)':'rgba(40,60,72,.46)';ctx.beginPath();ctx.moveTo(0,waterY);for(let x=0;x<=W;x+=45)ctx.lineTo(x,waterY-18-Math.sin(x*.035)*15);ctx.lineTo(W,waterY);ctx.closePath();ctx.fill()}
function drawWater(){let r=currentRegion(),c=oceanCondition(),g=ctx.createLinearGradient(0,waterY,0,H),night=c.night;g.addColorStop(0,night?'#173d57':r.water[0]);g.addColorStop(1,night?'#06192d':r.water[1]);ctx.fillStyle=g;ctx.fillRect(0,waterY,W,H-waterY);let wave=state.weather.type==='storm'?6:state.weather.type==='wind'?4.5:3,tideLift=c.tide*2;for(let i=0;i<11;i++){ctx.strokeStyle=`rgba(190,235,242,${night?.045:.07+i*.004})`;ctx.lineWidth=1;ctx.beginPath();let y=waterY+7+i*37+tideLift;for(let x=-20;x<=W+20;x+=18)ctx.lineTo(x,y+Math.sin(x*.05+animT*(state.weather.type==='storm'?2.1:1.3)+i)*wave);ctx.stroke()}let cur=c.current;ctx.strokeStyle='rgba(190,235,242,.045)';ctx.lineWidth=1;for(let i=0;i<8;i++){let y=waterY+45+i*50,x=((i*71+animT*cur*8)%(W+120)+W+120)%(W+120)-60;ctx.beginPath();ctx.moveTo(x-22,y);ctx.quadraticCurveTo(x,y+Math.sin(animT+i)*4,x+22,y);ctx.stroke()}if(currentRegion().ruin)drawRuins();drawHabitat()}

function drawHabitat(){let t=currentPrefs().motion?animT:0,region=state.region;ctx.save();let base=H-18;if(region===0||region===1||region===3){for(let i=0;i<12;i++){let x=18+i*39+(region*11%17),h=28+(i%5)*12;ctx.strokeStyle=region===3?'rgba(62,111,78,.35)':'rgba(50,96,74,.28)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,base);ctx.quadraticCurveTo(x+Math.sin(t*.8+i)*9,base-h*.55,x+Math.sin(t*.55+i)*5,base-h);ctx.stroke()}}if(region>=4){ctx.fillStyle='rgba(185,214,225,.035)';for(let i=0;i<18;i++){let x=(i*97+t*(4+i%3))%W,y=waterY+90+(i*53%(H-waterY-115));ctx.beginPath();ctx.arc(x,y,1+(i%3),0,TAU);ctx.fill()}}ctx.restore()}
function drawOceanLife(){let c=oceanCycle(),ev=activeOceanEvent();ctx.save();if(ev&&oceanRuntime.event==='frenzy'){let x=oceanRuntime.eventX;ctx.strokeStyle='rgba(255,255,255,.62)';ctx.lineWidth=1.4;for(let i=0;i<5;i++){let bx=x-70+i*32+Math.sin(animT*1.3+i)*13,by=45+(i%2)*17+Math.sin(animT*.8+i)*6;ctx.beginPath();ctx.moveTo(bx-7,by);ctx.quadraticCurveTo(bx-3,by-5,bx,by);ctx.quadraticCurveTo(bx+3,by-5,bx+7,by);ctx.stroke()}for(let i=0;i<5;i++){let sx=x-55+i*26,sy=waterY+2;ctx.globalAlpha=.3+.2*Math.sin(animT*4+i);ctx.beginPath();ctx.arc(sx,sy,5+(i%3)*3,Math.PI,TAU);ctx.stroke()}ctx.globalAlpha=1}if(oceanRuntime.ambientKind==='dolphin'&&!c.night){let p=1-(oceanRuntime.ambientUntil-performance.now())/6000,x=(p*W*1.35)-W*.15,y=waterY-4-Math.sin(clamp(p,0,1)*Math.PI)*26;ctx.strokeStyle='rgba(38,66,81,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,16,.2,Math.PI-.2);ctx.stroke();ctx.beginPath();ctx.moveTo(x+2,y-13);ctx.lineTo(x+9,y-24);ctx.lineTo(x+11,y-9);ctx.stroke()}ctx.restore()}
function drawNightBloom(){let c=oceanCycle();if(!c.night&&oceanRuntime.event!=='bloom')return;ctx.save();for(let i=0;i<42;i++){let x=(i*89+animT*(2+i%4))%W,y=waterY+28+(i*47%(H-waterY-52)),deep=(y-waterY)/(H-waterY),pulse=.25+.28*Math.sin(animT*1.4+i);ctx.globalAlpha=Math.max(.05,pulse)*(.35+deep*.65);ctx.fillStyle=i%3===0?'#83f5e4':'#8cc9ff';ctx.beginPath();ctx.arc(x,y,1+(i%4===0?1.2:0),0,TAU);ctx.fill()}ctx.restore()}

function drawRuins(){ctx.save();ctx.globalAlpha=.18+(sonar?.1:0);ctx.fillStyle='#b5a786';let base=H-28;ctx.fillRect(260,base-95,12,95);ctx.fillRect(330,base-78,14,78);ctx.fillRect(247,base-100,40,8);ctx.beginPath();ctx.arc(320,base-45,35,Math.PI,0);ctx.lineTo(355,base);ctx.lineTo(285,base);ctx.closePath();ctx.fill();ctx.restore()}
function drawBoat(){let color=paints[state.boat.paint]||paints[0],h=state.boat.hull,d=state.dockBuilder?.boatDesign||{sail:0,cabin:0,flag:0,sailColor:0,trim:0},sail=sailColors?.[d.sailColor%sailColors.length]||'#efe5cf',trim=trimColors?.[d.trim%trimColors.length]||'#d7c8a8';ctx.save();ctx.translate(74,waterY-39);ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(58,48,58,8,0,0,TAU);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(h==='crown'? -8:0,29);ctx.lineTo(99+(h==='trawler'||h==='crown'?13:0),29);ctx.lineTo(82,48);ctx.lineTo(18,48);ctx.closePath();ctx.fill();ctx.strokeStyle=trim;ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle=trim;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(22,42);ctx.lineTo(82,42);ctx.stroke();ctx.strokeStyle='#80633e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(45,29);ctx.lineTo(45,-8);ctx.stroke();ctx.fillStyle=sail;if(d.sail%4===1){ctx.beginPath();ctx.moveTo(48,-5);ctx.lineTo(86,5);ctx.lineTo(80,24);ctx.lineTo(48,17);ctx.closePath();ctx.fill()}else if(d.sail%4===2){ctx.beginPath();ctx.moveTo(48,-5);ctx.lineTo(85,17);ctx.lineTo(48,17);ctx.closePath();ctx.fill();ctx.globalAlpha=.9;ctx.beginPath();ctx.moveTo(42,0);ctx.lineTo(22,17);ctx.lineTo(42,17);ctx.closePath();ctx.fill();ctx.globalAlpha=1}else if(d.sail%4===3){ctx.beginPath();ctx.moveTo(48,-5);ctx.lineTo(83,16);ctx.lineTo(48,17);ctx.closePath();ctx.fill();ctx.fillStyle=trim;ctx.beginPath();ctx.moveTo(42,0);ctx.lineTo(24,17);ctx.lineTo(42,17);ctx.closePath();ctx.fill()}else{ctx.beginPath();ctx.moveTo(48,-5);ctx.lineTo(83,17);ctx.lineTo(48,17);ctx.closePath();ctx.fill()}if(d.cabin%4){let x=58,y=d.cabin%4===2?9:12,w=d.cabin%4===2?36:30,hh=d.cabin%4===2?20:17;ctx.fillStyle=d.cabin%4===3?'#c8b58d':'#dce7e6';ctx.fillRect(x,y,w,hh);ctx.fillStyle='#54778b';if(d.cabin%4===3){ctx.beginPath();ctx.arc(x+9,y+9,4,0,TAU);ctx.arc(x+21,y+9,4,0,TAU);ctx.fill()}else{ctx.fillRect(x+5,y+5,7,6);ctx.fillRect(x+16,y+5,7,6)}if(d.cabin%4===2){ctx.fillStyle=trim;ctx.beginPath();ctx.moveTo(x-3,y);ctx.lineTo(x+w+3,y);ctx.lineTo(x+w-2,y-5);ctx.lineTo(x+3,y-5);ctx.closePath();ctx.fill()}}if(d.flag%4){ctx.strokeStyle='#80633e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(45,-8);ctx.lineTo(45,-20);ctx.stroke();ctx.fillStyle=d.flag%4===1?'#b54d45':d.flag%4===2?'#1d2429':'#466e91';ctx.beginPath();ctx.moveTo(46,-20);ctx.lineTo(66,-15);ctx.lineTo(46,-10);ctx.closePath();ctx.fill();if(d.flag%4===2){ctx.fillStyle='#eee';ctx.font='8px system-ui';ctx.fillText('☠',50,-12)}}ctx.restore();}
function drawFish(q){let f=allDefs()[q.id],scale=(f.size/35)*(q.id in legendaryDefs?1.12:1),flip=q.vx<0?-1:1,c=oceanCycle(),deep=fishDepthProfile(f)==='deep',glow=c.night&&(deep||/moon|night|ghost|star|lantern|aurora/i.test(q.id+f.name));ctx.save();ctx.translate(q.x,q.y);ctx.rotate(clamp(q.vy/95,-.16,.16));if(glow){ctx.shadowBlur=14;ctx.shadowColor=f.accent||'#8fe7ff'}ctx.scale(flip*scale,scale);if(q.sonarUntil>performance.now()||q.id===state.hunts.active){ctx.strokeStyle=q.id===state.hunts.active?'#ffd46c':'#86ecff';ctx.lineWidth=2/scale;ctx.beginPath();ctx.ellipse(0,0,31,15,0,0,TAU);ctx.stroke()}ctx.fillStyle=f.c;ctx.beginPath();ctx.ellipse(0,0,25,12,0,0,TAU);ctx.fill();ctx.fillStyle=f.accent;ctx.beginPath();ctx.moveTo(-22,0);ctx.lineTo(-39,-13);ctx.lineTo(-34,0);ctx.lineTo(-39,13);ctx.closePath();ctx.fill();if(f.fight==='diver'||q.id.includes('ray')){ctx.globalAlpha=.35;ctx.beginPath();ctx.ellipse(0,3,33,9,0,0,TAU);ctx.fill();ctx.globalAlpha=1}ctx.fillStyle='#111923';ctx.beginPath();ctx.arc(15,-3,2.5,0,TAU);ctx.fill();if(q.id.includes('marlin')||q.id==='swordfish'){ctx.fillStyle='#dde8ed';ctx.beginPath();ctx.moveTo(23,-1);ctx.lineTo(44,-5);ctx.lineTo(23,3);ctx.fill()}ctx.restore()}
function drawSpecial(s){ctx.save();ctx.translate(s.x,s.y+Math.sin(animT*2+s.bob)*3);if(s.type==='chest'){ctx.fillStyle='#9c7140';ctx.fillRect(-13,-9,26,18);ctx.fillStyle='#d6b05f';ctx.fillRect(-13,-2,26,4);ctx.fillRect(-2,-9,4,18)}else if(s.type==='bottle'){ctx.rotate(-.35+Math.sin(animT+s.bob)*.08);ctx.fillStyle='rgba(163,222,205,.72)';ctx.beginPath();ctx.roundRect(-6,-13,12,23,4);ctx.fill();ctx.fillStyle='#d7c29b';ctx.fillRect(-3,-16,6,5);ctx.fillStyle='#f0e2bd';ctx.fillRect(-3,-6,6,8)}else if(s.type==='debris'){ctx.rotate(Math.sin(animT*.7+s.bob)*.12);ctx.fillStyle='#775437';ctx.fillRect(-16,-4,32,8);ctx.fillStyle='#a37b51';ctx.fillRect(-12,-1,24,2)}else{ctx.fillStyle='#ddc67c';ctx.font='bold 25px system-ui';ctx.textAlign='center';ctx.fillText((relicDefs.find(r=>r.id===s.id)||{}).icon||'◈',0,8)}ctx.restore()}
function drawCastAim(){if(hook.mode!=='idle'&& !powering)return;let tip=rodTip(),tx=clamp(castAimX,24,W-24),ty=waterY+3,dir=tx<tip.x?-1:1,dist=Math.abs(tx-tip.x),peak=Math.max(24,Math.min(78,30+dist*.22));ctx.save();ctx.strokeStyle=powering?'rgba(255,255,255,.66)':'rgba(255,255,255,.30)';ctx.lineWidth=1.25;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(tip.x,tip.y);ctx.quadraticCurveTo((tip.x+tx)/2,Math.min(tip.y,ty)-peak,tx,ty);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=powering?'rgba(255,255,255,.9)':'rgba(255,255,255,.55)';ctx.beginPath();ctx.arc(tx,ty,3.2,0,TAU);ctx.fill();ctx.font='600 7px system-ui';ctx.textAlign='center';ctx.fillText(dir<0?'AIM LEFT':'AIM RIGHT',tx,ty+13);ctx.restore()}
function drawAmbientFish(){let c=oceanCycle(),count=6;ctx.save();for(let i=0;i<count;i++){let lane=i%3,baseY=waterY+95+lane*115,x=((i*103+animT*(5+i%3)*((i%2)?1:-1))%(W+100)+W+100)%(W+100)-50,flip=i%2?-1:1,s=.42+(i%3)*.08;ctx.save();ctx.translate(x,baseY+Math.sin(animT*.45+i)*9);ctx.scale(flip*s,s);ctx.globalAlpha=c.night?.10:.085;ctx.fillStyle=c.night?'#8ec4d8':'#16384c';ctx.beginPath();ctx.ellipse(0,0,24,9,0,0,TAU);ctx.fill();ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(-34,-9);ctx.lineTo(-30,0);ctx.lineTo(-34,9);ctx.closePath();ctx.fill();ctx.restore()}ctx.restore()}
function drawHook(){if(hook.mode==='idle')return;let id=castHookId(),scale={fine:.82,standard:1,large:1.18,heavy:1.34}[id]||1;ctx.save();ctx.translate(hook.x,hook.y);ctx.rotate(Math.sin(animT*5)*(hook.actionEnergy||0)*.16);ctx.scale(scale,scale);ctx.strokeStyle=id==='heavy'?'#d6c39a':'#e6edf0';ctx.lineWidth=id==='fine'?1.5:2;ctx.beginPath();ctx.arc(0,0,6,.2,Math.PI*1.55);ctx.stroke();let ld=lureDefs[hook.lure]||lureDefs.none;ctx.fillStyle=ld.tag==='flash'?'#ffd665':ld.tag==='deep'?'#8df1dd':ld.tag==='treasure'?'#d7b869':ld.tag==='predator'?'#c5d6df':'#c9b073';if(ld.tag==='deep'&&oceanCycle().night){ctx.shadowBlur=10;ctx.shadowColor='#8df1dd'}ctx.beginPath();ctx.arc(-1,-6,3+(hook.actionEnergy||0)*1.5,0,TAU);ctx.fill();ctx.restore()}
function drawWeather(){let wt=state.weather.type;if(wt==='rain'||wt==='storm'){ctx.strokeStyle=wt==='storm'?'rgba(210,230,240,.34)':'rgba(220,240,245,.22)';ctx.lineWidth=1;for(let i=0;i<45;i++){let x=(i*37+animT*150)%520-35,y=(i*71+animT*260)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y+17);ctx.stroke()}}if(wt==='storm'&&now()+120>state.weather.lightningAt){ctx.fillStyle='rgba(255,255,255,.3)';ctx.fillRect(0,0,W,H)}}
function drawAtmosphere(){let t=currentPrefs().motion?animT:0,c=oceanCycle();ctx.save();for(let i=0;i<26;i++){let x=(i*91+t*(3+i%4))%(W+40)-20,y=waterY+28+(i*47%(H-waterY-55));ctx.globalAlpha=(c.night?.055:.035)+(i%4)*.011;ctx.fillStyle=c.night?'#a6e9ff':'#dff7ff';ctx.beginPath();ctx.arc(x,y,1+(i%3)*.45,0,TAU);ctx.fill()}if(state.weather.type==='clear'&&!c.night){let g=ctx.createLinearGradient(0,waterY,0,H);g.addColorStop(0,'rgba(255,255,255,.07)');g.addColorStop(.5,'rgba(255,255,255,0)');ctx.fillStyle=g;for(let i=0;i<4;i++){ctx.save();ctx.translate(70+i*105,waterY);ctx.rotate(-.09+Math.sin(t*.08+i)*.02);ctx.fillRect(0,0,26,H-waterY);ctx.restore()}}ctx.restore();drawNightBloom()}
function drawVignette(){let g=ctx.createRadialGradient(W*.5,H*.46,Math.min(W,H)*.25,W*.5,H*.5,Math.max(W,H)*.72);g.addColorStop(.58,'rgba(0,0,0,0)');g.addColorStop(1,'rgba(0,12,24,.2)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function renderScene(){ctx.save();let zoom=oceanRuntime.cinema||0;if(zoom){ctx.translate(W*.5,H*.5);ctx.scale(1+zoom,1+zoom);ctx.translate(-W*.5,-H*.5)}if(screenShake){ctx.translate(rand(-screenShake,screenShake),rand(-screenShake,screenShake));screenShake*=.83;if(screenShake<.2)screenShake=0}drawSky();drawHorizon();drawWater();drawAtmosphere();drawOceanLife();drawAmbientFish();specials.forEach(drawSpecial);fish.forEach(drawFish);drawCastAim();drawBoat();drawHook();drawWeather();drawVignette();ctx.restore()}
function update(dt){animT+=dt;updateWeather();updateOceanEvents(dt);rebalanceFishDensity(dt);spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=rand(.52,1.28);spawnFish(Math.random()<.055);maybeSpawnSpecial()}fish.forEach(q=>fishAI(q,dt));updateHook(dt);updateAquariumStudio(dt)}
function frame(ts){try{if(document.hidden){lastFrame=ts;return}let dt=Math.min(.035,(ts-lastFrame)/1000||.016);lastFrame=ts;update(dt);renderScene()}catch(error){console.error('[Tide & Tranquility] Animation recovered.',error);showSystemNotice?.('The scene recovered automatically.')}finally{requestAnimationFrame(frame)}}

function renderTop(){let r=currentRegion();$('#goldTxt').textContent=fmt(state.gold);$('#pearlTxt').textContent=fmt(state.pearls);$('#journalGold')&&($('#journalGold').textContent=fmt(state.gold));$('#regionKicker').textContent='REGION '+(state.region+1);$('#regionName').textContent=r.name;$('#regionDepth').textContent=`Reach ${Math.min(r.depth,lineDepth())}m · Rod Tier ${rodTier()} · ${rarity[state.equipment.rod.rarity].n}`;$('#weatherBadge').textContent=weatherLabel();$('#sonarBtn').classList.toggle('ready',now()>=state.sonarAt);$('#huntBtn').classList.toggle('ready',!!state.hunts.active)}
function renderBait(){let s=$('#baitSelect'),cur=String(state.selectedBait||0);s.innerHTML=Object.entries(baitDefs).map(([id,b])=>`<option value="${id}">${b.name}${+id?' · '+(state.bait[id]||0):''}</option>`).join('');s.value=cur;let b=activeBaitDef();$('#baitLoadoutName')&&($('#baitLoadoutName').textContent=b.name+(state.selectedBait?' ×'+(state.bait[state.selectedBait]||0):''))}
function renderLures(){let s=$('#lureSelect');s.innerHTML=Object.entries(lureDefs).map(([id,l])=>`<option value="${id}">${l.name}${id==='none'?'':' · '+(state.lures[id]||0)}</option>`).join('');if(!lureDefs[state.selectedLure])state.selectedLure='none';s.value=state.selectedLure;$('#lureLoadoutName')&&($('#lureLoadoutName').textContent=lureDefs[state.selectedLure].name);$('#hookLoadoutName')&&($('#hookLoadoutName').textContent=activeHookDef().name.replace(' Hook',''))}
function renderStatus(){let m=tackleMetrics(),hunt=state.hunts.active?` · Hunt: ${legendaryDefs[state.hunts.active].name}`:'',c=oceanCondition(),ev=activeOceanEvent(),r=$('#tackleReadout');if(r)r.innerHTML=`<span><small>TARGET</small><b>${m.target}</b></span><span><small>BITE</small><b>${m.biteLabel}</b></span><span><small>MAX</small><b>Tier ${m.maxTier}</b></span><span><small>RARE</small><b>${m.rare?'+'+m.rare+'%':'Normal'}</b></span>`;$('#status').innerHTML=`${m.h.name} · ${m.l.name} · ${m.b.name} · ${c.label.toLowerCase()} · ${currentLabel(c.current).toLowerCase()}${ev?' · '+ev.name.toLowerCase():''}${hunt}`;renderTackleModalSummary();renderOceanHud(true)}
function storyCondition(){let d=storyDefs[state.story];return d?d.ok(state):false}
function claimStory(){let d=storyDefs[state.story];if(!d||!d.ok(state))return toast('Story objective is not complete yet.');state.gold+=d.gold||0;state.pearls+=d.pearls||0;state.coral+=d.coral||0;if(Number.isInteger(d.unlock))state.unlockedRegion=Math.max(state.unlockedRegion,d.unlock);if(d.final)state.finalBonus=true;state.story=Math.min(storyDefs.length,state.story+1);save();renderAll();tone(820,.09);haptic('success');toast('Story chapter completed.')}
function instanceName(x){let f=allDefs()[x.id]||fishDefs.silverfin;if(x.nickname)return x.nickname;let g=x.gene||{};let p=g.mutant?'Mutant ':g.value>1.15?'Gilded ':g.size>1.12?'Grand ':'';return p+f.name}
function claimAquarium(){let n=aquariumStored();if(n<=0)return toast('No aquarium income ready yet.');state.gold+=n;state.totalGold+=n;state.aqua.lastClaim=now();save();renderAll();tone(720,.07);haptic('success');toast('Collected '+fmt(n)+' gold.')}
function feedAquarium(){if(!state.aquarium.length)return toast('Add fish first.');state.aqua.feedUntil=now()+30*60000;state.aqua.clean=clamp(state.aqua.clean+6,0,100);save();renderAll();toast('Fed. Happiness and income boosted for 30 minutes.')}
function cleanAquarium(){let cost=Math.max(20,Math.floor(state.aquarium.length*8));if(state.gold<cost)return toast('Need '+cost+' gold.');state.gold-=cost;state.aqua.clean=100;save();renderAll();toast('Tank cleaned.')}
function expandAquarium(){let cost=900+(state.aqua.slots-8)*280;if(state.aqua.slots>=30)return toast('Maximum aquarium size reached.');if(state.gold<cost)return toast('Need '+fmt(cost)+' gold.');state.gold-=cost;state.aqua.slots+=2;save();renderAll()}
function upgradeTank(){let cost=800*state.aqua.level;if(state.aqua.level>=10)return;if(state.gold<cost)return toast('Need '+fmt(cost)+' gold.');state.gold-=cost;state.aqua.level++;save();renderAll()}
function toggleBreeder(uid){let p=state.hatchery.parents;if(p.includes(uid))p.splice(p.indexOf(uid),1);else{if(p.length>=2)p.shift();p.push(uid)}save();renderAquarium()}
function renderHatchery(){let e=$('#hatchDisplay'),egg=state.hatchery.egg;if(egg){let left=Math.max(0,egg.ready-now());e.innerHTML=`<div><div class="egg">◉</div><b>${left<=0?'Egg ready to hatch!':'Incubating'}</b><div class="card-sub">${left<=0?'Tap HATCH / CHECK':Math.ceil(left/1000)+' seconds remaining'}</div></div>`;$('#hatchNowBtn').textContent=left<=0?'HATCH EGG':'HATCH EARLY · 1 PEARL';$('#breedBtn').disabled=true}else{let names=state.hatchery.parents.map(u=>{let x=state.aquarium.find(a=>a.uid===u);return x?instanceName(x):'?'});e.innerHTML=`<div><div style="font-size:30px">${state.hatchery.parents.length===2?'♡':'○'}</div><b>${names.length?names.join(' + '):'Select two breeders'}</b><div class="card-sub">Choose BREED on aquarium fish below.</div></div>`;$('#breedBtn').disabled=state.hatchery.parents.length!==2;$('#hatchNowBtn').textContent='NO EGG'} }
function breedSelected(){if(state.hatchery.egg)return;if(state.hatchery.parents.length!==2)return toast('Select two aquarium fish.');let a=state.aquarium.find(x=>x.uid===state.hatchery.parents[0]),b=state.aquarium.find(x=>x.uid===state.hatchery.parents[1]);if(!a||!b)return;let cost=500;if(state.gold<cost)return toast('Need 500 gold.');state.gold-=cost;let mutant=Math.random()<.12;let gene={value:clamp(((a.gene?.value||1)+(b.gene?.value||1))/2+rand(-.05,.1)+(mutant?.18:0),.85,1.55),size:clamp(((a.gene?.size||1)+(b.gene?.size||1))/2+rand(-.07,.12),.85,1.45),hue:Math.round(((a.gene?.hue||0)+(b.gene?.hue||0))/2+rand(-22,22)),mutant};let child=Math.random()<.5?a.id:b.id;state.hatchery.egg={id:child,gene,ready:now()+60000};save();renderAll();tone(560,.09);toast(mutant?'A strange mutation formed in the egg!':'Egg placed in the incubator.')}
function hatchEgg(force=false){let egg=state.hatchery.egg;if(!egg)return toast('No egg is incubating.');if(now()<egg.ready){if(!force){if(state.pearls<1)return toast('Wait or use 1 pearl to hatch early.');state.pearls--;force=true}}if(state.aquarium.length>=state.aqua.slots)return toast('Aquarium is full.');state.aquarium.push({uid:'h_'+now()+'_'+Math.random().toString(36).slice(2,6),id:egg.id,gene:egg.gene,nickname:'',added:now()});state.hatchery={parents:[],egg:null};save();renderAll();tone(920,.13);haptic('success');toast('A new hatchling joined the aquarium!')}

function huntEntries(){return Object.entries(legendaryDefs)}
function renderHunts(){
 let e=$('#huntList');if(!e)return;e.innerHTML='';
 let entries=huntEntries(),page=pagedLogItems('hunts',entries,logPageSize('hunts'));
 page.items.forEach(([id,h])=>{
   let done=state.hunts.completed[id]||0,unlocked=state.unlockedRegion>=h.region,active=state.hunts.active===id,r=document.createElement('div');
   r.className='row '+(active?'hunt-live':'');
   r.innerHTML=`<div class="row-icon" style="color:#b77700">★</div><div class="row-copy"><b>${h.name}</b><small>${regions[h.region].name} · ${h.desc} · Caught ${done}</small></div><button type="button" ${!unlocked?'disabled':''}>${active?'ACTIVE':done?'AGAIN':'START'}</button>`;
   r.querySelector('button').addEventListener('click',()=>{if(!unlocked)return;state.hunts.active=id;state.region=h.region;fish=[];specials=[];for(let i=0;i<14;i++)spawnFish(i>10);save();renderAll();toast('Hunt started: '+h.name)});
   e.appendChild(r);
 });
 renderLogPager();
}
function openHuntModal(){let h=state.hunts.active?legendaryDefs[state.hunts.active]:null;let e=$('#huntModalBody');if(h)e.innerHTML=`<div class="card legendary-card"><h3>ACTIVE: ${h.name}</h3><p>${h.desc}<br>Region: ${regions[h.region].name}<br>Storms increase appearance chance.</p><button class="widebtn danger" id="cancelHunt" type="button">CANCEL HUNT</button></div>`;else e.innerHTML='<div class="card"><h3>No hunt active</h3><p>Open Journal → Legendary Hunts and choose a target.</p></div>';$('#huntModal').classList.add('show');$('#cancelHunt')?.addEventListener('click',()=>{state.hunts.active=null;save();$('#huntModal').classList.remove('show');renderAll()})}
function renderRelics(){
 let e=$('#relicList');if(!e)return;e.innerHTML='';
 $('#relicSummary')&&($('#relicSummary').textContent=state.relics.length+' of '+relicDefs.length+' relics recovered.');
 let page=pagedLogItems('relics',relicDefs,logPageSize('relics'));
 page.items.forEach(r=>{let found=state.relics.includes(r.id),row=document.createElement('div');row.className='row';row.innerHTML=`<div class="row-icon">${found?r.icon:'?'}</div><div class="row-copy"><b>${found?r.name:'Unknown Relic'}</b><small>${found?r.desc:'Hidden near submerged ruins.'}</small></div>`;e.appendChild(row)});
 renderLogPager();
}
function renderBook(){
 let e=$('#bookGrid');if(!e)return;let defs=allDefs(),entries=Object.entries(defs),known=Object.keys(state.book).length;e.innerHTML='';
 $('#bookSummary')&&($('#bookSummary').textContent=known+' of '+entries.length+' species discovered.');
 let page=pagedLogItems('atlas',entries,logPageSize('atlas'));
 page.items.forEach(([id,f])=>{let seen=!!state.book[id],c=document.createElement('div');c.className='fish-card'+(id in legendaryDefs?' legendary-card':'');c.innerHTML=`<div class="fish-icon" style="filter:${seen?'none':'brightness(0) opacity(.28)'}">${fishSvg(id)}</div><h3>${seen?f.name:'Unknown Species'}</h3><p>Tier ${f.tier} · ${seen?'Caught '+state.book[id]+' · '+f.fight:'Change region, lure, weather, or depth.'}</p>`;e.appendChild(c)});
 renderMissions();renderLogPager();
}
function missionDefs(){return[
 {id:'catch10',name:'A Full Creel',desc:'Catch 10 fish',now:state.catches,max:10,reward:450},
 {id:'aqua5',name:'Living Gallery',desc:'Keep 5 aquarium fish',now:state.aquarium.length,max:5,reward:650},
 {id:'raregear',name:'Fine Equipment',desc:'Reforge any item to Rare',now:Object.values(state.equipment).some(g=>g.rarity>=2)?1:0,max:1,reward:800},
 {id:'relic2',name:'Ruins Scholar',desc:'Recover 2 relics',now:state.relics.length,max:2,reward:1100}
]}
function renderMissions(){
 let e=$('#missionList');if(!e)return;e.innerHTML='';
 let page=pagedLogItems('missions',missionDefs(),logPageSize('missions'));
 page.items.forEach(m=>{let done=m.now>=m.max,claimed=state.missions[m.id],r=document.createElement('div');r.className='row';r.innerHTML=`<div class="row-copy"><b>${m.name}</b><small>${m.desc} · ${Math.min(m.now,m.max)}/${m.max}</small><div class="progress"><span style="width:${clamp(m.now/m.max*100,0,100)}%"></span></div></div><button type="button" ${!done||claimed?'disabled':''}>${claimed?'CLAIMED':'+'+m.reward+'G'}</button>`;r.querySelector('button').addEventListener('click',()=>{if(!done||claimed)return;state.missions[m.id]=true;state.gold+=m.reward;save();renderAll();tone(740,.07);toast('Reward: '+m.reward+' gold')});e.appendChild(r)});
 renderLogPager();
}

function showCatch(c){let f=allDefs()[c.id];$('#catchArt').innerHTML=fishSvg(c.id,c.gene);$('#catchName').textContent=f.name+(c.id in legendaryDefs?' ★':'');$('#catchMeta').textContent=`Tier ${f.tier} · ${c.weight.toFixed(2)} kg · ${c.moment||oceanCycle().label} · Fight: ${f.fight} · Value ${c.val} gold${c.id in legendaryDefs?' · LEGENDARY':''}`;$('#aquaCatch').disabled=state.aquarium.length>=state.aqua.slots;$('#baitCatch').disabled=f.tier>=5;$('#catchModal').classList.add('show')}
function catchAction(type){if(!catchPending)return;haptic('success');let f=allDefs()[catchPending.id];if(type==='sell'){state.gold+=catchPending.val;state.totalGold+=catchPending.val;toast('Sold '+f.name+' for '+catchPending.val+' gold.')}else if(type==='aqua'){if(state.aquarium.length>=state.aqua.slots)return toast('Aquarium is full.');state.aquarium.push({uid:'c_'+now()+'_'+Math.random().toString(36).slice(2,7),id:catchPending.id,gene:catchPending.gene||{value:1,size:1,hue:0},nickname:'',added:now()});toast(f.name+' added to the aquarium.')}else if(type==='bait'){let tier=clamp(f.tier,1,5);state.bait[tier]=(state.bait[tier]||0)+1;toast(f.name+' prepared as '+baitDefs[tier].name+'.')}catchPending=null;$('#catchModal').classList.remove('show');save();renderAll()}
function sonarPing(){let n=now();if(n<state.sonarAt)return toast('Sonar recharging for '+Math.ceil((state.sonarAt-n)/1000)+'s.');state.sonarAt=n+sonarCooldown();sonar=true;fish.forEach(q=>{if(allDefs()[q.id].tier>=3)q.sonarUntil=performance.now()+7500});for(let i=0;i<3;i++)spawnFish(true);maybeSpawnSpecial();setTimeout(()=>{sonar=false},7500);haptic('sonar');tone(900,.08);setTimeout(()=>tone(650,.1),90);toast('Sonar reveals large fish, treasure, and ruin secrets.');save();renderAll()}

let tackleTab='hook',tacklePage=0;
function renderTackleModalSummary(){let e=$('#tackleModalSummary');if(!e)return;let m=tackleMetrics();e.innerHTML=`<div><small>TARGET</small><b>${m.target}</b></div><div><small>BITE RATE</small><b>${m.biteLabel}</b></div><div><small>MAX FISH</small><b>Tier ${m.maxTier}</b></div><div><small>TREASURE</small><b>${m.treasure?'+'+m.treasure+'%':'Normal'}</b></div>`}
function tackleList(){if(tackleTab==='hook')return Object.entries(hookDefs).map(([id,x])=>({id,...x,count:null,active:state.selectedHook===id,locked:!hookUnlocked(id),note:(!hookUnlocked(id)?'Rod Tier '+x.unlock+' required. ': '')+x.desc}));if(tackleTab==='lure')return Object.entries(lureDefs).map(([id,x])=>({id,...x,count:id==='none'?null:(state.lures[id]||0),active:state.selectedLure===id,locked:id!=='none'&&(state.lures[id]||0)<=0,note:x.desc||('Targets '+x.target+'.')}));return Object.entries(baitDefs).map(([id,x])=>({id:+id,...x,count:+id?(state.bait[id]||0):null,active:(state.selectedBait||0)===+id,locked:+id>0&&(state.bait[id]||0)<=0,note:x.desc}))}
function renderTackleSheet(){let grid=$('#tackleGrid'),pager=$('#tacklePager');if(!grid||!pager)return;document.querySelectorAll('#tackleTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tackleTab===tackleTab));let list=tackleList(),pages=Math.max(1,Math.ceil(list.length/4));tacklePage=clamp(tacklePage,0,pages-1);let items=list.slice(tacklePage*4,tacklePage*4+4);grid.innerHTML='';items.forEach(x=>{let b=document.createElement('button');b.type='button';b.className='tackle-option'+(x.active?' active':'')+(x.locked?' locked':'');b.disabled=!!x.locked;b.innerHTML=`<span class="tackle-art">${x.icon||'○'}</span><span class="tackle-option-copy"><b>${x.name}</b><small>${x.note}</small></span>${x.count!==null?`<span class="tackle-count">×${x.count}</span>`:''}${x.active?'<span class="tackle-equipped">EQUIPPED</span>':''}`;b.onclick=()=>{haptic('select');if(tackleTab==='hook')state.selectedHook=x.id;else if(tackleTab==='lure')state.selectedLure=x.id;else state.selectedBait=+x.id;save();renderAll();renderTackleSheet()};grid.appendChild(b)});pager.innerHTML='';if(pages>1){let p=document.createElement('button'),n=document.createElement('button'),s=document.createElement('span');p.textContent='‹';n.textContent='›';s.textContent=(tacklePage+1)+' / '+pages;p.disabled=tacklePage<=0;n.disabled=tacklePage>=pages-1;p.onclick=()=>{tacklePage--;renderTackleSheet()};n.onclick=()=>{tacklePage++;renderTackleSheet()};pager.append(p,s,n)}else{let s=document.createElement('span');s.textContent=tackleTab==='hook'?'Hooks unlock with Rod Tier.':tackleTab==='bait'?'Bait is prepared from catches.':'Lures are reusable unless lost on a snapped line.';pager.appendChild(s)}renderTackleModalSummary()}
function openTackle(){if(hook.mode!=='idle')return toast('Finish the current cast before changing tackle.');tacklePage=0;renderTackleSheet();$('#tackleModal').classList.add('show');haptic('select')}
function closeModal(id){$('#'+id).classList.remove('show')}$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
$$('.nav').forEach(b=>b.addEventListener('click',()=>{haptic('select');ensureAudio();
 $$('.nav').forEach(x=>{let active=x===b;x.classList.toggle('active',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});
 $$('.screen').forEach(x=>x.classList.toggle('active',x.id==='screen-'+b.dataset.screen));
 document.body.classList.toggle('aquarium-active',b.dataset.screen==='aquarium');
 if(b.dataset.screen==='map'){renderWorldMap();requestAnimationFrame(fitWorldMap)}
 if(b.dataset.screen==='dock')renderDockBuilder();
 if(b.dataset.screen==='aquarium')renderAquarium();
 if(b.dataset.screen==='journal'){renderBook();renderHunts();renderRelics();renderCaptainLog()}
}));
$('#huntBtn').addEventListener('click',openHuntModal);$('#sonarBtn').addEventListener('click',sonarPing);$('#tackleOpen').addEventListener('click',openTackle);document.querySelectorAll('#tackleTabs button').forEach(b=>b.addEventListener('click',()=>{tackleTab=b.dataset.tackleTab;tacklePage=0;renderTackleSheet()}));
$('#lureSelect').addEventListener('change',e=>{state.selectedLure=e.target.value;save();renderAll()});$('#baitSelect').addEventListener('change',e=>{state.selectedBait=+e.target.value||0;save();renderStatus()});
let castAimX=W*.72,castDragStartX=0,castDragBaseAim=castAimX;function setCastAimX(x,feedback=false){castAimX=clamp(x,24,W-24);if(feedback&&hook.mode==='idle')haptic('select')}const castBtn=$('#castBtn');castBtn.addEventListener('pointerdown',e=>{e.preventDefault();castDragStartX=e.clientX;castDragBaseAim=castAimX;try{castBtn.setPointerCapture?.(e.pointerId)}catch(_){}if(hook.mode==='idle')castStart();else reelPress(true)});castBtn.addEventListener('pointermove',e=>{if(!powering)return;let r=canvas.getBoundingClientRect(),scale=W/Math.max(1,r.width),dx=(e.clientX-castDragStartX)*scale;setCastAimX(castDragBaseAim+dx*1.25)});castBtn.addEventListener('pointerup',e=>{e.preventDefault();try{castBtn.releasePointerCapture?.(e.pointerId)}catch(_){}if(powering)castRelease();reelPress(false)});castBtn.addEventListener('pointercancel',e=>{try{castBtn.releasePointerCapture?.(e.pointerId)}catch(_){}if(powering)castRelease();reelPress(false)});castBtn.addEventListener('pointerleave',()=>{if(hook.mode==='hooked')reelPress(false)});
let castAimPointer=null;function castAimFromEvent(e,feedback=false){let r=canvas.getBoundingClientRect();setCastAimX((e.clientX-r.left)/Math.max(1,r.width)*W,feedback);$('#seaHint').textContent=(castAimX<rodTip().x?'Aiming left':'Aiming right')+' · Hold CAST, then release.'}canvas.addEventListener('pointerdown',e=>{if(hook.mode!=='idle'||powering)return;e.preventDefault();castAimPointer=e.pointerId;try{canvas.setPointerCapture?.(e.pointerId)}catch(_){}castAimFromEvent(e,true)},{passive:false});canvas.addEventListener('pointermove',e=>{if(castAimPointer!==e.pointerId||hook.mode!=='idle'||powering)return;e.preventDefault();castAimFromEvent(e,false)},{passive:false});function endCastAim(e){if(castAimPointer!==e.pointerId)return;try{canvas.releasePointerCapture?.(e.pointerId)}catch(_){}castAimPointer=null}canvas.addEventListener('pointerup',endCastAim,{passive:false});canvas.addEventListener('pointercancel',endCastAim,{passive:false});
let canvasPointerId=null,canvasLastY=0;
canvas.addEventListener('pointerdown',e=>{if(!['sinking','hooked'].includes(hook.mode))return;e.preventDefault();canvasPointerId=e.pointerId;canvas.setPointerCapture?.(e.pointerId);let r=canvas.getBoundingClientRect();hook.targetX=clamp((e.clientX-r.left)/r.width*W,24,W-24);canvasLastY=(e.clientY-r.top)/r.height*H},{passive:false});
canvas.addEventListener('pointermove',e=>{if(canvasPointerId!==e.pointerId||!['sinking','hooked'].includes(hook.mode))return;e.preventDefault();let r=canvas.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width*W,24,W-24),y=clamp((e.clientY-r.top)/r.height*H,waterY,H-20),dx=x-hook.x,dy=y-canvasLastY;if(hook.mode==='sinking'){let action=Math.abs(dy)>Math.abs(dx)*1.15?'JIG':Math.abs(dx)>10?'SWEEP':'TWITCH';hook.action=action;hook.actionEnergy=clamp((hook.actionEnergy||0)+.22+Math.min(.38,Math.hypot(dx,dy)/90),0,1);if(action==='JIG')hook.jigImpulse=clamp((hook.jigImpulse||0)-dy/20,-1.4,1.4);renderOceanHud(true)}hook.targetX=x;if(hook.mode==='hooked'){hook.pullX-=clamp(dx/130,-.35,.35);hook.pullY-=clamp(dy/85,-.28,.28)}canvasLastY=y},{passive:false});
