/* Rogue Quest board movement, events, merchants, and upgrades */
'use strict';
function rarityPick(force){if(Number.isInteger(force))return rarities[clamp(force,0,rarities.length-1)];let luck=artifactLuck(),roll=Math.random()*(1+luck*.18),idx=roll>.995?5:roll>.94?4:roll>.78?3:roll>.52?2:roll>.2?1:0;return rarities[idx]}
function dropGear(forceTier,forceSlot,silent=false){if(state.gear.length>=MAX_INV){let low=state.gear.filter(g=>!g.locked&&state.equipped[g.slot]!==g.id).sort((a,b)=>gearPower(a)-gearPower(b))[0];if(low)salvageGear(low.id);else return null}let rarity=rarityPick(forceTier),slot=forceSlot||gearSlots[Math.floor(Math.random()*gearSlots.length)],stats=slot==='Weapon'?['ATK','CRIT']:slot==='Armor'?['HP','DEF']:slot==='Helm'?['HP','DEF']:slot==='Boots'?['DEF','CRIT']:slot==='Ring'?['ATK','CRIT']:['ATK','HP','CRIT'],stat=stats[Math.floor(Math.random()*stats.length)],base=stat==='HP'?45:stat==='ATK'?9:stat==='DEF'?3:2.2,value=Math.round(base*rarity.m*(.86+Math.random()*.3)*10)/10,subPool=['ATK','HP','DEF','CRIT'].filter(x=>x!==stat),subStat=rarities.indexOf(rarity)>=2?subPool[Math.floor(Math.random()*subPool.length)]:null,subValue=subStat?(subStat==='HP'?Math.round(18*rarity.m):subStat==='ATK'?Math.round(4*rarity.m):subStat==='DEF'?Math.round(1.5*rarity.m):Math.round(1.2*rarity.m)):0,names={Weapon:['Runeblade','Storm Edge','Moonsteel Sword'],Armor:['Warden Plate','Drake Mail','Aether Coat'],Helm:['Sentinel Helm','Wyrm Crown','Scout Hood'],Charm:['Star Charm','Echo Orb','Spirit Seal'],Boots:['Gale Boots','Iron Greaves','Rift Steps'],Ring:['Ember Ring','Frost Band','Void Loop']},name=names[slot][Math.floor(Math.random()*names[slot].length)],g={id:'g'+Date.now()+Math.random().toString(36).slice(2,7),slot,name,rarity,stat,value,subStat,subValue,level:1,locked:false,power:Math.round((stat==='HP'?value*.25:stat==='CRIT'?value*9:value*4)*rarity.m)};state.gear.push(g);state.gearFound++;if(!silent)lootPop(gearIcons[slot],rarity.n+' '+name,`${stat} +${value}${stat==='CRIT'?'%':''}${subStat?' · '+subStat+' +'+subValue:''}`);return g}
function startRun(){if(!spendEnergy(RUN_COST))return openModal('energyModal'),toast('Not enough energy.');let h=heroBase(),chapter=state.currentChapter;state.run={chapter,pos:0,board:generateBoard(chapter),hp:h.hp,maxHp:h.hp,shield:0,atk:h.atk,def:h.def,crit:h.crit,critDmg:1.8,attackRate:h.rate,dodge:0,lifesteal:0,thorns:0,fire:0,frost:0,storm:0,poison:0,shock:0,bleed:0,regen:0,multi:0,execute:0,berserk:0,petPower:0,petSpeed:0,treasure:0,eliteBonus:0,skillHaste:0,focus:2,rerolls:1,camps:1,combo:0,ultimate:0,upgrades:[],powerCounts:{},synergies:[],goldRun:0};combat=null;sceneMode='board';rolling=false;buildBoard();saveState();tone(330,.12);banner('Adventure Begins');renderAll()}
function generateBoard(chapter){let pool=['battle','battle','battle','treasure','shrine','event','elite','merchant','camp','trap','portal'],board=['start'];for(let i=1;i<17;i++){let type=pool[Math.floor(Math.random()*pool.length)];if(i<3&&['elite','trap'].includes(type))type='battle';if(i===8)type=Math.random()<.5?'elite':'shrine';if(i===13)type=Math.random()<.5?'merchant':'camp';board.push(type)}board.push('boss');return board}
function buildBoard(){boardNodes=[];for(let i=0;i<18;i++){let p=i/17,y=H*.83-p*H*.62,x=W*.5+Math.sin(i*.92)*W*.27+(i%4===0?Math.cos(i*.37)*30:0);boardNodes.push({x,y,type:state.run?state.run.board[i]:(i===0?'start':i===17?'boss':['battle','treasure','shrine','elite','event','battle','merchant','camp'][i%8])})}}
function nodeLabel(type){return({start:'Trailhead',battle:'Battle',treasure:'Treasure',shrine:'Power Shrine',elite:'Elite Battle',merchant:'Merchant',camp:'Safe Camp',event:'Mystery Event',trap:'Trap',portal:'Portal',boss:'Boss'}[type]||type)}
async function rollDice(){if(!state.run||combat||rolling)return;rolling=true;state.rolls++;renderRun();let final=1+Math.floor(Math.random()*6),ticks=state.motion?5:1;for(let i=0;i<ticks;i++){banner('🎲 '+(i===ticks-1?final:1+Math.floor(Math.random()*6)));tone(180+i*30,.025,'square');await wait(state.motion?45:1)}await moveBy(final);rolling=false;saveState();renderAll()}
async function moveBy(n){if(!state.run)return;let target=Math.min(17,state.run.pos+n);for(let p=state.run.pos+1;p<=target;p++){state.run.pos=p;state.bestStages[state.run.chapter]=Math.max(state.bestStages[state.run.chapter]||1,p+1);tone(270+p*12,.035);if(state.motion)await wait(90)}resolveNode(state.run.board[state.run.pos])}
function fateDice(){let r=state.run;if(!r||combat||rolling||r.focus<=0)return;r.focus--;let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);showChoice('Fate Dice','You spend one Fate charge and glimpse two possible rolls.',[
 {label:'🎲 Choose '+a,sub:'Move '+a+' spaces',fn:()=>moveBy(a)},
 {label:'🎲 Choose '+b,sub:'Move '+b+' spaces',fn:()=>moveBy(b)}
]);saveState();renderAll()}
function fieldCamp(){let r=state.run;if(!r||combat||r.camps<=0||r.hp>=r.maxHp)return;r.camps--;let heal=r.maxHp*.45;r.hp=Math.min(r.maxHp,r.hp+heal);r.shield=Math.max(r.shield,r.maxHp*.08);tone(500,.09);toast('Camp restored '+Math.round(heal)+' HP and granted a small shield.');saveState();renderAll()}
function resolveNode(type){if(!state.run)return;if(type==='battle')return startCombat(false,false);if(type==='elite')return startCombat(true,false);if(type==='boss')return startCombat(true,true);if(type==='treasure')return treasure();if(type==='shrine')return chooseUpgrade();if(type==='merchant')return merchant();if(type==='camp'){state.run.camps++;state.run.hp=Math.min(state.run.maxHp,state.run.hp+state.run.maxHp*.25);toast('Safe camp · healed 25% and gained a Field Camp charge.');return renderAll()}if(type==='event')return randomEvent();if(type==='trap')return trapNode();if(type==='portal')return portalNode();renderAll()}
function treasure(){let r=state.run;state.chests++;state.dailyClaimed[dateKey()+':chestNow']=(state.dailyClaimed[dateKey()+':chestNow']||0)+1;let bonus=1+(r.treasure||0)+artifactLuck(),roll=Math.random(),desc='';if(roll<.13){let e=3+Math.floor(Math.random()*4);state.energy=Math.min(maxEnergy(),state.energy+e);desc='+'+e+' Energy'}else if(roll<.28){let g=2+Math.floor(Math.random()*4);state.gems+=g;desc='+'+g+' Gems'}else if(roll<.48){let ore=5+Math.floor(Math.random()*8);gainMaterial('ore',ore);desc='+'+ore+' Ore'}else if(roll<.68){dropGear(undefined,undefined,true);desc='Equipment discovered!'}else{let gold=Math.round((130+Math.random()*190)*r.chapter*bonus);gainGold(gold);r.goldRun+=gold;desc='+'+gold+' Gold'}tone(650,.08);lootPop('🎁','Treasure Found',desc);saveState();renderAll()}
function trapNode(){let r=state.run,dmg=Math.round(r.maxHp*(.08+Math.random()*.08));if((r.dodge||0)>Math.random()){toast('Phantom Step avoided the trap!')}else{r.hp=Math.max(1,r.hp-dmg);banner('⚠ Trap! -'+dmg+' HP');shake=8;tone(130,.08,'square')}if(Math.random()<.45){gainMaterial('ore',4);toast('You recovered 4 ore from the trap mechanism.')}saveState();renderAll()}
async function portalNode(){if(!state.run)return;let jump=Math.min(2,17-state.run.pos);banner('🌀 Rift Portal');tone(620,.14,'sine');if(jump>0){await wait(180);state.run.pos+=jump;state.bestStages[state.run.chapter]=Math.max(state.bestStages[state.run.chapter]||1,state.run.pos+1)}toast('The portal carried you '+jump+' spaces forward.');saveState();renderAll()}
function showChoice(title,desc,choices,closable=true){$('#choiceTitle').textContent=title;$('#choiceDesc').textContent=desc;let el=$('#choiceList');el.innerHTML='';choices.forEach(ch=>{let b=document.createElement('button');b.className='choice-btn';b.innerHTML=`<b>${ch.label}</b><span>${ch.sub||''}</span>`;b.disabled=!!ch.disabled;b.addEventListener('click',()=>{closeModal('choiceModal');Promise.resolve(ch.fn&&ch.fn()).then(()=>{saveState();renderAll()})});el.appendChild(b)});$('#choiceClose').style.display=closable?'block':'none';openModal('choiceModal')}
function randomEvent(){state.events++;let r=state.run,events=['altar','fountain','gambler','cache','spirit','smith'],kind=events[Math.floor(Math.random()*events.length)];if(kind==='altar')showChoice('Bloodstone Altar','Ancient runes pulse with dangerous power.',[
 {label:'Offer vitality',sub:'Lose 16% max HP · gain +24% attack for this run',fn:()=>{r.maxHp*=.84;r.hp=Math.min(r.hp,r.maxHp);r.atk*=1.24;banner('Power surges through you!')}},{label:'Take a shard',sub:'Gain 4 artifact dust',fn:()=>gainMaterial('dust',4)},{label:'Leave',sub:'Keep moving',fn:()=>{}}
]);
 if(kind==='fountain')showChoice('Moonlit Fountain','Clear water reflects a sky that is not your own.',[
 {label:'Drink',sub:'Heal 45% max HP',fn:()=>r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.45)},{label:'Bottle the water',sub:'+1 Fate Dice and +1 Field Camp',fn:()=>{r.focus++;r.camps++}}
 ]);
 if(kind==='gambler')showChoice('Masked Gambler','A traveler offers a very questionable wager.',[
 {label:'Wager 120 gold',sub:'70% chance for gear · 30% chance to lose it',disabled:state.gold<120,fn:()=>{state.gold-=120;if(Math.random()<.7){dropGear(undefined,undefined,true);lootPop('🎒','You Win!','A piece of gear is yours.')}else toast('The gambler wins this round.')}},{label:'Challenge for gems',sub:'50% chance +10 gems · otherwise nothing',fn:()=>{if(Math.random()<.5){state.gems+=10;lootPop('◆','Lucky Hand','+10 Gems')}else toast('No luck this time.')}},{label:'Walk away',sub:'No risk',fn:()=>{}}
 ]);
 if(kind==='cache')showChoice('Abandoned Supply Cache','Someone left useful supplies beside the trail.',[
 {label:'Take rations',sub:'+5 Energy',fn:()=>state.energy=Math.min(maxEnergy(),state.energy+5)},{label:'Take crafting supplies',sub:'+10 Ore · +3 Pet Treats',fn:()=>{gainMaterial('ore',10);gainMaterial('treats',3)}},{label:'Search the false bottom',sub:'Gain random gear, but lose 8% HP',fn:()=>{r.hp=Math.max(1,r.hp-r.maxHp*.08);dropGear(undefined,undefined,true);lootPop('🎒','Hidden Gear','A concealed item was inside.')}}
 ]);
 if(kind==='spirit')showChoice('Wandering Spirit','A forest spirit circles your companion.',[
 {label:'Bond with your pet',sub:'+15 pet affinity',fn:()=>state.pets[state.activePet].affinity+=15},{label:'Ask for protection',sub:'Gain a 30% max HP shield',fn:()=>r.shield+=r.maxHp*.3},{label:'Ask for wisdom',sub:'Open a power choice',fn:()=>setTimeout(chooseUpgrade,120)}
 ]);
 if(kind==='smith')showChoice('Wandering Smith','The smith offers to improve your expedition.',[
 {label:'Sharpen weapon · 150 gold',sub:'+15% run attack',disabled:state.gold<150,fn:()=>{state.gold-=150;r.atk*=1.15}},{label:'Reinforce armor · 150 gold',sub:'+3 run defense and +12% max HP',disabled:state.gold<150,fn:()=>{state.gold-=150;r.def+=3;r.maxHp*=1.12;r.hp*=1.12}},{label:'Trade scraps',sub:'+12 Ore',fn:()=>gainMaterial('ore',12)}
 ])}

function merchant(){let r=state.run;showChoice('Traveling Merchant','Spend permanent gold for immediate expedition advantages.',[
 {label:'🍲 Full Meal · 120 gold',sub:'Heal 55% max HP',disabled:state.gold<120,fn:()=>{state.gold-=120;r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.55)}},
 {label:'🎲 Fate Charm · 100 gold',sub:'+2 Fate Dice charges',disabled:state.gold<100,fn:()=>{state.gold-=100;r.focus+=2}},
 {label:'✨ Mystery Power · 180 gold',sub:'Choose another run upgrade',disabled:state.gold<180,fn:()=>{state.gold-=180;setTimeout(chooseUpgrade,100)}},
 {label:'🎒 Merchant Gear · 260 gold',sub:'Guaranteed Rare+ equipment',disabled:state.gold<260,fn:()=>{state.gold-=260;dropGear(Math.random()<.25?3:2,undefined,true);lootPop('🎒','Merchant Deal','Rare+ equipment acquired.')}},
 {label:'Leave',sub:'Save your gold',fn:()=>{}}
 ])}
function rollUpgradeRarity(){let x=Math.random()*100,sum=0;for(const r of rarityRolls){sum+=r.w;if(x<sum)return r}return rarityRolls[0]}
function chooseUpgrade(){if(!state.run)return;let picks=[],pool=upgradeDefs.slice();while(picks.length<3&&pool.length){let i=Math.floor(Math.random()*pool.length),u=pool.splice(i,1)[0];picks.push({u,r:rollUpgradeRarity()})}let el=$('#upgradeGrid');el.innerHTML='';picks.forEach(({u,r})=>{let b=document.createElement('button');b.className='upgrade '+r.c;b.innerHTML=`<div class="ui">${u.ico}</div><div><em>${r.n.toUpperCase()} · ${u.tag}</em><strong>${u.name}</strong><p>${u.desc} · ${Math.round(r.mult*100)}% potency.</p></div>`;b.addEventListener('click',()=>{applyUpgrade(u.id,r.mult);closeModal('upgradeModal');saveState();renderAll()});el.appendChild(b)});$('#rerollUpgradeBtn').disabled=(state.run.rerolls||0)<=0;$('#rerollUpgradeBtn').textContent=`🎲 REROLL CHOICES · ${state.run.rerolls||0}`;openModal('upgradeModal')}
function applyUpgrade(id,m=1){let r=state.run;if(!r)return;r.upgrades.push(id);r.powerCounts[id]=(r.powerCounts[id]||0)+1;switch(id){case'power':r.atk*=1+.22*m;break;case'speed':r.attackRate*=Math.max(.65,1-.18*m);break;case'crit':r.crit+=.09*m;break;case'critDmg':r.critDmg+=.32*m;break;case'multi':r.multi+=.12*m;break;case'execute':r.execute+=.22*m;break;case'combo':r.comboPower=(r.comboPower||0)+.018*m;break;case'berserk':r.berserk+=.28*m;break;case'vital':{let old=r.maxHp;r.maxHp*=1+.24*m;r.hp=Math.min(r.maxHp,r.hp+(r.maxHp-old)+r.maxHp*.15);break}case'armor':r.def+=3.5*m;break;case'dodge':r.dodge+=.055*m;break;case'thorns':r.thorns+=.12*m;break;case'shield':r.startShield=(r.startShield||0)+.18*m;r.shield+=r.maxHp*.18*m;break;case'regen':r.regen+=.007*m;break;case'lifesteal':r.lifesteal+=.035*m;break;case'heal':r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.38*m);break;case'fire':r.fire+=.16*m;break;case'frost':r.frost+=.13*m;break;case'storm':r.storm+=.18*m;break;case'poison':r.poison+=.12*m;break;case'shock':r.shock+=.045*m;break;case'bleed':r.bleed+=.13*m;break;case'petPower':r.petPower+=.28*m;break;case'petSpeed':r.petSpeed+=.18*m;break;case'treasure':r.treasure+=.18*m;break;case'elite':r.eliteBonus+=.2*m;break;case'focus':r.focus++;break;case'skill':r.skillHaste+=.12*m;break}r.crit=clamp(r.crit,0,.85);r.dodge=clamp(r.dodge,0,.48);checkSynergies();tone(680,.08);banner(upgradeDefs.find(x=>x.id===id).name)}
function checkSynergies(){let r=state.run;if(!r)return;let add=(id,name)=>{if(!r.synergies.includes(id)){r.synergies.push(id);lootPop('🌟','EVOLUTION UNLOCKED',name);tone(880,.16)}};if(r.fire>=.45&&(r.powerCounts.power||0))add('inferno','Inferno · burning enemies explode on defeat');if(r.frost>=.35&&(r.powerCounts.shield||0))add('glacier','Glacier Guard · shields slow enemy attacks');if(r.storm>=.45&&(r.powerCounts.speed||0))add('tempest','Tempest · every 5th hit calls lightning');if(r.lifesteal>=.09&&r.crit>=.2)add('vampire','Crimson Pact · critical lifesteal is doubled');if(r.poison>=.3&&(r.powerCounts.execute||0))add('plague','Plague Reaper · poison deals more damage to wounded foes')}
