/* Rogue Quest base combat and run completion */
'use strict';
function enemyFor(elite,boss){let r=state.run,ch=r.chapter,base;if(boss)base=enemyDefs.find(e=>e.id===chapters[ch].boss);else{let pool=enemyDefs.filter(e=>e.chapter===ch&&!e.boss);base=pool[Math.floor(Math.random()*pool.length)]}let scale=1+(r.pos*.035)+(state.level-1)*.022+(ch-1)*.07,e={...base};e.maxHp=Math.round(e.hp*scale*(elite?1.75:1));e.hp=e.maxHp;e.atk=e.atk*scale*(elite?1.4:1);e.reward=Math.round((55+ch*38+r.pos*5)*(elite?2.3:1));e.elite=elite;e.boss=boss;if(elite)e.name='Elite '+e.name;return e}
function startCombat(elite,boss,resume=false){let r=state.run,e=enemyFor(elite,boss);if(!resume)state.battles++;r.inCombat={elite:!!elite,boss:!!boss};r.shield=Math.max(r.shield||0,r.maxHp*(r.startShield||0));if(state.activePet==='golem')r.shield=Math.max(r.shield,r.maxHp*.1);combat={enemy:e,enemyHp:e.maxHp,enemyMax:e.maxHp,heroTimer:.12,enemyTimer:.7,petTimer:.45,specialTimer:boss?4.5:7+Math.random()*2,telegraph:0,enemyStun:0,cooldowns:{strike:0,guard:0,arc:0},boss,elite,bleedDps:0,bleedTime:0,phase2:false,heroAnim:0,enemyAnim:0,flash:0,petHealTimer:5};sceneMode='combat';banner(boss?'♛ BOSS BATTLE!':elite?'💀 ELITE BATTLE!':'⚔ BATTLE!');tone(boss?115:220,.18,'sawtooth');buzz(24);renderAll()}
function damageEnemy(base,{crit=false,skill=false,pet=false,color='#bfe8ff'}={}){if(!combat||!state.run)return 0;let r=state.run,c=combat,dmg=base;if((c.elite||c.boss)&&r.eliteBonus)dmg*=1+r.eliteBonus;if(c.enemyHp/c.enemyMax<.3)dmg*=1+(r.execute||0);if(r.hp/r.maxHp<.32)dmg*=1+(r.berserk||0);if(!pet)dmg*=1+(r.combo||0)*(r.comboPower||0);if(crit)dmg*=r.critDmg||1.8;if(r.synergies.includes('plague')&&c.enemyHp/c.enemyMax<.4)dmg*=1.18;dmg=Math.max(1,dmg);c.enemyHp-=dmg;state.totalDamage+=dmg;if(!pet){r.combo=(r.combo||0)+1+(state.activePet==='wolf'&&Math.random()<.28?1:0);state.maxCombo=Math.max(state.maxCombo,Math.floor(r.combo));r.ultimate=clamp((r.ultimate||0)+(skill?11:7)*(state.heroClass==='mystic'?1.2:1),0,100);if(r.lifesteal){let ls=dmg*r.lifesteal*(crit&&r.synergies.includes('vampire')?2:1);r.hp=Math.min(r.maxHp,r.hp+ls)}}spawnHit(W*.72,H*.53,color,crit?13:8);floatText(W*.72,H*.44,'-'+Math.round(dmg),crit?'#ffe08a':color);combat.heroAnim=.16;if(crit){shake=4;tone(660,.035)}else tone(430,.028);if(r.synergies.includes('tempest')&&Math.floor(r.combo)%5===0&&!pet){let chain=r.atk*.55;combat.enemyHp-=chain;state.totalDamage+=chain;spawnLightning(W*.42,H*.44,W*.7,H*.52);floatText(W*.72,H*.38,'⚡ '+Math.round(chain),'#9aefff')}return dmg}
function basicHeroAttack(){if(!combat)return;let r=state.run,crit=Math.random()<r.crit;damageEnemy(r.atk,{crit,color:crit?'#ffe18a':'#bfe8ff'});if(r.fire)combat.burn=Math.max(combat.burn||0,r.atk*r.fire*.22);if(r.poison)combat.poison=(combat.poison||0)+r.atk*r.poison*.055;if(r.bleed&&crit){combat.bleedDps=Math.max(combat.bleedDps,r.atk*r.bleed*.28);combat.bleedTime=4}if(r.shock&&Math.random()<r.shock)combat.enemyStun=Math.max(combat.enemyStun,.7);if(r.multi&&Math.random()<r.multi)damageEnemy(r.atk*.62,{crit:Math.random()<r.crit*.6,color:'#d7c8ff'});projectiles.push({x:W*.38,y:H*.53,tx:W*.67,ty:H*.53,life:.15,max:.15,color:state.heroClass==='mystic'?'#c69cff':state.heroClass==='ranger'?'#b8f0ff':'#d9f4ff',size:5})}
function petAttack(){if(!combat)return;let r=state.run,p=petStats(),mult=1+(r.petPower||0),dmg=p.atk*mult;if(p.id==='fox'&&combat.enemyHp/combat.enemyMax<.4)dmg*=1.45;if(p.id==='wisp'){let burst=1+Math.random()*.75;dmg*=burst;if(Math.random()<.18)combat.enemyStun=.55}if(p.id==='wolf'&&r.combo>=10)dmg*=1.3;damageEnemy(dmg,{pet:true,color:'#8fffc1'});r.ultimate=clamp(r.ultimate+3,0,100);projectiles.push({x:W*.3,y:H*.67,tx:W*.66,ty:H*.58,life:.2,max:.2,color:'#8fffc1',size:4})}
function enemyAttack(heavy=false){if(!combat||!state.run)return;let r=state.run,c=combat,e=c.enemy;if(Math.random()<r.dodge){banner('DODGE!');floatText(W*.28,H*.44,'DODGE','#b8f3ff');tone(780,.04);return}let raw=e.atk*(heavy?1.85:1),mit=raw*(100/(100+r.def*6)),guard=(r.guardTime||0)>0?(state.heroClass==='knight'?.3:.4):1,dmg=Math.max(1,mit*guard);if(state.activePet==='golem')dmg*=.84;if(r.shield>0){let absorbed=Math.min(r.shield,dmg);r.shield-=absorbed;dmg-=absorbed;floatText(W*.28,H*.41,'-'+Math.round(absorbed)+' SHIELD','#7fdcff')}if(dmg>0){r.hp-=dmg;floatText(W*.28,H*.47,'-'+Math.round(dmg),heavy?'#ff817c':'#ffaaa3');spawnHit(W*.3,H*.55,'#ff827a',heavy?14:8);if(r.thorns){let refl=mit*r.thorns;c.enemyHp-=refl;state.totalDamage+=refl;floatText(W*.7,H*.62,'↩'+Math.round(refl),'#a8ffbd')}}r.ultimate=clamp(r.ultimate+(heavy?9:4),0,100);r.combo=Math.floor((r.combo||0)*.55);c.enemyAnim=.18;shake=heavy?13:8;tone(heavy?105:155,.05,'square');buzz(heavy?45:20)}
function castSkill(k){if(!combat||!state.run)return;let r=state.run,c=combat,haste=clamp(1-(r.skillHaste||0),.5,1);if(k==='ultimate'){if(r.ultimate<100)return;state.skillsUsed++;state.dailyClaimed[dateKey()+':skillNow']=(state.dailyClaimed[dateKey()+':skillNow']||0)+1;r.ultimate=0;let crit=Math.random()<r.crit;damageEnemy(r.atk*5.2*(state.heroClass==='mystic'?1.15:1),{crit,skill:true,color:'#f1b0ff'});r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.15);r.shield+=r.maxHp*.16;combat.enemyStun=1.5;spawnBurst(W*.68,H*.54,'#d39cff',28);shake=10;banner('🌟 ASCENDANT BURST!');tone(950,.18,'sine');renderAll();return}
 if((c.cooldowns[k]||0)>0)return;state.skillsUsed++;state.dailyClaimed[dateKey()+':skillNow']=(state.dailyClaimed[dateKey()+':skillNow']||0)+1;if(k==='strike'){c.cooldowns.strike=3.8*haste;let crit=Math.random()<Math.min(.95,r.crit+.15);damageEnemy(r.atk*2.65,{crit,skill:true,color:'#ffe58a'});if(r.bleed){c.bleedDps=Math.max(c.bleedDps,r.atk*r.bleed*.55);c.bleedTime=5}banner('POWER STRIKE')}
 if(k==='guard'){c.cooldowns.guard=6.4*haste;r.shield+=r.maxHp*.3;r.guardTime=state.heroClass==='knight'?3.4:2.4;r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.04);banner('GUARD UP')}
 if(k==='arc'){c.cooldowns.arc=7.2*haste;damageEnemy(r.atk*1.65*(state.heroClass==='mystic'?1.3:1),{skill:true,color:'#89eaff'});c.enemyStun=Math.max(c.enemyStun,1.25);if(r.storm)damageEnemy(r.atk*r.storm*.55,{skill:true,color:'#a8f3ff'});spawnLightning(W*.38,H*.44,W*.72,H*.52);banner('ARC BURST')}
 tone(k==='guard'?300:k==='arc'?800:560,.08);buzz(18);renderAll()}
function combatTick(rawDt){if(!combat||!state.run)return;let dt=rawDt*state.battleSpeed,r=state.run,c=combat,e=c.enemy;c.heroAnim=Math.max(0,c.heroAnim-dt);c.enemyAnim=Math.max(0,c.enemyAnim-dt);c.flash=Math.max(0,c.flash-dt);if(r.guardTime>0)r.guardTime-=dt;Object.keys(c.cooldowns).forEach(k=>c.cooldowns[k]=Math.max(0,c.cooldowns[k]-dt));if(c.enemyStun>0)c.enemyStun-=dt;if(r.regen)r.hp=Math.min(r.maxHp,r.hp+r.maxHp*r.regen*dt);if(c.burn)c.enemyHp-=c.burn*dt;if(c.poison)c.enemyHp-=c.poison*dt*(1+Math.min(2,c.poison/c.enemyMax*8));if(c.bleedTime>0){c.bleedTime-=dt;c.enemyHp-=c.bleedDps*dt}else c.bleedDps=0;
 c.heroTimer-=dt;if(c.heroTimer<=0){c.heroTimer=r.attackRate;basicHeroAttack()}
 c.petTimer-=dt;if(c.petTimer<=0){let p=petStats();c.petTimer=Math.max(.42,p.speed*(1-(r.petSpeed||0)));petAttack()}
 if(state.activePet==='sprite'){c.petHealTimer-=dt;if(c.petHealTimer<=0){c.petHealTimer=5.5;r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.07);floatText(W*.3,H*.39,'+HEAL','#96ffc0')}}
 if(c.enemyStun<=0){if(c.telegraph>0){c.telegraph-=dt;if(c.telegraph<=0)enemyAttack(true)}else{c.specialTimer-=dt;if(c.specialTimer<=0){c.telegraph=c.boss?.95:1.15;c.specialTimer=(c.boss?5.2:7.4)+Math.random()*2;banner('⚠ HEAVY ATTACK INCOMING');tone(120,.13,'sawtooth')}}c.enemyTimer-=dt*(1-Math.min(.55,r.frost||0));if(c.enemyTimer<=0&&c.telegraph<=0){c.enemyTimer=e.rate;enemyAttack(false)}}
 if(c.boss&&!c.phase2&&c.enemyHp<c.enemyMax*.5){c.phase2=true;e.atk*=1.22;e.rate*=.82;c.specialTimer=1.6;banner('♛ BOSS ENRAGED');spawnBurst(W*.72,H*.55,'#ff836e',22);tone(95,.22,'sawtooth')}
 if(state.autoSkills){if(c.cooldowns.strike<=0)castSkill('strike');if(c.cooldowns.arc<=0&&Math.random()<.04)castSkill('arc');if(c.cooldowns.guard<=0&&r.hp/r.maxHp<.55)castSkill('guard');if(r.ultimate>=100)castSkill('ultimate')}
 if(c.enemyHp<=0)return combatWin();if(r.hp<=0)return combatLose()}
function combatWin(){if(!combat||!state.run)return;let c=combat,r=state.run,e=c.enemy,boss=c.boss,elite=c.elite;state.kills++;state.bestiary[e.id]=(state.bestiary[e.id]||0)+1;state.dailyClaimed[dateKey()+':battleNow']=(state.dailyClaimed[dateKey()+':battleNow']||0)+1;if(elite)state.elites++;if(boss)state.bosses++;state.pets[state.activePet].affinity++;let gold=Math.round(e.reward*(1+(r.treasure||0)*.5));gainGold(gold);r.goldRun+=gold;gainXp(boss?90*r.chapter:elite?45*r.chapter:24*r.chapter);if(elite){gainMaterial('ore',3+r.chapter);if(Math.random()<.35)gainMaterial('essence',1)}if(Math.random()<(.24+artifactLuck()+(elite?.16:0)+(boss?.45:0)))dropGear(boss?Math.min(5,2+r.chapter):undefined,undefined,true);if(boss){state.energy=Math.min(maxEnergy(),state.energy+5);gainMaterial('dust',4+r.chapter*2);if(Math.random()<.52)discoverArtifact();gainMaterial('essence',2+r.chapter)}let wasBoss=boss;r.inCombat=null;combat=null;sceneMode='board';tone(710,.08);setTimeout(()=>tone(920,.09),70);banner('VICTORY · +'+gold+' GOLD');if(r.synergies.includes('inferno'))spawnBurst(W*.7,H*.54,'#ff9b57',25);saveState();renderAll();if(wasBoss)setTimeout(completeRun,520);else setTimeout(chooseUpgrade,360)}
function combatLose(){if(!state.run)return;state.deaths++;state.run.inCombat=null;combat=null;sceneMode='board';let earned=Math.round(state.run.goldRun*.2);gainMaterial('ore',2);state.run=null;buildBoard();saveState();renderAll();lootPop('☠️','Expedition Failed',`You keep all permanent loot.\nConsolation: +2 Ore${earned?' · Run gold already banked':''}`);tone(100,.25,'sawtooth')}
function discoverArtifact(){let locked=artifactDefs.filter(a=>(state.artifacts[a.id]||0)===0),a=locked.length?locked[Math.floor(Math.random()*locked.length)]:artifactDefs[Math.floor(Math.random()*artifactDefs.length)];state.artifacts[a.id]=(state.artifacts[a.id]||0)+1;lootPop(a.ico,'Artifact Discovered',a.name+' · Lv '+state.artifacts[a.id])}
function completeRun(){let r=state.run;if(!r)return;let ch=r.chapter;state.wins++;state.chapterWins[ch]=(state.chapterWins[ch]||0)+1;let first=!state.claimedChapters[ch],bonusGold=350*ch,bonusGems=8*ch;gainGold(bonusGold);state.gems+=bonusGems;state.energy=Math.min(maxEnergy(),state.energy+5);if(first){state.claimedChapters[ch]=true;state.talentPoints+=2;if(ch<4)state.unlockedChapter=Math.max(state.unlockedChapter,ch+1)}gainMaterial('treats',3+ch);let msg=`+${bonusGold} Gold · +${bonusGems} Gems · +5 Energy\n+${3+ch} Pet Treats`;if(first)msg+='\nFIRST CLEAR: +2 Talent Points'+(ch<4?' · Chapter '+(ch+1)+' unlocked':'');state.run=null;combat=null;sceneMode='board';buildBoard();saveState();renderAll();lootPop('🏆',chapters[ch].name+' Cleared!',msg);tone(720,.12);setTimeout(()=>tone(950,.14),130)}
function claimDaily(){let today=dateKey();if(state.lastDaily===today)return toast('Daily supply already claimed.');state.lastDaily=today;state.dailyStreak=(state.dailyStreak||0)+1;let energy=12,gold=500+state.dailyStreak*25,gems=5+Math.min(10,state.dailyStreak);state.energy=Math.min(maxEnergy(),state.energy+energy);gainGold(gold);state.gems+=gems;gainMaterial('ore',8);gainMaterial('treats',4);lootPop('🎁','Daily Supply',`+${energy} Energy · +${gold} Gold · +${gems} Gems\n+8 Ore · +4 Pet Treats · Streak ${state.dailyStreak}`);saveState();renderAll()}
function claimPatrol(){let h=patrolHours();if(h<.03)return toast('Patrol is still gathering supplies.');let chapter=state.unlockedChapter,gold=Math.floor(h*180*chapter),xp=Math.floor(h*42*chapter),ore=Math.max(1,Math.floor(h*3.5));gainGold(gold);gainXp(xp);gainMaterial('ore',ore);if(h>=3&&Math.random()<.55)dropGear(Math.min(3,chapter-1),undefined,true);state.patrolLast=Date.now();lootPop('🏕️','Patrol Returned',`${h.toFixed(1)} hours\n+${gold} Gold · +${xp} XP · +${ore} Ore`);saveState();renderAll()}
function claimWell(){regenEnergy();let left=ENERGY_WELL_MS-(Date.now()-(state.lastEnergyWell||0));if(left>0)return toast('Energy Well is still recharging.');if(state.energy>=maxEnergy())return toast('Energy is already full.');state.lastEnergyWell=Date.now();state.energy=Math.min(maxEnergy(),state.energy+8);tone(620,.1);lootPop('💧','Energy Well','+8 Energy');saveState();renderAll()}
function buyEnergy(){if(state.gems<5)return toast('Need 5 gems.');if(state.energy>=maxEnergy())return toast('Energy is already full.');state.gems-=5;state.energy=Math.min(maxEnergy(),state.energy+10);lootPop('⚡','Energy Restored','5 Gems → +10 Energy');saveState();renderAll()}
function upgradeEnergyTalent(){if(state.talentPoints<1||(state.talents.energy||0)>=10)return;state.talentPoints--;state.talents.energy++;state.energy=Math.min(maxEnergy(),state.energy+4);lootPop('⚡','Endurance Increased','Maximum Energy +4');saveState();renderAll();renderTalents()}
function openModal(id){let e=$('#'+id);if(e)e.classList.add('show')}
