/* Rogue Quest hero, pets, gear, quests, achievements, and kingdom progression */
'use strict';
function heroBase(){let c=classDefs[state.heroClass]||classDefs.knight,lv=state.level-1;let hp=(245+lv*19)*c.hp,atk=(35+lv*3.6)*c.atk,def=(8+lv*.72)*c.def,crit=.08+c.crit,rate=.76*c.rate;
 hp*=1+(state.talents.vitality||0)*.05+(state.artifacts.heartroot||0)*.04;atk*=1+(state.talents.might||0)*.04+(state.artifacts.sunstone||0)*.03;def*=1+(state.talents.guard||0)*.03+(state.artifacts.aegis||0)*.03;rate*=Math.max(.55,1-(state.talents.swift||0)*.025-(state.artifacts.hourglass||0)*.02);
 for(const id of Object.values(state.equipped)){let g=state.gear.find(x=>x.id===id);if(!g)continue;let val=g.value*(1+(g.level-1)*.12);if(g.stat==='ATK')atk+=val;if(g.stat==='HP')hp+=val;if(g.stat==='DEF')def+=val;if(g.stat==='CRIT')crit+=val/100;if(g.subStat==='ATK')atk+=g.subValue||0;if(g.subStat==='HP')hp+=g.subValue||0;if(g.subStat==='DEF')def+=g.subValue||0;if(g.subStat==='CRIT')crit+=(g.subValue||0)/100}
 return{hp:Math.round(hp),atk:Math.round(atk),def:Math.round(def),crit:clamp(crit,0,.75),rate}}
function petStats(){let p=petDefs.find(x=>x.id===state.activePet)||petDefs[0],ps=state.pets[p.id]||{level:1,evo:0,affinity:0};return{...p,atk:(p.atk+(ps.level-1)*2.2)*(1+ps.evo*.25),speed:1.12*(1-ps.evo*.04),level:ps.level,evo:ps.evo,affinity:ps.affinity}}
function powerScore(){let h=heroBase(),p=petStats();return Math.round(h.atk*3.3+h.hp*.24+h.def*8.5+h.crit*180+p.atk*4.2+Object.values(state.artifacts).reduce((a,b)=>a+b,0)*25)}
function xpNeed(l=state.level){return 90+l*32+Math.floor(l*l*.7)}
function gainXp(n){state.xp+=n;let leveled=false;while(state.level<99&&state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.talentPoints++;state.energy=Math.min(maxEnergy(),state.energy+3);leveled=true;tone(760,.12);setTimeout(()=>tone(980,.14),100)}if(leveled)lootPop('⬆️','LEVEL UP!','Level '+state.level+'\n+1 Talent Point · +3 Energy')}
function gainGold(n){n=Math.max(0,Math.round(n));state.gold+=n;state.totalGoldEarned+=n}
function gainMaterial(k,n){state.materials[k]=(state.materials[k]||0)+n}
function applySettings(){document.body.classList.toggle('reduce-motion',!state.motion);document.body.classList.toggle('mode3d',state.depth);$('#soundToggle').classList.toggle('on',state.sound);$('#motionToggle').classList.toggle('on',state.motion);$('#depthToggle').classList.toggle('on',state.depth);$('#autoSkillToggle').classList.toggle('on',state.autoSkills);document.documentElement.lang=state.lang;$('#languageSelect').value=state.lang}
function renderTop(){regenEnergy();let cap=maxEnergy();$('#energyTxt').textContent=Math.floor(state.energy);$('#goldTxt').textContent=fmt(state.gold);$('#gemsTxt').textContent=fmt(state.gems);$('#levelTxt').textContent=state.level;$('#xpTxt').textContent=`${Math.floor(state.xp)} / ${xpNeed()} XP`;$('#xpFill').style.width=`${clamp(state.xp/xpNeed()*100,0,100)}%`;$('#powerTxt').textContent=fmt(powerScore());$('#app').style.setProperty('--heroHue',state.heroHue);let c=chapters[state.run?state.run.chapter:state.currentChapter];$('#chapterKicker').textContent=c.kicker;$('#chapterTitle').textContent=c.name;let pos=state.run?state.run.pos+1:(state.bestStages[state.currentChapter]||1);$('#stageTxt').textContent=`Stage ${state.run?state.run.chapter:state.currentChapter}-${pos}`;$('#chapterPrev').disabled=!!state.run||state.currentChapter<=1;$('#chapterNext').disabled=!!state.run||state.currentChapter>=state.unlockedChapter;$('#heroName').textContent=(classDefs[state.heroClass]||classDefs.knight).name;$('#energyCardText').textContent=`${Math.floor(state.energy)}/${cap} energy · +1 every 2 minutes.`}
function renderHero(){let h=heroBase(),c=classDefs[state.heroClass]||classDefs.knight;$('#heroHpStat').textContent=h.hp;$('#heroAtkStat').textContent=h.atk;$('#heroDefStat').textContent=Math.round(h.def);$('#heroCritStat').textContent=Math.round(h.crit*100)+'%';$('#classDesc').textContent=c.desc;$$('#classChoices .chip').forEach(b=>b.classList.toggle('selected',b.dataset.class===state.heroClass))}
function renderPets(){let el=$('#petGrid');el.innerHTML='';$('#treatsTxt').textContent=fmt(state.materials.treats);$('#essenceTxt').textContent=fmt(state.materials.essence);petDefs.forEach((p,i)=>{let ps=state.pets[p.id],active=state.activePet===p.id,unlocked=!!ps.unlocked,atk=Math.round((p.atk+(ps.level-1)*2.2)*(1+ps.evo*.25));let c=document.createElement('div');c.className='pet-card'+(active?' active':'');let evoName=['Base','Evolved','Ascended','Mythic'][ps.evo]||'Mythic';c.innerHTML=`<span class="rarity ${ps.evo>=2?'r-epic':ps.evo?'r-rare':'r-uncommon'}">${unlocked?'Lv '+ps.level:'LOCKED'}</span><div class="pet-art">${p.icon}</div><div class="pet-name">${p.name}</div><div class="pet-trait">${p.trait} · ATK ${atk} · ${evoName}</div><div class="pet-trait">${p.role}</div><div class="progress"><span style="width:${Math.min(100,(ps.affinity%50)/50*100)}%"></span></div><div class="pet-trait">Affinity ${ps.affinity}</div><div class="pet-actions"><button class="primary pet-main" type="button">${!unlocked?'UNLOCK '+p.unlock+'●':active?'LEVEL '+(80*ps.level)+'●':'SELECT'}</button><button class="pet-evolve" type="button" ${!unlocked||ps.level<(ps.evo+1)*10||ps.evo>=3?'disabled':''}>EVOLVE</button></div>`;
 let main=c.querySelector('.pet-main');main.addEventListener('click',()=>{if(!ps.unlocked){if(state.gold<p.unlock)return toast('Need '+p.unlock+' gold');state.gold-=p.unlock;ps.unlocked=true;toast(p.name+' joined your party!')}else if(!active){state.activePet=p.id;toast(p.name+' is now active.')}else{let cost=80*ps.level;if(state.gold<cost)return toast('Need '+cost+' gold');if(state.materials.treats<2)return toast('Need 2 pet treats');state.gold-=cost;state.materials.treats-=2;ps.level++;tone(560,.08);toast(p.name+' reached Lv. '+ps.level)}saveState();renderAll()});
 c.querySelector('.pet-evolve').addEventListener('click',()=>{let needEss=5+ps.evo*5;if(ps.level<(ps.evo+1)*10)return;if(state.materials.essence<needEss)return toast('Need '+needEss+' essence');state.materials.essence-=needEss;ps.evo++;tone(700,.12);lootPop(p.icon,p.name+' Evolved!','Evolution '+ps.evo+' · +25% pet power');saveState();renderAll()});el.appendChild(c)})}
function gearPower(g){return Math.round(g.power*(1+(g.level-1)*.14))}
function renderGear(){let el=$('#gearGrid');el.innerHTML='';$('#oreTxt').textContent=fmt(state.materials.ore);$('#gearEssenceTxt').textContent=fmt(state.materials.essence);$('#inventoryTxt').textContent=state.gear.length;if(!state.gear.length){el.innerHTML='<div class="card" style="grid-column:1/-1;color:var(--muted);font-size:10px">Equipment drops from battles, elites, bosses, treasure and merchants.</div>';return}state.gear.slice().sort((a,b)=>gearPower(b)-gearPower(a)).forEach(g=>{let equipped=state.equipped[g.slot]===g.id,c=document.createElement('div');c.className='gear-card'+(equipped?' equipped':'');c.innerHTML=`<span class="rarity r-${g.rarity.c}">${g.rarity.n} · +${g.level-1}</span><div class="pet-art">${gearIcons[g.slot]}</div><div class="gear-name">${g.name}</div><div class="gear-stat">${g.slot} · ${g.stat} +${Math.round(g.value*(1+(g.level-1)*.12))}${g.stat==='CRIT'?'%':''}</div><div class="gear-stat">${g.subStat?g.subStat+' +'+g.subValue+(g.subStat==='CRIT'?'%':''):'Power '+gearPower(g)}</div><div class="gear-actions"><button class="primary equip" type="button" ${equipped?'disabled':''}>${equipped?'EQUIPPED':'EQUIP'}</button><button class="upgradeGear" type="button">UPGRADE</button></div><div class="gear-actions"><button class="salvageOne" type="button" ${equipped?'disabled':''}>SALVAGE</button><button class="lockGear" type="button">${g.locked?'🔒 LOCKED':'🔓 LOCK'}</button></div>`;
 c.querySelector('.equip').addEventListener('click',()=>{state.equipped[g.slot]=g.id;saveState();renderAll();toast('Equipped '+g.name)});c.querySelector('.upgradeGear').addEventListener('click',()=>upgradeGear(g.id));c.querySelector('.salvageOne').addEventListener('click',()=>salvageGear(g.id));c.querySelector('.lockGear').addEventListener('click',()=>{g.locked=!g.locked;saveState();renderGear()});el.appendChild(c)})}
function upgradeGear(id){let g=state.gear.find(x=>x.id===id);if(!g)return;let gold=100*g.level*(g.rarity.m||1),ore=Math.ceil(3*g.level*(g.rarity.m||1));if(state.gold<gold)return toast('Need '+Math.ceil(gold)+' gold');if(state.materials.ore<ore)return toast('Need '+ore+' ore');state.gold-=Math.ceil(gold);state.materials.ore-=ore;g.level++;tone(610,.08);saveState();renderAll();toast(g.name+' upgraded to +'+(g.level-1))}
function salvageGear(id){let g=state.gear.find(x=>x.id===id);if(!g||g.locked||state.equipped[g.slot]===id)return;let idx=state.gear.findIndex(x=>x.id===id);state.gear.splice(idx,1);let ore=2+rarities.findIndex(r=>r.c===g.rarity.c)*3;gainMaterial('ore',ore);if(rarities.findIndex(r=>r.c===g.rarity.c)>=3)gainMaterial('essence',1);saveState();renderAll();toast('Salvaged · +'+ore+' ore')}
function autoEquip(){gearSlots.forEach(slot=>{let best=state.gear.filter(g=>g.slot===slot).sort((a,b)=>gearPower(b)-gearPower(a))[0];if(best)state.equipped[slot]=best.id});saveState();renderAll();toast('Best gear equipped.')}
function mergeGear(){for(let tier=0;tier<rarities.length-1;tier++){for(const slot of gearSlots){let pool=state.gear.filter(g=>g.slot===slot&&g.rarity.c===rarities[tier].c&&!g.locked&&state.equipped[slot]!==g.id);if(pool.length>=3){let used=pool.slice(0,3);state.gear=state.gear.filter(g=>!used.some(u=>u.id===g.id));dropGear(tier+1,slot,true);saveState();renderAll();lootPop('⚒️','Forge Success',`${rarities[tier+1].n} ${slot} created!`);return}}}toast('Need 3 unequipped items of the same slot and rarity.')}
function salvageCommon(){let ids=state.gear.filter(g=>['common','uncommon'].includes(g.rarity.c)&&!g.locked&&state.equipped[g.slot]!==g.id).map(g=>g.id);if(!ids.length)return toast('No unlocked Common/Uncommon gear to salvage.');let ore=0;state.gear=state.gear.filter(g=>{if(ids.includes(g.id)){ore+=g.rarity.c==='uncommon'?4:2;return false}return true});gainMaterial('ore',ore);saveState();renderAll();toast('Salvaged '+ids.length+' items · +'+ore+' ore')}
function renderTalents(){let el=$('#talentList');el.innerHTML='';$('#talentPointsTxt').textContent=state.talentPoints;talentDefs.forEach(t=>{let lv=state.talents[t.id]||0,d=document.createElement('div');d.className='talent-row';d.innerHTML=`<div class="talent-ico">${t.ico}</div><div><b>${t.name} · ${lv}/${t.max}</b><small>${t.desc}</small></div><button type="button" ${lv>=t.max||state.talentPoints<1?'disabled':''}>+ RANK</button>`;d.querySelector('button').addEventListener('click',()=>{if(state.talentPoints<1||state.talents[t.id]>=t.max)return;state.talentPoints--;state.talents[t.id]++;if(t.id==='energy')state.energy=Math.min(maxEnergy(),state.energy+4);saveState();renderAll();renderTalents();tone(530,.07)});el.appendChild(d)})}
function renderArtifacts(){let el=$('#artifactList');el.innerHTML='';$('#dustTxt').textContent=fmt(state.materials.dust);artifactDefs.forEach(a=>{let lv=state.artifacts[a.id]||0,cost=10+lv*8,d=document.createElement('div');d.className='artifact-row';d.innerHTML=`<div class="artifact-ico">${a.ico}</div><div><b>${a.name} · Lv ${lv}</b><small>${lv? a.desc:'Undiscovered · defeat bosses to find this relic.'}</small></div><button type="button" ${!lv||state.materials.dust<cost?'disabled':''}>${lv?'UP '+cost:'LOCKED'}</button>`;d.querySelector('button').addEventListener('click',()=>{if(!lv||state.materials.dust<cost)return;state.materials.dust-=cost;state.artifacts[a.id]++;saveState();renderAll();renderArtifacts();tone(720,.09)});el.appendChild(d)})}
function dailyDefs(){return[
 {id:'dailyBattle',ico:'⚔️',name:'Battle Warmup',desc:'Win 8 battles today',now:state.dailyClaimed[dateKey()+':battleNow']||0,max:8,reward:['energy',6]},
 {id:'dailySkills',ico:'✨',name:'Hands On',desc:'Cast 12 active skills today',now:state.dailyClaimed[dateKey()+':skillNow']||0,max:12,reward:['gems',12]},
 {id:'dailyTreasure',ico:'🎁',name:'Treasure Trail',desc:'Open 3 treasure nodes today',now:state.dailyClaimed[dateKey()+':chestNow']||0,max:3,reward:['ore',12]}
]}
function questDefs(){return[
 {id:'roll20',ico:'🎲',name:'Fate Walker',desc:'Roll dice 20 times',now:state.rolls,max:20,reward:['gold',650]},
 {id:'kill50',ico:'⚔️',name:'Monster Hunter',desc:'Defeat 50 enemies',now:state.kills,max:50,reward:['gems',35]},
 {id:'elite10',ico:'💀',name:'Elite Breaker',desc:'Defeat 10 elites',now:state.elites,max:10,reward:['essence',8]},
 {id:'boss4',ico:'♛',name:'Crown Breaker',desc:'Defeat 4 bosses',now:state.bosses,max:4,reward:['talent',2]},
 {id:'skills40',ico:'✨',name:'Combatant',desc:'Cast 40 active skills',now:state.skillsUsed,max:40,reward:['energy',12]},
 {id:'gear20',ico:'🎒',name:'Collector',desc:'Find 20 pieces of gear',now:state.gearFound,max:20,reward:['ore',25]},
 {id:'event10',ico:'❓',name:'Curious Soul',desc:'Resolve 10 events',now:state.events,max:10,reward:['gems',25]}
]}
function achievementDefs(){let hasMythic=state.gear.some(g=>g.rarity.c==='mythic');return[
 {id:'firstBlood',ico:'🩸',name:'First Blood',desc:'Defeat your first enemy.',now:state.kills,max:1,reward:10},
 {id:'combo25',ico:'🔥',name:'Unbroken',desc:'Reach a 25-hit combo.',now:state.maxCombo,max:25,reward:20},
 {id:'level10',ico:'⬆️',name:'Ascendant',desc:'Reach level 10.',now:state.level,max:10,reward:30},
 {id:'boss10',ico:'🐉',name:'Boss Hunter',desc:'Defeat 10 bosses.',now:state.bosses,max:10,reward:45},
 {id:'mythic',ico:'🌈',name:'Mythic Find',desc:'Own a Mythic item.',now:hasMythic?1:0,max:1,reward:55},
 {id:'chapter4',ico:'🏰',name:'Into the Void',desc:'Unlock Chapter 4.',now:state.unlockedChapter>=4?1:0,max:1,reward:75}
]}
function giveReward(r){let[k,n]=r;if(k==='gold')gainGold(n);if(k==='gems')state.gems+=n;if(k==='energy')state.energy=Math.min(maxEnergy(),state.energy+n);if(k==='ore')gainMaterial('ore',n);if(k==='essence')gainMaterial('essence',n);if(k==='treats')gainMaterial('treats',n);if(k==='dust')gainMaterial('dust',n);if(k==='talent')state.talentPoints+=n}
function renderQuestRows(defs,elId,prefix){let el=$(elId);el.innerHTML='';defs.forEach(q=>{let key=prefix+q.id,claimed=!!state.claimed[key],done=q.now>=q.max,d=document.createElement('div');d.className='list-row';d.innerHTML=`<div class="list-icon">${q.ico}</div><div class="list-copy"><div class="list-title">${q.name}</div><div class="list-desc">${q.desc} · ${Math.min(q.now,q.max)}/${q.max}</div><div class="progress"><span style="width:${Math.min(100,q.now/q.max*100)}%"></span></div></div><button type="button" ${!done||claimed?'disabled':''}>${claimed?'DONE':'CLAIM'}</button>`;d.querySelector('button').addEventListener('click',()=>{if(!done||claimed)return;giveReward(q.reward);state.claimed[key]=true;saveState();renderAll();renderQuests();lootPop(q.ico,'Quest Complete',rewardText(q.reward))});el.appendChild(d)})}
function rewardText(r){let[k,n]=r;let names={gold:'Gold',gems:'Gems',energy:'Energy',ore:'Ore',essence:'Essence',treats:'Treats',dust:'Artifact Dust',talent:'Talent Points'};return'+'+n+' '+(names[k]||k)}
function renderQuests(){renderQuestRows(dailyDefs(),'#dailyQuestList','D:'+dateKey()+':');renderQuestRows(questDefs(),'#questList','Q:');let qDone=questDefs().filter(q=>q.now>=q.max&&!state.claimed['Q:'+q.id]).length+dailyDefs().filter(q=>q.now>=q.max&&!state.claimed['D:'+dateKey()+':'+q.id]).length;$('#questCardText').textContent=qDone?`${qDone} reward${qDone>1?'s':''} ready to claim.`:'Complete objectives for energy, gems and materials.'}
function renderAchievements(){let el=$('#achievementList');el.innerHTML='';let ready=0;achievementDefs().forEach(a=>{let key='A:'+a.id,claimed=!!state.claimed[key],done=a.now>=a.max;if(done&&!claimed)ready++;let d=document.createElement('div');d.className='list-row';d.innerHTML=`<div class="list-icon">${a.ico}</div><div class="list-copy"><div class="list-title">${a.name}</div><div class="list-desc">${a.desc} · Reward ${a.reward} ◆</div><div class="progress"><span style="width:${Math.min(100,a.now/a.max*100)}%"></span></div></div><button type="button" ${!done||claimed?'disabled':''}>${claimed?'DONE':'CLAIM'}</button>`;d.querySelector('button').addEventListener('click',()=>{if(!done||claimed)return;state.gems+=a.reward;state.claimed[key]=true;saveState();renderAll();renderAchievements();lootPop(a.ico,'Achievement!',`+${a.reward} Gems`)});el.appendChild(d)});$('#achievementCardText').textContent=ready?ready+' achievement reward ready.':'Long-term challenges with gem rewards.'}
function renderCodex(){let el=$('#codexList');el.innerHTML='';let seen=0;enemyDefs.forEach(e=>{let kills=state.bestiary[e.id]||0;if(kills)seen++;let d=document.createElement('div');d.className='list-row';d.innerHTML=`<div class="list-icon">${kills?e.icon:'❔'}</div><div class="list-copy"><div class="list-title">${kills?e.name:'Unknown Creature'} ${e.boss?'· BOSS':''}</div><div class="list-desc">Chapter ${e.chapter} · ${kills?kills+' defeated · HP '+e.hp+' · ATK '+e.atk:'Encounter this creature to reveal its entry.'}</div></div><span class="mini-badge">${kills?'×'+kills:'???'}</span>`;el.appendChild(d)});$('#codexCardText').textContent=`${seen}/${enemyDefs.length} creatures discovered.`}
function renderStats(){let stats=[['⚔️','Enemies',state.kills],['💀','Elites',state.elites],['♛','Bosses',state.bosses],['🎲','Dice rolls',state.rolls],['✨','Skills cast',state.skillsUsed],['🔥','Best combo',state.maxCombo],['💥','Damage',fmt(state.totalDamage)],['●','Gold earned',fmt(state.totalGoldEarned)],['🎒','Gear found',state.gearFound],['🏆','Runs cleared',state.wins],['☠️','Defeats',state.deaths],['⚡','Power',fmt(powerScore())]];$('#statsGrid').innerHTML=stats.map(s=>`<div class="stat-card"><span>${s[0]} ${s[1]}</span><b>${s[2]}</b></div>`).join('')}
function patrolHours(){return clamp((Date.now()-(state.patrolLast||Date.now()))/3600000,0,8)}
function renderKingdom(){let ph=patrolHours();$('#patrolCardText').textContent=ph<.03?'Patrol just departed. Rewards build for up to 8 hours.':`${ph.toFixed(1)}h of offline loot is waiting.`;$('#claimPatrolBtn').disabled=ph<.03;$('#talentCardText').textContent=`${state.talentPoints} unspent talent point${state.talentPoints===1?'':'s'}.`;let art=Object.values(state.artifacts).filter(x=>x>0).length;$('#artifactCardText').textContent=`${art}/${artifactDefs.length} relics discovered · ${state.materials.dust} dust.`;$('#dailyCardText').textContent=state.lastDaily===dateKey()?`Claimed today · streak ${state.dailyStreak}.`:'Free energy, gold and materials ready.';$('#dailyBtn').disabled=state.lastDaily===dateKey();renderQuests();renderAchievements();renderCodex();renderStats()}
function renderEnergy(){regenEnergy();let cap=maxEnergy();$('#energyNow').textContent=Math.floor(state.energy);$('#energyMax').textContent=cap;let remaining=state.energy>=cap?0:ENERGY_MS-((Date.now()-(state.lastEnergy||Date.now()))%ENERGY_MS);$('#energyTimer').textContent=state.energy>=cap?'Energy is full.':`Next +1 in ${Math.floor(remaining/60000)}:${String(Math.floor((remaining%60000)/1000)).padStart(2,'0')}`;let wellLeft=Math.max(0,ENERGY_WELL_MS-(Date.now()-(state.lastEnergyWell||0)));$('#wellBtn').disabled=wellLeft>0||state.energy>=cap;$('#wellSub').textContent=wellLeft>0?`Ready in ${Math.ceil(wellLeft/60000)} min`:'+8 energy';$('#gemEnergyBtn').disabled=state.gems<5||state.energy>=cap;$('#energyUpgradeSub').textContent=`Rank ${state.talents.energy||0}/10 · costs 1 talent point`;$('#energyUpgradeBtn').disabled=state.talentPoints<1||(state.talents.energy||0)>=10;$('#dailyEnergyBtn').disabled=state.lastDaily===dateKey()}
function renderRun(){let r=state.run;if(!r){$('#runHud').style.display='none';$('#skillTray').classList.remove('show');$('#runStatus').textContent='Ready for adventure.';$('#nodeTxt').textContent='0';$('#primaryBtn').disabled=false;$('#primaryBtn').textContent=`START ADVENTURE · ${RUN_COST} ⚡`;$('#fateBtn').disabled=true;$('#campBtn').disabled=true;return}$('#runHud').style.display='flex';$('#nodeTxt').textContent=r.pos+1;$('#hpTxt').textContent=`${Math.max(0,Math.ceil(r.hp))}/${Math.ceil(r.maxHp)}`;$('#hpFill').style.width=clamp(r.hp/r.maxHp*100,0,100)+'%';$('#shieldFill').style.width=clamp((r.shield||0)/r.maxHp*100,0,100)+'%';$('#ultFill').style.width=clamp(r.ultimate||0,0,100)+'%';$('#buffCount').textContent='✦'+r.upgrades.length;$('#comboTxt').textContent='×'+Math.floor(r.combo||0);$('#runStatus').textContent=combat?`Fighting ${combat.enemy.name}`:`${chapters[r.chapter].name} · ${nodeLabel(r.board[r.pos])}`;$('#skillTray').classList.toggle('show',!!combat);$('#primaryBtn').disabled=!!combat||rolling;$('#primaryBtn').textContent=combat?'BATTLE IN PROGRESS':rolling?'ROLLING…':'🎲 ROLL DICE';$('#fateBtn').disabled=!!combat||rolling||(r.focus||0)<=0;$('#fateBtn').textContent=`🎲 FATE DICE · ${r.focus||0}`;$('#campBtn').disabled=!!combat||r.hp>=r.maxHp||(r.camps||0)<=0;$('#campBtn').textContent=`🍖 FIELD CAMP · ${r.camps||0}`;renderSkillButtons()}
function renderSkillButtons(){if(!combat)return;$$('.skill').forEach(b=>{let k=b.dataset.skill,cd=k==='ultimate'?(state.run.ultimate>=100?0:100-state.run.ultimate):(combat.cooldowns[k]||0),ready=cd<=0;b.classList.toggle('ready',ready);let e=b.querySelector('.cd');if(k==='ultimate')e.textContent=ready?'':Math.floor(state.run.ultimate)+'%';else e.textContent=ready?'':cd.toFixed(1);e.style.display=ready?'none':'grid'})}
function renderAll(){renderTop();renderHero();renderPets();renderGear();renderTalents();renderArtifacts();renderKingdom();renderEnergy();renderRun();$('#speedBtn').textContent='⏩ '+state.battleSpeed+'× SPEED';applySettings()}
