/* Blockforge contracts, relics, achievements, daily rewards, and offline earnings */
'use strict';
function generateContracts(){const z=state.zone+1,types=[['blocks','Block Breaker',60+z*15,2],['coins','Coin Haul',Math.floor(zoneDef().coin*500*Math.pow(2.1,difficultyCycle())),3],['crits','Precision Work',18+z*2,2],['chests','Treasure Hunter',2+Math.floor(z/6),3],['layers','Deep Shift',2+Math.min(4,Math.floor(z/4)),2],['petAbilities','Pet Teamwork',3+Math.floor(z/7),2]];const pool=[...types].sort(()=>Math.random()-.5).slice(0,3);state.contracts=pool.map((a,i)=>({id:`${dayKey()}-${i}`,type:a[0],name:a[1],target:a[2],progress:0,rewardCoins:Math.floor(zoneDef().coin*120*(i+1)*Math.pow(2.2,difficultyCycle())),rewardGems:a[3],claimed:false}));state.contractDay=dayKey();}
function ensureContracts(force=false){if(force||state.contractDay!==dayKey()||!Array.isArray(state.contracts)||state.contracts.length!==3)generateContracts();}
function trackContract(type,amount=1){for(const c of state.contracts)if(!c.claimed&&c.type===type)c.progress=Math.min(c.target,c.progress+amount);}
function claimContract(id){const c=state.contracts.find(x=>x.id===id);if(!c||c.claimed||c.progress<c.target)return;c.claimed=true;state.coins+=c.rewardCoins;state.lifetimeCoins+=c.rewardCoins;state.gems+=c.rewardGems;toast(`Contract complete: +${fmt(c.rewardCoins)} coins, +${c.rewardGems} gems`);sfx('coin');saveState(true);renderContracts();updateUI();}

function rollRarity(min=0){const r=Math.random();let idx=r<.58?0:r<.84?1:r<.95?2:r<.992?3:4;return Math.max(min,idx);}
function dropRelic(minRarity=0,source='Mine'){if(state.relics.length>=30){state.gems+=2;toast('Relic inventory full · converted to +2 gems');return;}const ri=rollRarity(minRarity),rar=RARITIES[ri],heads=['Breaker','Fang','Comet','Drill','Crescent','Maul','Shard','Titan'],adjs=['Dustborn','Iron','Lucky','Void','Molten','Crystal','Ancient','Starforged'];const power=rar.power*(.8+Math.random()*.4),relic={id:'r'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),name:`${adjs[Math.floor(Math.random()*adjs.length)]} ${heads[Math.floor(Math.random()*heads.length)]}`,rarity:ri,damage:.025*power,coins:.018*power,speed:.008*power};state.relics.unshift(relic);if(!state.equippedRelic)state.equippedRelic=relic.id;toast(`${source} dropped a ${rar.name} relic: ${relic.name}`);sfx('chest');}
function salvageRelic(id){const i=state.relics.findIndex(r=>r.id===id);if(i<0)return;const r=state.relics[i],gain=1+(r.rarity||0);state.gems+=gain;state.relics.splice(i,1);if(state.equippedRelic===id)state.equippedRelic=null;toast(`Relic salvaged for ${gain} gems`);saveState(true);renderRelics();updateUI();}

function checkAchievements(){for(const a of ACHIEVEMENTS){if(!state.achievements.includes(a.id)&&a.test(state)){state.achievements.push(a.id);state.gems+=a.reward;toast(`Achievement: ${a.name} · +${a.reward} gems`);sfx('coin');}}}
function dailyAvailable(){return Date.now()-state.lastDaily>=20*60*60*1000;}
function claimDaily(){if(!dailyAvailable())return;const today=Math.floor(Date.now()/86400000);state.dailyStreak=(state.lastDailyDay===today-1)?state.dailyStreak+1:1;state.lastDailyDay=today;state.lastDaily=Date.now();const coins=Math.floor(zoneDef().coin*210*Math.pow(2.25,difficultyCycle())*Math.max(1,coinMult())),gems=2+Math.floor(state.dailyStreak/3);state.coins+=coins;state.lifetimeCoins+=coins;state.gems+=gems;state.treats+=1;toast(`Daily crate · ${fmt(coins)} coins, ${gems} gems, 1 treat`);sfx('coin');saveState(true);updateUI(true);}
function applyOfflineEarnings(ms){if(ms<60000)return;const capHours=8+state.mastery.offline*.4,hours=Math.min(ms/3600000,capHours),basePerHour=zoneDef().coin*700*Math.pow(2.1,difficultyCycle())*(1+state.upgrades.coins*.07)*(1+state.mastery.offline*.12);const reward=Math.floor(basePerHour*hours);if(reward>0){state.coins+=reward;state.lifetimeCoins+=reward;setTimeout(()=>toast(`Night Shift: +${fmt(reward)} coins from ${hours.toFixed(1)}h away`),650);}}
