/* Tide tackle calculations and fish presentation helpers */
'use strict';
function fishSvg(id,gene){let f=allDefs()[id]||fishDefs.silverfin,g=gene||{hue:0},extra='';if(id.includes('squid')||id==='giantsquid')extra='<path d="M40 49q-12 16-4 24M52 50q-4 17 4 25M64 50q6 14 12 21" fill="none" stroke="'+f.accent+'" stroke-width="4" stroke-linecap="round"/>';if(id.includes('ray')||id==='manta')extra+='<path d="M38 40Q72 5 108 40Q75 70 38 40Z" fill="'+f.c+'" opacity=".75"/>';if(id.includes('shark'))extra+='<path d="M73 18L87 0L91 22Z" fill="'+f.accent+'"/>';if(id.includes('marlin')||id==='swordfish')extra+='<path d="M108 39L139 34L108 43Z" fill="#dce6eb"/>';let hue=g.hue||0;return `<svg viewBox="0 0 140 80" aria-label="${f.name}" style="filter:hue-rotate(${hue}deg)"><ellipse cx="72" cy="40" rx="${Math.min(46,34+f.size*.12)}" ry="${Math.min(24,15+f.size*.1)}" fill="${f.c}"/><path d="M39 40L9 15L15 40L9 65Z" fill="${f.accent}"/><path d="M77 20L95 7L91 26Z" fill="${f.accent}"/><circle cx="99" cy="34" r="3.6" fill="#101720"/><circle cx="100" cy="33" r="1" fill="white"/>${extra}</svg>`}
function boatMiniSvg(hull,color){let scale={skiff:0,cutter:4,sloop:7,research:9,trawler:12,crown:15}[hull]||0;return `<svg viewBox="0 0 120 65"><path d="M10 40h${78+scale}l-${15+scale*.2} 15H27z" fill="${color}"/><path d="M49 10v31" stroke="#d8c9aa" stroke-width="4"/>${hull==='research'||hull==='trawler'||hull==='crown'?'<rect x="55" y="23" width="24" height="17" rx="3" fill="#d9e6e8"/><rect x="60" y="27" width="7" height="6" fill="#5a8195"/>':'<path d="M52 12l30 18H52z" fill="#eee4cf"/>'}</svg>`}
function gearIcon(slot){if(slot==='rod')return '╱';if(slot==='line')return '◌';if(slot==='reel')return '⊙';return '⌁'}

let fish=[],specials=[],particles=[],floaters=[],animT=0,lastFrame=performance.now(),spawnTimer=0,weatherFx=[],catchPending=null,specialPending=null;
let hook={mode:'idle',x:125,y:waterY-12,vx:0,vy:0,targetX:220,power:0,fish:null,tension:0,stamina:0,maxStamina:0,reeling:false,lure:'none',carry:null,fightTimer:0,burstTimer:0,burstText:'',pullX:0,pullY:0};
let powering=false,powerDir=1,sonar=false,screenShake=0;
function hookUnlocked(id){let h=hookDefs[id];return !!h&&rodTier()>=h.unlock}
function activeHookDef(){let id=hookDefs[state.selectedHook]?state.selectedHook:'standard';return hookDefs[id]}
function activeBaitDef(){return baitDefs[state.selectedBait||0]||baitDefs[0]}
function fishDepthProfile(f){if(f.min>=180||f.max>=500)return'deep';if(f.fight==='diver'||f.fight==='tank')return'bottom';return'shallow'}
function lureAffinity(l,f){if(!l||l.tag==='bare')return 1;if(l.tag==='treasure')return .42;let score=1;if((l.prefer||[]).includes(f.temper))score*=1.55;if((l.prefer||[]).includes('deep')&&fishDepthProfile(f)==='deep')score*=1.48;if(l.tag==='surface'&&fishDepthProfile(f)==='deep')score*=.72;if(l.tag==='predator'&&f.temper!=='hunter')score*=.78;return score}
function baitAffinity(b,f){if(!b||!b.prefer||!b.prefer.length)return 1;let score=1;if(b.prefer.includes(f.temper))score*=1.6;if(b.prefer.includes(f.fight))score*=1.45;if(b.prefer.includes('deep')&&fishDepthProfile(f)==='deep')score*=1.45;if(b.prefer.includes('bottom')&&fishDepthProfile(f)==='bottom')score*=1.4;if(b.prefer.includes('rare')&&f.tier>=3)score*=1.55;return score}
function hookAffinity(h,f,hookId=state.selectedHook){if(!h)return 1;if(hookId==='fine')return f.tier<=2?1.35:.35;if(hookId==='large')return f.tier>=3?1.38:.78;if(hookId==='heavy')return f.tier>=4?1.55:.62;return 1}
function tackleAccessTier(){let l=lureDefs[state.selectedLure]||lureDefs.none,b=activeBaitDef(),h=activeHookDef();let presentation=Math.max(2,l.tier+2+(b.access||0),(state.selectedBait||0)+(b.access||0));return Math.max(1,Math.min(6,rodTier()+1,h.maxTier,presentation))}
function tackleMetrics(){let l=lureDefs[state.selectedLure]||lureDefs.none,b=activeBaitDef(),h=activeHookDef(),weather=state.weather.type==='rain'?1.18:state.weather.type==='storm'?1.08:1,c=oceanCycle(),ev=activeOceanEvent(),moment=c.twilight?1.12:c.night?.96:1,eventBite=ev?ev.bite:1;let bite=l.attract*b.bite*h.bite*weather*moment*eventBite;let biteLabel=bite>=2.3?'Excellent':bite>=1.65?'High':bite>=1.1?'Good':'Low';let target=l.target;if(state.selectedBait&&b.target!=='No bait bonus')target=l.tag==='bare'?b.target:(l.target+' + '+b.target);if(state.selectedHook==='heavy')target='Trophy / legendary';let treasure=Math.round((l.chest||0)*100),rareMulti=(b.rare||1)*(h.rare||1)*(ev?ev.rare:1)*chartLuckMultiplier(),rare=Math.max(0,Math.round((rareMulti-1)*100));return{l,b,h,bite,biteLabel,target,maxTier:tackleAccessTier(),treasure,rare}}
function depthToY(d){return waterY+(d/currentRegion().depth)*(H-waterY-22)}
function yToDepth(y){return clamp((y-waterY)/(H-waterY-22)*currentRegion().depth,0,currentRegion().depth)}
