/* Blockforge state validation, save, import, and export */
'use strict';
function sanitizeState(raw){const d=defaultState(),s={...d,...(raw||{})};s.upgrades={...d.upgrades,...(raw?.upgrades||{})};s.mastery={...d.mastery,...(raw?.mastery||{})};s.settings={...d.settings,...(raw?.settings||{})};s.character={...d.character,...(raw?.character||{})};if(!['en','es'].includes(s.settings.language))s.settings.language='en';if(!['detailed','subtle','off'].includes(s.settings.blockTexture))s.settings.blockTexture='detailed';if(!['2d','3d'].includes(s.settings.displayMode))s.settings.displayMode='2d';for(const k of ['body','style','head','face'])if(!CHARACTER_OPTIONS[k].some(x=>x[0]===s.character[k]))s.character[k]=d.character[k];for(const k of ['skin','outfit','accent'])if(!/^#[0-9a-f]{6}$/i.test(s.character[k]||''))s.character[k]=d.character[k];s.petData=defaultPetData();for(const p of PETS)s.petData[p.id]={...s.petData[p.id],...(raw?.petData?.[p.id]||{})};s.petsOwned=Array.isArray(s.petsOwned)?s.petsOwned.filter(x=>PETS.some(p=>p.id===x)):['mole'];if(!s.petsOwned.includes('mole'))s.petsOwned.unshift('mole');if(!PETS.some(p=>p.id===s.equippedPet)||!s.petsOwned.includes(s.equippedPet))s.equippedPet='mole';s.relics=Array.isArray(s.relics)?s.relics.slice(0,30).filter(r=>r&&r.id):[];if(!s.relics.some(r=>r.id===s.equippedRelic))s.equippedRelic=null;s.contracts=Array.isArray(s.contracts)?s.contracts:[];s.achievements=Array.isArray(s.achievements)?s.achievements:[];['coins','gems','treats','zone','row','totalBlocks','lifetimeCoins','totalCrits','chestsOpened','bossesDefeated','bestCombo','dashes','petAbilities','reforges','ancientCores','masteryPoints','lastDaily','lastDailyDay','dailyStreak','lastSaved'].forEach(k=>{s[k]=Number.isFinite(+s[k])?+s[k]:d[k];});for(const def of UPGRADE_DEFS)s.upgrades[def.id]=clamp(Math.floor(+s.upgrades[def.id]||0),0,def.id==='count'?MAX_PICKAXES-1:999999);for(const def of MASTERY_DEFS)s.mastery[def.id]=clamp(Math.floor(+s.mastery[def.id]||0),0,999999);s.zone=Math.max(0,Math.floor(s.zone));s.row=clamp(Math.floor(s.row),0,8);for(const p of PETS){const pd=s.petData[p.id];pd.level=Math.max(1,Math.floor(+pd.level||1));pd.xp=Math.max(0,+pd.xp||0);pd.affection=clamp(+pd.affection||0,0,100);pd.fed=Math.max(0,Math.floor(+pd.fed||0));}s.version=VERSION;return s;}
function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);return raw?sanitizeState(JSON.parse(raw)):defaultState();}catch(e){return defaultState();}}
function saveState(silent=false){state.worldSave=serializeWorld();state.lastSaved=Date.now();try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(!silent)toast(state.settings.language==='es'?'Progreso guardado':'Progress saved');if(els.saveStatus)els.saveStatus.textContent=(state.settings.language==='es'?'Guardado local a las ':'Saved locally at ')+new Date(state.lastSaved).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){if(!silent)toast(state.settings.language==='es'?'No se pudo guardar localmente':'Could not save locally');}}
function exportSave(){saveState(true);const raw=btoa(unescape(encodeURIComponent(JSON.stringify(state)))),text='BFC4.'+raw;if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(text).then(()=>toast('Save copied to clipboard')).catch(()=>window.prompt('Copy this save code:',text));else window.prompt('Copy this save code:',text);}
function importSave(){const code=window.prompt('Paste your Blockforge save code:');if(!code)return;try{const body=code.trim().replace(/^BFC[1234]\./,'');state=sanitizeState(JSON.parse(decodeURIComponent(escape(atob(body)))));restoreWorldFromSave();ensureContracts(true);saveState(true);updateUI(true);renderAllModals();toast(state.settings.language==='es'?'Partida importada':'Save imported');}catch(e){toast(state.settings.language==='es'?'Ese código de partida no es válido':'That save code is invalid');}}

function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;els.toastStack.appendChild(d);setTimeout(()=>d.remove(),2700);}
