/* Blockforge grid generation and world serialization */
'use strict';
function chooseKind(){const m=world.modifier||MODIFIERS[0],roll=Math.random();let gem=.018+(m.gemBoost||0),gold=.055+(m.goldBoost||0),explosive=.045+(m.explosiveBoost||0),armor=.055+(m.armorBoost||0),chest=.012;if(roll<chest)return'chest';if(roll<chest+gem)return'gem';if(roll<chest+gem+gold)return'gold';if(roll<chest+gem+gold+explosive)return'explosive';if(roll<chest+gem+gold+explosive+armor)return'armor';return'normal';}
function buildGrid(){world.pendingLayerClear=false;world.modifier=rollModifier();const grid=[];for(let r=0;r<5;r++){const row=[];for(let c=0;c<10;c++){let hp=hpFor(r,c),kind=chooseKind();if(kind==='gem')hp*=1.45;if(kind==='gold')hp*=1.18;if(kind==='armor')hp*=1.7;if(kind==='chest')hp*=2.25;if(kind==='explosive')hp*=.8;row.push({hp,maxHp:hp,kind,dead:false,hit:0});}grid.push(row);}world.grid=grid;world.boss=null;world.hazard=null;world.heat=Math.min(world.heat,75);world.layerTransition=.55;spawnPlayer();petSay('hello');}
function resetWorld(){world.combo=1;world.comboTimer=0;world.heat=0;world.frenzyTimer=0;world.dashCooldown=0;world.petCooldown=0;world.petBlastTimer=0;world.petBoostTimer=0;world.petCritTimer=0;world.comboLockTimer=0;world.hazard=null;buildGrid();}
function aliveBlocks(){const out=[];for(let r=0;r<world.grid.length;r++)for(let c=0;c<world.grid[r].length;c++)if(!world.grid[r][c].dead)out.push({b:world.grid[r][c],r,c});return out;}
function gridClear(){return world.grid.length===5&&world.grid.every(row=>row.every(b=>b.dead));}

function serializeWorld(){const g=gridGeom(),pb=playerBounds();return{grid:world.grid.map(row=>row.map(b=>({hp:b.hp,maxHp:b.maxHp,kind:b.kind,dead:!!b.dead}))),boss:world.boss?{hp:world.boss.hp,maxHp:world.boss.maxHp,variant:world.boss.variant}:null,player:{nx:clamp((world.player.x-pb.left)/Math.max(1,pb.right-pb.left),0,1),ny:clamp((world.player.y-pb.top)/Math.max(1,pb.bottom-pb.top),0,1)},heat:world.heat,combo:world.combo,frenzyTimer:world.frenzyTimer,petBoostTimer:world.petBoostTimer,petCritTimer:world.petCritTimer,comboLockTimer:world.comboLockTimer,modifier:world.modifier?.id||'normal',petCooldown:world.petCooldown,dashCooldown:world.dashCooldown};}
function restoreWorldFromSave(){const ws=state.worldSave;if(!ws||typeof ws!=='object'){buildGrid();return;}try{const source=Array.isArray(ws.grid)?ws.grid:(Array.isArray(ws.rows)?ws.rows:null);if(ws.boss&&Number.isFinite(+ws.boss.hp)){world.grid=[];world.boss={hp:Math.max(0,+ws.boss.hp),maxHp:Math.max(1,+ws.boss.maxHp),variant:ws.boss.variant||bossVariant(),hit:0};world.modifier=MODIFIERS.find(m=>m.id===ws.modifier)||MODIFIERS[0];spawnPlayer();}else if(source&&source.length===5&&source.every(r=>Array.isArray(r)&&r.length===10)){world.modifier=MODIFIERS.find(m=>m.id===ws.modifier)||MODIFIERS[0];world.grid=source.map(r=>r.map(b=>({hp:Math.max(0,+b.hp||0),maxHp:Math.max(1,+b.maxHp||1),kind:['normal','gold','gem','explosive','armor','chest'].includes(b.kind)?b.kind:'normal',dead:!!b.dead,hit:0})));world.boss=null;spawnPlayer();}else{buildGrid();return;}const pb=playerBounds();if(ws.player&&Number.isFinite(+ws.player.nx)){world.player.x=lerp(pb.left,pb.right,clamp(+ws.player.nx,0,1));world.player.y=lerp(pb.top,pb.bottom,clamp(+ws.player.ny,0,1));}else if(Number.isFinite(+ws.playerX)){world.player.x=lerp(pb.left,pb.right,clamp(+ws.playerX,0,1));}world.heat=clamp(+ws.heat||0,0,100);world.combo=clamp(+ws.combo||1,1,5);world.frenzyTimer=Math.max(0,+ws.frenzyTimer||0);world.petBoostTimer=Math.max(0,+ws.petBoostTimer||0);world.petCritTimer=Math.max(0,+ws.petCritTimer||0);world.comboLockTimer=Math.max(0,+ws.comboLockTimer||0);world.petCooldown=Math.max(0,+ws.petCooldown||0);world.dashCooldown=Math.max(0,+ws.dashCooldown||0);world.petPos.x=world.player.x-34;world.petPos.y=world.player.y+12;}catch(e){buildGrid();}}
