/* Blockforge mining, bosses, abilities, movement, and simulation */
'use strict';
function blockAtPoint(x,y){const g=gridGeom();if(x<g.left||x>g.left+g.width||y<g.top||y>g.bottom)return null;const c=clamp(Math.floor((x-g.left)/g.cellW),0,9),r=clamp(Math.floor((y-g.top)/g.cellH),0,4),b=world.grid[r]?.[c];if(!b||b.dead)return null;const q=blockRect(r,c);if(x>=q.x&&x<=q.x+q.w&&y>=q.y&&y<=q.y+q.h)return{b,r,c};return null;}
function circleHitsRect(x,y,rad,q){const nx=clamp(x,q.x,q.x+q.w),ny=clamp(y,q.y,q.y+q.h);return(x-nx)*(x-nx)+(y-ny)*(y-ny)<rad*rad;}
function collidingBlock(x,y,rad=12){for(let r=0;r<5;r++)for(let c=0;c<10;c++){const b=world.grid[r]?.[c];if(b&&!b.dead&&circleHitsRect(x,y,rad,blockRect(r,c)))return{b,r,c};}return null;}
function damageBlocksAround(x,y,rad,dmg,source='aoe'){for(let r=0;r<5;r++)for(let c=0;c<10;c++){const b=world.grid[r]?.[c];if(b&&!b.dead){const p=blockCenter(r,c);if(Math.hypot(p.x-x,p.y-y)<=rad)dealDamage(b,dmg,p.x,p.y,{r,c,source});}}}

function dealDamage(block,dmg,sx,sy,opt={}){if(!block||block.dead)return 0;const crit=Math.random()<critChance();let amount=dmg*(crit?3:1);if(block.kind==='armor'&&opt.source!=='dash')amount*=.64;block.hp-=amount;block.hit=.11;if(crit){state.totalCrits++;trackContract('crits',1);}spawnImpact(sx,sy,crit?7:4,crit);if(state.settings.damageNumbers)world.texts.push({x:sx,y:sy,text:(crit?'CRIT ':'')+fmt(amount),life:.68,max:.68,crit});sfx(crit?'crit':'hit');if(block.hp<=0){block.hp=0;block.dead=true;onBlockDestroyed(block,opt.r,opt.c,sx,sy,opt.source);}return amount;}
function onBlockDestroyed(block,r,c,x,y,source){const z=zoneDef();let reward=z.coin*Math.pow(2.25,difficultyCycle())*Math.pow(1.10,state.row)*coinMult();if(block.kind==='gold')reward*=8;if(block.kind==='gem'){state.gems++;reward*=2.5;toast('+1 gem crystal');}if(block.kind==='armor')reward*=1.8;if(block.kind==='explosive')reward*=1.35;if(block.kind==='chest')reward*=3.5;reward=Math.max(1,Math.floor(reward));state.coins+=reward;state.lifetimeCoins+=reward;state.totalBlocks++;trackContract('blocks',1);trackContract('coins',reward);world.combo=clamp(world.combo+.065,1,5);world.comboTimer=2.7;state.bestCombo=Math.max(state.bestCombo,world.combo);const comboReward=Math.floor(reward*(world.combo-1)*.15);state.coins+=comboReward;state.lifetimeCoins+=comboReward;world.heat=clamp(world.heat+3.2,0,100);if(state.settings.damageNumbers)world.texts.push({x,y:y-7,text:'+'+fmt(reward+comboReward)+' coins',life:.95,max:.95,coin:true});spawnBurst(x,y,block.kind==='chest'?22:11);if(block.kind==='explosive'&&Number.isInteger(r)&&Number.isInteger(c))explodeBlock(r,c,block.maxHp*.9);if(block.kind==='chest')openChest(x,y);addPetXp(block.kind==='chest'?3:1);sfx(block.kind==='chest'?'chest':block.kind==='gem'?'coin':'break');vibrate(block.kind==='chest'?34:12);if(Math.random()<.025)petSay('happy');checkAchievements();if(gridClear())world.pendingLayerClear=true;updateUI();}
function explodeBlock(r,c,dmg){spawnBurst(blockCenter(r,c).x,blockCenter(r,c).y,25);for(let rr=Math.max(0,r-1);rr<=Math.min(4,r+1);rr++)for(let cc=Math.max(0,c-1);cc<=Math.min(9,c+1);cc++){if(rr===r&&cc===c)continue;const b=world.grid[rr]?.[cc];if(b&&!b.dead){const p=blockCenter(rr,cc);dealDamage(b,dmg,p.x,p.y,{r:rr,c:cc,source:'explosion'});}}}
function openChest(x,y){state.chestsOpened++;trackContract('chests',1);const bonus=Math.floor(zoneDef().coin*85*Math.pow(2.25,difficultyCycle())*coinMult());state.coins+=bonus;state.lifetimeCoins+=bonus;const gems=1+(Math.random()<.28?1:0);state.gems+=gems;const treats=1+(Math.random()<.35?1:0);state.treats+=treats;toast(`Treasure chest: +${fmt(bonus)} coins, +${gems} gem, +${treats} treat`);petSay('chest');if(Math.random()<.16)dropRelic(0,'Chest');}
function completeLayer(){const bonus=Math.floor(zoneDef().coin*90*Math.pow(2.25,difficultyCycle())*coinMult());state.coins+=bonus;state.lifetimeCoins+=bonus;state.row++;trackContract('layers',1);world.rowFlash=.42;world.shockwaves.push({x:W*.5,y:gridGeom().bottom,r:18,life:.55,max:.55});toast(`Layer cleared · +${fmt(bonus)} coins`);if(state.row>=8)startBoss();else buildGrid();updateUI(true);saveState(true);}

function bossVariant(){return['Crusher','Shifter','Fortress','Reactor'][state.zone%4];}
function startBoss(){const z=zoneDef(),hp=z.baseHp*Math.pow(13,difficultyCycle())*Math.pow(1.24,8)*165;world.boss={hp,maxHp:hp,variant:bossVariant(),hit:0};world.grid=[];world.hazard=null;world.bossAttackTimer=2.7;spawnPlayer();els.bossBarWrap.style.display='block';toast(`${bossName(world.boss.variant).toUpperCase()} ${state.settings.language==='es'?'JEFE':'BOSS'}: ${zoneName(z).toUpperCase()}`);petSay('hurt');sfx('boss');vibrate(45);}
function bossWeakspot(t){const q=bossRect(),variant=world.boss?.variant||'Crusher',speed=variant==='Shifter'?2.2:1.15;return{x:q.x+q.w*.5+Math.sin(t*speed)*q.w*.31,y:q.y+q.h*.72+Math.cos(t*speed*.77)*q.h*.09,r:variant==='Fortress'?25:31};}
function damageBoss(dmg,x,y,t=performance.now()/1000){if(!world.boss)return;const w=bossWeakspot(t),weak=Math.hypot(x-w.x,y-w.y)<w.r;let mult=weak?3.2:(world.boss.variant==='Fortress'?.28:.52);if(pet().effect==='golem')mult*=1+passiveValue('golem');const crit=Math.random()<critChance(),amount=dmg*mult*(crit?3:1);world.boss.hp-=amount;world.boss.hit=.12;if(crit){state.totalCrits++;trackContract('crits',1);}spawnImpact(x,y,weak?10:4,crit||weak);if(state.settings.damageNumbers)world.texts.push({x,y,text:(weak?'WEAK ':'')+(crit?'CRIT ':'')+fmt(amount),life:.72,max:.72,crit:crit||weak});sfx(crit?'crit':'hit');if(world.boss.hp<=0)defeatBoss();}
function bossAttack(){if(!world.boss)return;const variant=world.boss.variant,r=variant==='Crusher'?64:variant==='Reactor'?54:48;world.hazard={x:variant==='Reactor'?gridGeom().left+Math.random()*gridGeom().width:world.player.x,y:variant==='Reactor'?lerp(gridGeom().bottom,H-150,Math.random()):world.player.y,r,t:.95,max:.95};world.bossAttackTimer=variant==='Shifter'?3.2:variant==='Crusher'?4.3:3.8;}
function resolveHazard(){if(!world.hazard)return;const h=world.hazard;if(Math.hypot(world.player.x-h.x,world.player.y-h.y)<h.r){world.combo=1;world.comboTimer=0;world.heat=Math.max(0,world.heat-28);world.stun=.42;petData().mood='Nervous';petSay('hurt');vibrate(55);toast('Boss slam! Combo and Frenzy charge lost.');}spawnBurst(h.x,h.y,22);world.shockwaves.push({x:h.x,y:h.y,r:12,life:.55,max:.55});world.hazard=null;}
function defeatBoss(){const reward=Math.floor(zoneDef().coin*480*Math.pow(2.25,difficultyCycle())*coinMult());state.coins+=reward;state.lifetimeCoins+=reward;state.gems+=4+Math.floor(state.zone/3);state.masteryPoints++;state.bossesDefeated++;trackContract('bosses',1);dropRelic(1,'Boss');state.zone++;state.row=0;world.boss=null;world.hazard=null;world.zoneIntro=2.1;world.combo=1;world.heat=0;buildGrid();spawnBurst(W*.5,H*.42,48);world.shockwaves.push({x:W*.5,y:H*.42,r:28,life:1,max:1});toast(`Zone conquered! +${fmt(reward)} coins · +1 Mastery Point`);sfx('coin');vibrate(70);checkAchievements();updateUI(true);saveState(true);}

function powerSwing(){unlockAudio();const dmg=miningDamage()*2.8;if(world.boss){const q=bossRect(),p={x:clamp(world.player.x,q.x,q.x+q.w),y:clamp(world.player.y,q.y,q.y+q.h)};damageBoss(dmg,p.x,p.y);}else{let nearest=null,dist=Infinity;for(const a of aliveBlocks()){const p=blockCenter(a.r,a.c),d=Math.hypot(p.x-world.player.x,p.y-world.player.y);if(d<dist&&d<orbitRadius()*1.45){nearest=a;dist=d;}}if(nearest){const p=blockCenter(nearest.r,nearest.c);dealDamage(nearest.b,dmg,p.x,p.y,{r:nearest.r,c:nearest.c,source:'power'});}else{world.texts.push({x:world.player.x,y:world.player.y-38,text:'SWING',life:.35,max:.35});}}world.shockwaves.push({x:world.player.x,y:world.player.y,r:15,life:.32,max:.32});vibrate(16);}
function activateDash(){if(world.dashCooldown>0||world.stun>0)return;let dx=pointer.down?pointer.dx:0,dy=pointer.down?pointer.dy:0;if(keys.left||keys.right||keys.up||keys.down){dx=(keys.right?1:0)-(keys.left?1:0);dy=(keys.down?1:0)-(keys.up?1:0);}let mag=Math.hypot(dx,dy);if(mag<.1){dx=0;dy=-1;mag=1;}world.dashDir={x:dx/mag,y:dy/mag};world.dashTimer=.30;world.dashCooldown=4;state.dashes++;sfx('dash');vibrate(22);updateUI();}
function activateFrenzy(){if(world.heat<100||world.frenzyTimer>0)return;world.heat=0;world.frenzyTimer=7.5*(1+state.mastery.frenzy*.04);world.cameraPulse=.6;toast('FRENZY! Faster movement, damage, and orbit speed.');sfx('frenzy');vibrate(40);petSay('happy');}
function petAbility(){if(world.petCooldown>0)return;const p=pet(),scale=petScale()*(1+state.mastery.companion*.05);world.petCooldown=p.cooldown;state.petAbilities++;trackContract('petAbilities',1);petSay('ability');sfx('pet');vibrate(28);if(p.id==='mole'){world.petBoostTimer=7*scale;toast('Tunnel Fever: damage and orbit speed boosted');}else if(p.id==='bot'){const gain=Math.floor(zoneDef().coin*160*Math.pow(2.25,difficultyCycle())*coinMult()*scale);state.coins+=gain;state.lifetimeCoins+=gain;trackContract('coins',gain);toast(`Profit Protocol: +${fmt(gain)} coins`);}else if(p.id==='wisp'){if(world.boss)damageBoss(miningDamage()*22*scale,bossRect().x+bossRect().w*.5,bossRect().y+bossRect().h*.7);else for(const a of [...aliveBlocks()]){const bp=blockCenter(a.r,a.c);dealDamage(a.b,miningDamage()*3.8*scale,bp.x,bp.y,{r:a.r,c:a.c,source:'pet'});}toast('Inferno scorched the chamber');}else if(p.id==='fox'){world.petCritTimer=9*scale;toast('Weakpoint Hunt: +25% critical chance');}else if(p.id==='slime'){world.combo=5;world.comboTimer=9;world.comboLockTimer=9*scale;toast('Sticky Streak: combo locked at 5×');}else if(p.id==='golem'){if(world.boss)damageBoss(miningDamage()*35*scale,bossRect().x+bossRect().w*.5,bossRect().y+bossRect().h*.7);else damageBlocksAround(world.player.x,world.player.y,orbitRadius()*3.3,miningDamage()*12*scale,'pet');world.shockwaves.push({x:world.player.x,y:world.player.y,r:24,life:.8,max:.8});toast('GROUND POUND');}saveState(true);updateUI();}
function petPassive(dt){if(pet().effect!=='blast')return;world.petBlastTimer-=dt;if(world.petBlastTimer>0)return;world.petBlastTimer=Math.max(2.1,pet().value/petScale());const dmg=miningDamage()*5.2;if(world.boss){const q=bossRect();damageBoss(dmg,q.x+q.w*.5,q.y+q.h*.72);}else{const living=aliveBlocks();if(living.length){const a=living[Math.floor(Math.random()*living.length)],p=blockCenter(a.r,a.c);dealDamage(a.b,dmg,p.x,p.y,{r:a.r,c:a.c,source:'pet'});spawnBurst(p.x,p.y,13);}}}

function movePlayer(dt){if(world.stun>0)return;let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);if(pointer.down&&(Math.abs(pointer.dx)>.04||Math.abs(pointer.dy)>.04)){dx=pointer.dx;dy=pointer.dy;}let mag=Math.hypot(dx,dy);if(world.dashTimer>0){dx=world.dashDir.x;dy=world.dashDir.y;mag=1;}if(mag<.05)return;dx/=mag;dy/=mag;const sp=moveSpeed()*(world.dashTimer>0?3.9:1),step=sp*dt,pb=playerBounds(),rad=11;let nx=clamp(world.player.x+dx*step,pb.left,pb.right),ny=world.player.y;if(!world.boss){let hit=collidingBlock(nx,ny,rad);if(hit&&world.dashTimer>0){const p=blockCenter(hit.r,hit.c);dealDamage(hit.b,miningDamage()*9,p.x,p.y,{r:hit.r,c:hit.c,source:'dash'});hit=collidingBlock(nx,ny,rad);}if(!hit)world.player.x=nx;}else world.player.x=nx;ny=clamp(world.player.y+dy*step,pb.top,pb.bottom);if(!world.boss){let hit=collidingBlock(world.player.x,ny,rad);if(hit&&world.dashTimer>0){const p=blockCenter(hit.r,hit.c);dealDamage(hit.b,miningDamage()*9,p.x,p.y,{r:hit.r,c:hit.c,source:'dash'});hit=collidingBlock(world.player.x,ny,rad);}if(!hit)world.player.y=ny;}else world.player.y=ny;if(world.dashTimer>0&&!state.settings.reducedMotion&&Math.random()<.55)world.particles.push({x:world.player.x,y:world.player.y,vx:-dx*50+(Math.random()-.5)*35,vy:-dy*50+(Math.random()-.5)*35,life:.28,max:.28,size:3,trail:true});}
function orbitMining(t){const interval=Math.max(.045,.11-state.upgrades.speed*.0018);for(;hitAccumulator>=interval;hitAccumulator-=interval){const total=pickaxeCount(),count=simulatedPickaxeCount(),virtualPower=total/count;for(let i=0;i<count;i++){const ang=t*orbitSpeed()+i*Math.PI*2/count,x=world.player.x+Math.cos(ang)*orbitRadius(),y=world.player.y+Math.sin(ang)*orbitRadius(),dmg=miningDamage()*virtualPower;if(world.boss){const q=bossRect();if(x>=q.x&&x<=q.x+q.w&&y>=q.y&&y<=q.y+q.h)damageBoss(dmg,x,y,t);}else{const h=blockAtPoint(x,y);if(h)dealDamage(h.b,dmg,x,y,{r:h.r,c:h.c,source:'orbit'});}}}}
function update(dt,t){if(world.stun>0)world.stun-=dt;world.dashCooldown=Math.max(0,world.dashCooldown-dt);world.dashTimer=Math.max(0,world.dashTimer-dt);world.petCooldown=Math.max(0,world.petCooldown-dt);world.frenzyTimer=Math.max(0,world.frenzyTimer-dt);world.petBoostTimer=Math.max(0,world.petBoostTimer-dt);world.petCritTimer=Math.max(0,world.petCritTimer-dt);world.comboLockTimer=Math.max(0,world.comboLockTimer-dt);if(world.comboLockTimer>0){world.combo=5;world.comboTimer=2;}else if(world.comboTimer>0)world.comboTimer-=dt;else{const decay=pet().effect==='combo'?(1-passiveValue('combo')):1;world.combo=lerp(world.combo,1,clamp(dt*2.2*decay,0,1));}if(world.rowFlash>0)world.rowFlash-=dt;if(world.zoneIntro>0)world.zoneIntro-=dt;if(world.layerTransition>0)world.layerTransition-=dt;if(world.cameraPulse>0)world.cameraPulse-=dt;movePlayer(dt);petPassive(dt);hitAccumulator+=dt;orbitMining(t);if(world.pendingLayerClear&&gridClear()){world.pendingLayerClear=false;completeLayer();}const follow=1-Math.pow(.0006,dt);world.petPos.x=lerp(world.petPos.x,world.player.x-30-Math.sin(t*2.7)*5,follow);world.petPos.y=lerp(world.petPos.y,world.player.y+15+Math.cos(t*3.1)*4,follow);if(world.petSpeech){world.petSpeech.life-=dt;if(world.petSpeech.life<=0)world.petSpeech=null;}else{world.petSpeechTimer-=dt;if(world.petSpeechTimer<=0){world.petSpeechTimer=8+Math.random()*10;if(Math.random()<.5)petSay('hello');}}if(world.boss){world.boss.hit=Math.max(0,world.boss.hit-dt);world.bossAttackTimer-=dt;if(world.bossAttackTimer<=0&&!world.hazard)bossAttack();if(world.hazard){world.hazard.t-=dt;if(world.hazard.t<=0)resolveHazard();}}for(const row of world.grid)for(const b of row)b.hit=Math.max(0,b.hit-dt);world.particles=world.particles.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(!p.trail)p.vy+=210*dt;return p.life>0;});world.texts=world.texts.filter(p=>{p.life-=dt;p.y-=26*dt;return p.life>0;});world.shockwaves=world.shockwaves.filter(s=>{s.life-=dt;s.r+=190*dt;return s.life>0;});}
