'use strict';
(() => {
  const SIZE=9,START_WALLS=10,dirs=[[-1,0],[1,0],[0,-1],[0,1]];
  const el=id=>document.getElementById(id),board=el('board'),cellsEl=el('cells'),wallsLayer=el('wallsLayer'),slotsLayer=el('slotsLayer'),toast=el('toast');
  let toastTimer=null,mode='move',orientation='H',historyStack=[],game;
  function freshGame(names){return{players:[{name:names?.[0]||'Player 1',row:8,col:4,goalRow:0,walls:START_WALLS},{name:names?.[1]||'Player 2',row:0,col:4,goalRow:8,walls:START_WALLS}],current:0,walls:[],moves:[],winner:null};}
  const snapshot=()=>JSON.stringify(game),inside=(r,c)=>r>=0&&r<SIZE&&c>=0&&c<SIZE;
  function edgeBlocked(r1,c1,r2,c2,walls=game.walls){if(Math.abs(r1-r2)+Math.abs(c1-c2)!==1)return true;if(r1===r2){const c=Math.min(c1,c2);return walls.some(w=>w.o==='V'&&w.c===c&&(r1===w.r||r1===w.r+1));}const r=Math.min(r1,r2);return walls.some(w=>w.o==='H'&&w.r===r&&(c1===w.c||c1===w.c+1));}
  function legalMoves(playerIndex=game.current){const me=game.players[playerIndex],other=game.players[1-playerIndex],out=[];const add=(r,c)=>{if(!out.some(p=>p.row===r&&p.col===c))out.push({row:r,col:c});};for(const[dr,dc]of dirs){const nr=me.row+dr,nc=me.col+dc;if(!inside(nr,nc)||edgeBlocked(me.row,me.col,nr,nc))continue;if(nr!==other.row||nc!==other.col){add(nr,nc);continue;}const jr=other.row+dr,jc=other.col+dc;if(inside(jr,jc)&&!edgeBlocked(other.row,other.col,jr,jc)){add(jr,jc);continue;}const perps=dr!==0?[[0,-1],[0,1]]:[[-1,0],[1,0]];for(const[pr,pc]of perps){const rr=other.row+pr,cc=other.col+pc;if(inside(rr,cc)&&!edgeBlocked(other.row,other.col,rr,cc))add(rr,cc);}}return out;}
  function wallCollision(candidate){for(const w of game.walls){if(candidate.o===w.o){if(candidate.o==='H'&&candidate.r===w.r&&Math.abs(candidate.c-w.c)<2)return'That wall would overlap another wall.';if(candidate.o==='V'&&candidate.c===w.c&&Math.abs(candidate.r-w.r)<2)return'That wall would overlap another wall.';}else if(candidate.r===w.r&&candidate.c===w.c)return'Walls cannot cross through each other.';}return null;}
  function hasPath(playerIndex,walls){const p=game.players[playerIndex],seen=Array.from({length:SIZE},()=>Array(SIZE).fill(false)),queue=[[p.row,p.col]];seen[p.row][p.col]=true;for(let i=0;i<queue.length;i++){const[r,c]=queue[i];if(r===p.goalRow)return true;for(const[dr,dc]of dirs){const nr=r+dr,nc=c+dc;if(!inside(nr,nc)||seen[nr][nc]||edgeBlocked(r,c,nr,nc,walls))continue;seen[nr][nc]=true;queue.push([nr,nc]);}}return false;}
  function validateWall(candidate){const p=game.players[game.current];if(game.winner!==null)return{ok:false,reason:'The game is already over.'};if(p.walls<=0)return{ok:false,reason:'You have no walls remaining.'};if(candidate.r<0||candidate.r>7||candidate.c<0||candidate.c>7)return{ok:false,reason:'That wall is outside the board.'};const collision=wallCollision(candidate);if(collision)return{ok:false,reason:collision};const testWalls=[...game.walls,candidate];if(!hasPath(0,testWalls)||!hasPath(1,testWalls))return{ok:false,reason:'A wall cannot completely block a player from reaching the far edge.'};return{ok:true,reason:''};}
  const coord=(r,c)=>String.fromCharCode(65+c)+(SIZE-r),wallCoord=w=>String.fromCharCode(65+w.c)+(SIZE-w.r-1)+' '+(w.o==='H'?'horizontal':'vertical');
  function commitAction(description){if(game.winner===null)game.current=1-game.current;game.moves.push(description);mode='move';render();}
  function moveTo(r,c){if(game.winner!==null||mode!=='move')return;const legal=legalMoves();if(!legal.some(p=>p.row===r&&p.col===c))return;historyStack.push(snapshot());const index=game.current,p=game.players[index];p.row=r;p.col=c;const desc={player:index,type:'move',text:'Moved to '+coord(r,c)};if(r===p.goalRow)game.winner=index;commitAction(desc);if(game.winner!==null)showWinner();}
  function placeWall(r,c,o){if(game.winner!==null||mode!=='wall')return;const candidate={r,c,o},check=validateWall(candidate);if(!check.ok){showToast(check.reason);renderSlots();return;}historyStack.push(snapshot());const index=game.current;game.walls.push(candidate);game.players[index].walls--;commitAction({player:index,type:'wall',text:'Wall at '+wallCoord(candidate)});}
  function undo(){if(!historyStack.length)return;game=JSON.parse(historyStack.pop());mode='move';render();el('winnerModal').classList.remove('show');showToast('Last action undone.');}
  function renderCells(){cellsEl.innerHTML='';const legal=game.winner===null&&mode==='move'?legalMoves():[];for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const b=document.createElement('button');b.type='button';b.className='cell';b.dataset.r=r;b.dataset.c=c;if(r===0)b.classList.add('goal-p1');if(r===8)b.classList.add('goal-p2');const isLegal=legal.some(p=>p.row===r&&p.col===c);if(isLegal)b.classList.add('legal');b.setAttribute('aria-label',isLegal?'Move to '+coord(r,c):'Square '+coord(r,c));if(isLegal)b.addEventListener('click',()=>moveTo(r,c));game.players.forEach((p,i)=>{if(p.row===r&&p.col===c){const piece=document.createElement('span');piece.className='piece p'+(i+1);piece.setAttribute('aria-hidden','true');b.appendChild(piece);}});cellsEl.appendChild(b);}}
  function wallStyle(node,w,interactive=false){if(w.o==='H'){node.classList.add('h');node.style.left=(w.c/9*100)+'%';node.style.top=((w.r+1)/9*100)+'%';node.style.width=(2/9*100)+'%';}else{node.classList.add('v');node.style.left=((w.c+1)/9*100)+'%';node.style.top=(w.r/9*100)+'%';node.style.height=(2/9*100)+'%';}if(interactive)node.setAttribute('aria-label','Place '+(w.o==='H'?'horizontal':'vertical')+' wall at '+wallCoord(w));}
  function renderWalls(){wallsLayer.innerHTML='';game.walls.forEach(w=>{const d=document.createElement('div');d.className='wall-piece';wallStyle(d,w);wallsLayer.appendChild(d);});}
  function renderSlots(){slotsLayer.innerHTML='';board.classList.toggle('wall-mode',mode==='wall');if(mode!=='wall'||game.winner!==null)return;for(let r=0;r<8;r++)for(let c=0;c<8;c++){const candidate={r,c,o:orientation},check=validateWall(candidate),b=document.createElement('button');b.type='button';b.className='slot active'+(check.ok?'':' invalid');wallStyle(b,candidate,true);b.title=check.ok?'Place wall':check.reason;b.addEventListener('click',()=>placeWall(r,c,orientation));slotsLayer.appendChild(b);}}
  function renderSticks(){[[el('p1Sticks'),game.players[0].walls],[el('p2Sticks'),game.players[1].walls]].forEach(([wrap,left])=>{wrap.innerHTML='';for(let i=0;i<START_WALLS;i++){const s=document.createElement('i');s.className='stick'+(i>=left?' used':'');wrap.appendChild(s);}});el('p1Count').textContent=game.players[0].walls+' left';el('p2Count').textContent=game.players[1].walls+' left';}
  function renderHistory(){const wrap=el('history');wrap.innerHTML='';if(!game.moves.length){wrap.innerHTML='<div class="history-empty">No moves yet.</div>';return;}game.moves.forEach((m,i)=>{const row=document.createElement('div');row.className='history-row';const n=document.createElement('span');n.className='n';n.textContent=String(i+1).padStart(2,'0');const who=document.createElement('span');who.className='who';who.textContent=game.players[m.player].name;const desc=document.createElement('span');desc.className='desc';desc.textContent=m.text;row.append(n,who,desc);wrap.appendChild(row);});wrap.scrollTop=wrap.scrollHeight;}
  function render(){const p=game.players[game.current];el('p1NameTop').textContent=game.players[0].name;el('p2NameTop').textContent=game.players[1].name;el('p1NameWalls').textContent=game.players[0].name;el('p2NameWalls').textContent=game.players[1].name;el('p1Chip').classList.toggle('active',game.current===0&&game.winner===null);el('p2Chip').classList.toggle('active',game.current===1&&game.winner===null);el('turnText').textContent=game.winner!==null?'Game over':p.name+"'s turn";el('turnSub').textContent=game.winner!==null?'Winner decided':mode==='move'?'Move or choose a wall':'Choose a wall position';el('statusLine').textContent=game.winner!==null?game.players[game.winner].name+' wins':p.name+' to move';el('moveMode').classList.toggle('active',mode==='move');el('wallMode').classList.toggle('active',mode==='wall');el('orientation').classList.toggle('show',mode==='wall');el('horizontal').classList.toggle('active',orientation==='H');el('vertical').classList.toggle('active',orientation==='V');el('wallMode').disabled=game.winner!==null||p.walls===0;el('moveMode').disabled=game.winner!==null;el('undoBtn').disabled=!historyStack.length;renderCells();renderWalls();renderSlots();renderSticks();renderHistory();}
  function showToast(message){clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2200);}
  function setMode(next){if(game.winner!==null)return;if(next==='wall'&&game.players[game.current].walls<=0){showToast('No walls remaining.');return;}mode=next;render();}
  function newGame(){const names=game?game.players.map(p=>p.name):['Player 1','Player 2'];game=freshGame(names);historyStack=[];mode='move';orientation='H';render();el('winnerModal').classList.remove('show');showToast('New game started.');}
  function showWinner(){const p=game.players[game.winner];el('winnerTitle').textContent=p.name+' wins!';el('winnerText').textContent=p.name+' reached the opposite edge in '+game.moves.length+' actions.';el('winnerModal').classList.add('show');}
  function openNames(){el('p1Input').value=game.players[0].name;el('p2Input').value=game.players[1].name;el('namesModal').classList.add('show');setTimeout(()=>el('p1Input').focus(),0);}
  function saveNames(){const n1=el('p1Input').value.trim().slice(0,18)||'Player 1',n2=el('p2Input').value.trim().slice(0,18)||'Player 2';game.players[0].name=n1;game.players[1].name=n2;el('namesModal').classList.remove('show');render();}
  el('moveMode').addEventListener('click',()=>setMode('move'));el('wallMode').addEventListener('click',()=>setMode('wall'));el('horizontal').addEventListener('click',()=>{orientation='H';render();});el('vertical').addEventListener('click',()=>{orientation='V';render();});el('undoBtn').addEventListener('click',undo);el('newBtn').addEventListener('click',newGame);el('rulesBtn').addEventListener('click',()=>el('rulesModal').classList.add('show'));el('closeRules').addEventListener('click',()=>el('rulesModal').classList.remove('show'));el('namesBtn').addEventListener('click',openNames);el('cancelNames').addEventListener('click',()=>el('namesModal').classList.remove('show'));el('saveNames').addEventListener('click',saveNames);el('closeWinner').addEventListener('click',()=>el('winnerModal').classList.remove('show'));el('playAgain').addEventListener('click',newGame);[el('rulesModal'),el('namesModal')].forEach(modal=>modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){el('rulesModal').classList.remove('show');el('namesModal').classList.remove('show');el('winnerModal').classList.remove('show');}});
  game=freshGame();render();
})();