'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,TAU=Math.PI*2;
const RUN_COST=3,ENERGY_MS=120000,ENERGY_WELL_MS=1200000,MAX_INV=80; // V3: core play is free; energy powers bonus systems
const chapters={
 1:{name:'Whisperwood',kicker:'CHAPTER 1',sky:['#152d4e','#315b6a','#112337'],ground:'#173c32',accent:'#78e7a0',weather:'leaf',boss:'thornwyrm'},
 2:{name:'Embervault',kicker:'CHAPTER 2',sky:['#3a1823','#7a3623','#1d1420'],ground:'#42241e',accent:'#ff9d58',weather:'ember',boss:'cinderTitan'},
 3:{name:'Frostspire',kicker:'CHAPTER 3',sky:['#19324d','#5b7893','#16253a'],ground:'#23495a',accent:'#9aeaff',weather:'snow',boss:'moonfang'},
 4:{name:'Void Citadel',kicker:'CHAPTER 4',sky:['#180f35','#3d2364','#0b0a1c'],ground:'#241b3a',accent:'#c58cff',weather:'void',boss:'voidRegent'}
};
const classDefs={
 knight:{name:'Storm Knight',desc:'Balanced bruiser. +18% HP, +12% DEF, Guard lasts longer.',hp:1.18,atk:1,def:1.12,crit:0,rate:1,icon:'🛡️'},
 ranger:{name:'Gale Ranger',desc:'Fast striker. +18% attack speed, +7% crit, slightly lower HP.',hp:.92,atk:1.05,def:.94,crit:.07,rate:.82,icon:'🏹'},
 mystic:{name:'Aether Mystic',desc:'Spell fighter. +12% attack, +20% ultimate gain and stronger Arc Burst.',hp:1,atk:1.12,def:.98,crit:.03,rate:.95,icon:'🔮'}
};
const petDefs=[
 {id:'fox',name:'Emberfox',icon:'🦊',trait:'Aggressive',role:'Deals extra damage to wounded enemies.',unlock:0,atk:9},
 {id:'owl',name:'Moonwing',icon:'🦉',trait:'Curious',role:'Improves treasure and gear drop luck.',unlock:500,atk:7},
 {id:'golem',name:'Pebble',icon:'🪨',trait:'Protective',role:'Reduces incoming damage and adds shield.',unlock:1100,atk:6},
 {id:'wisp',name:'Nimbus',icon:'✨',trait:'Chaotic',role:'Random elemental bursts can stun enemies.',unlock:1800,atk:11},
 {id:'wolf',name:'Ashfang',icon:'🐺',trait:'Loyal',role:'Builds combo faster and attacks with you.',unlock:2800,atk:13},
 {id:'sprite',name:'Luma',icon:'🧚',trait:'Gentle',role:'Periodically heals you during combat.',unlock:4200,atk:8}
];
const gearSlots=['Weapon','Armor','Helm','Charm','Boots','Ring'];
const gearIcons={Weapon:'⚔️',Armor:'🛡️',Helm:'⛑️',Charm:'🔮',Boots:'🥾',Ring:'💍'};
const rarities=[
 {n:'Common',c:'common',m:1},{n:'Uncommon',c:'uncommon',m:1.3},{n:'Rare',c:'rare',m:1.7},{n:'Epic',c:'epic',m:2.25},{n:'Legendary',c:'legendary',m:3},{n:'Mythic',c:'mythic',m:4.1}
];
const talentDefs=[
 {id:'might',ico:'⚔️',name:'Might',desc:'+4% base attack per rank.',max:10},
 {id:'vitality',ico:'❤️',name:'Vitality',desc:'+5% base HP per rank.',max:10},
 {id:'guard',ico:'🛡️',name:'Fortitude',desc:'+3% defense per rank.',max:10},
 {id:'swift',ico:'💨',name:'Swiftness',desc:'+2.5% attack speed per rank.',max:10},
 {id:'luck',ico:'🍀',name:'Fortune',desc:'+3% loot luck per rank.',max:10},
 {id:'energy',ico:'⚡',name:'Endurance',desc:'+4 maximum energy per rank.',max:10}
];
const artifactDefs=[
 {id:'sunstone',ico:'☀️',name:'Sunstone',desc:'Attack +3% per level.'},
 {id:'heartroot',ico:'🌿',name:'Heartroot Idol',desc:'HP +4% per level.'},
 {id:'aegis',ico:'🛡️',name:'Aegis Fragment',desc:'Defense +3% per level.'},
 {id:'coin',ico:'🪙',name:'Fortune Coin',desc:'Loot luck +4% per level.'},
 {id:'hourglass',ico:'⌛',name:'Chronoglass',desc:'Attack speed +2% per level.'},
 {id:'lantern',ico:'🏮',name:'Everlight Lantern',desc:'Maximum energy +2 per level.'}
];
const enemyDefs=[
 {id:'mossSlime',chapter:1,name:'Moss Slime',kind:'slime',icon:'🟢',hp:100,atk:13,rate:1.35},
 {id:'nightBat',chapter:1,name:'Night Bat',kind:'bat',icon:'🦇',hp:82,atk:17,rate:1.05},
 {id:'briarWraith',chapter:1,name:'Briar Wraith',kind:'wraith',icon:'👻',hp:125,atk:19,rate:1.3},
 {id:'stonekin',chapter:1,name:'Stonekin',kind:'golem',icon:'🗿',hp:168,atk:22,rate:1.65},
 {id:'thornwyrm',chapter:1,name:'Thornwyrm',kind:'dragon',icon:'🐉',hp:460,atk:31,rate:1.2,boss:true},
 {id:'cinderImp',chapter:2,name:'Cinder Imp',kind:'imp',icon:'👹',hp:128,atk:25,rate:1.05},
 {id:'lavaCrawler',chapter:2,name:'Lava Crawler',kind:'spider',icon:'🕷️',hp:165,atk:23,rate:1.3},
 {id:'ashMage',chapter:2,name:'Ash Mage',kind:'mage',icon:'🧙',hp:145,atk:31,rate:1.45},
 {id:'magmaGolem',chapter:2,name:'Magma Golem',kind:'golem',icon:'🗿',hp:220,atk:30,rate:1.75},
 {id:'cinderTitan',chapter:2,name:'Cinder Titan',kind:'titan',icon:'🔥',hp:650,atk:43,rate:1.35,boss:true},
 {id:'frostWolf',chapter:3,name:'Frost Wolf',kind:'wolf',icon:'🐺',hp:205,atk:37,rate:1.05},
 {id:'iceWisp',chapter:3,name:'Ice Wisp',kind:'wraith',icon:'❄️',hp:172,atk:39,rate:1.25},
 {id:'glacierGuard',chapter:3,name:'Glacier Guard',kind:'golem',icon:'🧊',hp:270,atk:36,rate:1.65},
 {id:'snowStalker',chapter:3,name:'Snow Stalker',kind:'spider',icon:'🕷️',hp:190,atk:42,rate:1.15},
 {id:'moonfang',chapter:3,name:'Moonfang',kind:'wolfBoss',icon:'🐺',hp:860,atk:56,rate:1.05,boss:true},
 {id:'voidling',chapter:4,name:'Voidling',kind:'slime',icon:'🟣',hp:245,atk:52,rate:1.15},
 {id:'riftKnight',chapter:4,name:'Rift Knight',kind:'golem',icon:'♞',hp:330,atk:49,rate:1.5},
 {id:'nullMage',chapter:4,name:'Null Mage',kind:'mage',icon:'🧙',hp:260,atk:62,rate:1.35},
 {id:'abyssEye',chapter:4,name:'Abyss Eye',kind:'wraith',icon:'👁️',hp:285,atk:58,rate:1.2},
 {id:'voidRegent',chapter:4,name:'Void Regent',kind:'regent',icon:'♛',hp:1150,atk:74,rate:1.22,boss:true}
];
const upgradeDefs=[
 {id:'power',ico:'⚔️',name:'Brutal Edge',desc:'Attack damage increases.',tag:'OFFENSE'},
 {id:'speed',ico:'💨',name:'Quick Hands',desc:'Attack much faster.',tag:'OFFENSE'},
 {id:'crit',ico:'🎯',name:'Deadeye',desc:'Critical chance increases.',tag:'OFFENSE'},
 {id:'critDmg',ico:'💥',name:'Savage Criticals',desc:'Critical hits deal more damage.',tag:'OFFENSE'},
 {id:'multi',ico:'🗡️',name:'Echo Strike',desc:'Chance for a second basic attack.',tag:'OFFENSE'},
 {id:'execute',ico:'☠️',name:'Executioner',desc:'More damage to enemies below 30% HP.',tag:'OFFENSE'},
 {id:'combo',ico:'🔥',name:'Momentum',desc:'Combo builds faster and hits harder.',tag:'OFFENSE'},
 {id:'berserk',ico:'😈',name:'Last Stand',desc:'Low HP greatly increases damage.',tag:'OFFENSE'},
 {id:'vital',ico:'❤️',name:'Vitality',desc:'Increase max HP and heal immediately.',tag:'DEFENSE'},
 {id:'armor',ico:'🛡️',name:'Iron Skin',desc:'Increase defense.',tag:'DEFENSE'},
 {id:'dodge',ico:'🪽',name:'Phantom Step',desc:'Chance to completely dodge attacks.',tag:'DEFENSE'},
 {id:'thorns',ico:'🌵',name:'Thornmail',desc:'Reflect damage when struck.',tag:'DEFENSE'},
 {id:'shield',ico:'🔷',name:'Arcane Barrier',desc:'Begin each battle with a shield.',tag:'DEFENSE'},
 {id:'regen',ico:'🌿',name:'Renewal',desc:'Regenerate HP during combat.',tag:'RECOVERY'},
 {id:'lifesteal',ico:'🩸',name:'Blood Pact',desc:'Heal from damage dealt.',tag:'RECOVERY'},
 {id:'heal',ico:'🍀',name:'Second Wind',desc:'Heal a large amount now.',tag:'RECOVERY'},
 {id:'fire',ico:'🔥',name:'Flamebrand',desc:'Attacks inflict burning damage.',tag:'ELEMENT'},
 {id:'frost',ico:'❄️',name:'Frostbite',desc:'Slow enemy attack speed.',tag:'ELEMENT'},
 {id:'storm',ico:'⚡',name:'Chain Spark',desc:'Pet attacks gain lightning damage.',tag:'ELEMENT'},
 {id:'poison',ico:'☣️',name:'Venom Edge',desc:'Build poison damage over time.',tag:'ELEMENT'},
 {id:'shock',ico:'🌩️',name:'Static Field',desc:'Attacks can briefly stun.',tag:'ELEMENT'},
 {id:'bleed',ico:'🩸',name:'Serrated Edge',desc:'Critical hits cause bleeding.',tag:'ELEMENT'},
 {id:'petPower',ico:'🐾',name:'Pack Tactics',desc:'Pet damage increases sharply.',tag:'COMPANION'},
 {id:'petSpeed',ico:'🐾',name:'Feral Rhythm',desc:'Pet attacks more frequently.',tag:'COMPANION'},
 {id:'treasure',ico:'💰',name:'Treasure Sense',desc:'Gain more gold and better loot.',tag:'UTILITY'},
 {id:'elite',ico:'💀',name:'Giant Slayer',desc:'Deal more damage to elites and bosses.',tag:'UTILITY'},
 {id:'focus',ico:'🎲',name:'Fate Weaver',desc:'Gain one Fate Dice charge.',tag:'UTILITY'},
 {id:'skill',ico:'✨',name:'Battle Mage',desc:'Active skills cool down faster.',tag:'UTILITY'}
];
const rarityRolls=[{n:'Common',c:'common',mult:1,w:62},{n:'Rare',c:'rare',mult:1.45,w:28},{n:'Epic',c:'epic',mult:2.05,w:10}];
function emptyPets(){let o={};petDefs.forEach((p,i)=>o[p.id]={unlocked:i===0,level:1,evo:0,affinity:0});return o}
function emptyEquipped(){let o={};gearSlots.forEach(s=>o[s]=null);return o}
function emptyTalents(){let o={};talentDefs.forEach(x=>o[x.id]=0);return o}
function emptyArtifacts(){let o={};artifactDefs.forEach(x=>o[x.id]=0);return o}
function defaultState(){return{
 version:2,lang:'en',sound:true,motion:true,depth:true,autoSkills:false,battleSpeed:1.25,heroHue:210,heroClass:'knight',
 level:1,xp:0,gold:450,gems:60,energy:36,baseMaxEnergy:36,lastEnergy:Date.now(),lastEnergyWell:0,lastDaily:'',dailyStreak:0,
 currentChapter:1,unlockedChapter:1,bestStages:{1:1,2:1,3:1,4:1},chapterWins:{1:0,2:0,3:0,4:0},claimedChapters:{},
 kills:0,elites:0,bosses:0,battles:0,deaths:0,wins:0,rolls:0,chests:0,events:0,skillsUsed:0,maxCombo:0,totalDamage:0,totalGoldEarned:0,gearFound:0,
 activePet:'fox',pets:emptyPets(),gear:[],equipped:emptyEquipped(),materials:{ore:35,essence:8,treats:15,dust:0},talentPoints:3,talents:emptyTalents(),artifacts:emptyArtifacts(),bestiary:{},claimed:{},dailyClaimed:{},
 patrolLast:Date.now(),run:null
}}
function mergeObj(base,val){return Object.assign(base,val||{})}
function migrate(raw){let base=defaultState();if(!raw)return base;let s=Object.assign({},base,raw);s.version=2;let petBase=emptyPets();s.pets={};petDefs.forEach(p=>{s.pets[p.id]=Object.assign({},petBase[p.id],raw.pets&&raw.pets[p.id]||{})});s.equipped=Object.assign({},base.equipped,raw.equipped||{});s.materials=Object.assign({},base.materials,raw.materials||{});s.talents=Object.assign({},base.talents,raw.talents||{});s.artifacts=Object.assign({},base.artifacts,raw.artifacts||{});s.bestStages=Object.assign({},base.bestStages,raw.bestStages||{});s.chapterWins=Object.assign({},base.chapterWins,raw.chapterWins||{});s.claimed=raw.claimed||{};s.dailyClaimed=raw.dailyClaimed||{};s.bestiary=raw.bestiary||{};s.claimedChapters=raw.claimedChapters||{};s.gear=(Array.isArray(raw.gear)?raw.gear:[]).map(g=>Object.assign({level:1,locked:false,subStat:null,subValue:0,power:1},g));if(raw.maxEnergy&&!raw.baseMaxEnergy)s.baseMaxEnergy=Math.max(30,raw.maxEnergy);return s}
function loadState(){try{let raw=localStorage.getItem('rogueQuestSaveV2')||localStorage.getItem('rogueQuestSave');if(raw)return migrate(JSON.parse(raw))}catch(e){}return defaultState()}
let state=loadState();
let particles=[],floatTexts=[],projectiles=[],sceneMode='board',combat=null,boardNodes=[],rolling=false,toastTimer=null,saveMode='export',audioCtx=null,animT=0,lastFrame=performance.now(),shake=0,lastUiTick=0,lootTimer=null;
const fmt=n=>{n=Math.floor(Number(n)||0);return n>=1e6?(n/1e6).toFixed(1)+'M':n>=1e3?(n/1e3).toFixed(n>=1e4?0:1)+'K':String(n)};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function dateKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function maxEnergy(){return state.baseMaxEnergy+(state.talents.energy||0)*4+(state.artifacts.lantern||0)*2}
function saveState(){try{localStorage.setItem('rogueQuestSaveV2',JSON.stringify(state))}catch(e){}}
function regenEnergy(){let now=Date.now(),cap=maxEnergy();if(state.energy>=cap){state.energy=cap;state.lastEnergy=now;return}let last=state.lastEnergy||now,steps=Math.floor((now-last)/ENERGY_MS);if(steps>0){state.energy=Math.min(cap,state.energy+steps);state.lastEnergy=state.energy>=cap?now:last+steps*ENERGY_MS}}
function spendEnergy(n){regenEnergy();if(state.energy<n)return false;if(state.energy>=maxEnergy())state.lastEnergy=Date.now();state.energy-=n;saveState();return true}
function tone(freq=440,dur=.06,type='sine',gain=.032){if(!state.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function buzz(ms=18){try{if(navigator.vibrate)navigator.vibrate(ms)}catch(e){}}
function toast(msg){let e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1700)}
function banner(msg){let e=$('#banner');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),760)}
function lootPop(icon,title,desc){clearTimeout(lootTimer);$('#lootIcon').textContent=icon;$('#lootTitle').textContent=title;$('#lootDesc').textContent=desc;$('#lootPop').classList.add('show');lootTimer=setTimeout(()=>$('#lootPop').classList.remove('show'),1800)}
function artifactLuck(){return(state.artifacts.coin||0)*.04+(state.talents.luck||0)*.03+(state.activePet==='owl'?.08:0)}
function heroBase(){let c=classDefs[state.heroClass]||classDefs.knight,lv=state.level-1;let hp=(245+lv*19)*c.hp,atk=(35+lv*3.6)*c.atk,def=(8+lv*.72)*c.def,crit=.08+c.crit,rate=.76*c.rate;
 hp*=1+(state.talents.vitality||0)*.05+(state.artifacts.heartroot||0)*.04;atk*=1+(state.talents.might||0)*.04+(state.artifacts.sunstone||0)*.03;def*=1+(state.talents.guard||0)*.03+(state.artifacts.aegis||0)*.03;rate*=Math.max(.55,1-(state.talents.swift||0)*.025-(state.artifacts.hourglass||0)*.02);
 for(const id of Object.values(state.equipped)){let g=state.gear.find(x=>x.id===id);if(!g)continue;let val=g.value*(1+(g.level-1)*.12);if(g.stat==='ATK')atk+=val;if(g.stat==='HP')hp+=val;if(g.stat==='DEF')def+=val;if(g.stat==='CRIT')crit+=val/100;if(g.subStat==='ATK')atk+=g.subValue||0;if(g.subStat==='HP')hp+=g.subValue||0;if(g.subStat==='DEF')def+=g.subValue||0;if(g.subStat==='CRIT')crit+=(g.subValue||0)/100}
 return{hp:Math.round(hp),atk:Math.round(atk),def:Math.round(def),crit:clamp(crit,0,.75),rate}}
function petStats(){let p=petDefs.find(x=>x.id===state.activePet)||petDefs[0],ps=state.pets[p.id]||{level:1,evo:0,affinity:0};return{...p,atk:(p.atk+(ps.level-1)*2.2)*(1+ps.evo*.25),speed:1.12*(1-ps.evo*.04),level:ps.level,evo:ps.evo,affinity:ps.affinity}}
function powerScore(){let h=heroBase(),p=petStats();return Math.round(h.atk*3.3+h.hp*.24+h.def*8.5+h.crit*180+p.atk*4.2+Object.values(state.artifacts).reduce((a,b)=>a+b,0)*25)}
function xpNeed(l=state.level){return 90+l*32+Math.floor(l*l*.7)}
function gainXp(n){state.xp+=n;let leveled=false;while(state.level<99&&state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.talentPoints++;state.energy=Math.min(maxEnergy(),state.energy+3);leveled=true;tone(760,.12);setTimeout(()=>tone(980,.14),100)}if(leveled)lootPop('⬆️','LEVEL UP!','Level '+state.level+'\n+1 Talent Point · +3 Energy')}
function gainGold(n){n=Math.max(0,Math.round(n));state.gold+=n;state.totalGoldEarned+=n}
function gainMaterial(k,n){state.materials[k]=(state.materials[k]||0)+n}
function applySettings(){document.body.classList.toggle('reduce-motion',!state.motion);document.body.classList.toggle('mode3d',state.depth);$('#soundToggle').classList.toggle('on',state.sound);$('#motionToggle').classList.toggle('on',state.motion);$('#depthToggle').classList.toggle('on',state.depth);$('#autoSkillToggle').classList.toggle('on',state.autoSkills);document.documentElement.lang=state.lang;$('#languageSelect').value=state.lang}
function renderTop(){regenEnergy();let cap=maxEnergy();$('#energyTxt').textContent=Math.floor(state.energy);$('#goldTxt').textContent=fmt(state.gold);$('#gemsTxt').textContent=fmt(state.gems);$('#levelTxt').textContent=state.level;$('#xpTxt').textContent=`${Math.floor(state.xp)} / ${xpNeed()} XP`;$('#xpFill').style.width=`${clamp(state.xp/xpNeed()*100,0,100)}%`;$('#powerTxt').textContent=fmt(powerScore());$('#app').style.setProperty('--heroHue',state.heroHue);let c=chapters[state.run?state.run.chapter:state.currentChapter];$('#chapterKicker').textContent=c.kicker;$('#chapterTitle').textContent=c.name;let pos=state.run?state.run.pos+1:(state.bestStages[state.currentChapter]||1);$('#stageTxt').textContent=`Stage ${state.run?state.run.chapter:state.currentChapter}-${pos}`;$('#chapterPrev').disabled=!!state.run||state.currentChapter<=1;$('#chapterNext').disabled=!!state.run||state.currentChapter>=state.unlockedChapter;$('#heroName').textContent=(classDefs[state.heroClass]||classDefs.knight).name;$('#energyCardText').textContent=`${Math.floor(state.energy)}/${cap} energy · +1 every 2 minutes.`}
function renderHero(){let h=heroBase(),c=classDefs[state.heroClass]||classDefs.knight;$('#heroHpStat').textContent=h.hp;$('#heroAtkStat').textContent=h.atk;$('#heroDefStat').textContent=Math.round(h.def);$('#heroCritStat').textContent=Math.round(h.crit*100)+'%';$('#classDesc').textContent=c.desc;$$('#classChoices .chip').forEach(b=>b.classList.toggle('selected',b.dataset.class===state.heroClass))}
function renderPets(){let el=$('#petGrid');el.innerHTML='';$('#treatsTxt').textContent=fmt(state.materials.treats);$('#essenceTxt').textContent=fmt(state.materials.essence);petDefs.forEach((p,i)=>{let ps=state.pets[p.id],active=state.activePet===p.id,unlocked=!!ps.unlocked,atk=Math.round((p.atk+(ps.level-1)*2.2)*(1+ps.evo*.25));let c=document.createElement('div');c.className='pet-card'+(active?' active':'');let evoName=['Base','Evolved','Ascended','Mythic'][ps.evo]||'Mythic';c.innerHTML=`<span class="rarity ${ps.evo>=2?'r-epic':ps.evo?'r-rare':'r-uncommon'}">${unlocked?'Lv '+ps.level:'LOCKED'}</span><div class="pet-art">${p.icon}</div><div class="pet-name">${p.name}</div><div class="pet-trait">${p.trait} · ATK ${atk} · ${evoName}</div><div class="pet-trait">${p.role}</div><div class="progress"><span style="width:${Math.min(100,(ps.affinity%50)/50*100)}%"></span></div><div class="pet-trait">Affinity ${ps.affinity}</div><div class="pet-actions"><button class="primary pet-main" type="button">${!unlocked?'UNLOCK '+p.unlock+'●':active?'LEVEL '+(80*ps.level)+'●':'SELECT'}</button><button class="pet-evolve" type="button" ${!unlocked||ps.level<(ps.evo+1)*10||ps.evo>=3?'disabled':''}>EVOLVE</button></div>`;
 let main=c.querySelector('.pet-main');main.addEventListener('click',()=>{if(!ps.unlocked){if(state.gold<p.unlock)return toast('Need '+p.unlock+' gold');state.gold-=p.unlock;ps.unlocked=true;toast(p.name+' joined your party!')}else if(!active){state.activePet=p.id;toast(p.name+' is now active.')}else{let cost=80*ps.level;if(state.gold<cost)return toast('Need '+cost+' gold');if(state.materials.treats<2)return toast('Need 2 pet treats');state.gold-=cost;state.materials.treats-=2;ps.level++;tone(560,.08);toast(p.name+' reached Lv. '+ps.level)}saveState();renderAll()});
 c.querySelector('.pet-evolve').addEventListener('click',()=>{let needEss=5+ps.evo*5;if(ps.level<(ps.evo+1)*10)return;if(state.materials.essence<needEss)return toast('Need '+needEss+' essence');state.materials.essence-=needEss;ps.evo++;tone(700,.12);lootPop(p.icon,p.name+' Evolved!','Evolution '+ps.evo+' · +25% pet power');saveState();renderAll()});el.appendChild(c)})}
function gearPower(g){return Math.round(g.power*(1+(g.level-1)*.14))}
function renderGear(){let el=$('#gearGrid');el.innerHTML='';$('#oreTxt').textContent=fmt(state.materials.ore);$('#gearEssenceTxt').textContent=fmt(state.materials.essence);$('#inventoryTxt').textContent=state.gear.length;if(!state.gear.length){el.innerHTML='<div class="card" style="grid-column:1/-1;color:var(--muted);font-size:10px">Equipment drops from battles, elites, bosses, treasure and merchants.</div>';return}state.gear.slice().sort((a,b)=>gearPower(b)-gearPower(a)).forEach(g=>{let equipped=state.equipped[g.slot]===g.id,c=document.createElement('div');c.className='gear-card'+(equipped?' equipped':'');c.innerHTML=`<span class="rarity r-${g.rarity.c}">${g.rarity.n} · +${g.level-1}</span><div class="pet-art">${gearIcons[g.slot]}</div><div class="gear-name">${g.name}</div><div class="gear-stat">${g.slot} · ${g.stat} +${Math.round(g.value*(1+(g.level-1)*.12))}${g.stat==='CRIT'?'%':''}</div><div class="gear-stat">${g.subStat?g.subStat+' +'+g.subValue+(g.subStat==='CRIT'?'%':''):'Power '+gearPower(g)}</div><div class="gear-actions"><button class="primary equip" type="button" ${equipped?'disabled':''}>${equipped?'EQUIPPED':'EQUIP'}</button><button class="upgradeGear" type="button">UPGRADE</button></div><div class="gear-actions"><button class="salvageOne" type="button" ${equipped?'disabled':''}>SALVAGE</button><button class="lockGear" type="button">${g.locked?'🔒 LOCKED':'🔓 LOCK'}</button></div>`;
 c.querySelector('.equip').addEventListener('click',()=>{state.equipped[g.slot]=g.id;saveState();renderAll();toast('Equipped '+g.name)});c.querySelector('.upgradeGear').addEventListener('click',()=>upgradeGear(g.id));c.querySelector('.salvageOne').addEventListener('click',()=>salvageGear(g.id));c.querySelector('.lockGear').addEventListener('click',()=>{g.locked=!g.locked;saveState();renderGear()});el.appendChild(c)})}
function upgradeGear(id){let g=state.gear.find(x=>x.id===id);if(!g)return;let gold=100*g.level*(g.rarity.m||1),ore=Math.ceil(3*g.level*(g.rarity.m||1));if(state.gold<gold)return toast('Need '+Math.ceil(gold)+' gold');if(state.materials.ore<ore)return toast('Need '+ore+' ore');state.gold-=Math.ceil(gold);state.materials.ore-=ore;g.level++;tone(610,.08);saveState();renderAll();toast(g.name+' upgraded to +'+(g.level-1))}
function salvageGear(id){let g=state.gear.find(x=>x.id===id);if(!g||g.locked||state.equipped[g.slot]===id)return;let idx=state.gear.findIndex(x=>x.id===id);state.gear.splice(idx,1);let ore=2+rarities.findIndex(r=>r.c===g.rarity.c)*3;gainMaterial('ore',ore);if(rarities.findIndex(r=>r.c===g.rarity.c)>=3)gainMaterial('essence',1);saveState();renderAll();toast('Salvaged · +'+ore+' ore')}
function autoEquip(){gearSlots.forEach(slot=>{let best=state.gear.filter(g=>g.slot===slot).sort((a,b)=>gearPower(b)-gearPower(a))[0];if(best)state.equipped[slot]=best.id});saveState();renderAll();toast('Best gear equipped.')}
function mergeGear(){for(let tier=0;tier<rarities.length-1;tier++){for(const slot of gearSlots){let pool=state.gear.filter(g=>g.slot===slot&&g.rarity.c===rarities[tier].c&&!g.locked&&state.equipped[slot]!==g.id);if(pool.length>=3){let used=pool.slice(0,3);state.gear=state.gear.filter(g=>!used.some(u=>u.id===g.id));dropGear(tier+1,slot,true);saveState();renderAll();lootPop('⚒️','Forge Success',`${rarities[tier+1].n} ${slot} created!`);return}}}toast('Need 3 unequipped items of the same slot and rarity.')}
function salvageCommon(){let ids=state.gear.filter(g=>['common','uncommon'].includes(g.rarity.c)&&!g.locked&&state.equipped[g.slot]!==g.id).map(g=>g.id);if(!ids.length)return toast('No unlocked Common/Uncommon gear to salvage.');let ore=0;state.gear=state.gear.filter(g=>{if(ids.includes(g.id)){ore+=g.rarity.c==='uncommon'?4:2;return false}return true});gainMaterial('ore',ore);saveState();renderAll();toast('Salvaged '+ids.length+' items · +'+ore+' ore')}
function renderTalents(){let el=$('#talentList');el.innerHTML='';$('#talentPointsTxt').textContent=state.talentPoints;talentDefs.forEach(t=>{let lv=state.talents[t.id]||0,d=document.createElement('div');d.className='talent-row';d.innerHTML=`<div class="talent-ico">${t.ico}</div><div><b>${t.name} · ${lv}/${t.max}</b><small>${t.desc}</small></div><button type="button" ${lv>=t.max||state.talentPoints<1?'disabled':''}>+ RANK</button>`;d.querySelector('button').addEventListener('click',()=>{if(state.talentPoints<1||state.talents[t.id]>=t.max)return;state.talentPoints--;state.talents[t.id]++;if(t.id==='energy')state.energy=Math.min(maxEnergy(),state.energy+4);saveState();renderAll();renderTalents();tone(530,.07)});el.appendChild(d)})}
function renderArtifacts(){let el=$('#artifactList');el.innerHTML='';$('#dustTxt').textContent=fmt(state.materials.dust);artifactDefs.forEach(a=>{let lv=state.artifacts[a.id]||0,cost=10+lv*8,d=document.createElement('div');d.className='artifact-row';d.innerHTML=`<div class="artifact-ico">${a.ico}</div><div><b>${a.name} · Lv ${lv}</b><small>${lv? a.desc:'Undiscovered · defeat bosses to find this relic.'}</small></div><button type="button" ${!lv||state.materials.dust<cost?'disabled':''}>${lv?'UP '+cost:'LOCKED'}</button>`;d.querySelector('button').addEventListener('click',()=>{if(!lv||state.materials.dust<cost)return;state.materials.dust-=cost;state.artifacts[a.id]++;saveState();renderAll();renderArtifacts();tone(720,.09)});el.appendChild(d)})}
function dailyDefs(){return[
 {id:'dailyBattle',ico:'⚔️',name:'Battle Warmup',desc:'Win 8 battles today',now:state.dailyClaimed[dateKey()+':battleNow']||0,max:8,reward:['energy',6]},
 {id:'dailySkills',ico:'✨',name:'Hands On',desc:'Cast 12 active skills today',now:state.dailyClaimed[dateKey()+':skillNow']||0,max:12,reward:['gems',12]},
 {id:'dailyTreasure',ico:'🎁',name:'Treasure Trail',desc:'Open 3 treasure nodes today',now:state.dailyClaimed[dateKey()+':chestNow']||0,max:3,reward:['ore',12]}
]}
function questDefs(){return[
 {id:'roll20',ico:'🎲',name:'Fate Walker',desc:'Roll dice 20 times',now:state.rolls,max:20,reward:['gold',650]},
 {id:'kill50',ico:'⚔️',name:'Monster Hunter',desc:'Defeat 50 enemies',now:state.kills,max:50,reward:['gems',35]},
 {id:'elite10',ico:'💀',name:'Elite Breaker',desc:'Defeat 10 elites',now:state.elites,max:10,reward:['essence',8]},
 {id:'boss4',ico:'♛',name:'Crown Breaker',desc:'Defeat 4 bosses',now:state.bosses,max:4,reward:['talent',2]},
 {id:'skills40',ico:'✨',name:'Combatant',desc:'Cast 40 active skills',now:state.skillsUsed,max:40,reward:['energy',12]},
 {id:'gear20',ico:'🎒',name:'Collector',desc:'Find 20 pieces of gear',now:state.gearFound,max:20,reward:['ore',25]},
 {id:'event10',ico:'❓',name:'Curious Soul',desc:'Resolve 10 events',now:state.events,max:10,reward:['gems',25]}
]}
function achievementDefs(){let hasMythic=state.gear.some(g=>g.rarity.c==='mythic');return[
 {id:'firstBlood',ico:'🩸',name:'First Blood',desc:'Defeat your first enemy.',now:state.kills,max:1,reward:10},
 {id:'combo25',ico:'🔥',name:'Unbroken',desc:'Reach a 25-hit combo.',now:state.maxCombo,max:25,reward:20},
 {id:'level10',ico:'⬆️',name:'Ascendant',desc:'Reach level 10.',now:state.level,max:10,reward:30},
 {id:'boss10',ico:'🐉',name:'Boss Hunter',desc:'Defeat 10 bosses.',now:state.bosses,max:10,reward:45},
 {id:'mythic',ico:'🌈',name:'Mythic Find',desc:'Own a Mythic item.',now:hasMythic?1:0,max:1,reward:55},
 {id:'chapter4',ico:'🏰',name:'Into the Void',desc:'Unlock Chapter 4.',now:state.unlockedChapter>=4?1:0,max:1,reward:75}
]}
function giveReward(r){let[k,n]=r;if(k==='gold')gainGold(n);if(k==='gems')state.gems+=n;if(k==='energy')state.energy=Math.min(maxEnergy(),state.energy+n);if(k==='ore')gainMaterial('ore',n);if(k==='essence')gainMaterial('essence',n);if(k==='treats')gainMaterial('treats',n);if(k==='dust')gainMaterial('dust',n);if(k==='talent')state.talentPoints+=n}
function renderQuestRows(defs,elId,prefix){let el=$(elId);el.innerHTML='';defs.forEach(q=>{let key=prefix+q.id,claimed=!!state.claimed[key],done=q.now>=q.max,d=document.createElement('div');d.className='list-row';d.innerHTML=`<div class="list-icon">${q.ico}</div><div class="list-copy"><div class="list-title">${q.name}</div><div class="list-desc">${q.desc} · ${Math.min(q.now,q.max)}/${q.max}</div><div class="progress"><span style="width:${Math.min(100,q.now/q.max*100)}%"></span></div></div><button type="button" ${!done||claimed?'disabled':''}>${claimed?'DONE':'CLAIM'}</button>`;d.querySelector('button').addEventListener('click',()=>{if(!done||claimed)return;giveReward(q.reward);state.claimed[key]=true;saveState();renderAll();renderQuests();lootPop(q.ico,'Quest Complete',rewardText(q.reward))});el.appendChild(d)})}
function rewardText(r){let[k,n]=r;let names={gold:'Gold',gems:'Gems',energy:'Energy',ore:'Ore',essence:'Essence',treats:'Treats',dust:'Artifact Dust',talent:'Talent Points'};return'+'+n+' '+(names[k]||k)}
function renderQuests(){renderQuestRows(dailyDefs(),'#dailyQuestList','D:'+dateKey()+':');renderQuestRows(questDefs(),'#questList','Q:');let qDone=questDefs().filter(q=>q.now>=q.max&&!state.claimed['Q:'+q.id]).length+dailyDefs().filter(q=>q.now>=q.max&&!state.claimed['D:'+dateKey()+':'+q.id]).length;$('#questCardText').textContent=qDone?`${qDone} reward${qDone>1?'s':''} ready to claim.`:'Complete objectives for energy, gems and materials.'}
function renderAchievements(){let el=$('#achievementList');el.innerHTML='';let ready=0;achievementDefs().forEach(a=>{let key='A:'+a.id,claimed=!!state.claimed[key],done=a.now>=a.max;if(done&&!claimed)ready++;let d=document.createElement('div');d.className='list-row';d.innerHTML=`<div class="list-icon">${a.ico}</div><div class="list-copy"><div class="list-title">${a.name}</div><div class="list-desc">${a.desc} · Reward ${a.reward} ◆</div><div class="progress"><span style="width:${Math.min(100,a.now/a.max*100)}%"></span></div></div><button type="button" ${!done||claimed?'disabled':''}>${claimed?'DONE':'CLAIM'}</button>`;d.querySelector('button').addEventListener('click',()=>{if(!done||claimed)return;state.gems+=a.reward;state.claimed[key]=true;saveState();renderAll();renderAchievements();lootPop(a.ico,'Achievement!',`+${a.reward} Gems`)});el.appendChild(d)});$('#achievementCardText').textContent=ready?ready+' achievement reward ready.':'Long-term challenges with gem rewards.'}
function renderCodex(){let el=$('#codexList');el.innerHTML='';let seen=0;enemyDefs.forEach(e=>{let kills=state.bestiary[e.id]||0;if(kills)seen++;let d=document.createElement('div');d.className='list-row';d.innerHTML=`<div class="list-icon">${kills?e.icon:'❔'}</div><div class="list-copy"><div class="list-title">${kills?e.name:'Unknown Creature'} ${e.boss?'· BOSS':''}</div><div class="list-desc">Chapter ${e.chapter} · ${kills?kills+' defeated · HP '+e.hp+' · ATK '+e.atk:'Encounter this creature to reveal its entry.'}</div></div><span class="mini-badge">${kills?'×'+kills:'???'}</span>`;el.appendChild(d)});$('#codexCardText').textContent=`${seen}/${enemyDefs.length} creatures discovered.`}
function renderStats(){let stats=[['⚔️','Enemies',state.kills],['💀','Elites',state.elites],['♛','Bosses',state.bosses],['🎲','Dice rolls',state.rolls],['✨','Skills cast',state.skillsUsed],['🔥','Best combo',state.maxCombo],['💥','Damage',fmt(state.totalDamage)],['●','Gold earned',fmt(state.totalGoldEarned)],['🎒','Gear found',state.gearFound],['🏆','Runs cleared',state.wins],['☠️','Defeats',state.deaths],['⚡','Power',fmt(powerScore())]];$('#statsGrid').innerHTML=stats.map(s=>`<div class="stat-card"><span>${s[0]} ${s[1]}</span><b>${s[2]}</b></div>`).join('')}
function patrolHours(){return clamp((Date.now()-(state.patrolLast||Date.now()))/3600000,0,8)}
function renderKingdom(){let ph=patrolHours();$('#patrolCardText').textContent=ph<.03?'Patrol just departed. Rewards build for up to 8 hours.':`${ph.toFixed(1)}h of offline loot is waiting.`;$('#claimPatrolBtn').disabled=ph<.03;$('#talentCardText').textContent=`${state.talentPoints} unspent talent point${state.talentPoints===1?'':'s'}.`;let art=Object.values(state.artifacts).filter(x=>x>0).length;$('#artifactCardText').textContent=`${art}/${artifactDefs.length} relics discovered · ${state.materials.dust} dust.`;$('#dailyCardText').textContent=state.lastDaily===dateKey()?`Claimed today · streak ${state.dailyStreak}.`:'Free energy, gold and materials ready.';$('#dailyBtn').disabled=state.lastDaily===dateKey();renderQuests();renderAchievements();renderCodex();renderStats()}
function renderEnergy(){regenEnergy();let cap=maxEnergy();$('#energyNow').textContent=Math.floor(state.energy);$('#energyMax').textContent=cap;let remaining=state.energy>=cap?0:ENERGY_MS-((Date.now()-(state.lastEnergy||Date.now()))%ENERGY_MS);$('#energyTimer').textContent=state.energy>=cap?'Energy is full.':`Next +1 in ${Math.floor(remaining/60000)}:${String(Math.floor((remaining%60000)/1000)).padStart(2,'0')}`;let wellLeft=Math.max(0,ENERGY_WELL_MS-(Date.now()-(state.lastEnergyWell||0)));$('#wellBtn').disabled=wellLeft>0||state.energy>=cap;$('#wellSub').textContent=wellLeft>0?`Ready in ${Math.ceil(wellLeft/60000)} min`:'+8 energy';$('#gemEnergyBtn').disabled=state.gems<5||state.energy>=cap;$('#energyUpgradeSub').textContent=`Rank ${state.talents.energy||0}/10 · costs 1 talent point`;$('#energyUpgradeBtn').disabled=state.talentPoints<1||(state.talents.energy||0)>=10;$('#dailyEnergyBtn').disabled=state.lastDaily===dateKey()}
function renderRun(){let r=state.run;if(!r){$('#runHud').style.display='none';$('#skillTray').classList.remove('show');$('#runStatus').textContent='Ready for adventure.';$('#nodeTxt').textContent='0';$('#primaryBtn').disabled=false;$('#primaryBtn').textContent=`START ADVENTURE · ${RUN_COST} ⚡`;$('#fateBtn').disabled=true;$('#campBtn').disabled=true;return}$('#runHud').style.display='flex';$('#nodeTxt').textContent=r.pos+1;$('#hpTxt').textContent=`${Math.max(0,Math.ceil(r.hp))}/${Math.ceil(r.maxHp)}`;$('#hpFill').style.width=clamp(r.hp/r.maxHp*100,0,100)+'%';$('#shieldFill').style.width=clamp((r.shield||0)/r.maxHp*100,0,100)+'%';$('#ultFill').style.width=clamp(r.ultimate||0,0,100)+'%';$('#buffCount').textContent='✦'+r.upgrades.length;$('#comboTxt').textContent='×'+Math.floor(r.combo||0);$('#runStatus').textContent=combat?`Fighting ${combat.enemy.name}`:`${chapters[r.chapter].name} · ${nodeLabel(r.board[r.pos])}`;$('#skillTray').classList.toggle('show',!!combat);$('#primaryBtn').disabled=!!combat||rolling;$('#primaryBtn').textContent=combat?'BATTLE IN PROGRESS':rolling?'ROLLING…':'🎲 ROLL DICE';$('#fateBtn').disabled=!!combat||rolling||(r.focus||0)<=0;$('#fateBtn').textContent=`🎲 FATE DICE · ${r.focus||0}`;$('#campBtn').disabled=!!combat||r.hp>=r.maxHp||(r.camps||0)<=0;$('#campBtn').textContent=`🍖 FIELD CAMP · ${r.camps||0}`;renderSkillButtons()}
function renderSkillButtons(){if(!combat)return;$$('.skill').forEach(b=>{let k=b.dataset.skill,cd=k==='ultimate'?(state.run.ultimate>=100?0:100-state.run.ultimate):(combat.cooldowns[k]||0),ready=cd<=0;b.classList.toggle('ready',ready);let e=b.querySelector('.cd');if(k==='ultimate')e.textContent=ready?'':Math.floor(state.run.ultimate)+'%';else e.textContent=ready?'':cd.toFixed(1);e.style.display=ready?'none':'grid'})}
function renderAll(){renderTop();renderHero();renderPets();renderGear();renderTalents();renderArtifacts();renderKingdom();renderEnergy();renderRun();$('#speedBtn').textContent='⏩ '+state.battleSpeed+'× SPEED';applySettings()}
function rarityPick(force){if(Number.isInteger(force))return rarities[clamp(force,0,rarities.length-1)];let luck=artifactLuck(),roll=Math.random()*(1+luck*.18),idx=roll>.995?5:roll>.94?4:roll>.78?3:roll>.52?2:roll>.2?1:0;return rarities[idx]}
function dropGear(forceTier,forceSlot,silent=false){if(state.gear.length>=MAX_INV){let low=state.gear.filter(g=>!g.locked&&state.equipped[g.slot]!==g.id).sort((a,b)=>gearPower(a)-gearPower(b))[0];if(low)salvageGear(low.id);else return null}let rarity=rarityPick(forceTier),slot=forceSlot||gearSlots[Math.floor(Math.random()*gearSlots.length)],stats=slot==='Weapon'?['ATK','CRIT']:slot==='Armor'?['HP','DEF']:slot==='Helm'?['HP','DEF']:slot==='Boots'?['DEF','CRIT']:slot==='Ring'?['ATK','CRIT']:['ATK','HP','CRIT'],stat=stats[Math.floor(Math.random()*stats.length)],base=stat==='HP'?45:stat==='ATK'?9:stat==='DEF'?3:2.2,value=Math.round(base*rarity.m*(.86+Math.random()*.3)*10)/10,subPool=['ATK','HP','DEF','CRIT'].filter(x=>x!==stat),subStat=rarities.indexOf(rarity)>=2?subPool[Math.floor(Math.random()*subPool.length)]:null,subValue=subStat?(subStat==='HP'?Math.round(18*rarity.m):subStat==='ATK'?Math.round(4*rarity.m):subStat==='DEF'?Math.round(1.5*rarity.m):Math.round(1.2*rarity.m)):0,names={Weapon:['Runeblade','Storm Edge','Moonsteel Sword'],Armor:['Warden Plate','Drake Mail','Aether Coat'],Helm:['Sentinel Helm','Wyrm Crown','Scout Hood'],Charm:['Star Charm','Echo Orb','Spirit Seal'],Boots:['Gale Boots','Iron Greaves','Rift Steps'],Ring:['Ember Ring','Frost Band','Void Loop']},name=names[slot][Math.floor(Math.random()*names[slot].length)],g={id:'g'+Date.now()+Math.random().toString(36).slice(2,7),slot,name,rarity,stat,value,subStat,subValue,level:1,locked:false,power:Math.round((stat==='HP'?value*.25:stat==='CRIT'?value*9:value*4)*rarity.m)};state.gear.push(g);state.gearFound++;if(!silent)lootPop(gearIcons[slot],rarity.n+' '+name,`${stat} +${value}${stat==='CRIT'?'%':''}${subStat?' · '+subStat+' +'+subValue:''}`);return g}
function startRun(){if(!spendEnergy(RUN_COST))return openModal('energyModal'),toast('Not enough energy.');let h=heroBase(),chapter=state.currentChapter;state.run={chapter,pos:0,board:generateBoard(chapter),hp:h.hp,maxHp:h.hp,shield:0,atk:h.atk,def:h.def,crit:h.crit,critDmg:1.8,attackRate:h.rate,dodge:0,lifesteal:0,thorns:0,fire:0,frost:0,storm:0,poison:0,shock:0,bleed:0,regen:0,multi:0,execute:0,berserk:0,petPower:0,petSpeed:0,treasure:0,eliteBonus:0,skillHaste:0,focus:2,rerolls:1,camps:1,combo:0,ultimate:0,upgrades:[],powerCounts:{},synergies:[],goldRun:0};combat=null;sceneMode='board';rolling=false;buildBoard();saveState();tone(330,.12);banner('Adventure Begins');renderAll()}
function generateBoard(chapter){let pool=['battle','battle','battle','treasure','shrine','event','elite','merchant','camp','trap','portal'],board=['start'];for(let i=1;i<17;i++){let type=pool[Math.floor(Math.random()*pool.length)];if(i<3&&['elite','trap'].includes(type))type='battle';if(i===8)type=Math.random()<.5?'elite':'shrine';if(i===13)type=Math.random()<.5?'merchant':'camp';board.push(type)}board.push('boss');return board}
function buildBoard(){boardNodes=[];for(let i=0;i<18;i++){let p=i/17,y=H*.83-p*H*.62,x=W*.5+Math.sin(i*.92)*W*.27+(i%4===0?Math.cos(i*.37)*30:0);boardNodes.push({x,y,type:state.run?state.run.board[i]:(i===0?'start':i===17?'boss':['battle','treasure','shrine','elite','event','battle','merchant','camp'][i%8])})}}
function nodeLabel(type){return({start:'Trailhead',battle:'Battle',treasure:'Treasure',shrine:'Power Shrine',elite:'Elite Battle',merchant:'Merchant',camp:'Safe Camp',event:'Mystery Event',trap:'Trap',portal:'Portal',boss:'Boss'}[type]||type)}
async function rollDice(){if(!state.run||combat||rolling)return;rolling=true;state.rolls++;renderRun();let final=1+Math.floor(Math.random()*6),ticks=state.motion?5:1;for(let i=0;i<ticks;i++){banner('🎲 '+(i===ticks-1?final:1+Math.floor(Math.random()*6)));tone(180+i*30,.025,'square');await wait(state.motion?45:1)}await moveBy(final);rolling=false;saveState();renderAll()}
async function moveBy(n){if(!state.run)return;let target=Math.min(17,state.run.pos+n);for(let p=state.run.pos+1;p<=target;p++){state.run.pos=p;state.bestStages[state.run.chapter]=Math.max(state.bestStages[state.run.chapter]||1,p+1);tone(270+p*12,.035);if(state.motion)await wait(90)}resolveNode(state.run.board[state.run.pos])}
function fateDice(){let r=state.run;if(!r||combat||rolling||r.focus<=0)return;r.focus--;let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);showChoice('Fate Dice','You spend one Fate charge and glimpse two possible rolls.',[
 {label:'🎲 Choose '+a,sub:'Move '+a+' spaces',fn:()=>moveBy(a)},
 {label:'🎲 Choose '+b,sub:'Move '+b+' spaces',fn:()=>moveBy(b)}
]);saveState();renderAll()}
function fieldCamp(){let r=state.run;if(!r||combat||r.camps<=0||r.hp>=r.maxHp)return;r.camps--;let heal=r.maxHp*.45;r.hp=Math.min(r.maxHp,r.hp+heal);r.shield=Math.max(r.shield,r.maxHp*.08);tone(500,.09);toast('Camp restored '+Math.round(heal)+' HP and granted a small shield.');saveState();renderAll()}
function resolveNode(type){if(!state.run)return;if(type==='battle')return startCombat(false,false);if(type==='elite')return startCombat(true,false);if(type==='boss')return startCombat(true,true);if(type==='treasure')return treasure();if(type==='shrine')return chooseUpgrade();if(type==='merchant')return merchant();if(type==='camp'){state.run.camps++;state.run.hp=Math.min(state.run.maxHp,state.run.hp+state.run.maxHp*.25);toast('Safe camp · healed 25% and gained a Field Camp charge.');return renderAll()}if(type==='event')return randomEvent();if(type==='trap')return trapNode();if(type==='portal')return portalNode();renderAll()}
function treasure(){let r=state.run;state.chests++;state.dailyClaimed[dateKey()+':chestNow']=(state.dailyClaimed[dateKey()+':chestNow']||0)+1;let bonus=1+(r.treasure||0)+artifactLuck(),roll=Math.random(),desc='';if(roll<.13){let e=3+Math.floor(Math.random()*4);state.energy=Math.min(maxEnergy(),state.energy+e);desc='+'+e+' Energy'}else if(roll<.28){let g=2+Math.floor(Math.random()*4);state.gems+=g;desc='+'+g+' Gems'}else if(roll<.48){let ore=5+Math.floor(Math.random()*8);gainMaterial('ore',ore);desc='+'+ore+' Ore'}else if(roll<.68){dropGear(undefined,undefined,true);desc='Equipment discovered!'}else{let gold=Math.round((130+Math.random()*190)*r.chapter*bonus);gainGold(gold);r.goldRun+=gold;desc='+'+gold+' Gold'}tone(650,.08);lootPop('🎁','Treasure Found',desc);saveState();renderAll()}
function trapNode(){let r=state.run,dmg=Math.round(r.maxHp*(.08+Math.random()*.08));if((r.dodge||0)>Math.random()){toast('Phantom Step avoided the trap!')}else{r.hp=Math.max(1,r.hp-dmg);banner('⚠ Trap! -'+dmg+' HP');shake=8;tone(130,.08,'square')}if(Math.random()<.45){gainMaterial('ore',4);toast('You recovered 4 ore from the trap mechanism.')}saveState();renderAll()}
async function portalNode(){if(!state.run)return;let jump=Math.min(2,17-state.run.pos);banner('🌀 Rift Portal');tone(620,.14,'sine');if(jump>0){await wait(180);state.run.pos+=jump;state.bestStages[state.run.chapter]=Math.max(state.bestStages[state.run.chapter]||1,state.run.pos+1)}toast('The portal carried you '+jump+' spaces forward.');saveState();renderAll()}
function showChoice(title,desc,choices,closable=true){$('#choiceTitle').textContent=title;$('#choiceDesc').textContent=desc;let el=$('#choiceList');el.innerHTML='';choices.forEach(ch=>{let b=document.createElement('button');b.className='choice-btn';b.innerHTML=`<b>${ch.label}</b><span>${ch.sub||''}</span>`;b.disabled=!!ch.disabled;b.addEventListener('click',()=>{closeModal('choiceModal');Promise.resolve(ch.fn&&ch.fn()).then(()=>{saveState();renderAll()})});el.appendChild(b)});$('#choiceClose').style.display=closable?'block':'none';openModal('choiceModal')}
function randomEvent(){state.events++;let r=state.run,events=['altar','fountain','gambler','cache','spirit','smith'],kind=events[Math.floor(Math.random()*events.length)];if(kind==='altar')showChoice('Bloodstone Altar','Ancient runes pulse with dangerous power.',[
 {label:'Offer vitality',sub:'Lose 16% max HP · gain +24% attack for this run',fn:()=>{r.maxHp*=.84;r.hp=Math.min(r.hp,r.maxHp);r.atk*=1.24;banner('Power surges through you!')}},{label:'Take a shard',sub:'Gain 4 artifact dust',fn:()=>gainMaterial('dust',4)},{label:'Leave',sub:'Keep moving',fn:()=>{}}
]);
 if(kind==='fountain')showChoice('Moonlit Fountain','Clear water reflects a sky that is not your own.',[
 {label:'Drink',sub:'Heal 45% max HP',fn:()=>r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.45)},{label:'Bottle the water',sub:'+1 Fate Dice and +1 Field Camp',fn:()=>{r.focus++;r.camps++}}
 ]);
 if(kind==='gambler')showChoice('Masked Gambler','A traveler offers a very questionable wager.',[
 {label:'Wager 120 gold',sub:'70% chance for gear · 30% chance to lose it',disabled:state.gold<120,fn:()=>{state.gold-=120;if(Math.random()<.7){dropGear(undefined,undefined,true);lootPop('🎒','You Win!','A piece of gear is yours.')}else toast('The gambler wins this round.')}},{label:'Challenge for gems',sub:'50% chance +10 gems · otherwise nothing',fn:()=>{if(Math.random()<.5){state.gems+=10;lootPop('◆','Lucky Hand','+10 Gems')}else toast('No luck this time.')}},{label:'Walk away',sub:'No risk',fn:()=>{}}
 ]);
 if(kind==='cache')showChoice('Abandoned Supply Cache','Someone left useful supplies beside the trail.',[
 {label:'Take rations',sub:'+5 Energy',fn:()=>state.energy=Math.min(maxEnergy(),state.energy+5)},{label:'Take crafting supplies',sub:'+10 Ore · +3 Pet Treats',fn:()=>{gainMaterial('ore',10);gainMaterial('treats',3)}},{label:'Search the false bottom',sub:'Gain random gear, but lose 8% HP',fn:()=>{r.hp=Math.max(1,r.hp-r.maxHp*.08);dropGear(undefined,undefined,true);lootPop('🎒','Hidden Gear','A concealed item was inside.')}}
 ]);
 if(kind==='spirit')showChoice('Wandering Spirit','A forest spirit circles your companion.',[
 {label:'Bond with your pet',sub:'+15 pet affinity',fn:()=>state.pets[state.activePet].affinity+=15},{label:'Ask for protection',sub:'Gain a 30% max HP shield',fn:()=>r.shield+=r.maxHp*.3},{label:'Ask for wisdom',sub:'Open a power choice',fn:()=>setTimeout(chooseUpgrade,120)}
 ]);
 if(kind==='smith')showChoice('Wandering Smith','The smith offers to improve your expedition.',[
 {label:'Sharpen weapon · 150 gold',sub:'+15% run attack',disabled:state.gold<150,fn:()=>{state.gold-=150;r.atk*=1.15}},{label:'Reinforce armor · 150 gold',sub:'+3 run defense and +12% max HP',disabled:state.gold<150,fn:()=>{state.gold-=150;r.def+=3;r.maxHp*=1.12;r.hp*=1.12}},{label:'Trade scraps',sub:'+12 Ore',fn:()=>gainMaterial('ore',12)}
 ])}
