(() => {
  'use strict';

  const WIN_SCORE=3, CANVAS_SIZE=560, MIN_PLAYERS=1, MAX_PLAYERS=10, STORAGE_KEY='perfectSplitV2';
  const SOLO={easy:{label:'Easy',tolerance:5},normal:{label:'Normal',tolerance:2},hard:{label:'Hard',tolerance:.5}};
  const EMOJIS={
    easy:['😀','😎','😺','🐼','🦋','🍎','⚽','🎃','🍉','🌕','❤️','🟣'],
    medium:['🍕','🐟','🚀','🍦','🌵','🦆','🍓','🥑','🎈','🐝','🛸','🍄'],
    hard:['🦒','🐙','🦩','🎸','🗝️','🦖','🦀','🦐','🛵','🦚','🪿','🦞']
  };
  const AVATARS=['🙂','😎','🤖','👾','🐱','🐶','🦊','🐸','🐵','🦁','🐯','🐼','🐧','🦄','👻','🔥','⚡','🎯','✂️','⚖️'];
  const ALL_EMOJIS=Object.entries(EMOJIS).flatMap(([difficulty,list])=>list.map(emoji=>({emoji,difficulty})));
  const el={
    setupScreen:document.getElementById('setupScreen'),handoffScreen:document.getElementById('handoffScreen'),gameScreen:document.getElementById('gameScreen'),revealScreen:document.getElementById('revealScreen'),
    newGameButton:document.getElementById('newGameButton'),minusPlayer:document.getElementById('minusPlayer'),plusPlayer:document.getElementById('plusPlayer'),playerCount:document.getElementById('playerCount'),soloDifficultyWrap:document.getElementById('soloDifficultyWrap'),soloDifficulty:document.getElementById('soloDifficulty'),emojiMode:document.getElementById('emojiMode'),shapeDifficulty:document.getElementById('shapeDifficulty'),shapeDifficultyRow:document.getElementById('shapeDifficultyRow'),pickRow:document.getElementById('pickRow'),emojiPicker:document.getElementById('emojiPicker'),soundToggle:document.getElementById('soundToggle'),vibrationToggle:document.getElementById('vibrationToggle'),playerRows:document.getElementById('playerRows'),beginButton:document.getElementById('beginButton'),
    handoffKicker:document.getElementById('handoffKicker'),handoffAvatar:document.getElementById('handoffAvatar'),handoffTitle:document.getElementById('handoffTitle'),handoffText:document.getElementById('handoffText'),handoffButton:document.getElementById('handoffButton'),
    roundNumber:document.getElementById('roundNumber'),turnStat:document.getElementById('turnStat'),scoreboard:document.getElementById('scoreboard'),turnAvatar:document.getElementById('turnAvatar'),turnName:document.getElementById('turnName'),turnSuffix:document.getElementById('turnSuffix'),shapeBadge:document.getElementById('shapeBadge'),targetEmojiLabel:document.getElementById('targetEmojiLabel'),gestureStatus:document.getElementById('gestureStatus'),slicePanel:document.getElementById('slicePanel'),canvasShell:document.getElementById('canvasShell'),sliceCanvas:document.getElementById('sliceCanvas'),sliceHint:document.getElementById('sliceHint'),motionFill:document.getElementById('motionFill'),cutStamp:document.getElementById('cutStamp'),sliceMessage:document.getElementById('sliceMessage'),sliceStyle:document.getElementById('sliceStyle'),nextButton:document.getElementById('nextButton'),
    revealKicker:document.getElementById('revealKicker'),revealTitle:document.getElementById('revealTitle'),revealPlayer:document.getElementById('revealPlayer'),gradeBanner:document.getElementById('gradeBanner'),gradeLabel:document.getElementById('gradeLabel'),gradeHint:document.getElementById('gradeHint'),leftPercent:document.getElementById('leftPercent'),rightPercent:document.getElementById('rightPercent'),balanceError:document.getElementById('balanceError'),balanceMarker:document.getElementById('balanceMarker'),scaleCard:document.getElementById('scaleCard'),scale:document.getElementById('scale'),leftPiece:document.getElementById('leftPiece'),rightPiece:document.getElementById('rightPiece'),accuracyLine:document.getElementById('accuracyLine'),ranking:document.getElementById('ranking'),revealButton:document.getElementById('revealButton')
  };

  const ctx=el.sliceCanvas.getContext('2d',{willReadFrequently:true});
  const sourceCanvas=document.createElement('canvas');sourceCanvas.width=sourceCanvas.height=CANVAS_SIZE;
  const sourceCtx=sourceCanvas.getContext('2d',{willReadFrequently:true});
  const draftPlayers=Array.from({length:MAX_PLAYERS},(_,i)=>({name:`Player ${i+1}`,avatar:AVATARS[i%AVATARS.length]}));

  let setupPlayerCount=2,soloDifficulty='normal',emojiMode='random',shapeDifficulty='mix',pickedEmoji='🍉',soundEnabled=true,vibrationEnabled=true;
  let players=[],round=1,currentEmoji='🍉',currentShapeDifficulty='easy',turnOrder=[],turnPosition=0,currentPlayerIndex=0,attempts=[],phase='setup',drawing=false,cutPoints=[],revealIndex=0,roundWinners=[],champions=[],audioContext=null,sliceOscillator=null,sliceGain=null,lastPointer=null,totalGestureDistance=0,gestureStartedAt=0,revealTimer=0;

  const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
  const formatPct=v=>`${v.toFixed(3)}%`;
  const escapeHtml=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);

  function loadSettings(){
    try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem('perfectSplitV1')||'null');if(!saved)return;setupPlayerCount=clamp(Number(saved.playerCount)||2,MIN_PLAYERS,MAX_PLAYERS);soloDifficulty=SOLO[saved.soloDifficulty]?saved.soloDifficulty:'normal';emojiMode=saved.emojiMode==='pick'?'pick':'random';shapeDifficulty=['mix','easy','medium','hard'].includes(saved.shapeDifficulty)?saved.shapeDifficulty:'mix';pickedEmoji=ALL_EMOJIS.some(i=>i.emoji===saved.pickedEmoji)?saved.pickedEmoji:'🍉';soundEnabled=saved.soundEnabled!==false;vibrationEnabled=saved.vibrationEnabled!==false;if(Array.isArray(saved.players))saved.players.slice(0,MAX_PLAYERS).forEach((p,i)=>{if(!p)return;draftPlayers[i].name=String(p.name||draftPlayers[i].name).slice(0,18);if(AVATARS.includes(p.avatar))draftPlayers[i].avatar=p.avatar;});}catch(_){ }
  }
  function saveSettings(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({playerCount:setupPlayerCount,soloDifficulty,emojiMode,shapeDifficulty,pickedEmoji,soundEnabled,vibrationEnabled,players:draftPlayers}));}catch(_){ }}
  function ensureAudio(){if(!soundEnabled)return null;const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;if(!audioContext)audioContext=new A();if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});return audioContext;}
  function tone(f,d=.06,v=.025,delay=0,type='sine'){const a=ensureAudio();if(!a)return;const start=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(f,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(v,start+.006);g.gain.exponentialRampToValueAtTime(.0001,start+d);o.connect(g);g.connect(a.destination);o.start(start);o.stop(start+d+.02);}
  function playCue(name){
    if(name==='snap'){tone(760,.035,.02,0,'square');tone(1120,.045,.018,.035,'square');}
    else if(name==='scale'){tone(260,.06,.016);tone(220,.06,.014,.09);tone(190,.09,.016,.18);}
    else if(name==='tick'){tone(540,.035,.012);}
    else if(name==='point'){tone(650,.07,.023);tone(900,.09,.023,.07);}
    else if(name==='perfect'){tone(760,.05,.026);tone(980,.06,.026,.05);tone(1260,.08,.026,.11);tone(1500,.13,.02,.19);}
    else if(name==='win'){tone(560,.07,.027);tone(760,.07,.027,.07);tone(980,.08,.027,.14);tone(1280,.16,.027,.22);}
    else if(name==='bad'){tone(180,.09,.02);tone(125,.11,.02,.07);}
  }
  function vibrate(pattern){if(vibrationEnabled&&navigator.vibrate)navigator.vibrate(pattern);}
  function startSliceSound(){const a=ensureAudio();if(!a||sliceOscillator)return;sliceOscillator=a.createOscillator();sliceGain=a.createGain();sliceOscillator.type='sawtooth';sliceOscillator.frequency.setValueAtTime(95,a.currentTime);sliceGain.gain.setValueAtTime(.0001,a.currentTime);sliceGain.gain.exponentialRampToValueAtTime(.013,a.currentTime+.02);sliceOscillator.connect(sliceGain);sliceGain.connect(a.destination);sliceOscillator.start();}
  function updateSliceSound(speed){if(!sliceOscillator||!audioContext)return;sliceOscillator.frequency.setTargetAtTime(clamp(85+speed*1.6,85,265),audioContext.currentTime,.02);}
  function stopSliceSound(){if(!sliceOscillator||!audioContext)return;try{sliceGain.gain.setTargetAtTime(.0001,audioContext.currentTime,.015);sliceOscillator.stop(audioContext.currentTime+.06);}catch(_){ }sliceOscillator=null;sliceGain=null;}

  function populateEmojiPicker(){el.emojiPicker.innerHTML='';ALL_EMOJIS.forEach(item=>{const o=document.createElement('option');o.value=item.emoji;o.textContent=`${item.emoji} · ${item.difficulty}`;o.selected=item.emoji===pickedEmoji;el.emojiPicker.appendChild(o);});}
  function renderPlayers(){el.playerRows.innerHTML='';for(let i=0;i<setupPlayerCount;i++){const row=document.createElement('div');row.className='player-row';const avatar=document.createElement('select');avatar.setAttribute('aria-label',`Player ${i+1} avatar`);AVATARS.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=draftPlayers[i].avatar===v;avatar.appendChild(o);});avatar.addEventListener('change',()=>{draftPlayers[i].avatar=avatar.value;saveSettings();});const name=document.createElement('input');name.type='text';name.maxLength=18;name.value=draftPlayers[i].name;name.placeholder=`Player ${i+1}`;name.setAttribute('aria-label',`Player ${i+1} name`);name.addEventListener('input',()=>{draftPlayers[i].name=name.value;saveSettings();});row.append(avatar,name);el.playerRows.appendChild(row);}}
  function updateToggle(button,enabled){button.classList.toggle('selected',enabled);button.setAttribute('aria-pressed',String(enabled));const s=button.querySelector('small');if(s)s.textContent=enabled?'On':'Off';}
  function renderSetup(){el.playerCount.textContent=String(setupPlayerCount);el.minusPlayer.disabled=setupPlayerCount<=MIN_PLAYERS;el.plusPlayer.disabled=setupPlayerCount>=MAX_PLAYERS;el.soloDifficultyWrap.hidden=setupPlayerCount!==1;el.soloDifficulty.querySelectorAll('[data-solo]').forEach(b=>b.classList.toggle('selected',b.dataset.solo===soloDifficulty));el.emojiMode.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===emojiMode));el.pickRow.hidden=emojiMode!=='pick';el.shapeDifficultyRow.hidden=emojiMode==='pick';el.shapeDifficulty.value=shapeDifficulty;el.emojiPicker.value=pickedEmoji;updateToggle(el.soundToggle,soundEnabled);updateToggle(el.vibrationToggle,vibrationEnabled);renderPlayers();}
  function normalizedPlayer(i){const p=draftPlayers[i];return{name:p.name.trim()||`Player ${i+1}`,avatar:p.avatar,score:0};}
  function chooseEmoji(){if(emojiMode==='pick')return ALL_EMOJIS.find(i=>i.emoji===pickedEmoji)||ALL_EMOJIS[0];let pool=shapeDifficulty==='mix'?ALL_EMOJIS:EMOJIS[shapeDifficulty].map(emoji=>({emoji,difficulty:shapeDifficulty}));let pick=pool[Math.floor(Math.random()*pool.length)];if(round>1&&pool.length>1&&pick.emoji===currentEmoji)pick=pool[(pool.indexOf(pick)+1)%pool.length];return pick;}
  function buildTurnOrder(){if(players.length===1){turnOrder=[0];return;}const start=(round-1)%players.length;turnOrder=Array.from({length:players.length},(_,o)=>(start+o)%players.length);}
  function syncTurn(){currentPlayerIndex=turnOrder[turnPosition]??0;el.turnStat.textContent=`TURN ${turnPosition+1}/${players.length}`;const p=players[currentPlayerIndex];el.turnAvatar.textContent=p.avatar;el.turnName.textContent=p.name;el.turnSuffix.textContent='is slicing';}
  function renderScoreboard(){el.scoreboard.innerHTML=players.map((p,i)=>{const active=phase!=='game-over'&&i===currentPlayerIndex?' active':'';const pips=Array.from({length:WIN_SCORE},(_,x)=>`<i class="score-pip${x<p.score?' on':''}"></i>`).join('');return `<div class="score-chip${active}"><span class="score-avatar">${escapeHtml(p.avatar)}</span><span class="score-name">${escapeHtml(p.name)}</span><span class="score-pips">${pips}</span></div>`;}).join('');const active=el.scoreboard.querySelector('.score-chip.active');if(active&&active.scrollIntoView)active.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});}

  function prepareSourceEmoji(emoji){sourceCtx.clearRect(0,0,CANVAS_SIZE,CANVAS_SIZE);sourceCtx.textAlign='center';sourceCtx.textBaseline='middle';sourceCtx.font='360px "Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif';sourceCtx.fillText(emoji,CANVAS_SIZE/2,CANVAS_SIZE/2+8);}
  function drawStage(){ctx.clearRect(0,0,CANVAS_SIZE,CANVAS_SIZE);ctx.drawImage(sourceCanvas,0,0);if(cutPoints.length>1){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=13;ctx.strokeStyle='rgba(141,240,210,.13)';ctx.beginPath();ctx.moveTo(cutPoints[0].x,cutPoints[0].y);for(let i=1;i<cutPoints.length;i++)ctx.lineTo(cutPoints[i].x,cutPoints[i].y);ctx.stroke();ctx.lineWidth=5;ctx.strokeStyle='rgba(215,255,246,.98)';ctx.shadowColor='rgba(141,240,210,.9)';ctx.shadowBlur=16;ctx.stroke();ctx.restore();}}
  function resetSliceState(){drawing=false;cutPoints=[];lastPointer=null;totalGestureDistance=0;gestureStartedAt=0;stopSliceSound();prepareSourceEmoji(currentEmoji);drawStage();el.sliceHint.hidden=false;el.sliceMessage.className='slice-message';el.sliceMessage.textContent='Start outside one side and drag all the way through.';el.sliceStyle.textContent='—';el.gestureStatus.textContent='READY';el.motionFill.style.width='0%';el.cutStamp.hidden=true;el.nextButton.hidden=true;el.slicePanel.classList.remove('active-cut','bad-cut','good-cut');}
  function pointerPoint(event){const r=el.sliceCanvas.getBoundingClientRect();return{x:clamp((event.clientX-r.left)*CANVAS_SIZE/r.width,0,CANVAS_SIZE),y:clamp((event.clientY-r.top)*CANVAS_SIZE/r.height,0,CANVAS_SIZE)};}
  function simplifyPath(points){if(points.length<=2)return points.slice();const out=[points[0]];let last=points[0];for(let i=1;i<points.length-1;i++){if(distance(last,points[i])>=9){out.push(points[i]);last=points[i];}}out.push(points[points.length-1]);if(out.length<=56)return out;const reduced=[],step=(out.length-1)/55;for(let i=0;i<56;i++)reduced.push(out[Math.min(out.length-1,Math.round(i*step))]);return reduced;}
  function sideOfPath(x,y,path){let best=Infinity,cross=0;for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],dx=b.x-a.x,dy=b.y-a.y,len2=dx*dx+dy*dy||1,t=clamp(((x-a.x)*dx+(y-a.y)*dy)/len2,0,1),px=a.x+t*dx,py=a.y+t*dy,d2=(x-px)*(x-px)+(y-py)*(y-py);if(d2<best){best=d2;cross=dx*(y-a.y)-dy*(x-a.x);}}return cross>=0?1:-1;}
  function pathLength(path){let total=0;for(let i=1;i<path.length;i++)total+=distance(path[i-1],path[i]);return total;}
  function pathTouchesEmoji(path,imageData){let hits=0;for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],len=distance(a,b),steps=Math.max(2,Math.ceil(len/4));for(let s=0;s<=steps;s++){const t=s/steps,x=clamp(Math.round(a.x+(b.x-a.x)*t),0,CANVAS_SIZE-1),y=clamp(Math.round(a.y+(b.y-a.y)*t),0,CANVAS_SIZE-1);if(imageData.data[(y*CANVAS_SIZE+x)*4+3]>30)hits++;if(hits>=10)return true;}}return false;}
  function analyzeCut(points,makePieces=false){const path=simplifyPath(points),source=sourceCtx.getImageData(0,0,CANVAS_SIZE,CANVAS_SIZE);if(path.length<2||pathLength(path)<150||!pathTouchesEmoji(path,source))return{valid:false,message:'Your slice must travel through the emoji from one side to the other.'};const leftData=makePieces?sourceCtx.createImageData(CANVAS_SIZE,CANVAS_SIZE):null,rightData=makePieces?sourceCtx.createImageData(CANVAS_SIZE,CANVAS_SIZE):null;let left=0,right=0,total=0;for(let y=0;y<CANVAS_SIZE;y++){for(let x=0;x<CANVAS_SIZE;x++){const o=(y*CANVAS_SIZE+x)*4,a=source.data[o+3];if(a<=3)continue;const w=a/255;total+=w;const side=sideOfPath(x+.5,y+.5,path);if(side>0)left+=w;else right+=w;if(makePieces){const target=side>0?leftData.data:rightData.data;target[o]=source.data[o];target[o+1]=source.data[o+1];target[o+2]=source.data[o+2];target[o+3]=a;}}}if(!total||left/total<.04||right/total<.04)return{valid:false,message:'That cut only clipped the emoji. Slice fully across it.'};const leftPct=left/total*100,rightPct=right/total*100,error=Math.abs(leftPct-50);return{valid:true,path,leftPct,rightPct,error,scoreError:Number(error.toFixed(3)),leftData,rightData};}
  function classifyGesture(){const elapsed=Math.max(1,performance.now()-gestureStartedAt),speed=totalGestureDistance/elapsed*1000;const pathRatio=cutPoints.length>1?pathLength(cutPoints)/Math.max(distance(cutPoints[0],cutPoints[cutPoints.length-1]),1):1;let label='STEADY CUT';if(speed>1200)label='LIGHTNING CUT';else if(speed>750)label='QUICK CUT';else if(speed<350)label='SURGICAL CUT';if(pathRatio>1.35)label='WILD CUT';return{label,speed,pathRatio};}
  function lockCut(result){const p=players[currentPlayerIndex],gesture=classifyGesture();attempts.push({playerIndex:currentPlayerIndex,name:p.name,avatar:p.avatar,emoji:currentEmoji,difficulty:currentShapeDifficulty,points:result.path,leftPct:result.leftPct,rightPct:result.rightPct,error:result.error,scoreError:result.scoreError,gesture:gesture.label});phase='locked';el.sliceHint.hidden=true;el.sliceMessage.className='slice-message good';el.sliceMessage.textContent=players.length===1?'Slice sealed. Send it to the scale.':'Slice sealed. Your balance stays private.';el.sliceStyle.textContent=gesture.label;el.gestureStatus.textContent='SEALED';el.motionFill.style.width='100%';el.cutStamp.hidden=false;el.slicePanel.classList.remove('active-cut');el.slicePanel.classList.add('good-cut');playCue('snap');vibrate([18,20,34]);el.nextButton.hidden=false;el.nextButton.textContent=players.length===1?'WEIGH MY SPLIT':(turnPosition<players.length-1?'PASS THE DEVICE':'WEIGH THE ROUND');}
  function onPointerDown(event){if(phase!=='slice-ready')return;event.preventDefault();drawing=true;cutPoints=[pointerPoint(event)];lastPointer={point:cutPoints[0],time:performance.now()};gestureStartedAt=performance.now();totalGestureDistance=0;if(el.sliceCanvas.setPointerCapture)el.sliceCanvas.setPointerCapture(event.pointerId);el.sliceHint.hidden=true;el.slicePanel.classList.add('active-cut');el.gestureStatus.textContent='CUTTING';startSliceSound();vibrate(8);drawStage();}
  function onPointerMove(event){if(!drawing||phase!=='slice-ready')return;event.preventDefault();const point=pointerPoint(event),prev=cutPoints[cutPoints.length-1];if(distance(prev,point)<2.5)return;const seg=distance(prev,point);totalGestureDistance+=seg;cutPoints.push(point);const now=performance.now(),speed=lastPointer?distance(lastPointer.point,point)/Math.max(1,now-lastPointer.time)*20:0;updateSliceSound(speed);el.motionFill.style.width=`${clamp(speed/3,8,100)}%`;lastPointer={point,time:now};drawStage();}
  function onPointerUp(event){if(!drawing||phase!=='slice-ready')return;event.preventDefault();drawing=false;stopSliceSound();const point=pointerPoint(event);if(!cutPoints.length||distance(cutPoints[cutPoints.length-1],point)>1)cutPoints.push(point);drawStage();const result=analyzeCut(cutPoints,false);if(!result.valid){playCue('bad');vibrate([25,35,25]);el.sliceMessage.className='slice-message bad';el.sliceMessage.textContent=result.message;el.sliceStyle.textContent='TRY AGAIN';el.gestureStatus.textContent='MISSED';el.slicePanel.classList.remove('active-cut');el.slicePanel.classList.add('bad-cut');window.setTimeout(()=>{if(phase==='slice-ready')resetSliceState();},850);return;}lockCut(result);}

  function startRound(){const selected=chooseEmoji();currentEmoji=selected.emoji;currentShapeDifficulty=selected.difficulty;attempts=[];turnPosition=0;roundWinners=[];champions=[];buildTurnOrder();el.roundNumber.textContent=String(round);el.shapeBadge.textContent=currentShapeDifficulty.toUpperCase();el.targetEmojiLabel.textContent=currentEmoji;showTurn();}
  function showTurn(){phase='slice-ready';syncTurn();renderScoreboard();resetSliceState();el.setupScreen.hidden=true;el.handoffScreen.hidden=true;el.gameScreen.hidden=false;el.revealScreen.hidden=true;}
  function showHandoff(){const nextIndex=turnOrder[turnPosition];const p=players[nextIndex];phase='handoff';el.gameScreen.hidden=true;el.revealScreen.hidden=true;el.handoffScreen.hidden=false;el.handoffKicker.textContent=`ROUND ${round} · TURN ${turnPosition+1}/${players.length}`;el.handoffAvatar.textContent=p.avatar;el.handoffTitle.textContent=`${p.name} is next`;el.handoffText.textContent='Previous results are hidden. Hand the device over before continuing.';el.handoffButton.textContent="I'M READY";vibrate(18);}
  function startGame(){players=Array.from({length:setupPlayerCount},(_,i)=>normalizedPlayer(i));round=1;el.setupScreen.hidden=true;el.handoffScreen.hidden=true;el.gameScreen.hidden=false;el.revealScreen.hidden=true;el.newGameButton.hidden=false;saveSettings();startRound();}
  function passOrReveal(){if(phase!=='locked')return;if(players.length===1){beginReveal();return;}if(turnPosition<players.length-1){turnPosition++;showHandoff();return;}beginReveal();}
  function splitForReveal(attempt){prepareSourceEmoji(attempt.emoji);return analyzeCut(attempt.points,true);}
  function drawPiece(canvas,imageData){const temp=document.createElement('canvas');temp.width=temp.height=CANVAS_SIZE;temp.getContext('2d').putImageData(imageData,0,0);const pc=canvas.getContext('2d');pc.clearRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/CANVAS_SIZE,canvas.height/CANVAS_SIZE)*1.05,w=CANVAS_SIZE*scale,h=CANVAS_SIZE*scale;pc.drawImage(temp,(canvas.width-w)/2,(canvas.height-h)/2,w,h);}
  function gradeFor(error){if(error<=.05)return{label:'PERFECT',hint:'Almost mathematically exact',cls:'perfect'};if(error<=.25)return{label:'RAZOR CLOSE',hint:'Exceptional balance',cls:'perfect'};if(error<=1)return{label:'CLEAN SPLIT',hint:'Excellent control',cls:'close'};if(error<=3)return{label:'GOOD CUT',hint:'Solid balance',cls:'close'};return{label:'OFF BALANCE',hint:'A little heavy on one side',cls:'off'};}
  function animateNumber(elm,from,to,suffix,duration=700){const start=performance.now();function frame(now){const t=clamp((now-start)/duration,0,1),e=1-Math.pow(1-t,3),v=from+(to-from)*e;elm.textContent=`${v.toFixed(3)}${suffix}`;if(t<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}
  function renderRevealAttempt(index){clearTimeout(revealTimer);const a=attempts[index],split=splitForReveal(a),grade=gradeFor(a.error);el.ranking.hidden=true;el.revealKicker.textContent=players.length===1?`ROUND ${round} · SOLO`:`ROUND ${round} · RESULT ${index+1}/${attempts.length}`;el.revealTitle.textContent='The weigh-in';el.revealPlayer.textContent=`${a.avatar} ${a.name} · ${a.gesture}`;el.leftPercent.textContent='—';el.rightPercent.textContent='—';el.balanceError.textContent='MEASURING';el.gradeBanner.className='grade-banner';el.gradeLabel.textContent='MEASURING';el.gradeHint.textContent='Calculating visible emoji area';el.balanceMarker.style.left='50%';el.scale.style.setProperty('--tilt','0deg');drawPiece(el.leftPiece,split.leftData);drawPiece(el.rightPiece,split.rightData);el.scaleCard.classList.remove('revealing','perfect-flash');void el.scaleCard.offsetWidth;el.scaleCard.classList.add('revealing');el.revealButton.disabled=true;el.revealButton.textContent='WEIGHING…';playCue('scale');vibrate([12,45,18]);revealTimer=window.setTimeout(()=>{const difference=a.rightPct-a.leftPct;el.scale.style.setProperty('--tilt',`${clamp(difference*.28,-8,8).toFixed(2)}deg`);el.balanceMarker.style.left=`${clamp(a.rightPct,4,96).toFixed(2)}%`;animateNumber(el.leftPercent,50,a.leftPct,'%',720);animateNumber(el.rightPercent,50,a.rightPct,'%',720);animateNumber(el.balanceError,0,a.error,'% off',720);el.gradeBanner.className=`grade-banner ${grade.cls}`;el.gradeLabel.textContent=grade.label;el.gradeHint.textContent=grade.hint;el.accuracyLine.textContent=`Actual rendered emoji area · ${a.difficulty.toUpperCase()} shape · ${a.gesture}`;el.revealButton.disabled=false;el.revealButton.textContent=players.length===1?'ROUND RESULT':(index<attempts.length-1?'NEXT RESULT':'ROUND RESULT');if(a.error<=.25){playCue('perfect');vibrate([22,18,22,18,60]);el.scaleCard.classList.add('perfect-flash');}else{playCue('tick');}},430);}
  function resolveRound(){const best=Math.min(...attempts.map(a=>a.scoreError));roundWinners=attempts.filter(a=>a.scoreError===best).map(a=>a.playerIndex);if(players.length===1)roundWinners=attempts[0].error<=SOLO[soloDifficulty].tolerance?[0]:[];roundWinners.forEach(i=>players[i].score++);champions=players.map((p,i)=>p.score>=WIN_SCORE?i:-1).filter(i=>i>=0);}
  function renderRoundResult(){resolveRound();el.ranking.hidden=false;const sorted=attempts.slice().sort((a,b)=>a.scoreError-b.scoreError||a.playerIndex-b.playerIndex),winnerSet=new Set(roundWinners);el.ranking.innerHTML=sorted.map((a,i)=>`<div class="rank-row${winnerSet.has(a.playerIndex)?' winner':''}" style="animation-delay:${i*60}ms"><span class="rank-position">${winnerSet.has(a.playerIndex)?'★':i+1}</span><div><strong>${escapeHtml(a.avatar)} ${escapeHtml(a.name)}</strong><small>${formatPct(a.leftPct)} / ${formatPct(a.rightPct)} · ${escapeHtml(a.gesture)}</small></div><span>${formatPct(a.error)} off</span></div>`).join('');el.revealKicker.textContent=`ROUND ${round} · FINAL`;if(players.length===1){const ok=roundWinners.length===1;el.revealTitle.textContent=ok?'Point earned':'No point';el.revealPlayer.textContent=ok?`Within ±${SOLO[soloDifficulty].tolerance.toFixed(3)}%`:`Needed within ±${SOLO[soloDifficulty].tolerance.toFixed(3)}%`;}else if(roundWinners.length>1){el.revealTitle.textContent='Exact tie';el.revealPlayer.textContent=`${roundWinners.length} players share the point`;}else{const w=players[roundWinners[0]];el.revealTitle.textContent='Round winner';el.revealPlayer.textContent=`${w.avatar} ${w.name} earns the point`;}renderScoreboard();if(roundWinners.length)playCue('point');if(champions.length){phase='game-over';if(champions.length>1){el.revealTitle.textContent='Game tied';el.revealPlayer.textContent=champions.map(i=>`${players[i].avatar} ${players[i].name}`).join(' · ');}else{const c=players[champions[0]];el.revealTitle.textContent='Perfect Split champion';el.revealPlayer.textContent=`${c.avatar} ${c.name} reached ${WIN_SCORE} points`;}el.revealButton.textContent='PLAY AGAIN';playCue('win');vibrate([35,30,35,30,80]);}else{phase='round-result';el.revealButton.textContent='NEXT ROUND';}}
  function beginReveal(){phase='reveal';revealIndex=0;el.gameScreen.hidden=true;el.handoffScreen.hidden=true;el.revealScreen.hidden=false;renderRevealAttempt(revealIndex);}
  function handleRevealButton(){if(phase==='reveal'){if(players.length>1&&revealIndex<attempts.length-1){revealIndex++;renderRevealAttempt(revealIndex);}else renderRoundResult();}else if(phase==='round-result'){round++;startRound();}else if(phase==='game-over'){players.forEach(p=>p.score=0);round=1;startRound();}}
  function resetToSetup(){clearTimeout(revealTimer);stopSliceSound();phase='setup';el.setupScreen.hidden=false;el.handoffScreen.hidden=true;el.gameScreen.hidden=true;el.revealScreen.hidden=true;el.newGameButton.hidden=true;renderSetup();}

  el.minusPlayer.addEventListener('click',()=>{setupPlayerCount=clamp(setupPlayerCount-1,MIN_PLAYERS,MAX_PLAYERS);saveSettings();renderSetup();});
  el.plusPlayer.addEventListener('click',()=>{setupPlayerCount=clamp(setupPlayerCount+1,MIN_PLAYERS,MAX_PLAYERS);saveSettings();renderSetup();});
  el.soloDifficulty.addEventListener('click',e=>{const b=e.target.closest('[data-solo]');if(!b)return;soloDifficulty=b.dataset.solo;saveSettings();renderSetup();});
  el.emojiMode.addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;emojiMode=b.dataset.mode;saveSettings();renderSetup();});
  el.shapeDifficulty.addEventListener('change',()=>{shapeDifficulty=el.shapeDifficulty.value;saveSettings();});
  el.emojiPicker.addEventListener('change',()=>{pickedEmoji=el.emojiPicker.value;saveSettings();});
  el.soundToggle.addEventListener('click',()=>{soundEnabled=!soundEnabled;saveSettings();updateToggle(el.soundToggle,soundEnabled);if(soundEnabled)tone(720,.05,.02);});
  el.vibrationToggle.addEventListener('click',()=>{vibrationEnabled=!vibrationEnabled;saveSettings();updateToggle(el.vibrationToggle,vibrationEnabled);if(vibrationEnabled)vibrate(22);});
  el.beginButton.addEventListener('click',startGame);el.handoffButton.addEventListener('click',showTurn);el.nextButton.addEventListener('click',passOrReveal);el.revealButton.addEventListener('click',handleRevealButton);el.newGameButton.addEventListener('click',resetToSetup);
  el.sliceCanvas.addEventListener('pointerdown',onPointerDown);el.sliceCanvas.addEventListener('pointermove',onPointerMove);el.sliceCanvas.addEventListener('pointerup',onPointerUp);el.sliceCanvas.addEventListener('pointercancel',onPointerUp);

  loadSettings();populateEmojiPicker();renderSetup();
})();