/* Rogue Quest V3 controls and compatibility overrides */
'use strict';
$('#modeBtn').addEventListener('click',()=>{renderModes();openModal('modesModal')});$('#kingdomModesBtn').addEventListener('click',()=>{renderModes();openModal('modesModal')});$('#loadoutBtn').addEventListener('click',()=>{renderHeroesV3();openModal('heroesModal')});$('#heroRosterBtn').addEventListener('click',()=>{renderHeroesV3();openModal('heroesModal')});$('#kingdomHeroesBtn').addEventListener('click',()=>{renderHeroesV3();openModal('heroesModal')});$('#weaponMasteryBtn').addEventListener('click',()=>{renderWeaponsV3();openModal('weaponsModal')});$('#petOpsBtn').addEventListener('click',()=>{renderPetOps();openModal('petOpsModal')});$('#baseBtn').addEventListener('click',()=>{renderBase();openModal('baseModal')});$('#collectionsBtn').addEventListener('click',()=>{renderCollections();openModal('collectionsModal')});$('#sweepBtn').addEventListener('click',rapidClear);$('#rapidClearModalBtn').addEventListener('click',rapidClear);$('#weeklyStartBtn').addEventListener('click',()=>{if(state.run)return;state.selectedMode='weekly';closeModal('modesModal');startRun('weekly')});$('#breedBtn').addEventListener('click',breedPets);$$('[data-potion]').forEach(b=>b.addEventListener('click',()=>craftPotion(b.dataset.potion)));$('#fishBtn').addEventListener('click',startFishing);$('#clearUpgradeLockBtn').addEventListener('click',()=>{if(state.run){state.run.upgradeLock=null;chooseUpgrade()}});
// Existing class chips now also keep hero selection coherent.
$$('#classChoices .chip').forEach(b=>b.addEventListener('click',()=>{if(state.run)return;let map={knight:'stormKnight',ranger:'galeRanger',mystic:'aetherMystic'};state.heroId=map[b.dataset.class];saveState();renderAll()}));
// Forge level, blueprint sets and bred offspring feed permanent combat power.
function collectionBonusV3(){let b={atk:0,hp:0,crit:0};if(Object.values(state.bestiary).filter(x=>x>0).length>=enemyDefs.length)b.atk+=.05;if(petDefs.filter(p=>state.pets[p.id]?.unlocked).length>=petDefs.length)b.hp+=.05;if(Object.values(state.artifacts).filter(x=>x>0).length>=artifactDefs.length)b.crit+=.02;if(Object.values(state.weaponMastery).filter(x=>x>=3).length>=Object.keys(weaponDefsV3).length)b.atk+=.04;return b}
const v3DropGearBase=dropGear;dropGear=function(forceTier,forceSlot,silent=false){if(forceTier===undefined){let forge=state.base?.forge||1,smith=state.npcRep?.smith||0,boost=Math.min(.6,(forge-1)*.06+smith*.02);if(Math.random()<boost)forceTier=Math.min(5,1+Math.floor(forge/2))}return v3DropGearBase(forceTier,forceSlot,silent)};
const v3HeroBaseFinal=heroBase;heroBase=function(){let h=v3HeroBaseFinal(),cb=collectionBonusV3();h.atk*=1+blueprintBonus()+cb.atk;h.hp*=1+cb.hp;h.crit+=cb.crit;let child=state.bredPets.find(p=>p.id===state.activeBredPet);if(child){if(child.stat==='ATK')h.atk*=1+child.bonus/100;if(child.stat==='HP')h.hp*=1+child.bonus/100;if(child.stat==='CRIT')h.crit+=child.bonus/100}return{hp:Math.round(h.hp),atk:Math.round(h.atk),def:h.def,crit:clamp(h.crit,0,.85),rate:h.rate}}
// Treasure can now include seeds, temporary weapons and world-modifier bonuses.
const v2Treasure=treasure;treasure=function(){let before=state.chests;v2Treasure();if(state.chests>before){if(Math.random()<.32){state.seeds++;toast('+1 Garden Seed')}if(currentModifier().id==='treasure'){let bonus=100*state.currentChapter;gainGold(bonus);toast('Treasure Frenzy +'+bonus+' gold')}}}
// More elite rooms under the weekly Double Elites modifier.
const v2ResolveNode=resolveNode;resolveNode=function(type){if(state.run?.mode==='maze'&&type==='event'){if(Math.random()<.6){state.run.mazeKeys=(state.run.mazeKeys||0)+1;lootPop('🗝️','Maze Key','A locked route can now be opened.');saveState();renderAll();return}else return randomEvent()}if(state.run?.mode==='maze'&&type==='portal'){if((state.run.mazeKeys||0)>0){state.run.mazeKeys--;state.run.mazeTreasure=(state.run.mazeTreasure||0)+1;lootPop('🚪','Locked Door Opened','Key consumed · hidden treasure room discovered.');treasure();return}else{state.run.gainKeyAfterCombat=true;toast('Door is locked · defeat the guardian for a key.');return startCombat(true,false)}}if(type==='battle'&&currentModifier().id==='doubleElite'&&Math.random()<.45)return startCombat(true,false);return v2ResolveNode(type)}
// New hydration extends old saves without invalidating V2 progress.
hydrate=function(){ensureV3State();v2Hydrate();ensureV3State();renderAll();renderArenaHud()}
